### ISSUE TITLE
CHECK_-Macros must be used with care

### ISSUE THREAD

**Issue by everclear72216** [cpputest/cpputest#1000]
I'm new to using CppUTest and so far I think it is the best testing framework for embedded. However, I came across a little problem that of course was my fault. I wrote a lot of tests that have CHECK statements like this one.

CHECK_EQUAL(60, ParamMgrGetParamByIndex(kTestParameter1Index, kSECLVL_PIN_X));

I have been using this for very simple functions so far. Now I needed the function above to call a mock whose return value would change the behavior and thus the return value of my CuT. My test kept failing due to (2nd) calls to my mock. I did not know where these additional calls were coming from until I looked at CHECK_EQUAL_LOCATION's definition. The macro parameter "actual" is used up to two times.

Isn't there a way to make the macro an actual function, so my syntax above does not lead to this unexpected behavior?

**Comment by itavero** [comment]
I would assign the return value of that function to a local variable and check that.
This problem will not arise in that case.

Note this common pattern for writing unit tests, the three A's:
* **Arrange**: set-up the tests, making sure you are in a defined state.
* **Act**: call the component under test and gather results
* **Assert**: check if the asserts match.

**Comment by arstrube** [comment]
I agree with both of you:

1. Follow the three A's; this will make for clearer tests and keep you out of trouble
2. CppUTest shouldn't do this.

**Comment by uecasm** [comment]
There is a way to make it an actual function, but that requires either GCC extensions or templates, and both are banned.  I define a `CHECK_EQUAL_SAFE` macro in my own tests that does the trick however. :grin:

**Comment by everclear72216** [comment]
I ended up using CHECK/CHECK_TRUE and doing the comparison myself while there haven't been any answers to this thread. Now I'm actually doing it the Triple A way. I read about it in Grennings book half a year ago. However, I wasn't aware of any violation of that principle other than that the last two steps were happening on the same line. But maybe it makes more sense to strictly separate these three concepts by using new lines or even empty lines.

Thank you all for your advice.

**Comment by jwgrenning** [comment]
The principle is not really a unit testing principle, but a macro usage 
principle.  When using a macro you generally don't want arguments to 
have side effects, in case the macro expands them twice.

Thanks for reading the book!

The three As or the Four Phase Test Pattern help give some guidance on 
test structure

1 Setup preconditions
2 Do something to the system
3 Check to see if the right thing happened
4 Restore the system to its original state.

James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)
