### ISSUE TITLE
include/CppUTestExt/CodeMemoryReportFormatter.h not installed

### ISSUE THREAD

**Issue by rhertzog** [cpputest/cpputest#1001]
If you use autotools, the generated Makefile won't install include/CppUTestExt/CodeMemoryReportFormatter.h

You should apply the patch below:

```
--- a/Makefile.am
+++ b/Makefile.am
@@ -108,6 +108,7 @@ if INCLUDE_CPPUTEST_EXT
 include_cpputestextdir = $(includedir)/CppUTestExt

 include_cpputestext_HEADERS = \
+       include/CppUTestExt/CodeMemoryReportFormatter.h \
        include/CppUTestExt/GMock.h \
        include/CppUTestExt/GTest.h \
        include/CppUTestExt/GTestConvertor.h \
```

The patch can be grabbed here:
http://anonscm.debian.org/cgit/collab-maint/cpputest.git/plain/debian/patches/Install-include-CppUTestExt-CodeMemoryReportFormatter.h.patch

**Comment by basvodde** [comment]
Resolved.
