### ISSUE TITLE
CppUTestExt tests failing on multiple architectures

### ISSUE THREAD

**Issue by rhertzog** [cpputest/cpputest#1004]
Hello, I uploaded version 3.8 to Debian and unfortunately the package did not build on all architectures since the test suite is failing on many of them:
https://buildd.debian.org/status/package.php?p=cpputest

The errors are not the same on all architectures. Those I care the most about are armel and s390x:
https://buildd.debian.org/status/fetch.php?pkg=cpputest&arch=s390x&ver=3.8-2&stamp=1465996058
https://buildd.debian.org/status/fetch.php?pkg=cpputest&arch=armel&ver=3.8-2&stamp=1465996758

On s390x you get this:
```
tests/CppUTestExt/MockSupport_cTest.cpp:194: error: Failure in TEST(MockSupport_c, outputParametersOfType)
	expected <2 0x2>
	but was  <1 0x1>
```
On armel you get this:
```
tests/CppUTestExt/IEEE754PluginTest.cpp:109: error: Failure in TEST(FE__with_Plugin, should_fail_only_once_when_all_flags_are_set)
	expected <1 0x1>
	but was  <0 0x0>

....
tests/CppUTestExt/IEEE754PluginTest.cpp:72: error: Failure in TEST(FE__with_Plugin, should_fail____when__FE_INEXACT____is_set_and_enabled)
./include/CppUTest/TestTestingFixture.h:123: error:
	actual <.
OK (1 tests, 1 ran, 5 checks, 0 ignored, 0 filtered out, 0 ms)

>
	did not contain  <IEEE754_CHECK_CLEAR(FE_INEXACT) failed>

.
tests/CppUTestExt/IEEE754PluginTest.cpp:65: error: Failure in TEST(FE__with_Plugin, should_fail____when__FE_UNDERFLOW__is_set)
./include/CppUTest/TestTestingFixture.h:123: error:
	actual <.
OK (1 tests, 1 ran, 5 checks, 0 ignored, 0 filtered out, 0 ms)

>
	did not contain  <IEEE754_CHECK_CLEAR(FE_UNDERFLOW) failed>

.
tests/CppUTestExt/IEEE754PluginTest.cpp:58: error: Failure in TEST(FE__with_Plugin, should_fail____when__FE_OVERFLOW___is_set)
./include/CppUTest/TestTestingFixture.h:123: error:
	actual <.
OK (1 tests, 1 ran, 5 checks, 0 ignored, 0 filtered out, 0 ms)

>
	did not contain  <IEEE754_CHECK_CLEAR(FE_OVERFLOW) failed>

.
tests/CppUTestExt/IEEE754PluginTest.cpp:51: error: Failure in TEST(FE__with_Plugin, should_fail____when__FE_DIVBYZERO__is_set)
./include/CppUTest/TestTestingFixture.h:123: error:
	actual <.
OK (1 tests, 1 ran, 5 checks, 0 ignored, 0 filtered out, 0 ms)

>
	did not contain  <IEEE754_CHECK_CLEAR(FE_DIVBYZERO) failed>
```

**Comment by arstrube** [comment]
Sorry about this.

Offhand I can't say anything about the s390x one.

The armel one means that we need to include it among those processors that do not properly implement the IEEE754 exception flags (interestingly it compiles, but it pretty much doesn't seem to set any relevant flags.

I'll post a quick fix (which is also the proper solution) soon. 

@rhertzog meanwhile, could you please provide us with a defined value that allows us to know we are on that architecture? Something like __ARMEL__ or so.

**Comment by arstrube** [comment]
In CppUTestConfig.h
```c++
#177: #if defined(__WATCOMC__)
#178: #define CPPUTEST_FENV_IS_WORKING_PROPERLY 0

```
needs to beome:
```c++
#177: #if defined(__WATCOMC__) || defined(__YOUR_ARCHITECTURE__)
#178: #define CPPUTEST_FENV_IS_WORKING_PROPERLY 0
```

**Comment by rhertzog** [comment]
According to https://wiki.debian.org/ArmEabiPort the define to use is ```__ARMEL__```.

If you have a patch to test or a way to gather more data about the other problem, I can re-run the test suite on a s390x porter machine that Debian makes available to use.

**Comment by arstrube** [comment]
As for the s390x, even after taking a closer look at the code, the failure still seems mysterious, I don't really know where to look yet.

**Comment by rhertzog** [comment]
So s390x is not alone, the exact same failure happens on ppc64 and sparc64:
https://buildd.debian.org/status/fetch.php?pkg=cpputest&arch=ppc64&ver=3.8-2&stamp=1465997329
https://buildd.debian.org/status/fetch.php?pkg=cpputest&arch=sparc64&ver=3.8-2&stamp=1465997289

What the 3 architectures have in common is that they are 64 bit and big-endian (whereas amd64 is little endian). Could there be an endianness problem somewhere in that code?

Looking at other architectures also:
x32: https://buildd.debian.org/status/fetch.php?pkg=cpputest&arch=x32&ver=3.8-2&stamp=1465997681
Looks like the code is not aware that pointers are 32 bits on that architecture.

m68k: https://buildd.debian.org/status/fetch.php?pkg=cpputest&arch=m68k&ver=3.8-2&stamp=1466107688
It needs the same fixes as armel apparently. The preprocessor symbol to check is ```__m68k__```.

**Comment by rhertzog** [comment]
Ok, I found the issue typeCopy access the pointers as "int" and the variables (param, retval) are actually long. If I switch the variable definition to int, the test passes.

**Comment by rhertzog** [comment]
Here is my [patch](https://github.com/cpputest/cpputest/files/321319/patch.txt). I just uploaded an updated package (3.8-3) with that patch, we will quickly see the result on https://buildd.debian.org/status/package.php?p=cpputest&suite=sid

**Comment by arstrube** [comment]
@basvodde I noticed there are still some issues with other architectures that we perhaps might want to look into.

**Comment by rhertzog** [comment]
The x32 failure is at least worth fixing IMO. I wonder if it can also be fixed with with a CppUTestConfig.h update. Shouldn't the check for 64 bit be something like ```#if sizeof(void*) == 8``` ?

**Comment by arstrube** [comment]
@rtherzog can you run the tests with the -v parameter, so we can see easily in which TEST the crash occurs? Or did you already find out perhaps?

**Comment by rhertzog** [comment]
x32 has no crash: https://buildd.debian.org/status/fetch.php?pkg=cpputest&arch=x32&ver=3.8-3&stamp=1466203361
It fails here:
```
tests/SimpleStringTest.cpp:714: error: Failure in TEST(SimpleString, _64BitAddressPrintsCorrectly)
	expected <0x12345678901234>
	but was  <0x78901234>
	difference starts at position 2 at: <        0x78901234  >
```

hppa shows some segfault but that architecture is not very reliable in terms of toolchain/kernel support so I would not spend time on it.
https://buildd.debian.org/status/fetch.php?pkg=cpputest&arch=hppa&ver=3.8-3&stamp=1466256299

**Comment by arstrube** [comment]
Oh, I see -- I just saw the segfault, not this one. Apologies.

**Comment by arstrube** [comment]
> The x32 failure is at least worth fixing IMO. I wonder if it can also be fixed with with a CppUTestConfig.h update. Shouldn't the check for 64 bit be something like #if sizeof(void*) == 8 ?

Unfortunately, things are not quite as simple as that. However, I am surprised that for x32 obviously one of the 64 bit criteria we use was defined. Where can I find out more about that architecture? How is it possible that it had _any_ of the 64 bit indicators that we use #defined?

**Comment by arstrube** [comment]
> Machine Architecture: amd64
Host Architecture: x32
Build Architecture: x32

Okay. So we are running (and building for) 32 bit Linux on a 64 bit machine.... my guess is that `__x86_64` is the problem here, because it will be true. We introduced that one with Windows machines in mind.

There is only one architecture I know of that has 16 bit bytes (and thus the size of void* would be 4 for 64 bit), so combining the check for a size of 8 in combination with `__x86_64` should be safe in principle.

Since sizeof cannot be used in preprocessor macros, we would need to move the check(s) into autoconf. That seems a better place to set CPPUTEST_64BIT. @basvodde what would it take to do that?

**Comment by rhertzog** [comment]
See https://en.wikipedia.org/wiki/X32_ABI it's basically the amd64/x86_64 ABI with pointers reduced to 32 bits from what I know.

**Comment by basvodde** [comment]
@arstrube I'm not sure. I guess there must be a Autoconf macro available for this as I assume it is common. With the CppUtestConfig now being installed, it shouldn't be too hard.
