### ISSUE TITLE
Test failure handling improvement request

### ISSUE THREAD

**Issue by stephen-d-hill** [cpputest/cpputest#1012]
When developing testcases, typically for legacy code, one finds it a little painful as you just get the test failure printed out on the shell.
It would be a nice feature if one could hook into the testcase failure mechanism to perform things like automatically bringing up the debugger at the file/line of the failure or maybe flushing logging files, if one were building for debug. This could be performed via a variety of methods, e.g. callback function or by raising an exception so one could use the standard unhandled exception mechanism.

**Comment by uecasm** [comment]
For mock failures, you can use `mock().crashOnFailure()` to make it crash (thereby breaking into the debugger, if one is attached) for failures like unexpected calls.  These are generally the sort of things that a file+line number in the test aren't really sufficient for.

For test check failures, the line by itself should be sufficient in all cases except when you're using it in a loop or something more ambiguous like that -- you can use the `_TEXT` suffix macros to add some disambiguating information to the failure for those cases.

Another thing you can do is to set a breakpoint in `UtestShell::failWith`.  When this gets hit, you can examine the call stack to find the exact point and context of failure.

**Comment by basvodde** [comment]
@stephen-d-hill as @uecasm mentioned, the crashOnFailure is created for that. There is no platform independent way to automatically start the debugger, so I think that won't be possible. Though the crashOnFailure should work independent of platform.

Close this issue?

**Comment by stephen-d-hill** [comment]
Please close this issue.
