### ISSUE TITLE
areNewDeleteOverloaded() doesn't take into account turnOnThreadSafeNewDeleteOverloads()

### ISSUE THREAD

**Issue by stephen-d-hill** [cpputest/cpputest#1017]
If one calls MemoryLeakWarningPlugin::turnOnThreadSafeNewDeleteOverloads() before running testcases, then MemoryLeakWarningPlugin::areNewDeleteOverloaded() disables leak detection.
One would have thought this would be better:
# if CPPUTEST_USE_MEM_LEAK_DETECTION

```
return operator_new_fptr != normal_operator_new;
```
# else

```
return false;
```
# endif

**Comment by basvodde** [comment]
This has been fixed.
