### ISSUE TITLE
why Deallocating non-allocated memory report unknown line

### ISSUE THREAD

**Issue by cuitoldfish** [cpputest/cpputest#1024]
```.cpp
     Deallocating non-allocated memory
allocated at file: <unknown> line: 0 size: 0 type: unknown
deallocated at file: <unknown> line: 0 type: delete []
```

Is this designed on purpose? 

Why not pass __FILE__ and __LINE__ to
**static void mem_leak_operator_delete (void* mem) UT_NOTHROW** ?

**Comment by cuitoldfish** [comment]
OK, as c++ standard say, the **new**  expression can have additional arguments except the size, so we can add file and line information, but the **delete** expression can not have additional arguments, but only the pointer to the resources, so no chance to give more information to **Deallocating non-allocated memory** failure report

**Comment by maxilai** [comment]
Hi. If you really want to know the details of memory issue, try drmemory. Ｉusually use drmemory to help address memory related issue.  Thanks.
