### ISSUE TITLE
How about change CppUTest to a more distinctive name?

### ISSUE THREAD

**Issue by cuitoldfish** [cpputest/cpputest#1033]
Currently the name "CppUTest" can be easily mixed up with "CppUnit", "CXXUnit", I have met this scenario  several times where people are speaking different name "CppTest", "CxxUnit" and "CppUTest" but actually referring to only one framework "CppUTest".

what's more, the name "CppUTest" also doesn't represent its own distinctive feature such as, cross-platform, API in C, better and more efficient  in embedded systems....

How about change CppUTest to a more distinctive name? such as, ETest(Embeded test framework).....

**Comment by basvodde** [comment]
Eheh. Though I agree it is confusing, I don't think we want to rename it again. It got renamed 4 times already it its history :)

Thanks for the suggestion!

**Comment by jwgrenning** [comment]
Here is some history on the name.

Michael Feathers wanted a smaller test harness that self installed 
tests, enter CppUnitLite.  I made it a bit heavier adding the initial 
memory leak detection and some other stuff.  Bas and I met and he liked 
the test harness and wanted to make it open source.

We were thinking of names. I offered CppUTest.  Bas and I agreed on the 
name.  There is a play on words too Cpp-You-Test.

When I correct someone from saying CppUnit, I tell them "That is the 
best name but the worst choice or test harnesses". People eventually 
learn.

Hope that helps, James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by basvodde** [comment]
And James is forgetting the time when it was part of "CppTestTools" :)

**Comment by jwgrenning** [comment]
We can all be happy we moved on from that!

**Comment by cuitoldfish** [comment]
@jwgrenning , thanks for the history, However, Cpp-You-Test doesn't give this framework a good name which directly epitomize the distinctive character of CppUTest, I mean, people always misuse the name among "CppUTest", "CXXUnit" and "CppUnit", but people will never misuse the name Google Test.

**Comment by uecasm** [comment]
Wait, you mean gtest isn't GNU Test?

**Comment by cuitoldfish** [comment]
No， I just mean people never misuse the name of GTest with CXXUnit

**Comment by jwgrenning** [comment]
Hi Liu

I'm hearing that CppUTest is not a name you approve of. What are you 
suggesting?  Maybe I missed it. Sorry if I did.  Both the names you are 
mentioning are already taken.  Personally, I don't view the name as a 
problem.  You probably figured that out.  It has been around a long 
time.  Its users all know it. Readers of my book know it. I am not sure 
if there are others that share your concern.

When people mix up CppUnit for CppUTest I warn them that CppUnit is the 
least desirable C/C++ unit test harness.  I don't know much about 
CXXTest.  I am of the opinion that CppUTest has many advantages over the 
CppUnit, CXXTest and the C-only test harnesses: memory leak detection 
and mocking for both C and C++.

The 'U' is for Unit.  You say Cpp-You-Test which is a clever double 
meaning, not completely unintended, though maybe never spoken about in 
this or any other forum.

I'd be more interested in renaming MockSupport to CppUMock.  But not 
enough to spend my time on it anytime soon.

I hope it i s helping yo create better code!

James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
Cell: +1 847-630-0998
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by cuitoldfish** [comment]
@jwgrenning , off course, CppUTest has make my design and code better, and actually I am one of your book's readers :)
