### ISSUE TITLE
CI failures due googlecode 404 – gmock unavailable

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#1034]
**CI builds** which are related to **gmock fail** since **googlecode** is **down**. Links like `https://googlemock.googlecode.com/files/gmock-1.6.0.zip` will return **404**.

Gmock has been moved to [Github](https://github.com/google/googletest) (gmock is part of gtest). Old gmock releases (up to v1.7.0) are still available [here](https://github.com/google/googlemock).

The CI script and Makefile.am should be updated.

**Comment by offa** [comment]
PR's: #1040 / #1039

**Comment by offa** [comment]
Has been fixed.

**Comment by basvodde** [comment]
Although I'm not comfortable with the CTest fix. I fixed it by deleting a line, and I'm not sure it ought to be deleted :)
