### ISSUE TITLE
C++ testing of C code works fine, but unable to duplicate with C-only (build fail)

### ISSUE THREAD

**Issue by jerrylogansquare** [cpputest/cpputest#1036]
Hello, 
New to CppUTest..  just downloaded this week.

I got my test working using C++ compiler, but I wanted to 'redo' with C only.  

So, I followed the instructions for the C wrapper.

**I'm getting a build error, it can't seem to find the macro definition of TEST_C, TEST_GROUP_C_SETUP, etc.**  
The odd thing is, when I go look at the CppUTest header files (at least the ones I found) I don't see these macros defined, so I don't know how the compiler would find them anyway.  I'm curious how this works for C++, which are similar macro names.
1. yes, I have the correct header file included  - TestHarness_c.h
2. yes, C++ works fine

I'm using Ubuntu 14.04.

thanks
Jerry
Chicago, Illinois, USA

**Comment by basvodde** [comment]
I assume this has been resolved by now, so will be closing it.

If not, it would be useful to put the actual error in the issue report.
