### ISSUE TITLE
Build library with -fPIC or offer an option to do it

### ISSUE THREAD

**Issue by rhertzog** [cpputest/cpputest#1041]
In Debian we would like to build all binaries with -fPIE by default (for security purpose) but this implies that you can only link with static libraries build with -fPIC. I would thus like to suggest to build cpputest with -fPIC (in Debian this has been suggested in http://bugs.debian.org/837363).

There might be platforms where this is not desirable so I'm fine if you put this as an optional configure-time feature.

In the mean time, please find the patch I used here:
[build-with-fPIC.patch.txt](https://github.com/cpputest/cpputest/files/471638/build-with-fPIC.patch.txt)

You can at least merge the parts where the flags set for the test executables are not copied from the flags used to build the library since they differ in my case.

**Comment by rhertzog** [comment]
Looks like -fPIC is not required, -fPIE is sufficient and that flag is implicitly enabled in Debian so I don't have to make any change to cpputest. See https://bugs.debian.org/842105

**Comment by basvodde** [comment]
Oh ok. Thanks @rhertzog
