### ISSUE TITLE
static variable causes CppUtest to cry about a false memory leak.

### ISSUE THREAD

**Issue by Infogeekx** [cpputest/cpputest#1043]
![result](https://cloud.githubusercontent.com/assets/22279360/18618357/d789a4ce-7ded-11e6-9210-362718835f2b.png)
hi

I am using **Visual Studio 2013** and **std::regex c++11** with **CppUtest 3.8** release. I have a regex expression ![](http://www.techsupportalert.com/freeware-forum/images/icons/icon4.gif)declared as a static variable in a function of a library class that is used in tests. The fact that it is static makes it ![](http://www.techsupportalert.com/freeware-forum/images/icons/icon4.gif)lie to me about memory leaks and fail the tests. It does so with the regex variable but not with something more simple like std::string or int.

**Library Project**

_MyClass.h_

``` c++
class MyClass
{
public:
    static bool matchesRegex(char *s);
};
```

_MyClass.cpp_

``` c++
#include "MyClass.h"

#include <regex>

bool MyClass::matchesRegex(char *s)
{
    static std::regex IrExp("wazaaaa");

    return std::regex_match(s, IrExp);
}
```

**Unit tests Project**

_main.cpp_

``` c++
#include <CppUTest/CommandLineTestRunner.h>

#ifndef DEBUG
#pragma comment(lib, "CppUTest.lib")
#else
#pragma comment(lib, "CppUTestd.lib")
#endif

int main(int argc, char** argv)
{
    int result = CommandLineTestRunner::RunAllTests(argc, argv);
    system("pause");
    return result;
}
```

_TestTest.cpp_

``` c++
#include "CppUTest/TestHarness.h"
#include "../Project1/MyClass.h"

TEST_GROUP(MyClassTest)
{

};

TEST(MyClassTest, DA_TEST)
{
    bool result = MyClass::matchesRegex("wazaaaa");

    CHECK(result);
}
```

I linked stuff through project properties to link the library projetc with the test one. that is all. 

![image](https://cloud.githubusercontent.com/assets/22279360/18618281/d24fc404-7deb-11e6-833b-10681e82ac05.png)

[source files.zip](https://github.com/cpputest/cpputest/files/478925/source.files.zip)

**Comment by jwgrenning** [comment]
CppUTest is not lying to you. It is telling you that during the run of 
your test, your code allocated memory and did not release it before the 
test ended.  As far as CppUTest is concerned that is a leak.  It did its 
job nicely.

There are several design changes that can fix it.  Is this library 
something you own and maintain?  If so, I suggest a design that does not 
look like a leak.

If it is not code that you control, then before your main calls 
RunAllTests, you could call matchesRegex, so the allocation happens 
before CppUTest starts paying attention to your code's allocations.

Hope that helps, James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by Infogeekx** [comment]
How is that a leak? It's a static variable, not even a heap allocation. Hell, it's not even on the stack. It does a good job at being bad. #SMH

**Comment by basvodde** [comment]
@Infogeekx It is because the std::regex IrExp does memory allocation, and probably caches it, causing a leak.

**Comment by Infogeekx** [comment]
What would be " a design that does not look like a leak"?

**Comment by basvodde** [comment]
Not make it static shouldn't leak. Likewise, if you make it a static class variable, I guess it won't leak either.

Although, I'm not sure where the allocation is, I guess it is the regex allocating a string which allocates memory and never releasing it until your program ends.

**Comment by jwgrenning** [comment]
The standard library does this same thing in other std:: functions.  
When you run into a problem like this you need to make these allocations 
happen before RunAllTests is called.  Making `static std::regex 
IrExp("wazaaaa");` file scope or a class static (as Bas suggested) 
should work.

Sometimes just making one on main before RunAllTests can fix it.

What happens if you change `static std::regex IrExp("wazaaaa");` to a 
local `std::regex IrExp("wazaaaa");`

Not knowing the code in std::regex, you may have to experiment.

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by Infogeekx** [comment]
Making the scope to file(outside function) and still static works. Reason it didn't work earlier because I called my variable "exp" which was redefenition of something, probably standard exponent fucntions or whatever.(and yeah if it's non-static it works any way possible)

In short, I'm an idiot. Case closed. BUUUUUT, i recommend you to put some kind of FAQ on such things. Come to think of it, you guys have an awesome and helpful website that is clean and easy to understand. put this case under some ISSUES section there. Many thanks gentleboys.

**Comment by jwgrenning** [comment]
I must say your request for help was rather rude.  You were answered 
respectfully by the professionals that have contributed to this system.

**Comment by Infogeekx** [comment]
@jwgrenning the request wasn't rude. the comment about it's behaviour was. :3

**Comment by basvodde** [comment]
@Infogeekx Also the cpputest manual is open source *hint* *hint* *hint* :P

**Comment by jwgrenning** [comment]
After re-reading your original email, there was no request. There was 
only the statement of behavior.  Just sayin'.

We look foreword to your contribution to our documentation that would 
have helped.  If you want some help, there are generous people here to 
help you understand how CppUTest works.

James

**Comment by Infogeekx** [comment]
@basvodde This thing https://cpputest.github.io/manual.html ? No it's not >:( unless I don't know how to put my inappropriate text there. If you are talking about some text readme file... no one reads those!

@jwgrenning So you did notice. and you are so kind to my harlequin personality. I applaud you sir

**Comment by arstrube** [comment]
Mr. Harlequin / InfoGeek,

I am not one to take offense easily, but calling our online documentation "this thing" is not going to win you any friends around here. I am one of the contributors to both CppUTest and the online documentation, and I consider your last comment unbelievably rude.

And yes, you don't know a lot of things, about CppUTest, about the documentation, and about how we work around here. If you simply asked how to do it, it might get you further.

**Comment by arstrube** [comment]
@Infogeekx - There have been excellent answers to this problem in the Google Group and probably in issues raised here. I would suggest you search for those, and sum them up, rather than starting from a blank page.

**Comment by Infogeekx** [comment]
@arstrube well Mr Serious, first things I searched google. having found nothing of value i went here and tried to report as detailed as possible.
and really "this thing" is considered rude? I wans't even trying to be. is like "this thing" "that thing" if you have read my previous post things you would see that i greatly compliment on it to beging with. you need to loose up ma man. besides who would want to be friends with a random internet person that is so brash?

**Comment by arstrube** [comment]
https://groups.google.com/forum/#!searchin/cpputest/memory$20leak%7Csort:relevance

**Comment by Infogeekx** [comment]
@arstrube weeeeell... it's in a cpputest group and you are one of the big boys in cpputest who helps people, so naturally you would know about that post. i failed to find it using my google search skills and the title doesn't directly contain "static", i mean who knows how many memory leak issues cpputest had to deal over it's period. AND to be fair he seems to have the static vector outside any function... then again he is modifying it by pushing stuff during the execution of of his test. ¯\_(ツ)_/¯

all in all i still think it's a good idea to add this issue to your online documentation. it should also make google searches easier as it would have been indexed.

**Comment by jwgrenning** [comment]
Mr Infogeekx, you make it very clear why you us a made up name.  You are 
afraid of making friends! I hope it keeps working so well for you.

Have a nice day.

**Comment by Infogeekx** [comment]
@jwgrenning yeah man. friends are scary. they always ask to use your hairdryer and eat your sausages.

**Comment by basvodde** [comment]
People, please put the energy in updating the documentation and the code, and not in calling each other names and determining what is rude :P

**Comment by Infogeekx** [comment]
This guy knows what's up.

**Comment by basvodde** [comment]
Although I loved this thread, I'll be closing this issue as it was resolved :)
