### ISSUE TITLE
Undefined reference to 'new' when MemoryLeakDetection is  off

### ISSUE THREAD

**Issue by yeti1026** [cpputest/cpputest#1045]
Hi!

I have compiled CppUTest with MemoryLeakDetection turned off, and since then I get undefined references to 'new'.
With MemoryLeakDetection on, everything compiles fine.

I'm using Mingw+GCC 5.3.0

![2016-10-02_13h24_55](https://cloud.githubusercontent.com/assets/2306308/19020248/ada5bda8-88a3-11e6-8ec9-40c2e21a52f2.png)

**Comment by basvodde** [comment]
Uhm, can you at least mention the compiler and version :) Now it is impossible to work on this as the CI build also builds with Memory Leak Detection off and there is passes.

**Comment by yeti1026** [comment]
Yes, sorry I have pressed enter accidentally after added the title of the issue..

**Comment by basvodde** [comment]
As we are now building this is the travis build, I assume this is fixed on trunk. Let me know if that is not true.
