### ISSUE TITLE
Best Setup

### ISSUE THREAD

**Issue by Mick-P** [cpputest/cpputest#1046]
2 questions:-
1. The 'WalkThrough_VS21010' document indicates that i need to include 'Platform.h" ($(CPPUTEST_HOME)\include\Platforms\VisualCpp\Platform.h) but neither the file nor the folder exists. I assume this is simply some legacy requirement that is no longer needed?
2. I am confused about the recommended setup, with the unit tests as separate project from the application to be tested. I assume what is required is some setting that makes the unit test project include the application within it when it is built. This does not seem to be mentioned in the walkthrough document and the setup it suggests appears to be of no practical value as the unit tests can not interact in any way with the application project. As a newbie to this I have a feeling I am missing something obvious!

**Comment by offa** [comment]
1. You typically add the CppUTest include directory to compiler include searchpath. Then you only have to `#include <CppUTest/TestHarness.h>` in your test implementations.
1. This depends a little on the build system you are using. You can take this project as example: There's a `src/` folder which contains all the production code while the `test/` folder contains only the tests. While the latter uses the production code under test (eg. links the code to the tests), the production code should not include any test stuff.

**Comment by Mick-P** [comment]
Hi Offa
Thanks. Your suggestion for 2. is exactly how I thought it should be done. I guess there must be  a way of telling VS201x to use the app project when building the unit test project.
Not sure that your answer 1 address my q1. :-) Everything builds nicely and nothing objects to the "Platform.h" file being omitted. Just looking for confirmation that this really is not required when using VS2013.

**Comment by offa** [comment]
> Just looking for confirmation that this really is not required when using VS2013.

No, it shouldn't be required anymore. The header mentioned above will take care of everything you need.

**Comment by basvodde** [comment]
I removed the VS2010 doc and moved it to the pages repository. There someone can update it. Thanks!
