### ISSUE TITLE
The Extensions directory has a few of these.

### ISSUE THREAD

**Issue by neuroscot** [cpputest/cpputest#1047]
Looking to use my own class with CHECK_EQUAL and have implemented operator== but need also to create 'SimpleString StringFrom (const yourType&)' according to the advanced help, which then says see the extension directory. Any clue where that directory is?

**Comment by cuitoldfish** [comment]
hi, I think it just say, there are some examples in the cpputest extension directory regarding to the *StringFrom*.

you can see this kind of usage in this file *cpputest\src\cpputestext\mockexpectedcall.cpp*:
```.cpp
SimpleString StringFrom(const MockNamedValue& parameter)
{
    return parameter.toString();
}
```
