### ISSUE TITLE
Broken link on project page

### ISSUE THREAD

**Issue by tumdum** [cpputest/cpputest#1048]
On the [main project page](http://cpputest.github.io) link 'mocking tests' points to [not exitsing file](https://github.com/cpputest/cpputest/blob/master/tests/CppUTestExt/TestMockSupport.cpp). I think it should point to [this file](https://github.com/cpputest/cpputest/blob/master/tests/CppUTestExt/MockSupportTest.cpp). Most likely introduced in bdb469d494924f35997e755311393186b8bdd79d.

**Comment by basvodde** [comment]
Tnx. Fixed.
