### ISSUE TITLE
Breakpoints in CppUTest program

### ISSUE THREAD

**Issue by mldmelissa** [cpputest/cpputest#1051]
I have a gcc executable project that consumes the static CppUTest static library. I am trying to run unit tests and print the outputs through a UART to a termite terminal. I am not getting the correct output on the terminal, so I am in the debug stage. I tried setting breakpoints inside my actual TEST_GROUP() setup and also inside the associated TESTS(), and the program is not breaking in them even though it runs and gives an output.

Should I be able to set breakpoints inside the TESTS()? If so, any idea why my program is not letting me do so?

Also, I am using Atmel Studio 7 as my IDE, targeting a SAM4E16E board. gcc compiler (my code uses c++)

**Comment by Andne** [comment]
Two thoughts:
1) You aren't getting correct output, what output are you getting?
2) First one may answer this, but is main calling the test runner?
