### ISSUE TITLE
Mock function returnBoolValueOrDefault behaves not as expected

### ISSUE THREAD

**Issue by windelbouwman** [cpputest/cpputest#1052]
During our development we faced a strange behaviour with the mock function returnBoolValueOrDefault. It seems return always false when all calls are ignored. Also this test-case, specifically line 154, is not what I expect:

https://github.com/cpputest/cpputest/blob/master/tests/CppUTestExt/MockActualCallTest.cpp#L154

Is this a bug, or is this intended behaviour?

**Comment by maxilai** [comment]
Hi, windelbouwman
    From below snippet. It seems that this behavior is intended.

class MockIgnoredActualCall: public MockActualCall
{
    virtual bool returnBoolValueOrDefault(bool) _override { **return false;** }
}

**Comment by windelbouwman** [comment]
Ah, super! Does this fix work?

**Comment by maxilai** [comment]
It should be. The PR was approved and merged by Basvodde.
