### ISSUE TITLE
TEST(FE__with_Plugin, should_not_fail_again_when_test_has_already_failed) failing on OSX

### ISSUE THREAD

**Issue by felipe-lavratti** [cpputest/cpputest#1066]
Hi Bas et al,

I found this bug quite hard to understand, so I decided to open an Issue to discuss it with you guys.

What we have is one test failing on two OSX build, at Travis CI. The Travis config for the jobs are:
```
  "compiler": "gcc",
  "env": "BUILD=autotools",
  "os": "osx"
```
and
```
  "compiler": "clang",
  "env": "BUILD=autotools",
  "os": "osx"
```
These are the failing Travis jobs:
https://travis-ci.org/felipe-lavratti/cpputest/jobs/181419754
https://travis-ci.org/felipe-lavratti/cpputest/jobs/181419758
(Scroll to the end, and expand the line `$ ../scripts/travis_ci_after.sh`, it will show the Tests run result)

`BUILD=autotools` selects the following script to run:
```
    autoreconf -i ..
    ../configure
    echo "CONFIGURATION DONE. Compiling now."
    make check_all #<<< CppUTestExt Test FAILS HERE
    make dist
    make dist-zip
```

The test that fails is this (file IEEE754PluginTest.cpp):
```
TEST(FE__with_Plugin, should_not_fail_again_when_test_has_already_failed)
{
    fixture.setTestFunction(set_everything_but_already_failed);
    fixture.runAllTests();
    CHECK(IEEE754ExceptionsPlugin::checkIeee754OverflowExceptionFlag()); /* This check FAILS */
    CHECK(IEEE754ExceptionsPlugin::checkIeee754UnderflowExceptionFlag());
    CHECK(IEEE754ExceptionsPlugin::checkIeee754InexactExceptionFlag());
    CHECK(IEEE754ExceptionsPlugin::checkIeee754DivByZeroExceptionFlag());
    LONGS_EQUAL(1, fixture.getCheckCount());
    LONGS_EQUAL(1, fixture.getFailureCount());
}
```

It says it is not supposed to fail again, but it does. So I don't know if the problem is the IEEE754 Plugin or the internals of CppUTest.

Can you point me any direction on this ?

**Comment by basvodde** [comment]
It has been a pain in the past as the OS support isn't great.

@arstrube is probably the best one to decide how to fix this one this time?

**Comment by arstrube** [comment]
@basvodde These tests shouldn't run under MacOS.  It cannot really fine fixed because the necessary interfaces are not implemented under MacOS. 

I  surprised that the tests run at all.  They shouldn't.

**Comment by arstrube** [comment]
BE fixed.

**Comment by felipe-lavratti** [comment]
Pardon my ignorance, does it make sense to build the IEEE extension for Mac at all? Is it useful in this platform?

**Comment by arstrube** [comment]
It doesn't make sense for Mac.

**Comment by felipe-lavratti** [comment]
btw: this issue's already been solved.
