### ISSUE TITLE
Travis CI Builds are way too long

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#1070]
The **Travis CI builds** are **_too long_**, after a commit it takes **> 2 hours** – not minutes – to get the final result. There are builds taking almost 30 minutes and a total build count of 20 is huge.

------------------------
### Here's an idea:

Some days ago, travis added support for *Cron Job Builds*<sup>1)</sup> (per day / week / month). This allows following splitting:

- **Fast Builds** *(each commit)* — Some fast builds (~ 5 min total) for each commit that *(a)* build the project, *(b)* execute the tests and *(c)* do some checking steps like Coveralls
- **Slow Builds** *(Cron)* — all the extensive other builds, eg. gtest builds, autotools, rare compilers etc.

This will give fast feedback for commits / PR's while maintaining the exhaustive build suite<sup>2)</sup>.

------------------------------
<sup>1)</sup> I use them in some other projects, really nice feature.  
<sup>2)</sup> This also allows some kind of *nightly* builds or version. That's full tested and created by the cron.

**Comment by basvodde** [comment]
Yeah, I guess that makes sense.

**Comment by Andne** [comment]
I think some of the build count comes from the recent additions of Mac OSX.  It's probably not needed to run all of the same build tools as we do on the other environments there, mostly just need to check the compiler.  I think that was mentioned on a different pull request when Mac OSX got added.

That said, it appears that cmake is faster than autotools, so does it make sense to keep those then?  I don't know enough off the top of my head what the `check_all` target does under autotools, so maybe there's more going on there than needs too for the quick build.  It looks like the coverage build runs using the cmake toolchain, so maybe just run that configuration (cmake_coverage) for each compiler and platform only?  That would be 4 builds that run for each commit, serially probably about 5-10 minutes, with parallel builds (seems to be the default behavior) less.

Some questions, do the cron job builds only run if the repository has changed, or do they always run?  What do they run against (my first guess would be master)? Do we have a way to force a full build if the PR is changing stuff that is normally only checked during the cron job build?

**Comment by offa** [comment]
> Some questions, do the cron job builds only run if the repository has changed, or do they always run? What do they run against (my first guess would be master)? Do we have a way to force a full build if the PR is changing stuff that is normally only checked during the cron job build?

They run always, you can select between once a day, a week or a month. The branches are selected in the settings, so eg. "master once a day"* and *"feature-xy once a week"*. Have a look at the [travis blog article](https://blog.travis-ci.com/2016-12-06-the-crons-are-here), there's a screenshot showing the options.

As cron builds do not depend on any commit or PR, I don't know whether it's possible build on a PR. But a build > 2 h is really long, even for a PR. Better give a fast feedback. Or maybe there's a wildcard for branch selection.

**Comment by felipe-lavratti** [comment]
Well, Mac builds are terrible slow in Travis, they said they would improve servers but I guess they are not being able to handle it.

Depending on where you are commiting, some travis builds might work fine while others will not. Mac build were added after a difference between OSX LLVM and other platforms headers were detected. Anyways, maybe we don't need all that Mac builds.  

What I do is to do the CI on my own fork, there I'll select which builds I'll run whenever I push. I'll only let all the builds go trough if I am about to Pull Request.

**Comment by offa** [comment]
I guess we can close here 👍
