### ISSUE TITLE
Too many expectNCalls?

### ISSUE THREAD

**Issue by mldmelissa** [cpputest/cpputest#1071]
Is it possible to make too many calls to "expectNCalls" in the CppUTest Mocking framework? I am trying to make ~300 calls. 

mock().expectNCalls(300 , "function").andReturnValue(1);

When I try to run this test, the programs hangs and my call stack looks like:

![image](https://cloud.githubusercontent.com/assets/22821428/21236413/e5cbe95a-c2c8-11e6-8f68-9ff597782769.png)

I am using Atmel Studio 7.0. Targetting a SAM4E16E.

**Comment by offa** [comment]
This happens because `expectNCalls()` is _horrible_ slow at that much calls (see #22 and #1023). Unfortunately this isn't fixed so far.

**Comment by mldmelissa** [comment]
@offa If you step through the program itself, does it hang when you try to step over the call to ExpectNCalls? Or does it hang when checkExpectations is called?

Also, have you tried making this many calls to "ExpectOneCall"? I attempted this for 300 calls, and it will step over some of them, but after the number of calls gets too high, the program will hang.

**Comment by offa** [comment]
> @offa If you step through the program itself, does it hang when you try to step over the call to ExpectNCalls? Or does it hang when checkExpectations is called?
That's a good question.

> Also, have you tried making this many calls to "ExpectOneCall"? I attempted this for 300 calls, and it will step over some of them, but after the number of calls gets too high, the program will hang.

Yes, with > 1000 and this will make the test run very long. Actually it's not *hanging* it's just very slow and will finish after some time. Please see #22 for a workaround. You can also check #1023 – this will speed up the the `excpectNCalls()` notably.

**Comment by jwgrenning** [comment]
Why do you need N=300?

Could another design only need 3?

Maybe a mock is the wrong tool for the job.

can we see some code?

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by matthewpiatt** [comment]
See also: Google Groups thread on this topic https://groups.google.com/forum/#!topic/cpputest/CRSu2EDqlcs

**Comment by jgonzalezdr** [comment]
@basvodde: PR #1023 which fixes this issue has been merged, so it can be closed.

**Comment by basvodde** [comment]
Oki!
