### ISSUE TITLE
Automatic released version out of date

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#1072]
There's a *"automatic released version"* mentioned at the [website](http://cpputest.github.io/):

> You can download the latest ‘automatically released’ version:
> 
> Latest version passing the build This version is automatically packages after a build has passed.

But the linked version is **out of date** (v3.7-dev).

**Comment by offa** [comment]
ping.

**Comment by basvodde** [comment]
:)

**Comment by offa** [comment]
Hey @basvodde, how can we get this up again? :-D

**Comment by basvodde** [comment]
Mostly spending time on it. It'll come, it is getting better.

**Comment by offa** [comment]
Ok, thanks!

**Comment by offa** [comment]
Any news on this?

**Comment by basvodde** [comment]
Nope, no progress as I got overwhelmed with other work at the moment. Sorry about that.

**Comment by offa** [comment]
Now, since there's an automated tagging of the latest build, I guess we can finally close here. Thanks for your efforts @basvodde :smile:

**Comment by basvodde** [comment]
Yeah, although the link on the website is still out of date.
