### ISSUE TITLE
Cygwin test failure

### ISSUE THREAD

**Issue by basvodde** [cpputest/cpputest#1074]
Hi all,

Read the book, wandered through the different setup texts and postings.

Followed the procedure given for CppUTest 3.7.2 in the Starter project on James' site.

On a Win 10 64bit i7  install, no problems in the bash on windows environment.

On a Win 10 32bit i7 install however the build succeeds but the initial test fails for  CppUTestTests.exe,  CppUTestExtTests.exe passes

excerpt from log:

TEST(UtestShell, TestDefaultCrashMethodInSeparateProcessTest)
tests/UtestTest.cpp:183: error: Failure in TEST(UtestShell, TestDefaultCrashMethodInSeparateProcessTest)
./include/CppUTest/TestTestingFixture.h:112: error:
    actual < Generic:1: error: Failure in TEST(Generic, Generic)
    Failed in separate process.
Errors (1 failures, 1 tests, 0 ran, 0 checks, 0 ignored, 0 filtered out, 35 ms) >
    did not contain  <Failed in separate process - killed by signal 11>  - 35 ms

TEST(UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess, AccessViolationInSeparateProcessWorks)
tests/UtestPlatformTest.cpp:113: error: Failure in TEST(UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess, AccessViolationInSeparateProcessWorks)
./include/CppUTest/TestTestingFixture.h:112: error:
    actual < Generic:1: error: Failure in TEST(Generic, Generic)
    Failed in separate process.
Errors (1 failures, 1 tests, 0 ran, 0 checks, 0 ignored, 0 filtered out, 35 ms) >
    did not contain  <Failed in separate process - killed by signal 11>  - 35 ms

TEST(UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess, FailureInSeparateProcessWorks) - 7 ms

Errors (2 failures, 480 tests, 466 ran, 834 checks, 14 ignored, 0 filtered out, 125 ms)

Default Cygwin current Install

$ make -v
GNU Make 4.2.1
Built for i686-pc-cygwin

$ gcc -v
Target: i686-pc-cygwin
Thread model: posix
gcc version 5.4.0 (GCC)

Any ideas?

Cheers

Don

**Comment by denniswjackson** [comment]
I'm getting the similar failures on Windows 7 using 32-bit cygwin:

```

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: CppUTestTests
===================

..................................................
..................................................
..................................................
..................................................
...........!......................................
..................................................
..................................................
..................................................
..................................................
................!....!.!......!.....!..!..!..!..!.
.!..!..!..!..!..!..!..!..!........!..!..!..!..!..!
..!..!..!..!..!..!..!........!..!..!..!..!..!..!..
!..!..!..........................
tests/UtestTest.cpp:202: error: Failure in TEST(UtestShell, TestDefaultCrashMethodInSeparateProcessTest)
./include/CppUTest/TestTestingFixture.h:123: error:
        actual <
Generic:1: error: Failure in TEST(Generic, Generic)
        Failed in separate process

.
Errors (1 failures, 1 tests, 0 ran, 0 checks, 0 ignored, 0 filtered out, 364 ms)

>
        did not contain  <Failed in separate process - killed by signal>

.........!.......

tests/UtestPlatformTest.cpp:107: error: Failure in TEST(UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess, AccessViolationInSeparateProcessWorks)
./include/CppUTest/TestTestingFixture.h:123: error:
        actual <
Generic:1: error: Failure in TEST(Generic, Generic)
        Failed in separate process

.
Errors (1 failures, 1 tests, 0 ran, 0 checks, 0 ignored, 0 filtered out, 86 ms)

>
        did not contain  <Failed in separate process - killed by signal 11>

..
Errors (2 failures, 652 tests, 609 ran, 1134 checks, 43 ignored, 0 filtered out, 770 ms)

FAIL CppUTestTests.exe (exit status: 2)

```

**Comment by koffes** [comment]
Has anyone found a solution to this issue? I'm seeing similar output on Win 10 32-bit Cygwin.

**Comment by dcomer** [comment]
FYI: Downloaded cygwin32 and cygwin64 and followed the instructions in Jame's cpputeststarterkit. Had issues similar to the above with cygwin32, but success with cygwin64 on a Windows 10/I7 machine. This does not help solve the problem on Cygwin32, but maybe someone reading may be able to save time by forging ahead with cygwin64 to learn as I am.

**Comment by basvodde** [comment]
I assume these are solved on trunk now. Lemme know if this isn't the case.
