### ISSUE TITLE
Code coverage check suggestion

### ISSUE THREAD

**Issue by ccwinder** [cpputest/cpputest#1076]
Hello,

I use `cpputest` in my current project to do unit test. 
It's a great unit test framework for us.

Currently I need to check code coverage in my production code. 
My development system is `windows` and use VS2010 to build test,  
it seems there is no `gcov` to use.

Could you give use some suggestion about the code coverage tool ?

**Comment by cuitoldfish** [comment]
I think pcoverage from IBM is a good tool, supporting both UI and command line, you can integrate it with your CI. May be the flaw is you need to pay money :)

**Comment by ccwinder** [comment]
Hi, cuitoldfish
Thanks for your suggestion. I will try it.

**Comment by wiredsource** [comment]
We use CPPUtest and Jenkis CI.
To handle code coverage we CopenCppCoverage
https://opencppcoverage.codeplex.com

It integrates well on Jenkins and visual studio.

N.P. the commandline arg can be autogenerated by the OpenCppCoverage extension for VS...

**Comment by ccwinder** [comment]
Hi, wiredsource
Thanks for your replay.
