### ISSUE TITLE
Is there a way to implement inheritance with CppUtest?

### ISSUE THREAD

**Issue by ruipacheco** [cpputest/cpputest#1077]
I have a class that can be instantiated in a number of ways and to test it I end up copy/pasting the same tests over and over. If this was a OO framework I'd implement an abstract class and specialisations for each set of configuration parameters. Is there a way to go around this with cpputest?

**Comment by Andne** [comment]
You can put other functions besides `setup()` and `teardown()` in the `TEST_GROUP` structure.  There's also the `TEST_BASE` and `TEST_GROUP_BASE` macros that can be used to define common functionality for use across multiple test groups.  You still need to define a `TEST` for each set of parameters, but you could reduce each test to calling a helper function and passing in the configuration parameters.  The helper function would then perform the setup/execute/check logic and contain the various assertions (`CHECK_*` macros).

**Comment by ruipacheco** [comment]
So no real inheritance, more of a hack?

**Comment by uecasm** [comment]
`TEST_BASE`/`TEST_GROUP_BASE` is real inheritance.  Yes, you still need to declare individual `TEST`s to define the top-level parameters, but you would have to do that anyway.  The entire body of the actual test can be shared via inheritance.  (Or templating, if you want to test multiple types with the same tests.)

CppUTest doesn't provide boilerplate to do parameterised tests from a table of values like some other frameworks do, but that's not inheritance either.

**Comment by ruipacheco** [comment]
This seems to be what I want. I cannot find a reference to TEST_BASE here: https://cpputest.github.io/manual.html#test_macros
