### ISSUE TITLE
Cannot compile latest release nor latest commit as x64 Windows executable

### ISSUE THREAD

**Issue by Adnn** [cpputest/cpputest#1079]
When compiling under Windows, warnings are treated as error. A previous PR, merged in 6b06b13, fixed the warnings for Windows x32.

Yet, it is still impossible to compile as a 64 bits Windows executable, because of several C4312 errors (on 64bits Windows, converting an unsigned int to a pointer raise a warning, because the pointer is of greater size...)

There is also a warning C4723 (potential divide by 0) in IEEE754PluginTest_c.c.

**Comment by andrew-elder** [comment]
Any updates on this issue?

**Comment by basvodde** [comment]
Not yet, I think.

**Comment by Andne** [comment]
I have some code on my machine to fix the divide by zero, but unfortunately it's causing MinGW to crash on appveyor, so I've been trying to figure that out.

**Comment by andrew-elder** [comment]
Ok, I have reverted my fix, applied latest from master (thanks @Andne) and the issue remains  fixed. I think this issue can be closed out.
