### ISSUE TITLE
clang-format messes up test formatting

### ISSUE THREAD

**Issue by ruipacheco** [cpputest/cpputest#1080]
I use clang-format with [this](https://gist.github.com/ruipacheco/6df1eef336062ec7b9bf60d631c2d61e) specification to automatically format my code on every save.

While this works well for my C++ code and worked well with [Catch](github.com/philsquared/Catch) it seems to fail with CppUTest. A simple test file ends up looking like this after applying clang-format:

```
TEST_GROUP(SocketTestGroup){void setup(){std::cerr << "setup" << std::endl;
}

void teardown() {}
}
;

TEST(SocketTestGroup, Foo) {
  // Test FOO
}

TEST(SocketTestGroup, MoreFoo) {
  // Test more FOO
}
```

The only way I have to fix this is to add semi-colons at the end of the curly brackets where the body for setup and teardown is defined, but then I end up with clang warnings about extra semi-colons in the code - false positives I'd like to avoid.

Is there a solution for this?

**Comment by alexandear** [comment]
@ruipacheco you can use the workaround. Modify your `.clang-format` config with the following:
```
ForEachMacros: ['TEST_GROUP', 'TEST']
```
After applying clang-format:
```
TEST_GROUP (SocketTestGroup)
{
    void setup() { std::cerr << "setup" << std::endl; }

    void teardown() {}
};

TEST (SocketTestGroup, Foo)
{
    // Test FOO
}

TEST (SocketTestGroup, MoreFoo)
{
    // Test more FOO
}
}
```

**Comment by ruipacheco** [comment]
Thanks!

**Comment by ben-edna** [comment]
For me with ClangFormat >9.0.0 using `TypenameMacros` instead of `ForEachMacros` for `TEST`  looses the space after the macro as well

```yaml
TypenameMacros: ['TEST']
```

After applying clang-format:

```c++
TEST_GROUP (SocketTestGroup)
{
    void setup() { std::cerr << "setup" << std::endl; }

    void teardown() {}
};

TEST(SocketTestGroup, Foo)
{
    // Test FOO
}

TEST(SocketTestGroup, MoreFoo)
{
    // Test more FOO
}
```
