### ISSUE TITLE
unit64_t support on 32bits architecture

### ISSUE THREAD

**Issue by r4nd0m6uy** [cpputest/cpputest#1084]
Considering the following test:
```
#include <cstdint>

#include <CppUTest/TestHarness.h>
#include <CppUTestExt/MockSupport.h>

//--------------------------------------------------------------------------------------------
void important_function(uint64_t p)
{
  mock().actualCall("important_function").
      withParameter("p", p);
}

//--------------------------------------------------------------------------------------------
TEST_GROUP(cpputestWithUint64)
{
  TEST_SETUP()
  {
  }

  TEST_TEARDOWN()
  {
    mock().clear();
  }
};

//--------------------------------------------------------------------------------------------
TEST(cpputestWithUint64, uint64MockedCall)
{
  uint64_t p = 1234;

  mock().expectOneCall("important_function").
      withParameter("p", p);

  important_function(p);

  mock().checkExpectations();
}
```

It compiles very well on my amd64 host architecture but when cross compiling for a 32 bit system, I have a compiler error:

> CppUTestTest.cpp:28:27: error: call of overloaded ‘withParameter(const char [2], uint64_t&)’ is ambiguous
>        withParameter("p", p);
> ...
> /home/random/sources/charguychess/tests/CppUTestTest.cpp:50:27: error: call of overloaded ‘withParameter(const char [2], uint64_t&)’ is ambiguous
>        withParameter("p", p);
> ...

The problem come from the uint64_t definition that is "unsigned long long int" on this target (stdint.h):
```
#if __WORDSIZE == 64
typedef unsigned long int       uint64_t;
#else
__extension__
typedef unsigned long long int  uint64_t;
#endif
```

Thanks to the flexibility of CPPUtest I could get over it using a custom copier for uint64_t! However, do you think it would make sense to add a "unsigned long long int" mock function? Would this create problems on other OS and architectures?

**Comment by jacob-keller** [comment]
I believe the problem was that unsigned long long isn't supported on all platforms, so adding it to the vtable is problematic. I don't think anyone has proposed a better solution yet. See the discussion at #847 and #1142

**Comment by r4nd0m6uy** [comment]
I thought it would not be so straightforward, thanks for the info!

**Comment by r4nd0m6uy** [comment]
I guess this can be closed as "WONTDO", thanks for the feedback!
