### ISSUE TITLE
CppUTestTests fails in Cygwin CYGWIN_NT-6.1

### ISSUE THREAD

**Issue by fdm85** [cpputest/cpputest#1088]
Hello there,
I am having problems to even install CppUTest.
I did follow the README_InstallCppUTest.txt
Using Cygwin 6.1 with GCC 5.4
that fails at make tdd:

>  ~/cpputest-3.8
$ make tdd
./CppUTestTests
..................................................
..................................................
..........................make: *** [Makefile:3399: tdd] Segmentation fault

then i found README.md to differ in the installing part so i tried that:
First of I get the error 

> ~/cpputest-3.8
$ ./autogen.sh
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake-1.15 line 3936.

The make call seems to work but throws some warnings as for function calls mixxed up parameter-types

then the make check call throws at CppUTestTests 
FAIL CppUTestTests.exe (exit status: 139) 
PASS CppUTestExtTests.exe (exit status: 0)

Is GCC 5.4 to old in some respects and i need to update to GCC6.3?
Or did i miss anything?

Kind Regards

**Comment by Dracoir** [comment]
Were you able to resolve this?

**Comment by fdm85** [comment]
Negative. Just dropped the approach and used GTest with MinGW-W64-builds-4.3.0 (GCC 6.3.0)
The minimal Example needed some adaption but otherwise it was smooth to integrate...
Been using GTest combined with eclipse and GCov... Its a very good fit.
