### ISSUE TITLE
JUnit XML output contains random characters and duplicate lines.

### ISSUE THREAD

**Issue by KevinOlsthoorn** [cpputest/cpputest#1090]
When running a CppUTest test with the '-o junit' arguments, the output XML files contain random characters and various duplicate lines.

For example:
`<?xml version="1.0" encoding="UTF-8" ?>
$<properties>
</properties>
$</testcase>
$</testcase>
$</testcase>
$</testcase>
$</testcase>
$</testcase>
<testcase classname="TG_GroupName" name="TC_CaseName" time="0.000">
</testcase>
<system-out></system-out>
<system-err></system-err>
</testsuite>`

As you can see, '$' and `</testcase>` is inserted multiple times which makes the JUnit XML invalid.

I see the same thing with other files, but with other characters ('r' in the example below). 

For example:
`<?xml version="1.0" encoding="UTF-8" ?>
r<properties>
</properties>
<testcase classname="TG_GroupName2" name="TC_CaseName2" time="0.000">
</testcase>
r</testcase>
<system-out></system-out>
<system-err></system-err>
</testsuite>`

Do you have any idea what causes this issue?

**Comment by wiredsource** [comment]
Hi

Do you run from master or release 3.8?

**Comment by KevinOlsthoorn** [comment]
Issue is solved.

We made some local changes to 'UtestPlatform.cpp' that caused CppUTest to use '_vsnprintf' instead of 'vsnprintf' since we were having issues with MinGW and forgot to revert those changes (wasn't necessary in the end). 

After replacing '_vsnprintf' back to 'vsnprintf' the issue didn't occur anymore.
