### ISSUE TITLE
Compiler error due to clang version check miscalculation

### ISSUE THREAD

**Issue by sosodin** [cpputest/cpputest#1093]
Hi,

I encountered a compile-time error in Xcode, which led me to the following bug, I believe.

The following clang version check is done in a few places within the codebase:

#if __clang_major__ >= 3 && __clang_minor__ >= 6
...
#endif

However, this check won't allow through versions like e.g. 4.2.0 as the minor (.2.) is less than 6

The correct form should be something like the following:

#if (__clang_major__ == 3 && __clang_minor__ >= 6) || __clang_major__ >= 4

Odin

**Comment by offa** [comment]
Curiously  this works fine on Linux using Clang 4.0.

**Comment by basvodde** [comment]
Fixed, sorry that took so long.
