### ISSUE TITLE
error: macro name is a reserved identifier [-Werror,-Wreserved-id-macro]

### ISSUE THREAD

**Issue by mkesselaers** [cpputest/cpputest#1099]
Based on the book TDD for Embedded C, I downloaded the source code from the book and installed cpputest 3.8 on my Mac OSX.
When i use brew, the make fails, due to not having the folder $(CPPUTEST_HOME)/build/MakefileWorker.mk

When I install it manually, I do have this fail, but make gives me a lot of errors like the following:
error: macro name is a reserved identifier [-Werror,-Wreserved-id-macro]

Any idea about the reason why?

Make-file in attachment
[MakefileCppUTest.txt](https://github.com/cpputest/cpputest/files/1051258/MakefileCppUTest.txt)

**Comment by jwgrenning** [comment]
Hi

Is it the book code or something else?  Can you give the whole error 
text for that error please.

You can probably just shut it off by adding this compiler flag

-Wno-reserved-id-macro  (the "no-" prefix on the error give you the 
solution to many similar problems.

thanks, James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
Cell: +1 847-630-0998
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by mkesselaers** [comment]
Hi James,

It is indeed the code that I downloaded from https://pragprog.com/titles/jgade/source_code <https://pragprog.com/titles/jgade/source_code>.
In the makefile, the compiler flag is already set, as far as I can see :
CPPUTEST_CXX_WARNINGFLAGS += -Wno-reserved-id-macro -Wno-keyword-macro	

The full error is as follows, but I get plenty of those for other lines in CppuTestConfig.h as well :
/Users/maarten/cpputest-3.8/include/CppUTest/CppUTestConfig.h:107:11: error: macro name is a reserved identifier [-Werror,-Wreserved-id-macro]
  #define __no_return__ __attribute__((noreturn))

Best regards,
Maarten

**Comment by offa** [comment]
The Compiler is right, there are some reserved identifiers used as they start with `__`.

**Comment by Chaser** [comment]
Maarten, Grab the latest code from the repo. I came across this issue with OS X https://github.com/jwgrenning/tddec-code/pull/3 and we were able to solve it.

**Comment by SaeedYasin** [comment]
I got the same issue, pull request open here #1164

**Comment by basvodde** [comment]
Resolved on trunk
