### ISSUE TITLE
Compiler Warning/Error on VC2010 Express

### ISSUE THREAD

**Issue by michelepagot** [cpputest/cpputest#1100]
Build FAILED like:

"####\BUILD\src\CppUTestExt\CppUTestExt.vcxproj" (default target) (7) ->
(Lib target) ->
  IEEE754ExceptionsPlugin.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation t hat consumes this library [####\BUILD\src\CppUTestExt\CppUTestExt.vcxproj]

"####\BUILD\CppUTest.sln" (default target) (1) ->
"####\BUILD\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"####\BUILD\tests\CppUTestExt\CppUTestExtTests.vcxproj.metaproj" (default target) (8) ->
"####\BUILD\tests\CppUTestExt\CppUTestExtTests.vcxproj" (default target) (9) ->
(ClCompile target) ->
  ..\..\..\cpputest-3.8\tests\CppUTestExt\MockSupport_cTestCFile.c(103): warning C4244: 'function' : conversion from 'double' to 'unsigned int', possible loss of data [####\BUILD\tests\CppUTestExt\CppUTestExtTests.vcxproj]
  ..\..\..\cpputest-3.8\tests\CppUTestExt\MockSupport_cTestCFile.c(107): warning C4244: 'function' : conversion from 'double' to 'long', possible loss of data [####\BUILD\tests\CppUTestExt\CppUTestExtTests.vcxproj]
  ..\..\..\cpputest-3.8\tests\CppUTestExt\MockSupport_cTestCFile.c(111): warning C4244: 'function' : conversion from 'double' to 'unsigned long', possible loss of data [ ####\BUILD\tests\CppUTestExt\CppUTestExtTests.vcxproj]

"####\BUILD\CppUTest.sln" (default target) (1) ->
"####\BUILD\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"####\BUILD\tests\CppUTestExt\CppUTestExtTests.vcxproj.metaproj" (default target) (8) ->
"####\BUILD\tests\CppUTestExt\CppUTestExtTests.vcxproj" (default target) (9) ->
(ClCompile target) ->
  ..\..\..\cpputest-3.8\tests\CppUTestExt\MockSupport_cTestCFile.c(103): error C2220: warning treated as error - no 'object' file generated [####\BUILD\tests\CppUTestExt\CppUTestExtTests.vcxproj]

    4 Warning(s)
    1 Error(s)

Offending code seems to be:
    mock_c()->expectOneCall("boo2")->andReturnUnsignedIntValue(1.0);
    mock_c()->expectOneCall("boo3")->andReturnLongIntValue(1.0);
    mock_c()->expectOneCall("boo3")->andReturnUnsignedLongIntValue(1.0);

**Comment by basvodde** [comment]
Are these resolved yet ?

**Comment by Mode-77** [comment]
@basvodde I was able to build on VC2010 Express, toolset v100, debug and release with no errors. It seems this has been resolved.

**Comment by basvodde** [comment]
Thanks
