### ISSUE TITLE
src/CppUTest/CMakeLists.txt uses target_sources() (v3.1) but specifies cmake minimum version as 2.8.7

### ISSUE THREAD

**Issue by pmalek** [cpputest/cpputest#1110]
In https://github.com/cpputest/cpputest/blob/master/src/CppUTest/CMakeLists.txt#L22 there is a piece of code:

```
if (CPP_PLATFORM) #[[Set CPP_PLATFORM in a parent CMakeLists.txt if reusing one of the provided platforms,
                     else supply the missing definitions]]
    target_sources(CppUTest
        PRIVATE
            ../Platforms/${CPP_PLATFORM}/UtestPlatform.cpp
    )
endif(CPP_PLATFORM)
```

which:
* has a comment with improperly broken line
* uses [target_sources](https://cmake.org/cmake/help/v3.1/command/target_sources.html) which has been introduced in cmake v3.1 but https://github.com/cpputest/cpputest/blob/master/CMakeLists.txt defines minimum version as 2.8.7

I suggest either we remove this `target_sources` usage or increase `cmake_minimum_version` to 3.1 + fix the comment by putting it above the if (if it's needed).

**Comment by basvodde** [comment]
Thanks. Could you make a pull request for it?

**Comment by pmalek** [comment]
Sure but would you like to go with v3.1 minimum or some kind of magic trickery to replace `target_sources()`?

**Comment by offa** [comment]
> Sure but would you like to go with v3.1 

Even the oldest supported ubuntu ships v3.2, we could use that too.

**Comment by pmalek** [comment]
The reason I asked was that I use RHEL7.3 on one of my testing boxes and it ships with cmake 2.8.12 (with possibility to upgrade through external EPEL repositories to cmake 3.6) but sure we can push it up a notch to v3.1 :)
