### ISSUE TITLE
Example makefile when using CppUTest installed via apt-get

### ISSUE THREAD

**Issue by jwgrenning** [cpputest/cpputest#1112]
Hi

Is there an example makefile that does not depend on MakefileWorker.mk and uses the full capabilities of CppUTest?

thanks, James

**Comment by TediCreations** [comment]
Hello,

I have a Makefile [here](https://github.com/TediCreations/GNUMakefile4TDD) if it helps somehow.
I use it for cross-compiling between GNU/Linux and arm cortex m.

Ilias

PS: Your book is super. Thank you.

**Comment by basvodde** [comment]
Anything that needs to be done for this?

**Comment by jwgrenning** [comment]
A minimal example would be good.

**Comment by basvodde** [comment]
An example been added to the examples. Also the example makefile has been added to the daily build to ensure it works (at least... there)
