### ISSUE TITLE
Format error in MemoryLeakDetector.cpp

### ISSUE THREAD

**Issue by shyanjenq** [cpputest/cpputest#1116]
Hi,

I tried compiling 3.7.2 in a ubuntu g++5.4 and I am seeing an invalid format error in the stated file that goes like : cpputest_3.7.2/src/CppUTest/MemoryLeakDetector.cpp:69:38: error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t {aka unsigned int}’ [-Werror=format=]
         add("    %04lx: ", currentPos);
Dont know if anyone ran into this particular same problem or not out there.  Can size_t definition be changed here?

**Comment by basvodde** [comment]
Seems current trunk has a cast added to that, which solves this. Closing it.
