### ISSUE TITLE
I have Makefile to build CppUtest for ARM by GCC

### ISSUE THREAD

**Issue by SudakovIvan** [cpputest/cpputest#1117]
May it helps you to make Makefile for gcc. I've built CppUTests for ARM
using this Makefile
[Makefile-to-build-CppUtest-for-ARM-by-cross-gcc.txt](https://github.com/cpputest/cpputest/files/1267592/Makefile-to-build-CppUtest-for-ARM-by-cross-gcc.txt)

**Comment by basvodde** [comment]
I'm unclear on this. You can generate a makefile using ctest to configure.

**Comment by rserranosmith** [comment]
@SudakovIvan Thank you! I was able to compile mine using your makefile as a guide!
