### ISSUE TITLE
CHECK needs a way to print a message

### ISSUE THREAD

**Issue by dlindelof** [cpputest/cpputest#112]
The `JUnit` folks have an overloaded `assertTrue()` method that takes, in addition to a boolean condition to check, an explanatory message. It would be great if we could also have  some means of explaining the conditions under which a `CHECK` fails.

I am testing an implementation of Euclid's algorithm for calculating greatest common divisors. I'm testing every combination of integers between 1 and 100, but when the test fails I only see this:

```
CHECK(a % gcd == 0) failed
```

Without `gdb` there is no way for me to see which combination of integers caused the test to fail.

**Comment by mattiasettin** [comment]
Hi
Is it possible to log/print massage for not-fail check ?

**Comment by basvodde** [comment]
At the moment not. I don't think we would accept it as a pull requests, unless you can convince me that would be good functionality to have :)
