### ISSUE TITLE
MinGW 32-bit tests crash on Appveyor

### ISSUE THREAD

**Issue by Andne** [cpputest/cpputest#1120]
After the last update in Appveyor, the 32-bit MinGW builds are unable to runs tests.  I have been able to reproduce the issue locally by using CMake 3.9.1 (I was previously using CMake 3.4.3).

It appears that something changed between CMake 3.4.3 and CMake 3.9.1 regarding link libraries, the new version is linking in gcc_eh while the old version removed it from the list.  I've managed to manually tweak the library list and removing gcc_eh from it does appears to allow the executables to work again.

Unfortunately, it appears that the change that caused the addition of gcc_eh is upstream in CMake itself (https://github.com/Kitware/CMake/commit/d59e3509850329096a7d6dfbc037d721b70034c9).  I also don't understand why linking in gcc_eh is such a problem.

**Comment by Andne** [comment]
Some more investigation appears that it's a conflict between libgcc_eh and libgcc_s.

libgcc_eh is the static version of the C++ exception handler
libgcc_s is (among other things) the shared version of the exception handler.

It looks like there's a conflict between the implicit libraries detected for the C compiler and the C++ compiler.  The C compiler is picking up libgcc and libgcc_eh while the C++ compiler is picking up libgcc_s and libgcc.

As best I can tell, the implicit library detection in CMake uses different settings for shared/static linkage when testing the C and C++ compilers.  It does appear to be possible to override this using `CMAKE_EXE_LINKER_FLAGS`, so any thoughts on what the correct approach should be?  Shared or Static linkage?

**Comment by Andne** [comment]
So the problem isn't completely due to CMake I've determined.  For some reason, gcc and g++ have different ideas on the default linkage of libgcc and similar libraries.  gcc wants to use static linkage (so therefore `libgcc` and `libgcc_eh` get included) while g++ wants to use shared linkage (so therefore `libgcc` and `libgcc_s` get included).  Since cpputest includes both C and C++ sources, CMake adds the implicit libraries from the C compiler to the C++ compiler if the C++ compiler doesn't already have them.  So the weird conflict in the libraries actually seems to come from GCC itself, and has been there for a while and continues to be there.

However, prior to CMake 3.9, there was a filter in place that removed the gcc libraries from the implicit list, so the difference in linkage was pretty much ignored.  In the commit I referenced above, this filter was modified to no longer remove the gcc libraries.  From the comment on the commit I referenced above, it appears to have something to do with using a third-party compiler to link files compiled by GCC.

Anyways, the only solution I've found so far is to force static linkage in order to change the implicit library list for the C++ compiler.  CMake ignores `CMAKE_EXE_LINKER_FLAGS` when detecting the compiler ABI's, which means that you can't trick the implicit library list into being something more sane.

I've also learned that travis-ci uses CMake 3.2.2.  I don't know what will happen if that gets updated to something newer, if a similar problem will start to occur or not.  I'm inclined to think not, the reason this hasn't been changed/fixed is that MinGW is a less common compiler and it's only when you have mixed source that it occurs (and the bug still shows up in 3.9.4 for me).

**Comment by bradking** [comment]
> CMake ignores `CMAKE_EXE_LINKER_FLAGS` when detecting the compiler ABI's

FYI, that was fixed by [CMP0056](https://cmake.org/cmake/help/v3.10/policy/CMP0056.html).
