### ISSUE TITLE
Clang 5.0 Static Analyzer warnings

### ISSUE THREAD

**Issue by vronchetti** [cpputest/cpputest#1126]
8 warnings generated by Clang 5.0 scan-build:

[cpputest_clang_5_0_scan_build.zip](https://github.com/cpputest/cpputest/files/1422150/cpputest_clang_5_0_scan_build.zip)

I suspect most need only to be suppressed, e.g.:

File: | tests/CppUTest/MemoryOperatorOverloadTest.cpp
-- | --
Warning: | line 52, column 5

<img width="542" alt="screen shot 2017-10-27 at 9 03 14 am" src="https://user-images.githubusercontent.com/8479744/32105243-c8d78248-baf5-11e7-95f4-f24cdfc2dc06.png">

How to proceed?

**Comment by vronchetti** [comment]
Is it reasonable to expect no static analyzer warnings from cpputest?  Thank You!

**Comment by basvodde** [comment]
Reasonable. And the analyzer is very right. However, it is testing exactly what it warns for, so I do not know how to remove the warning.

**Comment by basvodde** [comment]
I guess most of these been fixed...

**Comment by basvodde** [comment]
@vronchetti Double checked them. It is not reasonable to expect no static analyzer warnings as some of these warnings are there on purpose. E.g. a method that purposely crashes the application. The other ones seem all fixed. Closing this.
