### ISSUE TITLE
Memory leak error in MinGW GCC with setting ISO C++1y

### ISSUE THREAD

**Issue by leventesen** [cpputest/cpputest#1132]
After setting this:

![image](https://user-images.githubusercontent.com/4161187/32981813-f97ba354-cc82-11e7-9b0b-3e2205229445.png)

A simple test code `CHECK(false);` gives failure as expected but `CHECK(true);` gives memory leak error of type 'new'.

All I want is to use C++14 features.

**Comment by basvodde** [comment]
Do you know anything about the cause?

**Comment by basvodde** [comment]
I assume this is resolved now. If not, I'll open it again.
