### ISSUE TITLE
IAR 8.11 complains about virtual method override

### ISSUE THREAD

**Issue by dangu** [cpputest/cpputest#1135]
I have upgraded to IAR EWARM 8.11 and now it complains about the following lines in MockCheckedActualCall.h:

    virtual void (*returnFunctionPointerValue())() _override;
    virtual void (*returnFunctionPointerValueOrDefault(void (*)()))() _override;

This all worked in IAR EWARM 7.50. I have asked the IAR support about this and they told me that they now use C++ 2014 (before it was C++ 2003) in their compilers. I have searched some C++ standard documents, including [1] (Appendix C.2 for example) but I don't find anything about changes to the override syntax.

The following lines pass through without complains from the IAR compiler:

    virtual void * returnPointerValue() _override;
    virtual void * returnPointerValueOrDefault(void *) _override;

I tested this in version ccd7cb433f.

References:
[1] C++ standard: http://open-std.org/JTC1/SC22/WG21/docs/papers/2016/n4618.pdf

**Comment by Andne** [comment]
What's the actual error you're getting?  The changes you made mean the function is returning a void pointer instead of a function pointer.

If memory serves, the `override` keyword was new in C++11, the reason it's `_override` is that the config file detects the active version of C++ and defines `_override` as either nothing or `override` based on the detected version.  Does the original syntax work if you remove `_override` from the declarations?

**Comment by dangu** [comment]
I get the following error from IAR:
    Error[Pe065]: expected a ";" C:\Lokalt\test_tools\cpputest\include\CppUTestExt\MockCheckedActualCall.h 87 

This is an excerpt from MockCheckedActualCall.h:

    86
    87 virtual void (*returnFunctionPointerValue())() _override; // IAR error!
    88 virtual void (*returnFunctionPointerValueOrDefault(void (*)()))() _override; // IAR error!
    89
    90 virtual MockActualCall& onObject(const void* objectPtr) _override;  // Works

I also tried replacing "_override" with "override" to see if there are problems with the #ifdef around the _override #define:

    86
    87 virtual void (*returnFunctionPointerValue())() override; // IAR error!
    88 virtual void (*returnFunctionPointerValueOrDefault(void (*)()))() override; // IAR error!
    89
    90 virtual MockActualCall& onObject(const void* objectPtr) _override; // Works

If I remove the "override" it works:

    86
    87 virtual void (*returnFunctionPointerValue())(); // Works
    88 virtual void (*returnFunctionPointerValueOrDefault(void (*)()))() override; // IAR error!
    89
    90 virtual MockActualCall& onObject(const void* objectPtr) _override; // Works

**Comment by Andne** [comment]
Looks like IAR is getting a bit confused about where the function is when a function pointer is being passed/returned (can't blame it, I'm confused by that line).  The error isn't very helpful, but I'm guessing that it loses track of the virtual function and can't figure out what to associate the `override` keyword with.

**Comment by CFlix** [comment]
I ran into the same issue. So is this a IAR bug or should that be fixed in CppUTest?
My temporary fix is to just remove the `_override` everywhere IAR complained but I doubt this is a proper fix...

**Comment by jovere** [comment]
I'm also having an issue based on this. I'm using CppUTest as a single test suite for use on multiple architectures. If I was to remove the offending _override macros, would it break the implementation when using other compilers, such as gcc or visual studio?

**Comment by jgonzalezdr** [comment]
The virtual operator with an override keyword is legit C++11 and C++14, therefore if the IAR compiler claims to support C++14 it is a bug to throw an error. Open a ticket to IAR.

**Comment by dehein** [comment]
> I ran into the same issue. So is this a IAR bug or should that be fixed in CppUTest?
> My temporary fix is to just remove the `_override` everywhere IAR complained but I doubt this is a proper fix...

IAR 8.22.2 here.

Is this fix viable enough to use it?

Would it somehow be able to still make an andjustment here in cpputest? Or is just definetly a IAR problem.

**Comment by carlosande** [comment]
Hello,
here IAR 8.11 I used to compile CppUTest (master) to ARM M with settings as : 
Options -> C/ C++ compiler -> Language : Auto , Standard
Options -> C/ C++ compiler -> C Dialect : C11, C++ exceptions enabled
Options -> C/ C++ compiler -> Preprocessor: __arm__
To compile CppUTestTest, I've commented out line in file CommandLineTestRunnerTest.cpp :
#include "CppUTestExt/MockSupport.h"
Rgds.

**Comment by Salamist** [comment]
Hello folks,
In IAR 8.32 this issue doesn't occur anymore.
