### ISSUE TITLE
How to generate coverage using CMake?

### ISSUE THREAD

**Issue by tehKaiN** [cpputest/cpputest#1139]
I've read "How to create a coverage report" paragraph on main page, but still don't know how to generate `gcov_report.txt` using CMake. In cpputest_build I run:

```
cmake .. -G "MinGW Makefiles" -DCOVERAGE=ON
make
cd tests/cpputest
cpputesttests

.............................................!....
..................................................
..................................................
..................................................
..................................................
...................!..............................
..................................................
..................................................
..................................................
...................................!....!.!......!
.....!..!..!..!..!..!..!..!..!..!..!..!...!..!....
...!..!...!..!..!..!..!..!..!..!..!..!..!..!..!...
.....!..!..!..!..!..!..!..!..!..!.................
.........!........!................
OK (685 tests, 638 ran, 1192 checks, 47 ignored, 0 filtered out, 188 ms)
```

But gcov coverage report doesn't appear anywhere. Also I don't see any specific cmake-generated makefile goal which would generate it. I have gcov installed and it's in my PATH. I'm using win10, tdm-gcc and CMake 3.9.2. What am I missing?

**Comment by basvodde** [comment]
@offa  ?

**Comment by offa** [comment]
As far as I know, the option adds only `--coverage` to C/C++ flags. We can add targets for report generation indeed.

**Comment by offa** [comment]
lcov has become a real pain with the recent versions . Can't we switch to [gcovr](https://github.com/gcovr/gcovr) which provides the same features but is generally more usable?

**Comment by offa** [comment]
@basvodde I guess you can close here.
