### ISSUE TITLE
CMake Cross-Compile Fails

### ISSUE THREAD

**Issue by jovere** [cpputest/cpputest#1144]
When using CMake to compile CppUTest, it automatically attempts to run the test for verification.  This is great.

However, it's not great when you're using CMake/CppUTest with a cross compiler.  If the executable is for a different architecture, it still tries to run, fails, and then proceeds to delete the executable.  It appears the issue is specifically in `CppUTestBuildTimeDiscoverTests.cmake` where `execute_process` is called.  

Is there some kind of flag to disable the compile time execution?

**Comment by offa** [comment]
Is disabling the tests an alternative, you still want to build the them? There's currently only a option to disable tests completely; adding one to disable the discover shouldn't be a problem though.

**Comment by basvodde** [comment]
@offa Close or add flag?

**Comment by offa** [comment]
I can add an option, no problem.

**Comment by basvodde** [comment]
Thanks. Merged and close this issue.
