### ISSUE TITLE
Segmenation fault with cygwin gcc with --std=c++11

### ISSUE THREAD

**Issue by abominous** [cpputest/cpputest#1147]
When I start blank program, it segfaults on exit.

```
#include "CppUTest/CommandLineTestRunner.h"

TEST_GROUP( TestGroup )
{
};

TEST( TestGroup, Test1 )
{
}

int main( int argc, const char** const argv )
{
    CommandLineTestRunner::RunAllTests(argc, argv);
    return 0;
}
```
```
$ ./a.exe -h
usage [-v] [-c] [-p] [-lg] [-ln] [-ri] [-r#] [-g|sg|xg|xsg groupName]... [-n|sn|xn|xsn testName]... ["TEST(groupName, testName)"]... [-o{normal, junit, teamcity}] [-k packageName]
Segmentation fault (core dumped)
```
```
$ cat a.exe.stackdump
Exception: STATUS_ACCESS_VIOLATION at eip=6F004C72
eax=000000B8 ebx=0028CC9C ecx=00000017 edx=80005E24 esi=612AB547 edi=612AB542
ebp=0028CB64 esp=0028CB64 program=[-cut-]\a.exe, pid 8156, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0028CB64  6F004C72 (80005E24, 000000B8, 00000002, 0028CBC8)
0028CB88  6F004E8E (80005E24, 00000002, 00000130, 80005EE0)
0028CBA8  6F004FEE (80005D5C, 00000002, 0028CBE8, 6F006E34)
0028CBB8  6F005B84 (80004D40, 00000002, 0028CBE8, 6F002E74)
0028CBE8  6F006E34 (0028CC14, 00000000, 0028CC9C, 6F023240)
0028CC58  6F002CCB (00000002, 0028CC9C, 6126F0C0, 0028CC9C)
0028CC78  004011F6 (00000002, 0028CC9C, 800000D0, 610079C2)
0028CD18  61007A27 (00000000, 0028CD74, 61006A20, 00000000)
End of stack trace
```
```
$ addr2line.exe -f -C -e libCppUTest.a 0x6F004C72
ZN22MemoryLeakDetectorList10isInPeriodEP22MemoryLeakDetectorNode13MemLeakPeriod
/cygdrive/[-cut-]/CppUTest/MemoryLeakDetector.cpp:270
```
When c++11 is not used, everything is fine.

```
$ sed -n 269,271p CppUTest/MemoryLeakDetector.cpp
{
    return period == mem_leak_period_all || node->period_ == period || (node->period_ != mem_leak_period_disabled && period == mem_leak_period_enabled);
}
```
This `node` address is weird. Sometimes it's high (>= 2^31 and <= 2^32), sometimes it's very low, like 0x50, and dereferencing it leads to memory violation.

Should I report this to cygwin instead?
gcc is 6.4.0, CppUTest is 3.8 and cygwin version is 32-bit.
```
$ gcc --version
gcc (GCC) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by abominous** [comment]
I checked this on my linux box, and this segfault does **not** happen with 6.4.0-r1 gcc and --std=c++11.
```
$ gcc --version
gcc (Gentoo 6.4.0-r1 p1.3) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by abominous** [comment]
Cygwin gcc as it turns out, defaults to C++14(201402) for c++.
{c,gnu}++98 and ++11 segfault, while ++14 and ++17 work fine.

**Comment by basvodde** [comment]
Thanks. So, based on your analysis, is this likely to be just an issue with the compiler on cygwin?

**Comment by abominous** [comment]
Not quite sure. As far as I can judge this could be either a problem with cygwin build of gcc, or CppUTest's memory leak detector running into some unexpected corner case when running on Windows.

My own experience debugging this type of memory issues is too small to say with certainty.

**Comment by keith-at-spacee** [comment]
I also get a stack dump with MSYS2 and g++ (GCC) version 9.1.0

**Comment by jwgrenning** [comment]
Is there a segfault when building cpputest and running its tests, or 
running your tests?

To find the offending test, run the test runner with `-v`.  You can 
further narrow your test run with command line switches, which may be 
helpful to track down the problem.

Cheers, James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by keith-at-spacee** [comment]
Thanks for the hint.  In my case the problem went away when I updated all packages in my Msys2 image.  (Msys2 is derived from Cygwin.)  regards, Keith
