### ISSUE TITLE
Compilation error when using CppUtest and protobuf in project

### ISSUE THREAD

**Issue by rakmane76** [cpputest/cpputest#1151]
I am new to CppUtest so please bear with me. In our project we are using C++ protobuf library, most of the code is in C though. Now I am trying to add CppUtest to create Unit testing framework for our project.

So I integrated CheatSheet sample code from CppUtest I used for my initial testing (without using any header file or function from my project) in my project and it worked completely fine.

Now I just added my project header file(that includes lot of header files including protobuf header file(google/protobuf/message.h)) in CheatSheet.c file.

I am getting following error : I think there is double definition of new operator in CppUtest and protobuf .

g++ -g -std=c99 -w -Wall -I.. -I../../common -I../../common/UDP_Protobuf -c ICP_Test.c -o ICP_Test.o In file included from /usr/include/CppUTest/MemoryLeakWarningPlugin.h:32:0,

             from /usr/include/CppUTest/TestHarness.h:45,

             from ICP_Test.c:5:
/usr/local/include/google/protobuf/arena.h: In constructor

‘google::protobuf::ArenaOptions::ArenaOptions()’:

/usr/local/include/google/protobuf/arena.h:146:33: error: invalid conversion from ‘const char*’ to ‘std::size_t {aka long unsigned int}’ [-fpermissive] block_alloc(&::operator new), ^ In file included from /usr/include/c++/5/ext/new_allocator.h:33:0,

             from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33,

            from /usr/include/c++/5/bits/allocator.h:46,

            from /usr/include/c++/5/string:41,

            from /usr/include/CppUTest/SimpleString.h:155,

            from /usr/include/CppUTest/Utest.h:34,

            from /usr/include/CppUTest/TestHarness.h:39,

            from ICP_Test.c:5:
/usr/include/c++/5/new:129:14: note: initializing argument 1 of ‘void* operator new(std::size_t, void*)’ inline void* operator new(std::size_t, void* __p) _GLIBCXX_USE_NOEXCEPT

I am able to resolve the issue by adding following to my g++ compiler parameter. 
 -DCPPUTEST_MEM_LEAK_DETECTION_DISABLED while compiling the CheatSheet.c file.

But I think this will mean I will not be able to do any memory leak test in my project (functions in my project where I allocate and deallocate memory).

Can I get help on how to resolve the issue of compilation error without disabling memory leak test. 
Or is there a way after enabling DCPPUTEST_MEM_LEAK_DETECTION_DISABLED in compilation I can still test memory leak in my project.

**Comment by PengZheng** [comment]
Two ways:

1) Define `MyOwnNewMacros.h`, add `CPPUTEST_CXXFLAGS += -include MyOwnNewMacros.h` to your Makefile

```C
#include <malloc.h>
#include "CppUTest/MemoryLeakDetectorNewMacros.h"
```
2) a better, easier, and more powerful way of detecting memory problems is to use [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer)

Just add the following into you Makefile, it works like magic:
```
CPPUTEST_CFLAGS += -fsanitize=address -fno-omit-frame-pointer 
CPPUTEST_LDFLAGS += -lasan
```
