### ISSUE TITLE
CppUTest cygwin installation trouble: - Error during CreateProcess

### ISSUE THREAD

**Issue by vasanth8791** [cpputest/cpputest#1152]
I am running the commands given in the README.md 
1) ./configure 
2) make 

In the second step, I am getting  process_begin: CreateProcess(NULL, /usr/bin/mkdir -p src/CppUTest, ...) failed. How should I complete the CppUTest installation in cygwin ?

**Comment by basvodde** [comment]
I assume this is a cygwin problem that has been solved by now? Closing it. Lemme know if that is wrong.
