### ISSUE TITLE
Compiling examples under MSYS/MINGW32 > Error 

### ISSUE THREAD

**Issue by williamhuang03** [cpputest/cpputest#1157]
objs/AllTests/PrinterTest.o: In function `ZN36TEST_Printer_PrintConstCharStar_Test8testBodyEv':
d:\repos\cpputest\examples/AllTests/PrinterTest.cpp:52: undefined reference to `StringFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
objs/AllTests/PrinterTest.o: In function `ZN27TEST_Printer_PrintLong_Test8testBodyEv':
d:\repos\cpputest\examples/AllTests/PrinterTest.cpp:59: undefined reference to `StringFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
objs/AllTests/PrinterTest.o: In function `ZN33TEST_Printer_StreamOperators_Test8testBodyEv':
d:\repos\cpputest\examples/AllTests/PrinterTest.cpp:66: undefined reference to `StringFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libCppUTest.a(lib_libCppUTest_a-UtestPlatform.o):UtestPlatform.cpp:(.text+0x2c1): undefined reference to `pthread_mutex_init'
../lib/libCppUTest.a(lib_libCppUTest_a-UtestPlatform.o):UtestPlatform.cpp:(.text+0x2d7): undefined reference to `pthread_mutex_lock'
../lib/libCppUTest.a(lib_libCppUTest_a-UtestPlatform.o):UtestPlatform.cpp:(.text+0x2eb): undefined reference to `pthread_mutex_unlock'
../lib/libCppUTest.a(lib_libCppUTest_a-UtestPlatform.o):UtestPlatform.cpp:(.text+0x305): undefined reference to `pthread_mutex_destroy'
collect2.exe: error: ld returned 1 exit status
make: *** [CppUTestExamples_tests] Error 1

**Comment by bneumann** [comment]
You might try adding libpthread to the main CMakeLists.txt. Worked for me though

**Comment by basvodde** [comment]
Yup, needed to add pthread. Though now we added some checks and it should work without also.
