### ISSUE TITLE
Code crashing in constructor with CppU framework

### ISSUE THREAD

**Issue by vinayakadj** [cpputest/cpputest#1161]
The code looks like this

#include<stdio.h>
class MY_CLASS
{
public:
	typedef unsigned char UINT8;
	typedef unsigned short UINT16;
	typedef struct {
		UINT16 slotId;
		UINT8 slotType;
		char * slotDescription;  // Code works fine if this line is commented
		UINT8 defaultSlotValue;
		UINT8 slotValue;
   }Slot_t;
   
   MY_CLASS( )
   {
		this->startAddress = 1;
   }
   // Destructor
   ~MY_CLASS() = default;
   // No copy constructor
   MY_CLASS(const MY_CLASS &) = delete;
   // No assignment operator
   MY_CLASS& operator=(const MY_CLASS &) = delete;
private:
   Slot_t slot[6];
   UINT16 startAddress;
};

TEST_GROUP(TestMyClass)
{
   MY_CLASS *object;

   void setup()
   {
      mock().enable();
      mock().ignoreOtherCalls();

      object = new MY_CLASS();
   }

   void teardown()
   {
      mock().checkExpectations();
      mock().clear();

      delete object ;
   }

};

TEST(TestMyClass, TestCase1)
{

}

The code crashes after running this unit test. shows code coverage as 0.00%. But the same class works fine when compiled in standalone g++ compiler. When "char * slotDescription;" line is removed code works fine, can you let me know if there is something to do with initialization of structure? Or if this is an issue with CppU framework?

**Comment by basvodde** [comment]
Hi,

I ran the code on my Mac with g++ and it worked fine (unfortunately).

I wouldn’t recommend to write code like that though :)

Bas
