### ISSUE TITLE
cc1plus: error: unrecognized command line option "-Wno-weak-vtables"

### ISSUE THREAD

**Issue by AntCGreen** [cpputest/cpputest#1162]
Built on x86 Debian 5.x with kernel 2.6.18 with GCC 4.3.2. Issue #991 discusses this as a warning, however now it appears to manifest an error with both the git current 3.7dev build and the 3.8 release. I note that same changes were made to the build as a result of #991.

Is there any workaround for this? Thanks.

mv -f src/CppUTest/.deps/lib_libCppUTest_a-Utest.Tpo src/CppUTest/.deps/lib_libCppUTest_a-Utest.Po
g++ -DHAVE_CONFIG_H -I.   -include ./include/CppUTest/MemoryLeakDetectorMallocMacros.h -I ./include     -include ./include/CppUTest/MemoryLeakDetectorNewMacros.h  -Wno-c++11-long-long -Wno-long-long -Wall -Wextra -Wshadow -Wswitch-default -Wswitch-enum -Wconversion -pedantic -Wsign-conversion -Woverloaded-virtual -Wno-disabled-macro-expansion -Wno-padded -Wno-reserved-id-macro -Wno-keyword-macro -Wno-global-constructors -Wno-exit-time-destructors -Wno-weak-vtables -Wno-old-style-cast   -g -O2 -MT src/Platforms/Gcc/lib_libCppUTest_a-UtestPlatform.o -MD -MP -MF src/Platforms/Gcc/.deps/lib_libCppUTest_a-UtestPlatform.Tpo -c -o src/Platforms/Gcc/lib_libCppUTest_a-UtestPlatform.o `test -f 'src/Platforms/Gcc/UtestPlatform.cpp' || echo './'`src/Platforms/Gcc/UtestPlatform.cpp
src/Platforms/Gcc/UtestPlatform.cpp: In function ‘int IsNanImplementation(double)’:
src/Platforms/Gcc/UtestPlatform.cpp:244: warning: conversion to ‘float’ from ‘double’ may alter its value
src/Platforms/Gcc/UtestPlatform.cpp: In function ‘int IsInfImplementation(double)’:
src/Platforms/Gcc/UtestPlatform.cpp:249: warning: conversion to ‘float’ from ‘double’ may alter its value
At global scope:
cc1plus: error: unrecognized command line option "-Wno-weak-vtables"
cc1plus: error: unrecognized command line option "-Wno-exit-time-destructors"
cc1plus: error: unrecognized command line option "-Wno-global-constructors"
cc1plus: error: unrecognized command line option "-Wno-keyword-macro"
cc1plus: error: unrecognized command line option "-Wno-reserved-id-macro"
cc1plus: error: unrecognized command line option "-Wno-disabled-macro-expansion"
cc1plus: error: unrecognized command line option "-Wno-c++11-long-long"
make[1]: *** [src/Platforms/Gcc/lib_libCppUTest_a-UtestPlatform.o] Error 1
make[1]: Leaving directory `/home/anthony/downloads/tools/cpputest-3.8'
make: *** [all] Error 2

**Comment by basvodde** [comment]
Is this still an issue ?

**Comment by basvodde** [comment]
Actually, this is a bug in gcc. The real warning is the conversation from float to double. When there is a real warning, gcc gives these weird additional warnings. Unfortunately, I got them too. We try to get rid of them by fixing the real warning. Closing this issue.
