### ISSUE TITLE
link error in VS2017 when calling a a function out of the project lib (code under test)

### ISSUE THREAD

**Issue by Hallo-Du-Da** [cpputest/cpputest#1169]
error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""int __cdecl calc(int,int)" (?calc@@YAHHH@Z)" in Funktion ""public: virtual void __thiscall TEST_TEMPLATETestGroup_TEMPLATETest_Test::testBody(void)" (?testBody@TEST_TEMPLATETestGroup_TEMPLATETest_Test@@UAEXXZ)".

Can some help me? I Set the linker options (Additional Linker include paths) and the additional dependencies like I did it for the CppUTest.lib. Without calling the function in the project, everything work fine.... 

If I include the source and the header directly into the project and delete the lib, the error is still the same.

If I try to set up ceedling UnitTest with the same configuration option like I did it for cppUTest with the same lib, everything works fine. Out of ceedling I could call the application function out of the lib which I like to test....

**Comment by basvodde** [comment]
Hi,

It says you are not linking the function calc. AFAIK. That is not in CppuTest, so I guess you have a method called calc somewhere that you aren’t linking?

Bas

**Comment by Hallo-Du-Da** [comment]
Yes, it is a function "calc()" in a lib (the production code project which I compile as a static lib). I have added this lib and its output path to the "UTest" Testproject linker settings in VS like I did it for the CppUTest.lib (as described in the WalkThrough_VS21010.docx).

If I add the same lib and path to a ceedling/Unity test project and call this function calc() on the same way form this project, everything compiles and links fine... 

I don't see my brainless mistakes currently ;)...

**Comment by basvodde** [comment]
It is hard to give more info. The linker says it cannot find the calc method. If it is in the static library, then either it isn't linking that library, or it is not in the library, or the link order is wrong, or you have different methods for generating the symbols. The latter 2 are unlikely in VC, so I would assume it is either (1) or (2)

**Comment by Hallo-Du-Da** [comment]
What do you mean with:
- "different methods for linking the name"
-  " latter 2 are unlikely" ... I would assume ... or (2) ?

I had try to add a source and a header directly into the cppUTest project and write a dumme function. This also result in the same linking error. 

Could the the problem be, that my lib (and my dummy function source + header) are plain C functions and a plan C project and the linker search for a cpp lib to link? If so, how can I change this and what is the different between a cpp and a c lib? Is it only the file extansion "*.cpp" and "*.hpp" which corresponds into a cpp lib? Or what are the depandencies to generate a cpp or a c. 
Must I "only" use the C Macros?

So much thanks for your help! :)

**Comment by Hallo-Du-Da** [comment]
WOOOWW YMMD !! I never knew that rally before to set the  header include in extern "C" braces. I spend so much hours into learning this. And without you I would have spent many more hours searching at wrong places additionally. Thanyou.

**Comment by jwgrenning** [comment]
You are welcome.

I learned that the hard way too. I make a point of that in my TDD for 
Embedded C training course. (I have one coming up, maybe you want to 
attend).

Cheers and happy you are not stuck!

James

**Comment by Hallo-Du-Da** [comment]
Thank you James, my father of TDD ;)
