### ISSUE TITLE
any roadmap or release schedule?

### ISSUE THREAD

**Issue by jacob-keller** [cpputest/cpputest#1171]
I'm curious if there is a visible roadmap or release schedule anywhere for when the next main release will be cut :)

Thanks,
Jake

**Comment by selsiddharthsingh** [comment]
This will be helpful. It has been 3 years since last release and added functionality in that time can be put into a release. We love cpputest in our group here and it will be nice to lock on a release instead of locking on a commit.

**Comment by jacob-keller** [comment]
We're in the same boat here, the newest fixes for uint64_t (long long) aren't in any release, and it's rather annoying to have to have a local build of cpputest, or to manage our own packaging of it to get on all our test systems.

**Comment by basvodde** [comment]
Yeah, sorry people (!)

I still have hope it will get better in the future, but perhaps we ought to look for an additional maintainer to help out. A release ought to be done soon, though we'll need to look at that darn null_ptr_t issue :)

**Comment by selsiddharthsingh** [comment]
Thanks @basvodde. That null_ptr_t is an issue for sure, we can think about release after that.

**Comment by aegaas** [comment]
is the nullptr_t issue you reference  #1248? If so, it is closed. Does this mean we're close to a release? 

I ask because my internal tools team has a fork ready to merge from master into our mainline, but if a release is imminent, we'd prefer to wait for that.

**Comment by basvodde** [comment]
I'm aiming for a release 2H
