### ISSUE TITLE
Compilation error with arm-none-eabi-g++ and std=c++11

### ISSUE THREAD

**Issue by free-easy** [cpputest/cpputest#1173]
```
In file included from /home/chenlijun/Repositories/Kerr/street-light/third-party/cpputest/include/CppUTest/Utest.h:34:0,
                 from /home/chenlijun/Repositories/Kerr/street-light/third-party/cpputest/include/CppUTest/TestHarness.h:39,
                 from /home/chenlijun/Repositories/Kerr/street-light/third-party/cpputest/src/CppUTest/CommandLineArguments.cpp:28:
/home/chenlijun/Repositories/Kerr/street-light/third-party/cpputest/include/CppUTest/SimpleString.h:178:36: error: 'nullptr_t' in namespace 'std' does not name a type
 SimpleString StringFrom(const std::nullptr_t value);
                                    ^~~~~~~~~
```

It seems that the arm toolchain doesn't support std::nullptr_t

![screenshot from 2018-09-06 10-02-30](https://user-images.githubusercontent.com/20483759/45143595-00c9e700-b1bc-11e8-9519-4e98f5a18abd.png)
From [here](https://developer.arm.com/docs/dui0472/l/c-and-c-implementation-details/c11-supported-features), though this document is related to `armcc` and not `arm-none-eabi-g++`.

Some possible solutions:
* as ARM suggests, define this somewhere (I'm new to the codebase and I've no idea of the best location)
    ```
    namespace std
    {
	   typedef decltype(nullptr) nullptr_t;
    }
    ```
* Don't use C++11 with ARM compiler
* change this `#if __cplusplus > 199711L` to `#if __cplusplus > 199711L && !defined __arm__`

**Comment by basvodde** [comment]
I think the third one makes most sense (to me). Will you make a PR?

**Comment by free-easy** [comment]
Certainly! It's a pleasure.
