### ISSUE TITLE
unknown type name ‘class’  class SimpleStringCollection;

### ISSUE THREAD

**Issue by DattatrayHinge** [cpputest/cpputest#1175]
Installed cpputest as mentioned in http://cpputest.github.io/ for ubuntu 16.04 
$ apt-get install cpputest
Then create C project in eclipse and add below files at main.c 
```
#include <stdio.h>
#include <stdlib.h>
#include "CppUTest/CommandLineTestRunner.h"
#include "CppUTest/TestHarness_c.h"
int main (void) { 
	puts("!!!Hello World!!!"); /* prints !!!Hello World!!! */
//	CommandLineTestRunner::RunAllTests(ac, av);
	return EXIT_SUCCESS;
}

```
then build the project but build failed with below error 

Building file: ../src/edgeDeviceApp.c
Invoking: GCC C Compiler
gcc -I"/home/dattatray/workspace_C/edgeDeviceApp/src/common" -I"/home/dattatray/workspace_C/edgeDeviceApp/src/utils" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/edgeDeviceApp.d" -MT"src/edgeDeviceApp.o" -o "src/edgeDeviceApp.o" "../src/edgeDeviceApp.c"
In file included from /usr/include/CppUTest/Utest.h:34:0,
                 from /usr/include/CppUTest/TestHarness.h:39,
                 from /usr/include/CppUTest/CommandLineTestRunner.h:31,
                 from ../src/edgeDeviceApp.c:14:
/usr/include/CppUTest/SimpleString.h:43:1: error: unknown type name ‘class’
 class SimpleStringCollection;
src/subdir.mk:18: recipe for target 'src/edgeDeviceApp.o' failed
 ^
/usr/include/CppUTest/SimpleString.h:44:1: error: unknown type name ‘class’
 class TestMemoryAllocator;
 ^
/usr/include/CppUTest/SimpleString.h:46:1: error: unknown type name ‘class’
 class SimpleString
 ^
/usr/include/CppUTest/SimpleString.h:47:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
/usr/include/CppUTest/SimpleString.h:114:1: error: unknown type name ‘class’
 class SimpleStringCollection
 ^
/usr/include/CppUTest/SimpleString.h:115:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
/usr/include/CppUTest/SimpleString.h:134:1: error: unknown type name ‘SimpleString’
 SimpleString StringFrom(bool value);
 ^
/usr/include/CppUTest/SimpleString.h:134:25: error: unknown type name ‘bool’
 SimpleString StringFrom(bool value);
                         ^
/usr/include/CppUTest/SimpleString.h:135:1: error: unknown type name ‘SimpleString’
 SimpleString StringFrom(const void* value);
 ^
/usr/include/CppUTest/SimpleString.h:136:1: error: unknown type name ‘SimpleString’
 SimpleString StringFrom(char value);
 ^
/usr/include/CppUTest/SimpleString.h:136:14: error: conflicting types for ‘StringFrom’
 SimpleString StringFrom(char value);
              ^
/usr/include/CppUTest/SimpleString.h:135:14: note: previous declaration of ‘StringFrom’ was here
 SimpleString StringFrom(const void* value);
              ^
/usr/include/CppUTest/SimpleString.h:137:1: error: unknown type name ‘SimpleString’
 SimpleString StringFrom(const char *value);
 ^
/usr/include/CppUTest/SimpleString.h:137:14: error: conflicting types for ‘StringFrom’
 SimpleString StringFrom(const char *value);
              ^
/usr/include/CppUTest/SimpleString.h:135:14: note: previous declaration of ‘StringFrom’ was here
 SimpleString StringFrom(const void* value);
              ^
/usr/include/CppUTest/SimpleString.h:138:1: error: unknown type name ‘SimpleString’
 SimpleString StringFromOrNull(const char * value);
 ^
/usr/include/CppUTest/SimpleString.h:139:1: error: unknown type name ‘SimpleString’
 SimpleString StringFrom(int value);
 ^
/usr/include/CppUTest/SimpleString.h:139:14: error: conflicting types for ‘StringFrom’
 SimpleString StringFrom(int value);
              ^
/usr/include/CppUTest/SimpleString.h:135:14: note: previous declaration of ‘StringFrom’ was here
 SimpleString StringFrom(const void* value);
              ^
/usr/include/CppUTest/SimpleString.h:140:1: error: unknown type name ‘SimpleString’
 SimpleString StringFrom(unsigned int value);
 ^
/usr/include/CppUTest/SimpleString.h:140:14: error: conflicting types for ‘StringFrom’
 SimpleString StringFrom(unsigned int value);
              ^
/usr/include/CppUTest/SimpleString.h:135:14: note: previous declaration of ‘StringFrom’ was here
 SimpleString StringFrom(const void* value);
              ^
/usr/include/CppUTest/SimpleString.h:141:1: error: unknown type name ‘SimpleString’
 SimpleString StringFrom(long value);
 ^
/usr/include/CppUTest/SimpleString.h:141:14: error: conflicting types for ‘StringFrom’
 SimpleString StringFrom(long value);
              ^
/usr/include/CppUTest/SimpleString.h:135:14: note: previous declaration of ‘StringFrom’ was here
 SimpleString StringFrom(const void* value);
              ^
/usr/include/CppUTest/SimpleString.h:142:1: error: unknown type name ‘SimpleString’
 SimpleString StringFrom(unsigned long value);
 ^
/usr/include/CppUTest/SimpleString.h:142:14: error: conflicting types for ‘StringFrom’
 SimpleString StringFrom(unsigned long value);
              ^
/usr/include/CppUTest/SimpleString.h:135:14: note: previous declaration of ‘StringFrom’ was here
 SimpleString StringFrom(const void* value);
              ^
/usr/include/CppUTest/SimpleString.h:143:1: error: unknown type name ‘SimpleString’
 SimpleString HexStringFrom(long value);
 ^
/usr/include/CppUTest/SimpleString.h:144:1: error: unknown type name ‘SimpleString’
 SimpleString HexStringFrom(unsigned long value);
 ^
/usr/include/CppUTest/SimpleString.h:144:14: error: conflicting types for ‘HexStringFrom’
 SimpleString HexStringFrom(unsigned long value);
              ^
/usr/include/CppUTest/SimpleString.h:143:14: note: previous declaration of ‘HexStringFrom’ was here
 SimpleString HexStringFrom(long value);
              ^
/usr/include/CppUTest/SimpleString.h:145:1: error: unknown type name ‘SimpleString’
 SimpleString HexStringFrom(const void* value);
 ^
/usr/include/CppUTest/SimpleString.h:145:14: error: conflicting types for ‘HexStringFrom’
 SimpleString HexStringFrom(const void* value);
              ^
/usr/include/CppUTest/SimpleString.h:143:14: note: previous declaration of ‘HexStringFrom’ was here
 SimpleString HexStringFrom(long value);
              ^
/usr/include/CppUTest/SimpleString.h:146:1: error: unknown type name ‘SimpleString’
 SimpleString StringFrom(double value, int precision = 6);
 ^
/usr/include/CppUTest/SimpleString.h:146:53: error: expected ‘;’, ‘,’ or ‘)’ before ‘=’ token
 SimpleString StringFrom(double value, int precision = 6);
                                                     ^
/usr/include/CppUTest/SimpleString.h:147:1: error: unknown type name ‘SimpleString’
 SimpleString StringFrom(const SimpleString& other);
 ^
/usr/include/CppUTest/SimpleString.h:147:43: error: expected ‘;’, ‘,’ or ‘)’ before ‘&’ token
 SimpleString StringFrom(const SimpleString& other);
                                           ^
/usr/include/CppUTest/SimpleString.h:148:1: error: unknown type name ‘SimpleString’
 SimpleString StringFromFormat(const char* format, ...) __check_format__(printf, 1, 2);
 ^
/usr/include/CppUTest/SimpleString.h:149:1: error: unknown type name ‘SimpleString’
 SimpleString VStringFromFormat(const char* format, va_list args);
 ^
/usr/include/CppUTest/SimpleString.h:150:1: error: unknown type name ‘SimpleString’
 SimpleString StringFromBinary(const unsigned char* value, size_t size);
 ^
/usr/include/CppUTest/SimpleString.h:151:1: error: unknown type name ‘SimpleString’
 SimpleString StringFromBinaryOrNull(const unsigned char* value, size_t size);
 ^
/usr/include/CppUTest/SimpleString.h:155:18: fatal error: string: No such file or directory
compilation terminated.
make: *** [src/edgeDeviceApp.o] Error 1

21:30:07 Build Failed. 38 errors, 0 warnings. (took 932ms)

**Comment by basvodde** [comment]
Can you include TestHarness.h and not the _c variant?

**Comment by redengin** [comment]
You've got C++ syntax in a main.c.  Rename to main.cpp.

**Comment by Hallo-Du-Da** [comment]
Is it working now or still problems there?
