### ISSUE TITLE
[feature] Support for nonfatal checks

### ISSUE THREAD

**Issue by momobel** [cpputest/cpputest#1178]
Hi,

I am currently in the process of choosing a unit test framework and I am checking CppUTest. The assertion documentation mentions the following.

> The failure of one of these macros causes the current test to immediately exit

I checked the code and there doesn't seem to be nonfatal checks/assertion. This is useful to discriminate between fatal assertions (validating a pointer before further checking for example) and nonfatal checks (checking function call count for example) where one may want all check to be performed without premature test termination.

Would this feature be of interest for CppUTest?

Thanks!

**Comment by basvodde** [comment]
Hi,

Not really.

I don’t understand non-fatal checks. When a test fails, it fails. It needs to be fixed. Adding non-fatal checks just adds confusion IMHO.

Thanks,

Bas

**Comment by momobel** [comment]
Hi Bas,

Thanks for the quick feedback.
I feel it is useful for the use case below (pseudocode).
`
pointer = do_something()
fatal_assert(pointer != NULL) // no point continuing the test since no additional check can be performed
check(pointer->a == 10) // the test may want to also check b so a complete report summary can be given
check(pointer->b == 5)
`
If the report mentions both a and b checks to be failing, the user can see every test failure (and not only a) without having to modify the code, re-compile, re-run. For sure each check needs to be fixed anyway.

Thanks & Best regards,
Mohamed

**Comment by basvodde** [comment]
Hi,

Yes, but we wouldn’t want to have that because one failure is enough and giving multiple failures only causes people to have to read more before they find the ‘real’ failure (especially as the second failure often is caused by the first one)

Bas

**Comment by momobel** [comment]
Alright, thanks for your time Bas!

Mohamed

**Comment by jwgrenning** [comment]
I agree with Bas. There is little reason to have more than one failure 
per test.  Multiple failures might lead you the wrong way, kind of like 
leaving semicolon off a c statement and the multitude of errors are at 
least distracting and usually misleading.

Essentially, well designed tests are checking a single scenario. (Not to 
be confused with one 'CHECK').

Cheers, James


--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)
