### ISSUE TITLE
IAR example project compilation errors

### ISSUE THREAD

**Issue by DonPavlov** [cpputest/cpputest#1180]
While using IAR 8.22.2 i am getting the following Linker Errors for compiling CppUTestTest:

    Error[Li005]: no definition for "TestTestingFixture::lineOfCodeExecutedAfterCheck" [referenced from C:\Tools\cpputest-3.8\platforms\iar\Debug\Obj\UtestTest.o] 
    Error[Li005]: no definition for "TestTestingFixture::checkTestFailsWithProperTestLocation(char const *, char const *, int)" [referenced from C:\Tools\cpputest-3.8\platforms\iar\Debug\Obj\TestUTestMacro.o] 
    Error[Li005]: no definition for "TestTestingFixture::lineExecutedAfterCheck()" [referenced from C:\Tools\cpputest-3.8\platforms\iar\Debug\Obj\TestUTestMacro.o] 
    Error[Li005]: no definition for "TeamCityTestOutput::TeamCityTestOutput()" [referenced from CommandLineTestRunner.o(cpputest.a)]

**Comment by cuitoldfish** [comment]
did you use the CppUTest.ewp file included in the repository to open the project and build the library?  if yes then you need to add some missing files from the repository to the project file.

**Comment by dehein** [comment]
Yes the included file was used.

**Comment by basvodde** [comment]
Has this been resolved ?

**Comment by DonPavlov** [comment]
Can not currently verify this, as i am not using iar 8.22 anymore.

**Comment by basvodde** [comment]
Ok, closing it for now then. Not sure how to reproduce it.
