### ISSUE TITLE
cygwin64

### ISSUE THREAD

**Issue by Hallo-Du-Da** [cpputest/cpputest#1183]
Hello, 

if i call a function from the production code I get the following linker error:

... undefined reference to `somefunction' 

... relocation truncated to fit: R_X86_64_PC32 against undefined symbol `somefunction'

how to solve the linker problem? It looks like a 32 vs 64 bit problem. I'm using cygwin64 on a 64 bit windows system. I use extern "C" arround the included header files, but this dosent solve the problem.

Kind regards

**Comment by basvodde** [comment]
This doesn't seem like a CppUTest related issue. Hope it is resolved by now. I'll close this issue.
