### ISSUE TITLE
CMake error when CppUTest is a sub-project

### ISSUE THREAD

**Issue by smfelsher** [cpputest/cpputest#1186]
I am following the instructions in `src/CppUTest/CMakeIntegration-README.md` to include CppUTest as a sub-project of my project. When I attempt to configure my build directory, the following error occurs:

```
CMake Error at cpputest/src/CppUTest/CMakeLists.txt:69 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "CppUTest".
```
In looking at that line in the CMake list file, the variable `CMAKE_INSTALL_LIBDIR` does not appear to be defined. I searched through the CppUTest source for a definition, but none was found. I assume this needs to be set to something like `lib`, etc.

Do the instructions in the aforementioned README need to be updated to indicate that the variable, `CMAKE_INSTALL_LIBDIR`, need to be defined also?

**Comment by KevinWMatthews** [comment]
Referencing #1187 : Looks like this issue was introduced while fixing #1150 
If I follow the instructions in the [CMakeIntegration-README.md](https://github.com/cpputest/cpputest/blob/master/src/CppUTest/CMakeIntegration-README.md) from v3.8, it seems to work. I have the same issue from the latest master.

@smfelsher  do you see the same?

**Comment by KevinWMatthews** [comment]
I thought that `CMAKE_INSTALL_LIBDIR` was a variable that is defined by CMake itself, but I can't seem to find it in CMake's documentation. Am I missing something? Anyone have a link?

**Comment by smfelsher** [comment]
@KevinWMatthews , I do **_not_** see a CMake configuration error if I use code from v3.8.

**Comment by basvodde** [comment]
This should be done when releasing, right? Can I close this?
