### ISSUE TITLE
withOutputParameterReturning doesn't have overloads

### ISSUE THREAD

**Issue by jacob-keller** [cpputest/cpputest#1197]
The cpputest examples website https://cpputest.github.io/mocking_manual.html#output_parameters lists .withOutputParameterReturning as having function overloads for some basic types.

In v3.8 of CppUTest, this is not true, as I get the following compiler error:

error: too few arguments to function call, expected 3, have 2
                .withOutputParameterReturning("value", &actual_value)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                       ^
/usr/local/include/CppUTestExt/MockExpectedCall.h:55:5: note: 'withOutputParameterReturning' declared here
    virtual MockExpectedCall& withOutputParameterReturning(const SimpleString& name, const void* value, size_t size)=0;

I checked the master branch, and I don't see any reference or test which uses these supposed overloads.

I think the documentation should be updated to remove the reference to this unimplemented feature.

**Comment by basvodde** [comment]
Removed it from the manual. Wonder how unimplemented features entered the manual.
