### ISSUE TITLE
CppUTestConfig.cmake is not present in the debian package

### ISSUE THREAD

**Issue by avrahamshukron** [cpputest/cpputest#1201]
I installed `cpputest` on Mac OS using `brew install cpputest` and then I could use the `find_package(CppUTest)` command.

Then I installed cpputest in a debian-based docker image ([rikorose/gcc-cmake:gcc-8](https://hub.docker.com/r/rikorose/gcc-cmake/)) using `apt-get install cpputest`.

When using the `find_package(CppUTest)` command inside that docker it failed because it could not find `CppUTestConfig.cmake`.

Running `find /usr -name CppUTestConfig.cmake` returned no results.
Both `dpkg -L cpputest` and `dpkg -L libcpputest-dev` did not list the config file as part of the package.

**Comment by basvodde** [comment]
Yah, this is a seemingly easy request that isn't so easy :)

In homebrew, the build system used in CMake. But for apt-get it is autotools. We support both and I do think we want to keep that. However, generating the CMake package files from autotools seems non-trivial.

**Comment by avrahamshukron** [comment]
We can keep supporting `autotools` by means of a CI test.
That doesn't mean we need to actually compile the packaged .deb using autotools.

Worst case scenario - during package build we can compile the entire lib twice:
1. once using autotools, and install it to the directory that will become the package.
2. second time using cmake and install it to a temp dir, then take the relevant files from said temp dir and put them in the actual package dir.

**Comment by basvodde** [comment]
Yup, I added a test in the build to check whether the install of both is the same. For this, for now, I use cached CMake package files. I read through them and I *think* this will not cause any problems as there doesn't seem to be a lot of variation per installation.

So, I'll give this a try and see whether that works. It is implemented and committed to trunk, so I will close this issue.

If you do experience problems with the new 4.0 version, lemme know.
