### ISSUE TITLE
Clang 8 build fails due empty expressions

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#1206]
Compilation on clang 8 (C++11 and Werror enabled) fails with many _"empty expression statement has no effect"_ warnings.

This problem is easy to fix:

1. Remove the `;` from the macro definition – callers are required to end the statement with `;`.
1. Add the `;` to the macro definition and remove it from any internal callers – only clients get the warning

Both solution can potentially break existing code, depending on whether clients have ended the statement with `;` or not.

I'd prefer _1.)_ as it maintains the function-like usage. This is also the fix I previously included into #1205, but removed it as I'm not sure about the compatibility impacts.

**Comment by basvodde** [comment]
Sucks. I guess we'll need to do with (1). Does it have any potential to mess up or is it just lead to compile errors?

**Comment by offa** [comment]
It should only lead to compile errors. Within CppUTest I don't even expect any impact as those macros are already called correctly:

```cpp
UT_THROW_BAD_ALLOC_WHEN_NULL(memory);
```

3rd party callers outside of this project could omit the `;` and see a compile error therefore.

I'll create a PR once fixed.

**Comment by offa** [comment]
Fixed via #1215
