### ISSUE TITLE
Change to Clang

### ISSUE THREAD

**Issue by Hallo-Du-Da** [cpputest/cpputest#1208]
Hello, 

1.
How can I configure and build CppUtest with Clang and llvm tools (llvm-link) in cygwin? Currently it is build with gcc/g++

2.
How can I change CppUTest to use Clang instead of using gcc/g++ after rebuilding it?

Thanks for some help

**Comment by offa** [comment]
I don't use Cygwin, but what I typically do on Linux:

```
mkdir clang_build && cd clang_build
CC=clang
CXX=clang++
cmake -DC++11=ON -DWERROR=ON ..
make
```

This is going to configure and build CppUTest with Clang using CMake. Rebuilds automatically use the same compiler.

If you want to use _libc++_, you can execute following line before calling cmake: `CXXFLAGS="-stdlib=libc++"`.

**Comment by Hallo-Du-Da** [comment]
first off all, thanks a lot for the fast reply. 

Now I get this output:

Current compiler options:
    CC:                                 /usr/bin/cc
    CXX:                                /usr/bin/c++.exe
...

Need I reconfigure and configure again and do I need to set other flags as well like LD=llvm-link? 

Next question: Do I need to export this variables again after reboot or is it only needed 

Kind regards

**Comment by offa** [comment]
These variables are only necessary for the initial configuration. Can you check `echo $CC` and `echo $CXX` before running cmake? They should show their appropriate Clang values.

If this doesn't work you can start the cmake-gui and set the native compilers there. This is also where you can set additional settings (eg. compiler or linker flags).

**Comment by vpod** [comment]
The initial solution above lacks "export", I guess
Need either: `CC=clang CXX=clang++ cmake <whatever>`
or
```bash
export CC=clang
export CXX=clang++
cmake <whatever>
```

**Comment by Marco-Israel** [comment]
thx alot btw :)
