### ISSUE TITLE
TEST overview output

### ISSUE THREAD

**Issue by K0ertis** [cpputest/cpputest#1209]
Hi! 

I develop embedded code and test it with cpputest. It is really handy and intuitive to use cpputest to test the code and to mock hardware.
When operating with pointers it could often occur that there is a memory leak, pointer which got too big and an invalid write occurs. The program breaks during run, which is always bad to debug if a lot of TESTS are already there.

An option to faster debug would be by printing the output file before the test file starts. I am not sure if this is possible but the printing each TEST_GROUP once for sure should be possible.

Of course i could enter a stdout in each TEST_GROUP to get an overview which test run but then it get printed for each TEST.

**Comment by K0ertis** [comment]
Suggestion: 

In TestOutput I added po protected:     

`SimpleString tmpGroupString;`

and modified TestOutput.cpp:
```cpp
void TestOutput::printCurrentTestStarted(const UtestShell& test)
{
    if (verbose_) print(test.getFormattedName().asCharString());


    if (test.willRun()) {
      SimpleString st =  test.getGroup();
      if(tmpGroupString !=  st){
        print("\nGROUP: ");
        print(st.asCharString());
        print(" ");
        tmpGroupString =  (st);
       }
      else{
        setProgressIndicator(".");
      }
    }
    else {
       setProgressIndicator("!");
    }
}
```

**Comment by basvodde** [comment]
Thanks for the suggestion. Right now, there is the -v option to let the output be move verbose. That will not do for you?

We do not want the output more verbose than just printing the .s But it should be easy to change the Formatter for your project.

**Comment by K0ertis** [comment]
Hi! Thanks for the hint! That fit quite well for me
