### ISSUE TITLE
With -p option, count of tests run is always 0

### ISSUE THREAD

**Issue by alameth** [cpputest/cpputest#1210]
If a test suite is run with the -p option, the number of tests run is always zero:

`OK (4 tests, 0 ran, 0 checks, 0 ignored, 0 filtered out, 71 ms)`

That's because the run count is incremented in `UtestShell::runOneTestInCurrentProcess()`, which is run in the child's memory space and discarded on exit.

I moved the call to `result.countRun()` into `UtestShell::runOneTest()`, before the check is made for whether `-p` is set.

Happy to submit a pull request if you'd like.

**Comment by vpod** [comment]
@basvodde : please assign to me as I faced this issue in https://github.com/cpputest/cpputest/issues/1262 fixing and thus will have to fix both.

**Comment by vpod** [comment]
At least my opinion is that `fork()` failure is "not run", so `countRun()` should not be done fore we check result of `fork()`
