### ISSUE TITLE
JUnit XML text does not encode unsafe characters

### ISSUE THREAD

**Issue by alameth** [cpputest/cpputest#1212]
When writing text to JUnit XML, illegal characters in `<system-out>` are not escaped.

To fix, I extracted the escaping code in `JUnitTestOutput::writeFailure()` into a separate function, which is called from both `writeFailure()` (for the failure text) and in `writeTestCases()` (for `<system-out>`). While I was in there, I revised the code to use correct escapes; now failure messages like "`CHECK_C(result > -1)`" are properly emitted as "`CHECK_C(result &gt; -1)`".

I'm a little concerned about using `SimpleString.replace()` is this way, repeatedly running over the same string. But for now I'm focussing on making it functionally correct and will make it fast later.

**Comment by basvodde** [comment]
Thanks. But no pull request for this?

**Comment by alameth** [comment]
Happy to make the PR. I'm a n00b with this code base, so wanted to confirm you were interested in the PR first.

**Comment by basvodde** [comment]
Having a PR is a lot easier to look at then a description, so would definitively be interested :)

**Comment by alameth** [comment]
Question: Since I needed it in a hurry (the builds were breaking :D), my encoder function is brute force:
```
SimpleString JUnitTestOutput::encodeXmlText(const SimpleString& textbody)
{
    SimpleString buf = textbody.asCharString();
    buf.replace("\"", "\\\"");
    buf.replace("&", "&amp;");
    buf.replace("<", "&lt;");
    buf.replace(">", "&gt;");
    buf.replace("\n", "{newline}");
    return buf;
}
```
I was thinking about adding an implementation of `SimpleString::replace()` that accepts a mapping table, something like this:
```typedef struct {
    char         to;
    SimpleString with;
} replacemap_t;

    void replace(replacemapt_t tw[]);
```
and
```static replacemap_t JsonSpecials[] = {
    { '"', "\\\"" },
    { '&', "&amp;"},
    { '<', "&lt;"},
    { '>', "&gt;"},
    { '\n', "{newline}"}
};
```
Would you accept a new method in SimpleString?

**Comment by alameth** [comment]
Had a question, which I deleted because it was a terrible idea.

**Comment by alameth** [comment]
Fix verified, thank you!
