### ISSUE TITLE
CHECK_TRUE and CHECK_FALSE inconsistency while checking against an explicit bool operator. 

### ISSUE THREAD

**Issue by monique-pless** [cpputest/cpputest#1216]
I've recently run into strange behavior when testing an **std::unique_ptr** variable by the **CHECK_FALSE** macro and then by the **CHECK_TRUE**. The **std::unique_ptr** class has an _explicit bool operator_ that helps to check whether it holds a **nullptr** or not.
Here's an example:
`auto const aNull = std::unique_ptr<int>(nullptr);`
`CHECK_FALSE(aNull); // works fine due to the negation(!) operator applied at the UtestShell::getCurrent()->assertTrue(!(condition)...`

`auto const notNull = std::make_unique<int>(1);`
`CHECK_TRUE(notNull); // can't use the explicit bool operator thus it does not work as the CHECK_FALSE version.`

A contextual conversion is required to call the _explicit bool operator_, so the **static_cast<bool>(notNull)** or **!!notNull** fixes compilation, but it does not solve the problem of the inconsistency.

My preference is to add an explicit cast at the **UtestShell::getCurrent()->assertTrue(static_cast<bool>(condition)**... to the both macros.

**Comment by vpod** [comment]
Have you fixed this already?

**Comment by basvodde** [comment]
Not sure

**Comment by basvodde** [comment]
Ok. fixed now.
