### ISSUE TITLE
InstallScripts.sh: CPPUTEST_HOME improvement

### ISSUE THREAD

**Issue by bhase** [cpputest/cpputest#1230]
Hi,
I had some trouble with the scripts/InstallScripts.sh shell script. It did not work correct when running in the scripts folder (I have seen now, that in the README a call to InstallScript.sh is made outside of the scripts folder). But I think, it would be better if it could be called from any folder?
So this change is working for me:
```patch
diff --git a/scripts/InstallScripts.sh b/scripts/InstallScripts.sh
index 54b85e3a..948679ef 100755
--- a/scripts/InstallScripts.sh
+++ b/scripts/InstallScripts.sh
@@ -3,7 +3,8 @@ FirstLetter=${0:0:1}
 if [[ $FirstLetter == "/" ]] ;  then
 	CPPUTEST_HOME=${0%/scripts/*}
 else
-	CPPUTEST_HOME="$(pwd)/${0%/scripts/*}"
+	file=$(pwd)/${0}
+	CPPUTEST_HOME="${file%/scripts/*}"
 fi
 
 EXE_DIR=${EXE_DIR:-/usr/local/bin}
```

Greetings
Benjamin

**Comment by basvodde** [comment]
adopted.
