### ISSUE TITLE
Request: support skipping some tests at runtime?

### ISSUE THREAD

**Issue by andioz** [cpputest/cpputest#1237]
Hi all,

I have an interesting situation right now, and want to ask if I can find some support in the current implementation.

I write a module which is wrapping a licensed library, protected by license file or USB dongle. I decided to implement a low level wrapper at first, which hides all library specific details behind interfaces and concrete implementations. Then I can implement higher level code using mocks, fakes, etc. 

But I want to run tests for the licensed code as well on systems having a license. I simply add an if (isLicensed) {} block. This is not perfect, but good enough for now. But one thing I am missing. I want to influence the report for the case this tests are skipped. Like the "!" for ignored tests. Maybe with an "S"? 

Is this possible in some way? Or would it be something for a future enhancement? 

Thanks,
Andi

**Comment by vpod** [comment]
What about splitting to two test binaries? I.e. distinguish tests at compile time and run only proper binary for the system.

**Comment by uecasm** [comment]
There are several different command line options that let you request that certain tests be included or excluded based on their name or test group name.  For example, passing

    -xg Licensed

Will skip any test groups with "Licensed" as a substring.

**Comment by gavv** [comment]
This would be a very useful feature, and I think other test frameworks have it for a reason (e.g. GTEST_SKIP). There are situations where you know that a test should be skipped only at run-time, for example:

* skip test if an external library reports that it doesn't support a certain codec or file format (through a run-time call)
* skip test when running under valgrind

It may be quite tricky implementing such checking logic outside of the test.
