### ISSUE TITLE
C++ Standards in build

### ISSUE THREAD

**Issue by basvodde** [cpputest/cpputest#1242]
Add a build for all the C++ standards in Travis.

**Comment by offa** [comment]
Here's what's covered in the ci builds (only the standard related):

| Compiler | C++11 option | Standard used |
|-------------|-------------------|--------------------|
| GCC | On | C++11 |
| GCC | Off | C++98 |
| Clang | On | C++11 |
| Clang | Off | C++98 |

What should we add further? C++14 and 17 for both Gcc and Clang? Is C++03 necessary too?

**Comment by basvodde** [comment]
I think it would be good to add all of the C++ versions.

**Comment by offa** [comment]
For both compiler?

**Comment by basvodde** [comment]
I guess clang would do as it tends to be the picker

**Comment by offa** [comment]
This has been solved already, I guess we can close here @basvodde.
