### ISSUE TITLE
Return code is zero if command line parsing fails

### ISSUE THREAD

**Issue by vpod** [cpputest/cpputest#1243]
CommandLineTestRunner::RunAllTests returns 0 if command line arguments are invalid.
We faced it by chance when runner scripts go broken and provided incorrect command line. No tests were run, but the application looked like all tests passed due to success code returned.
Is this expected behavior? How to detect that nothing was run due to some error and fail?

**Comment by basvodde** [comment]
That doesn't seem correct.

**Comment by vpod** [comment]
Will maintainers fix it? Or am I expected to fix it (which will take time to do via corporate account)?

**Comment by vpod** [comment]
ping @basvodde

**Comment by basvodde** [comment]
You can do a pull request if you want. It will probably be faster. If not, I hope to have time to fix it.... one day in the future... :)

**Comment by vpod** [comment]
Please assign to me

**Comment by basvodde** [comment]
Sure.
