### ISSUE TITLE
Print list of all failed tests.

### ISSUE THREAD

**Issue by angelskieglazki** [cpputest/cpputest#1244]
Hi, I’ve made a small patch that displays the list of all failed tests at the end. I think it would be useful. For example, my friend wrote about 400 tests and there’s no point in trying to find a failed test in the terminal log.

regards, max

**Comment by basvodde** [comment]
Did he write 400 tests without running them?

**Comment by angelskieglazki** [comment]
> Did he write 400 tests without running them?

No :). Just now the code base of the project is changing very much

**Comment by basvodde** [comment]
Ok, but if there are so much tests failing, then I would think you don't run them frequently enough. Personally I never needed a summary at the end, so I'm a bit surprised by the request.

I'll definitively not merge a feature that always gives a summary at the end as it would just produce more output that is most of the time not needed....

**Comment by angelskieglazki** [comment]
@basvodde Hello, Bas. I added a flag for this functionality(-pse) so that it does not work by default as you would like. I remember your remark about the std::list container. What is the best way to replace it based on the guideline project? Write a template class or just make a dynamic array of strings in pure-c style?

Regards.

**Comment by basvodde** [comment]
Unfortunately, also templates ought to be avoided, so you'll need to build your own list. You'd probably end up making a TestFailureList.

Also, there are no tests in the pull requests. We will not accept anything that doesn't have any test coverage and recommend people to actually test-drive their changed.

Other than these two, I have no comments on the PR so far.

**Comment by basvodde** [comment]
Closing this issue as we have an open PR for the discussion related to this.
