### ISSUE TITLE
Link to include folder seems wrong

### ISSUE THREAD

**Issue by heroichornet** [cpputest/cpputest#1249]
https://github.com/cpputest/cpputest/blob/eb71de9015f04e078a17b707f7182f2bc2a66f00/build/MakefileWorker.mk#L279

Hello
`$(CPPUTEST_HOME) = /usr/share/cpputest/` per default

I installed using `apt-get install cpputest` and I saw that my includes are in 
`CPPUTEST_MEMLEAK_DETECTOR_NEW_MACRO_FILE=/usr/include/CppUTest/MemoryLeakDetectorNewMacros.h `
`CPPUTEST_MEMLEAK_DETECTOR_MALLOC_MACRO_FILE=/usr/include/CppUTest/MemoryLeakDetectorMallocMacros.h`

and not in the ones listed in the file& line i've referenced. Why is this? Do I need to move the includes? I also installed the script with the setup.sh file

**Comment by basvodde** [comment]
My initial reaction is that this is indeed wrong and ought to be fixed.

That said, the MakefileWorker.mk isn't really made for using with the apt-get install. Still, can be fixed.

**Comment by basvodde** [comment]
I'm not going to touch the Makefile.worker further for now. It hasn't been created with apt-get install in mind as it assumes the CppuTest git repository structure.
