### ISSUE TITLE
Allow to alter JUnit output file name

### ISSUE THREAD

**Issue by vpod** [cpputest/cpputest#1256]
We've come up with innovative way to screw things up: the test binaries have the same test group, but test different things (probably not uncommon). If they run in the same "make check" or similar, we get only 1 file instead of as many as binaries.
It seems that cpputest either needs to append "package" to file name (as we can easily say that these tests are for different packages), or provide some other way to alter file names to make them unique (extra "prefix" argument?).

Am I right that currently there is no way to alter the junit output behavior? IMO, we need to add it.
Seems to be lacking part of #263...

**Comment by vpod** [comment]
It seems that my observation is correct.

Can anybody suggest the best way to fix this?
I mean that I see some options, but not sure what option fits cpputest design the best:

1. Modify the file name generator to include something additional. E.g. it can be program name (argv[0]). But program name alone will not help if we have working directory like "/work" and programs "a/test", "b/test", etc. Probably need to include also program path replacing slashes with underscores? (Windows vs Linux issues...)

2. Modify -ojunit to have optional `=prefix`. Is it natural to cpputest? Do we need to support `=` vs ` ` (space)? Variations...

3. Introduce new argument like `report-prefix` for the prefix (should it be postfix?).

4. Introduce some variation of `-ojunit`, like `-ojunit-with-prefix <prefix>` that needs extra prefix after the argument...

I'm not sure what to choose. Proposals?

**Comment by basvodde** [comment]
Same test group in same binary, right? Just in different directories?

**Comment by vpod** [comment]
Well... For me different binary name may be fine as well. Just before doing something, better to see what potential usage scenarios may be.
I can guess that someone could have UTs per some component and they may decide to name those like: a_ut, b_ut, or may instead have a/ut and b/ut.
And then something like test group "startup" or similar is very likely to appear in both.
And then some CI may want to just run all UT binaries from the same working directory (e.g. "make check" or similar).
So, we can do something simple, like adding binary name, or binary+path from working directory, or allow custom prefix.
As I wrote, I'm not sure how to decide.

**Comment by basvodde** [comment]
So, you run the different binaries with the same current dir? And in the different binaries is the same test group?

**Comment by vpod** [comment]
Yes, in the case we faced it happens to be like that: same working directory and test group collision between binaries. And so we cannot get full Junit report as only one binary wins.
And in our case binary names are different. But in general case, I'm not sure if this can be assumed.

**Comment by basvodde** [comment]
I would suggest to not add a feature related to this and instead fix this in the build process. You ought to be able to run them from different current dirs relatively easily.

If we do want to fix it, then I would suggest to add -junit-output-dir as parameter or something like that. That seems more useful than a prefix. Though it would lead to additional depdenencies on the file system and I'm not completely happy with that.

**Comment by vpod** [comment]
After some internal discussion, we got a question: why is the package parameter present, but file name is not impacted by package? It seems to have been done exactly for this use case, when test groups collide.
Can we adjust cpputest file name to include package name if provided via existing parameter in command line?

**Comment by basvodde** [comment]
Yeah, I think that would actually make sense....
