### ISSUE TITLE
 IAR 8.10 does not support __attribute__((unused)) unless extensions are enabled.

### ISSUE THREAD

**Issue by watersne** [cpputest/cpputest#1257]
In SimpleString.cpp:
```
#if __cplusplus > 199711L && !defined __arm__
SimpleString StringFrom(const nullptr_t __attribute__((unused)) value)
{
    return "(null)";
}
#endif
```
IAR produces the following output:
```
Error[Pe079]: expected a type specifier Z:\upstream\cpputest\src\CppUTest\SimpleString.cpp 565 
Warning[Pe815]: type qualifier on return type is meaningless Z:\upstream\cpputest\src\CppUTest\SimpleString.cpp 565 
Error[Pe018]: expected a ")" Z:\upstream\cpputest\src\CppUTest\SimpleString.cpp 565 
Error while running C/C++ Compiler 
```

IAR supports the `unused` GCC extension. However, by default in the CppUTest IAR project `C/C++ Compiler -> Language 1 -> Language Conformance` is set to "Standard" instead of "Standard with IAR extensions".

However, it seems like just deleting `__attribute__((unused))` and casting `value` to void would be a more portable solution. That seems to build, but I am not sure if there are other ramifications.

This seems to be related to changes made to resolve #1248 #1232 and #1193.

**Comment by offa** [comment]
> However, it seems like just deleting __attribute__((unused)) would be a more portable solution. That seems to build, but I am not sure if there are other ramifications.

Then compilers warn about the unused parameter. But a cast to void should solve the problem on all compiler.

**Comment by watersne** [comment]
> > However, it seems like just deleting **attribute**((unused)) would be a more portable solution. That seems to build, but I am not sure if there are other ramifications.
> 
> Then compilers warn about the unused parameter. But a cast to void should solve the problem on all compiler.

Thanks, I thought I put the bit about casting to void in my OP, but I didn't. I edited the post.

**Comment by basvodde** [comment]
Fixed, thanks
