### ISSUE TITLE
Return error for zero run tests

### ISSUE THREAD

**Issue by vpod** [cpputest/cpputest#1262]
As discussed in https://github.com/cpputest/cpputest/pull/1254 before, if there are no tests run, cpputest returns 0.
It seems that a lot of persons agree that "0 run" is usually not an expected result.
However, I can come up with situations when CI scripts run a pack of test binaries with some default filters and it is OK if some binary has no tests to run. Example out of my mind: we package all UTs to single executable and then run the executable on many test systems that may or may not have some library or some hardware instruction or co-processor (e.g. AVXnnn algorithm testing and we want to verify the algorithm, but skip in on non-enabled systems in a reliable way). Maybe not the best example, but I hope the point is clear.
We can also have a debate if 0 tests passed out of 0 run is 100% passed or 0% passed. :-)
As I've already faced few times the issue that CI is "green", but runs nothing due to bug in build scripts, I think, this should be addressed.
My proposal is to choose one of these options (I can implement it, but would like to know what to implement):
1. just assume that zero test run is an issue and return error, let caller fix itself to expect that (seems to be the most likely to cause issues);
2. add new parameter, return failure if zero tests run and the parameter _is not_ provided (may need fixing callers during cpputest update);
3. add new parameter, return failure if zero tests run and the parameter _is_ provided (whoever wants the feature has to enable it in the caller);
4. add build configuration flag to choose 2 or 3;
5. add build configuration flag to choose 1 or current behavior.

If I would have to decide, I'd choose 3 or 4 (possibly 3 for simplicity). It seems to be aligned to valgrind's `--error-exitcode=n` (do we want the code to be configurable?).

Could maintainers please give some guidance?

**Comment by basvodde** [comment]
I'm leaning towards 1 as it is the simplest.

Not just return an error but also report an error message probably.

**Comment by vpod** [comment]
Working on it, but takes time as a lot of code assumes "no failed tests = OK"; have to think about each occurrence

Could you please assign to me to avoid duplicate work?

**Comment by vpod** [comment]
@basvodde : seems the #1 does not work even with cpputest's own CMake tests (seen in https://github.com/cpputest/cpputest/pull/1268, Travis CI [link](https://travis-ci.org/cpputest/cpputest/builds/623293846?utm_source=github_status&utm_medium=notification)):
```
68: Test command: /home/travis/build/cpputest/cpputest/cpputest_build/tests/CppUTestExt/CppUTestExtTests "-sg" "IEEE754ExceptionsPlugin2"
68: Test timeout computed to be: 1500
68: !
68: Errors (ran nothing, 510 tests, 0 ran, 0 checks, 1 ignored, 509 filtered out, 0 ms)
68: 
68/70 Test #68: CppUTestExtTests.IEEE754ExceptionsPlugin2 ....................................................***Failed    0.00 sec
```

As you can see, it automatically splits test groups to tests in CTest and some groups have zero tests to run (all ignored). As a result, my change fails the test (quite reasonably).

So, the point is that it seems that restrictions to always treat empty test run (i.e. no tests executed) as failure may be too strict. Probably options 2 or 3 are better (need to decide default to fail or to not fail)

**Comment by vpod** [comment]
@basvodde : can we get back to this please?
I need guidance how to handle this as option #1 did not work easily (it seems likely to be breaking change for many users)

**Comment by basvodde** [comment]
I thought it over some more and still think option #1 is the correct one. What do we need to do to fix our own build?

**Comment by vpod** [comment]
The issue comes from this test group (`tests/CppUTestExt/IEEE754PluginTest.cpp`), I believe:
```c++
static IEEE754ExceptionsPlugin ip;

TEST_GROUP(IEEE754ExceptionsPlugin2)
{
    void setup(void) _override
    {
        TestRegistry::getCurrentRegistry()->installPlugin(&ip);
    }
};

IGNORE_TEST(IEEE754ExceptionsPlugin2, should_not_fail_in_ignored_test)
{
    set_everything_c();
}
```

As a fix I can propose to merge the test to the main test group for the plugin (the same file):
```c++
TEST_GROUP(FE__with_Plugin)
```
But the group uses fixture instead of real test registry, so I'm not 100% sure that it is valid replacement.

**Comment by basvodde** [comment]
If there are no test run but still tests IGNORED, then I would assume that it ought to pass.

**Comment by vpod** [comment]
To summarize: `OK (510 tests, 0 ran, 0 checks, 1 ignored, 509 filtered out, 0 ms)`

1. if `tests` is `0` -> fail;
2. if `ran + ignored` is `0` -> fail. (This covers previous 1 as well as 0 tests will result in 0 ran.)

**Comment by vpod** [comment]
Sorry, for clarity: if there failures also fail as before
