### ISSUE TITLE
Clang-format support

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#1267]
How about supporting clang-format and use it to format the code base?

**Comment by offa** [comment]
@basvodde what's your take on this?

**Comment by basvodde** [comment]
Not sure about it yet. I will check this .. at least his year :)

**Comment by offa** [comment]
I'm here for contributions / help, let me know.

**Comment by basvodde** [comment]
Will do, if the world continues being a mess like it is now, I might end up with more free time than expected. Not the case yet though.

**Comment by offa** [comment]
@basvodde any news on this?

**Comment by basvodde** [comment]
Thanks for picking this up again!
