### ISSUE TITLE
v3.9?

### ISSUE THREAD

**Issue by AlanRosenthal** [cpputest/cpputest#1277]
3.8 was released on May 25, 2016. Any ideas when 3.9 or 4.0 will be released?

**Comment by basvodde** [comment]
Probably 2H this year. So far, most people have been using trunk (I suspect) and the urge to release has been low.

**Comment by AlanRosenthal** [comment]
I personally like releases becuase A) they come with a change log and B) they're typically more stable than the latest commit on trunk

**Comment by basvodde** [comment]
Yah, it will come. Trunk been pretty stable though.

**Comment by AlanRosenthal** [comment]
woohoo!

**Comment by r4nd0m6uy** [comment]
Good to know, we are also eager in having compilers warning fixes from the master branch!

Sorry for duplicating the question ..

**Comment by basvodde** [comment]
On, the way. Will close it.
