### ISSUE TITLE
Mocking input parameters of unknown type

### ISSUE THREAD

**Issue by stefan-misik** [cpputest/cpputest#1281]
Is there a way to mock a function which takes `const void *` input pointer to data of unknown type, so that the type is provided inside a test case rather inside mock function? I would like something like `.withParameterOfType()` but the type should be specified inside test case when defining expected calls.

Closest to the solution of my problem would be `.withMemoryBufferParameter()`, however since the data may be a structure with potentially random data inside member padding sections, a custom comparator is needed.

**Comment by basvodde** [comment]
Hi,

With the OfType, you can create any comparison you want, so it shouldn’t be too hard?

Did you try that yet? You can create type “unknown” :P

Bas

**Comment by stefan-misik** [comment]
Hi, maybe I am missing somethig, but that would not help me much, as the pointer does not carry the information on the actual type either, so the "unknown" comparator wouldn't know how to compare what is being passed to it. One option would be to send that information directly to the comparator from within the test itself, however that could become comlicated, once multiple types need to be compared in single test.

What I enventually ended up doing is this: I asked myself how does the information on the type of the actual object gets to the real version of the mocked function (I am mocking FreeRTOS' functions to send and receive to/from a queue)? - through a handle which is passed to it. So I made my mock handle into a pointer to a structure holding string describing actual comparator to use.

Thank you.
Best regards
