### ISSUE TITLE
CMake build failing

### ISSUE THREAD

**Issue by dipakgmx** [cpputest/cpputest#1282]
I am attempting to build v3.8 using MSVC and CMake. 
The build fails due to the MockSupport_cTestCFile.c. file. Here is the build output:

`Building C object tests/CppUTestExt/CMakeFiles/CppUTestExtTests.dir/MockSupport_cTestCFile.c.obj
MockSupport_cTestCFile.c
C:\cpputest\tests\CppUTestExt\MockSupport_cTestCFile.c(103): error C2220: the following warning is treated as an error
C:\cpputest\tests\CppUTestExt\MockSupport_cTestCFile.c(103): warning C4244: 'function': conversion from 'double' to 'unsigned int', possible loss of data
C:\cpputest\tests\CppUTestExt\MockSupport_cTestCFile.c(107): warning C4244: 'function': conversion from 'double' to 'long', possible loss of data
C:\cpputest\tests\CppUTestExt\MockSupport_cTestCFile.c(111): warning C4244: 'function': conversion from 'double' to 'unsigned long', possible loss of data`

Incidentally, this was fixed with [#1015](https://github.com/cpputest/cpputest/pull/1015), but over written with commit [83658bb](https://github.com/cpputest/cpputest/commit/83658bbda96c1a914a19eb20967264c2303b9a63).

**Comment by offa** [comment]
Does this fail on master too?

**Comment by dipakgmx** [comment]
I guess it works on the master since the [CMakeLists.txt](https://github.com/cpputest/cpputest/blob/master/CMakeLists.txt) has this line included.

> option(WERROR "Compile with warnings as errors" OFF)

**Comment by offa** [comment]
But the warning still appears?

**Comment by dipakgmx** [comment]
No warnings are issued now.

**Comment by offa** [comment]
Since v3.8 is outdated, better use master.
