### ISSUE TITLE
CRLF/LF issue with autoreconf on Windows/cygwin

### ISSUE THREAD

**Issue by jhugh95** [cpputest/cpputest#1286]
When I clone cpputest and attempt to run `autoreconf -i` in the cygwin64 terminal I get the following:

```
$ autoreconf -i
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: copying file './ltmain.sh'
libtoolize:   error: AC_CONFIG_MACRO_DIRS([m4]) conflicts with ACLOCAL_AMFLAGS=-. m4
autoreconf-2.69: libtoolize failed with exit status: 1
```

From googling, my understanding of this error is that it's almost always a line endings problem in the makefile. So, I opened makefile.am in notepad++, which indicated it was using CRLF. I used notepad++ to change makefile.am to LF and saved the file. When I ran `autoreconf -i` again, it completed successfully. The 'configure' script also completed successfully, 'make' ran successfully, and my pre-existing cpputest project linked successfully and ran tests. This is obviously not ideal, as it requires modifying the source to get a successful build.

I'm pretty bewildered why I need to change makefile.am to LF endings for autoreconf to work on windows with cygwin, especially since I took a look at the git blame for .gitattributes and saw that there was a [merged PR 8 months ago](https://github.com/cpputest/cpputest/pull/1229) which specifically did the opposite, forced *.am files to CRLF. To be honest I have very little knowledge of Unix systems, so all I can really do at this point is post the issue and hope someone else knows what this means.

**Comment by basvodde** [comment]
@Jak-o-Shadows any idea why the pull request wasn't auto in the gitattributes ?

**Comment by basvodde** [comment]
I'll try changing them to auto. But I'm a bit puzzled why this didn't show earlier as we run autoconf in the Appveyor windows build.

**Comment by basvodde** [comment]
Changed to auto.
