### ISSUE TITLE
Question: Is CppuTest usable for Bare Metal embedded development?

### ISSUE THREAD

**Issue by stefaneicher** [cpputest/cpputest#1287]
Hi,
I would like to use a test framework with which we can run test on the hardware. We have no OS. So my question is CppuTest can be run on a bare metal embedded device?

Regards Stefan

**Comment by basvodde** [comment]
Yes, although there might be a problem with memory usage of CppUTest itself.

You will need to create a new "Platform" and implement all of the dependencies to Standard C (they are all separated out). We tried to minimize these, so it shouldn't be a huge amount of work.

**Comment by stefaneicher** [comment]
ok thanks for the answer. We try to get cpputest running on our https://www.st.com/en/evaluation-tools/nucleo-f411re.html
let me know if you are aware of some helpfull tips.

**Comment by basvodde** [comment]
I'd check what is there already. IAR and Keil support was implemented earlier, I believe. You'll mostly ought to check the "Platform" directories which is where all the dependencies to platform and Standard C are.

**Comment by basvodde** [comment]
I updated trunk last week to move a few standard C functions that had sneaked into he codebase to the PlatformSpecific functions. So the current trunk ought to be better than 2 weeks ago.
