### ISSUE TITLE
New minor release?

### ISSUE THREAD

**Issue by r4nd0m6uy** [cpputest/cpputest#1300]
The release 3.8 is already 4 years old! There are a lot of compilers warnings especially for clang that were fixed in the latest master that we would be happy to benefit!

Is there any plan for a new release, even minor such as 3.8.1?

Other than that, I would like to congratulate and thank for the awesome work, I have been using CppUTest in most of my projects flawlessly and has always been working great!

**Comment by basvodde** [comment]
Hi Random Guy :)

It should be soon. There are a couple of things I'd like to fix.

**Comment by r4nd0m6uy** [comment]
Great, I've just saw there was already an issue for that, sorry for the duplicate!

All the best!

**Comment by r4nd0m6uy** [comment]
Duplicate #1277
