### ISSUE TITLE
Travis CI doesn't report build status

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#1303]
As mentioned in #1294, Travis CI is broken and doesn't report the build status back to Github. The build is actually executed, but now status is shown on PRs, commits or branches.

Unfortunately this may hide build failures as typically none visits the builds' page.

I have experienced this on other projects too, but typically the issue went away after some time. 

- https://travis-ci.community/t/ci-passed-on-travis-but-not-updating-github-pull-requests/8056
- https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798

**Comment by offa** [comment]
For whatever reasons, Travis started reporting the build results again. At least for all commits since 0f01550602c44aa54f6f455ab8f7801808cfd0ab.

**Comment by basvodde** [comment]
Maybe it was because it was red too long ?

**Comment by offa** [comment]
I don't think so. I guess there are still some issues with travis <--> Github integration.
