### ISSUE TITLE
No rule to make target 'build/cmake_package_files/CppUTestConfig.cmake',

### ISSUE THREAD

**Issue by shibinkr** [cpputest/cpputest#1344]
In this commit 5d8e7037445601d6a4ff83504331d2adc853d89a

causing make to break.
ranlib lib/libCppUTestExt.a
make[1]: *** No rule to make target 'build/cmake_package_files/CppUTestConfig.cmake', needed by 'all-am'.  Stop.
make[1]: Leaving directory '/home/skoikkar/Documents/cpk/src/test/cpputest'
Makefile:951: recipe for target 'all' failed

Steps to reproduce.
./autogen.sh
./configure
make

**Comment by jbrandeb** [comment]
This has broken our automated builds as well.

**Comment by jbrandeb** [comment]
Reverting this commit makes the problem go away.

**Comment by basvodde** [comment]
Should be fixed now.
