### ISSUE TITLE
CppUTest does not build via CMake using GCC 8.2.0 (mingw)

### ISSUE THREAD

**Issue by nacansino** [cpputest/cpputest#1405]
### Issue
CppUTest does not build via CMake using GCC 8.2.0 (MinGW) on Windows.

I am trying to build CppUTest using CMake as indicated in Readme.  I am using the exact CMakeLists script.

```
 include(FetchContent)
    FetchContent_Declare(
        CppUTest
        GIT_REPOSITORY https://github.com/cpputest/cpputest.git
        GIT_TAG        latest-passing-build # or use release tag, eg. v3.8
    )
    # Set this to ON if you want to have the CppUTests in your project as well.
    set(TESTS OFF CACHE BOOL "Switch off CppUTest Test build")
    FetchContent_MakeAvailable(CppUTest)

```

I am getting a localtime_s, fopen_s not found error on the build message.
```
[build] C:\Users\niel.cansino\XTX3_RH850EVM\build\_deps\cpputest-src\src\Platforms\Gcc\UtestPlatform.cpp: In function 'const char* TimeStringImplementation()':
[build] C:\Users\niel.cansino\XTX3_RH850EVM\build\_deps\cpputest-src\src\Platforms\Gcc\UtestPlatform.cpp:216:5: error: 'localtime_s' was not declared in this scope
[build]      localtime_s(&lastlocaltime, &theTime);
[build]      ^~~~~~~~~~~
[build] C:\Users\niel.cansino\XTX3_RH850EVM\build\_deps\cpputest-src\src\Platforms\Gcc\UtestPlatform.cpp:216:5: note: suggested alternative: 'localtime'
[build]      localtime_s(&lastlocaltime, &theTime);
[build]      ^~~~~~~~~~~
[build]      localtime
[build] C:\Users\niel.cansino\XTX3_RH850EVM\build\_deps\cpputest-src\src\Platforms\Gcc\UtestPlatform.cpp: In function 'void* PlatformSpecificFOpenImplementation(const char*, const char*)':
[build] C:\Users\niel.cansino\XTX3_RH850EVM\build\_deps\cpputest-src\src\Platforms\Gcc\UtestPlatform.cpp:242:4: error: 'fopen_s' was not declared in this scope
[build]     fopen_s(&file, filename, flag);
[build]     ^~~~~~~
[build] C:\Users\niel.cansino\XTX3_RH850EVM\build\_deps\cpputest-src\src\Platforms\Gcc\UtestPlatform.cpp:242:4: note: suggested alternative: 'fopen'
[build]     fopen_s(&file, filename, flag);
[build]     ^~~~~~~
[build]     fopen
```

Upon further researching on this matter, this seems that the compiler does not support the aforementioned methods. I tried changing my kit to Clang 3.9.1, and it passes the build.
I'm curious at it was indicated in the Appveyor that the code builds on various MINGW Platform Toolset. What does the 4.8.x and 5.3.x indicate? Obviously they are not the GCC versions. A little bit of enlightenment is appreciated! Thank you.

**Comment by basvodde** [comment]
Interesting. I know where they come from and how to probably fix that :)

However, I'm first interested in failing the AppVeyor (or travis) build on this. Any suggestions? Just change to gcc?

**Comment by offa** [comment]
Shouldn't adding a appveyer build of the mentioned gcc version be enough? From what I've seen there are already builds of earlier mingw gcc version.

**Comment by nacansino** [comment]
@basvodde Thank you for responding to this.

Quoting @offa, I'm also thinking of the same thing. The 4.8.x, and 5.3.x in the AppVeyor/Travis, they are the GCC versions, are they not?

> Shouldn't adding a appveyor build of the mentioned gcc version be enough? From what I've seen there are already builds of earlier mingw gcc version.

Another thing. I just noticed today that build is also failing on GCC 9.2.0 (mingw.org). However, it builds on GCC 8.1.0 (mingw-w32.org). Could it be that I am on x64 machine that my system does not have the _s functions? Hmm..

**Comment by basvodde** [comment]
@nacansino If not, then we'll need to find out how to discover their absence.

In the code, it says:

#ifdef _WIN32
    static struct tm lastlocaltime;
    localtime_s(&lastlocaltime, &theTime);
    struct tm *tmp = &lastlocaltime;
#else
    struct tm *tmp = localtime(&theTime);
#endif

So, the code for not using the _s function is there! However, it detected that you are on W32 and thus have the _s functions. Clearly ... that is not true :)

**Comment by nacansino** [comment]
@basvodde Now that's interesting! I just verified that I'm indeed using a 64-bit Windows. Why is it then that the compilation enters the _WIN32? Hmm.

I have a lot of mingw/mingw-w32/64 kit in both my office and home PCs. I'll verify the case for all of the versions to pinpoint the problem.

**Comment by basvodde** [comment]
Yes, WIN32 just checks whether you run on Windows. The code assumes windows has the _s versions of the functions. This is because not using them will cause a warning on Windows.... (clearly not for you, using them causes an error :P)

**Comment by nacansino** [comment]
I checked the time.h of my mingw for two separate terminals (GCC 8.2.0 and 9.2.0), and of my mingw-w64 installation. It seems that the former does not have the _s variants in them, only the _32 or _64 ones.
I haven't used AppVeyor yet, but I suspect they are only checking the build for the latter (mingw-w64), hence the passing result.

**Comment by nacansino** [comment]
I verified that the package manager used by `AppVeyor`, which is [chocolatey](https://chocolatey.org/packages/mingw) only seems to have [mingw-w64](http://mingw-w64.org/doku.php). `chocolatey` seems to not have [mingw](http://mingw.org/) in their package repository. Moreover, I also do not see the need to support the latter, as the former community seems to be more proactive in integrating their compiler to more recent tools.

That being said, I am closing this issue. Thanks @basvodde and @offa for responding!

**Comment by basvodde** [comment]
But why close the issue? I would love to make a change so we can detect this case and build properly. The code is already there, so it should be a question of finding the right #define.

**Comment by nacansino** [comment]
Oops, sorry about that! Reopening the issue.

Anyway, I tried bypassing the #define to use the non-_s variant, but I instead get the following linker error:
```
[build] c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../libmingw32.a(mbrscan.o):(.text+0xb6): undefined reference to `SetLastError@4'
[build] c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../libmingw32.a(wcharmap.o):(.text+0x208): undefined reference to `WideCharToMultiByte@32'
[build] c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../libmingwex.a(codeset.o):(.text+0xbe): undefined reference to `GetCPInfo@8'
[build] c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../libmingwex.a(codeset.o):(.text+0x143): undefined reference to `GetCPInfo@8'
[build] collect2.exe: error: ld returned 1 exit status
```

I will try to look deeper into this. Right now, a quick Google search won't give me any useful leads; in fact, there is a very recent question on [StackOverflow](https://stackoverflow.com/questions/62154803/what-does-undefined-reference-to-setlasterror4-mean) about 9 days ago about this.

**Comment by basvodde** [comment]
I've just done a pull request with a small change. Can you try to compile that ?

**Comment by nacansino** [comment]
I tried it. While it made the compiler use the non-_s variant as expected, it resulted in the same linker error as my earlier comment.

**Comment by basvodde** [comment]
Ok, these linker errors do not seem to be CppUTest related at all though....

**Comment by basvodde** [comment]
Ok, I merged the pull request as it seems to still use the _s variants when available. I don't know about the linker errors yet.

**Comment by basvodde** [comment]
This suggests: https://stackoverflow.com/questions/62161702/mingw-gcc-linker-complains-when-using-std-option-flag

Either add -lwin32 or update mingw...

**Comment by nacansino** [comment]
> This suggests: https://stackoverflow.com/questions/62161702/mingw-gcc-linker-complains-when-using-std-option-flag
> 
> Either add -lwin32 or update mingw...

Exactly... since mingw-w32 (and mingw-w64) works perfectly, we might as well avoid using the mingw.org variant when compiling CppUTest. What do you think?

**Comment by basvodde** [comment]
Yup, well, the CppUTest-part is now fixed. This linker error doesn't seem related :)

Close now?

**Comment by nacansino** [comment]
Yes! Thanks for dealing with this.
