### ISSUE TITLE
Cpputest fails to build for IAR - missing rand/srand definitions

### ISSUE THREAD

**Issue by sm-github-work** [cpputest/cpputest#1412]
I am building cpputest using IAR EWARM 8.50.  The build fails with missing definitions.

I had to add the following code to Iar/UtestPlatform.cpp:

```
void (*PlatformSpecificSrand)(unsigned int) = srand;
int (*PlatformSpecificRand)(void) = rand;
```

I don't see any CONTRIBUTING documentation, so I'm not sure of the guidelines for making pull requests.

**Comment by basvodde** [comment]
This one is fixed now, right?

**Comment by sm-github-work** [comment]
Yes, this is fixed by https://github.com/cpputest/cpputest/pull/1417/commits/4d53a449ad30be85bd08623d76669496d7d6fe54
