### ISSUE TITLE
Break into debugger on failure, instead of crashing

### ISSUE THREAD

**Issue by TheSoftwareGuy** [cpputest/cpputest#1415]
Usually when TDDing, you want know know from the outset about *all* the tests that fail, and because of this it is usually discouraged to have any `mock().crashOnFailure` checked into the source code. but when developing and iterating on a test/series of tests you want the tests to crash so you can observe everything in a debugger. But it becomes annoying to have to re-compile the tests just to use the debugger properly.

I suggest that the framework could try to break into a debugger without seg-faulting, as the Catch2 framework does with the `--break` [flag](https://github.com/catchorg/Catch2/blob/master/docs/command-line.md#breaking-into-the-debugger.)
 They do this with the CATCH_BREAK_INTO_DEBUGGER macro, which tries to use some platform-specific asm magic to force a breakpoint in the debugger: https://github.com/catchorg/Catch2/blob/bad3c930493d08dd7cca2af57cf355d9b7cddb21/include/internal/catch_debugger.h#L59

**Comment by CiderMan** [comment]
I second the proposal for something like this. While we TDD in places, a lot of our code was written before our unit-test framework was put in place and, as a result, debugging a test failure can be quite involved. Several devs have requested that the framework trigger the JIT debugger when the test fails when running in debug mode - they currently have to run it from the debugger, insert breakpoints, etc., which is doable but this option would certainly make it easier and quicker.

I've spent some time looking (Googling and looking at the source code) into this (I would be happy if this were compile-time even) but can't see anything. It looks like a custom TestTerminator object would do this but I can't see how to use any implementation other than the default.

**Comment by stephen-d-hill** [comment]
Was requested some time ago in [https://github.com/cpputest/cpputest/issues/1012](https://github.com/cpputest/cpputest/issues/1012)

**Comment by CiderMan** [comment]
For traceability, the mailing list thread is [here](https://groups.google.com/g/cpputest/c/YccLe8MaGUU)

**Comment by TheSoftwareGuy** [comment]
At the very least, it would be really great if "crashOnFailure" could be enabled/disabled via command line flag. It's a bit annoying to have to recompile every time I want to change that behavior

**Comment by CiderMan** [comment]
@basvodde, I believe that this issue can now be closed.
