### ISSUE TITLE
Document and valgrind the -p option

### ISSUE THREAD

**Issue by basvodde** [cpputest/cpputest#142]
So far, -p has been a "hidden feature" for running the tests in a separate process. It is quite a lot slower and depends on the platform. It might be good to actually document it, add it to the build and also see if we can resolve the valgrind warnings on the -p run.

**Comment by TafThorne** [comment]
Is this hinting that the `-p` option must be used when looking at memory options with either Dr. Memory or Valgrind?  I certainly get very different results when I use it with my own unit test sets or those performed by CppUTest's `make check` process.  I see something very like #1024 (and other stuff) when I do not use the -p option.

**Comment by basvodde** [comment]
I think this was for making sure that valgrind didn't give errors with the -p option. But it has been a while.

**Comment by TafThorne** [comment]
I get errors either way.  I shall try and setup a nice test case to demo my problem and make sure it is not some junk in my build system.  If that works I will try to make a new ticket that explains my difficulties.

**Comment by basvodde** [comment]
Its documented, closing this for now.
