### ISSUE TITLE
Docs refer to seemingly non-existent MemoryLeakWarningPlugin::turnOnNewDeleteOverloads()

### ISSUE THREAD

**Issue by claremacrae** [cpputest/cpputest#1428]
http://cpputest.github.io/manual.html#memory_leak_detection has a code example:

```cpp
void setup()
{
    MemoryLeakWarningPlugin::turnOffNewDeleteOverloads();
}

void teardown()
{
    MemoryLeakWarningPlugin::turnOnNewDeleteOverloads();
}
```

In the v4.0 source, there is no method `MemoryLeakWarningPlugin::turnOnNewDeleteOverloads()`.

Also, `turnOnNewDeleteOverloads` does not appear anywhere in the source code for that release.

**Comment by basvodde** [comment]
Ok, fixed. It changed to save and restore.
