### ISSUE TITLE
`make test` hides nonzero return codes

### ISSUE THREAD

**Issue by mtfurlan** [cpputest/cpputest#1443]
I recently learned that if you make a test case that divides by 0 the test binary will crash, which is to be expected.
The problem is that `make test` returns 0 (meaning success), and the only difference while glancing at the output is that the green `OK` was replaced by an uncoloured `Floating point exception` that just blends in with the other uncoloured text.

Returning 0 here is quite suboptimal, I'd really like any nonzero return code and maybe even some red text.

I run tests via `make test` (or in CI by having `junit: CPPUTEST_EXE_FLAGS := $(CPPUTEST_EXE_FLAGS) -o junit` and running `make junit`)

I'm running cpputest from [master from a few weeks ago](https://github.com/cpputest/cpputest/commit/887621db6c7cb6a9bd25e6fee90be22b352b296c).
I did check current master and it does the same thing.

Proposed fix approach:
In `MakefileWorker.mk` change the test and vtest targets to be something along the lines of
```
TEST_RETURN_CODE=/tmp/foo
test: $(TEST_TARGET)
        ($(RUN_TEST_TARGET); echo $$? > $(TEST_RETURN_CODE)) | tee $(TEST_OUTPUT)
        @ret=$$(cat $(TEST_RETURN_CODE)); rm $(TEST_RETURN_CODE); if [ "$$ret" -ne 0 ]; then echo "$$(tput setaf 1)$(TEST_TARGET) returned $${ret}$$(tput sgr0)"; fi; exit $$ret
```
I don't like the hardcoded filename or how hard the shell script is to read, but it's working on my debian machine and a coworkers cygwin.

**Comment by basvodde** [comment]
Thanks. Just to be sure. The make test you run is not with the autotools or cmake build then?

**Comment by mtfurlan** [comment]
I'm not quite sure what you're getting at.
I have cpputest as a git submodule, and I build it with 
```
./autogen.sh
./configure
make check
```
Then in my makefile I set `CPPUTEST_HOME` and other variables documented in MakefileWorker before including MakefileWorker.
If you want I can clean up and post my entire makefile that includes MakefileWorker?

**Comment by basvodde** [comment]
Ah ok, no, this makes it clear :)

The proposed solution looks a bit complicated. Also, I'm worried about the cross-platform-ness of it. There ought to be an easier solution, right?

**Comment by mtfurlan** [comment]
It seems like there should be, but I couldn't think of it.
If you have any suggestions I can try to implement something different.

**Comment by mtfurlan** [comment]
Well, it's been working at $work for a while now, on a mix of debian, osx, and cygwin.

**Comment by basvodde** [comment]
You can make a pull request. The CppUTest build works on several systems and we can see what it thinks of it.
