### ISSUE TITLE
Buy you a coffee

### ISSUE THREAD

**Issue by r4nd0m6uy** [cpputest/cpputest#1448]
Hallo CppUtest maintainers!

Sorry for bloating the issues tracker but I didn't find any other way to contact you.

We are using CppUTest heavily and are very happy with it! To thank you we would like to make a small donation but we didn't find any link to do so. How could we proceed?

All the best!

**Comment by basvodde** [comment]
It is always nice to get appreciations from a random guy.

I guess you can buy @jwgrenning his book of appreciation... and also learn something :)

Other than that, I can say, thanks.... but we have no way to donate. Spread the word would be the best donation.

**Comment by r4nd0m6uy** [comment]
Thanks for your quick reply. Unfortunately, I've already own and read the book more than once. What a pitty, I will spread the word!

**Comment by basvodde** [comment]
Hah, well you can read my books then instead :P They are a bit less code focused. :)
