### ISSUE TITLE
Update this project for the addition of CppUTest to Conan Center

### ISSUE THREAD

**Issue by claremacrae** [cpputest/cpputest#1449]
Now that CppUTest is in Conan Center, what updates should be made to this repo?

Options:

* [x] Document how to consume the package, in CMake and possible other generators too
* [ ] Document what needs to be done in conan-center-index to add any future new releases of this project

**Comment by claremacrae** [comment]
See the related ticket: https://github.com/cpputest/conan-cpputest/issues/22

**Comment by offa** [comment]
> Document what needs to be done in conan-center-index to add any future new releases of this project

I don't see this as part of the CppuTest project. Additionally, Conan Center provides related docs already.

**Comment by claremacrae** [comment]
> > Document what needs to be done in conan-center-index to add any future new releases of this project
> 
> I don't see this as part of the CppuTest project. Additionally, Conan Center provides related docs already.

OK, that's a fair point... Perhaps instead a reminder that when a new release is done, the recipe in Conan-center-index should be updated...

The text I would have added would mainly have said to follow Conan's PR procedure add the new version to these two files:

* https://github.com/conan-io/conan-center-index/blob/master/recipes/cpputest/config.yml
* https://github.com/conan-io/conan-center-index/blob/master/recipes/cpputest/all/conandata.yml

**Comment by offa** [comment]
I'm working on a conan example for the readme.

Btw. huge thanks to you @claremacrae for getting CppUtest into conan-center.

**Comment by claremacrae** [comment]
> I'm working on a conan example for the readme.

Oh that's great news - thanks very much!

> Btw. huge thanks to you @claremacrae for getting CppUtest into conan-center.

You're very welcome... it took some persistence, but I learned a lot along the way! 😄

**Comment by bryceschober** [comment]
I was going to suggest that we should add a conan badge to CppUTest... but it seems that maybe that isn't yet supported.

**Comment by offa** [comment]
> I was going to suggest that we should add a conan badge to CppUTest... but it seems that maybe that isn't yet supported.

Already added a few minutes ago. But yeah, no official one available yet.

**Comment by offa** [comment]
I've updated to badge, it shows the current version now.

**Comment by claremacrae** [comment]
What remains on this is to decide if/how to write up how to update the files in Conan-center-index when new releases of this project are made...

There was a discussion about about whether to do this - and what it might say.

@basvodde Thanks for merging the docs. I'd like to get this issue closed - so would appreciate knowing your thoughts on this...  I'd be happy for you to just ping me, to ask me to update the Conan recipe, if you wanted to just note that...

**Comment by basvodde** [comment]
Yup, just pinging you is good. Honestly, we are usually not very organized around that and just have people pick it up (like you did so far). I tend to update the Homebrew package and the Debian package... but leave most others for whomever picks it up at that time. Will that do?

**Comment by claremacrae** [comment]
Great - thanks... I'll close this ticket then.
