### ISSUE TITLE
Clang version checking bugs

### ISSUE THREAD

**Issue by mtfurlan** [cpputest/cpputest#1456]
I saw an error `/bin/sh: 1: [[: not found` and traced it to how `CLANG_VERSION_NUM_GT_700` is getting set.
Turns out the entire clang version checking stuff doesn't work on my system.

A sampling of the output of `clang++ -v 2>&1 | head -n1`:
* my debian buster with clang from apt:
  * `clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)`
* coworkers macs with clang from xcode:
  * `Apple clang version 11.0.3 (clang-1103.0.32.62)`
  * `Apple clang version 12.0.0 (clang-1200.0.32.2)`
* [random ubuntu people](https://askubuntu.com/questions/561750/how-i-know-what-version-of-clang-i-have-installed):
  * `Ubuntu clang version 3.5-1ubuntu1 (trunk) (based on LLVM 3.5)`
  * `Ubuntu clang version 11.0.0-++20200916113328+8f2c29681ce-1~exp1~20200916094014.99`

`CLANG_VERSION` is set by putting that through [`grep -o 'clang-[0-9][0-9][0-9]*.'`](https://github.com/cpputest/cpputest/blob/master/build/MakefileWorker.mk#L205)
In the end, `CLANG_VERSION_NUM` has `1103` on my coworkers mac, empty for my debian, and empty for the ubuntu strings.

The best idea I have is replace the grep with
`sed -n 's/.* \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' | sed 's/\.//g'`
Works for everything except the first ubuntu example, which is from before 7, so the end check of "is it greater than 7.0.0" will be false, which is correct.

Also, clang 12 added `-Wno-poison-system-directories`, so it would be cool if we could add a second check for that.

Going back to the reason I was looking at this, on my debian  `$(shell whatever)` runs whatever with sh, not bash, and sh doesn't believe in `[[`.
`[` does support `-ge` though, so I don't see any reason not to change
```diff
-CLANG_VERSION_NUM_GT_700 := $(shell [[ $(CLANG_VERSION_NUM) -ge 700 ]] && echo Y)
+CLANG_VERSION_NUM_GT_700 := $(shell [ "$(CLANG_VERSION_NUM)" -ge 700 ] && echo Y)
```

**Comment by basvodde** [comment]
Cool, thanks.

Do you think you can make the proposed change in a pull request?
