### ISSUE TITLE
Typecasting in test macros

### ISSUE THREAD

**Issue by stefan-misik** [cpputest/cpputest#1461]
Is there a reason why the type casting in test macros is done without enclosing the macro argument in parentheses as follows:

https://github.com/cpputest/cpputest/blob/51e34fea879f65b5cd5cb311bd91b4246db3c32b/include/CppUTest/UtestMacros.h#L226-L227

As opposed to following:

```cpp
#define UNSIGNED_LONGS_EQUAL_LOCATION(expected, actual, text, file, line)\ 
   do { UtestShell::getCurrent()->assertUnsignedLongsEqual((unsigned long)(expected), (unsigned long)(actual), text, file, line); } while(0) 
```

This would improve following situation:
Lets say I want to test against a difference in two pointers e.g.:

```cpp
TEST(Buffer, Test)
{
    char * buffer = tested_fn();
    char * buffer2 = tested_fn();
    UNSIGNED_LONGLONGS_EQUAL(5, buffer2 - buffer);
}
```

I can of course add the parentheses myself into the test code, however it feels surprising that I have to do that and it would help new users not to potentially debug not-very-helpful compilation error (saying that I am trying to subtract two incompatible types).

**Comment by basvodde** [comment]
No reason I can imagine :)

Would be good to have them and some tests around it.

**Comment by stefan-misik** [comment]
Sorry, I've just realized it is already implemented in the top-level macros. I just need to update to the latest CppUTest.
