### ISSUE TITLE
Travis .org needs migration to .com before the end of May 2021

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#1467]
https://blog.travis-ci.com/2021-05-07-orgshutdown

> This means that any repositories you currently have connected to travis-ci.org must be migrated over to travis-ci.com before the end of May 2021 if you want your builds to continue without interruption. _**To do this you can simply sign up to travis-ci.com and link the repositories that you want to migrate.**_ Your existing configurations will work as expected on travis-ci.com and you do not need to alter your build definitions. Alternatively, there’s a migration feature, which will allow transferring a limited amount of build history data from travis-ci.org to travis-ci.com.

**Comment by basvodde** [comment]
Thanks, trying... 

Sorry, I've been so busy with other things. I think we will seriously need to look for a maintainer to help us with CppUTest :)

**Comment by basvodde** [comment]
Done

**Comment by offa** [comment]
Thanks!
