### ISSUE TITLE
Won't install on Cygwin

### ISSUE THREAD

**Issue by lenerdv2005** [cpputest/cpputest#1468]
I'm trying to install on windows 10 using cygwin. I've tried 2 methods:

1. The "official" one, at [https://cpputest.github.io/](https://cpputest.github.io/), which errors `error: AC_CONFIG_MACRO_DIRS([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4` when I run `autoreconf .. -i` (which, [if I've understood correctly](https://github.com/cpputest/cpputest/issues/1286#issuecomment-616940268), should have been fixed)
2. Following [this set](https://apmcgregor.com/index.php/2020/05/12/installing-cpputest-on-windows-10/) of unofficial instructions, which becomes useless when running `make` says `*** No targets specified and no makefile found.  Stop.`.

Any solutions?

**Comment by basvodde** [comment]
I did a quick google for you related to (1). Could you check this: https://stackoverflow.com/questions/47582762/ac-config-macro-dirsbuild-aux-m4-conflicts-with-aclocal-amflags-i-build-aux

**Comment by lenerdv2005** [comment]
Running `dos2unix Makefile.am` in the `cpputest` directory fixed it, now it complains that `'configure.ac' or 'configure.in' is required`, even though there's a `configure.ac` right besides it.

**Comment by basvodde** [comment]
Do the same ? It seems your line endings are messed up... but not understand why that is.

**Comment by basvodde** [comment]
Can you run the autoreconf from the directory that the files are instead of the ..

**Comment by lenerdv2005** [comment]
worked, thanks!
