### ISSUE TITLE
cpputest.github.com link is dead

### ISSUE THREAD

**Issue by KulaGGin** [cpputest/cpputest#1479]
The link in the About section is dead:
![chrome_cbk8OJmBcu](https://user-images.githubusercontent.com/16989713/126644780-cb8f4338-76de-4df5-95e9-1922587f7db3.png).

It was probably ported to https://cpputest.github.io/, but it wasn't updated anywhere on this github repo.

**Comment by basvodde** [comment]
Thanks, fixed
