### ISSUE TITLE
MemoryLeakDetection doesnt work with mingw64

### ISSUE THREAD

**Issue by neubertm** [cpputest/cpputest#1504]
### MemoryLeakDetection
I have problem with memoryleakdetection when i compile with mingw64.

### Windows tools
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

### How i compile library
Download cpputest lib as zip.
Using cmake:
mkdir mingw64_build
cd mingw64_build
cmake .. -G "MinGW Makefiles" / in cygwin only cmake ..
mingw32-make                          / in cygwin make

Static libraries and test software is compiled and linked properly. But there is different num of test between cyg and mingw versions.

When i use function malloc in code or in test and i do not deallocate, test does no detect any problem.
An return value from testapp is zero and report no problem in tests.

When i use same test under cygwin or linux i got information about memoryleak and memory dump.

Other functionality looks corrrect.
Should i turn off something special for mingw?

Thanks
Milan

**Comment by basvodde** [comment]
Ok, thanks for closing again!
