### ISSUE TITLE
Borland v5.4 throws a runtime error on division by zero: TestFailureNaNTest

### ISSUE THREAD

**Issue by pjshelton** [cpputest/cpputest#1544]
The Borland v5.4 compiler does not have a NaN or Inf .
if one wants the program to catch the division by zero  error, and not crash, it has to contain an signal handler that catches the exception and deal with it itself. 
From the help file:
>For / and %, op2 must be nonzero op2 = 0 results in an error. (You can't divide by zero.)

For  tests/CppUTests/TestFailureNaNTest.cpp this means that the program does not get past these lines.
```
static double zero = 0.0;
static double one = 1.0;
static double not_a_number = zero / zero;
static double infinity = one / zero;
```
As the rest of this file is about how the compiler compares numbers to NaN and Inf.  I propose that we remove the reference to this file when compiling with the Borland compiler.

I suggest we do this with generator expressions.  

This is part of #1493

**Comment by pjshelton** [comment]
Using generator expressions in ```cpputest\tests\cppUTest\CMakeLists.txt``` gives 
```
set(CppUTestTests_src
    AllTests.cpp
    SetPluginTest.cpp
    CheatSheetTest.cpp
    SimpleStringTest.cpp
    SimpleStringCacheTest.cpp
    CompatabilityTests.cpp
    CommandLineArgumentsTest.cpp
    TestFailureTest.cpp
    $<$<NOT:$<CXX_COMPILER_ID:Borland>>:TestFailureNaNTest.cpp>
    CommandLineTestRunnerTest.cpp
    TestFilterTest.cpp
    TestHarness_cTest.cpp
    JUnitOutputTest.cpp
    TestHarness_cTestCFile.c
    DummyMemoryLeakDetector.cpp
    MemoryLeakDetectorTest.cpp
    TestInstallerTest.cpp
    AllocLetTestFree.c
    MemoryOperatorOverloadTest.cpp
    TestMemoryAllocatorTest.cpp
    MemoryLeakWarningTest.cpp
    TestOutputTest.cpp
    AllocLetTestFreeTest.cpp
    TestRegistryTest.cpp
    AllocationInCFile.c
    PluginTest.cpp
    TestResultTest.cpp
    PreprocessorTest.cpp
    TestUTestMacro.cpp
    TestUTestStringMacro.cpp
    AllocationInCppFile.cpp
    UtestTest.cpp
    SimpleMutexTest.cpp
    UtestPlatformTest.cpp
    TeamCityOutputTest.cpp
)
```

or we wrap from line 37 or the end of ```cpputest\tests\cppUTest\TestFailureNaNTest.cpp```
in a capability switch.  

```
#if defined HAS_NAN and defined HAS_INF

...

#endif
```

**Comment by basvodde** [comment]
I'm not sure I understand the generator expression, I thought we were going for the capability switch (probably prefixed with CPPUTEST)

**Comment by pjshelton** [comment]
Happy to do the switch thing

**Comment by pjshelton** [comment]
#1552 is the first of two PR that help CppUTest to compile under the Borland compiler.
