### ISSUE TITLE
Borland v5.4 throws a runtime error on division by zero: tests\CppUTest\UtestTest.cpp

### ISSUE THREAD

**Issue by pjshelton** [cpputest/cpputest#1545]
This is similar to #1544 
The Borland v5.4 compiler does not have a NaN or Inf .
if one wants the program to catch the division by zero  error, and not crash, it has to contain an signal handler that catches the exception and deal with it itself. 
From the help file:
>For / and %, op2 must be nonzero op2 = 0 results in an error. (You can't divide by zero.)

For  tests/CppUTests/UtestTest.cpp this means that the following test fails with a NUMERICAL error. 
```
static volatile double zero = 0.0;

TEST(UtestShell, compareDoubles)
{
    double not_a_number = zero / zero;
    double infinity = 1 / zero;
    CHECK(doubles_equal(1.0, 1.001, 0.01));
    CHECK(!doubles_equal(not_a_number, 1.001, 0.01));
    CHECK(!doubles_equal(1.0, not_a_number, 0.01));
    CHECK(!doubles_equal(1.0, 1.001, not_a_number));
    CHECK(!doubles_equal(1.0, 1.1, 0.05));
    CHECK(!doubles_equal(infinity, 1.0, 0.01));
    CHECK(!doubles_equal(1.0, infinity, 0.01));
    CHECK(doubles_equal(1.0, -1.0, infinity));
    CHECK(doubles_equal(infinity, infinity, 0.01));
    CHECK(doubles_equal(infinity, infinity, infinity));
    double a = 1.2345678;
    CHECK(doubles_equal(a, a, 0.000000001));
}
```
How should we remove this one test when compiling with Borland v5.4?

This is part of #1493

**Comment by pjshelton** [comment]
There are in fact only three of those CHECKs that have any chance of passing.
```
    CHECK(doubles_equal(1.0, 1.001, 0.01));
    CHECK(!doubles_equal(1.0, 1.1, 0.05));
    double a = 1.2345678;
    CHECK(doubles_equal(a, a, 0.000000001));
```

**Comment by basvodde** [comment]
Perhaps split the test in NaN, infinity and others ? Then have a check for the support for NaN and the support for infinity and turn these off in BC ?

**Comment by pjshelton** [comment]
Yep.  
Question. Not sure how to test for NaN and Inf support.  Will have to do some homework.

**Comment by basvodde** [comment]
You can just leave it on by default and then turn it off for the BC. Just would like to avoid compiler specific switches in any file and prefer capability specific switches (well... prefer no switches at all but that is not an option)

**Comment by pjshelton** [comment]
#1552 is the first of two PR that help CppUTest to compile under the Borland compiler.
