### ISSUE TITLE
Borland v5.4 doesn't do long long

### ISSUE THREAD

**Issue by pjshelton** [cpputest/cpputest#1547]
the Borland v5.4 compiler doesn't do the long long integer type.  

Suggesting setting the cmake variable LONGLONG to OFF in cmake/Modules/CppUTestConfigurationOptions.cmake

this is part of #1493

**Comment by basvodde** [comment]
Ok, this is not a pull request ?

**Comment by pjshelton** [comment]
Don’t worry, it will be, just waiting for you to either comment or accept the current Borland pull request

**Comment by pjshelton** [comment]
Which you closed as I was typing

**Comment by basvodde** [comment]
Yah, sorry, it was burried in my mail, but I found it! :)
