### ISSUE TITLE
Borland v5.4 vsnprintf() is broken with respect to the current standard

### ISSUE THREAD

**Issue by pjshelton** [cpputest/cpputest#1556]
Looking at the SimpleString failure:
C:\cpputest\tests\CppUTest\SimpleStringTest.cpp:785: error: Failure in TEST(SimpleString, PlatformSpecificSprintf_doesNotFit)
expected <123456789>
but was <1234567890>
difference starts at position 9 at: < 1234567890 >
^
from https://www.cplusplus.com/reference/cstdio/vsnprintf/?kw=vsnprintf we have
n
Maximum number of bytes to be used in the buffer.
The generated string has a length of at most n-1, leaving space for the additional terminating null character.
size_t is an unsigned integral type.

and the important bit there is that the generated string has a length of at most n-1. This is what the test expects.

from the C++ Builder documentation
If the number of bytes to output is:
< nsize, then all of the characters have been written, including the terminating ‘\0’ character.
== nsize, then nsize characters are written, with no terminating ‘\0’ character.
> nsize, then only nsize characters are written, with no terminating ‘\0’ character.

and the important bit here is that it will write a string having a length of at most n. This is one more than the test expects.

So the Borland v5.4 compiler adds an extra character over the expected length of the resultant string in the input buffer when using vsnprintf()

See https://github.com/cpputest/cpputest/issues/1493#issuecomment-949078327

I don't know what to do with this.  I have just been ignoring it.

**Comment by pjshelton** [comment]
Should I create a CPPUTEST_BROKEN_VSNPRINT flag similar to the CPPUTEST_HAS_NAN?

**Comment by basvodde** [comment]
No... but this is a PlatformSpecific function, so you can fix that in the Borland Platform file, probably ?
