### ISSUE TITLE
`CPPUTEST_HAVE_FENV` cannot be overridden

### ISSUE THREAD

**Issue by thetic** [cpputest/cpputest#1571]
CppUTest tries to deduce `CPPUTEST_HAVE_FENV` and `CPPUTEST_FENV_IS_WORKING` from what compiler is used, but this is sometimes incorrect and depends on explicit support for each compiler. For example, the ARM embedded GCC compiler may not have fenv.h, but all GCC builds with `CPPUTEST_USE_STD_C_LIB` defined are assumed to have it. I think this should be an explicit setting that may still be inferred when unset, but the user can predefine.

**Comment by basvodde** [comment]
And then the checking can be moved to the autoconf file and the cmake file ?

**Comment by thetic** [comment]
that's my thought. I know nothing about autconf, but it's a pretty straight-forward check in CMake: https://cmake.org/cmake/help/latest/module/CheckIncludeFile.html

**Comment by jjungo** [comment]
I'm having the same issue on my projects. My (very ugly) workaround is to `git apply` a patch after having fetched through `FetchContent_Declare` where all `IEEE754` related source files are remove from the build.
I would definitely like to have a cleaner way to do that.
