### ISSUE TITLE
Call the real implementation of a function after mocking it

### ISSUE THREAD

**Issue by lchagnoleau** [cpputest/cpputest#1581]
Hello and thanks for your awesome lib !

Does it possible to mock a function, and be able to call the real implementation of this function.

Here is my production code i want to test
```cpp
void set_io()
{
    FILE *fp_driver = fopen("/dev/sys/my/io", "w");
    fprintf(fp_driver, "1");
    fclose(fp_driver);
}
```

And here is my testing code:
```cpp
TEST_GROUP(IO)
{
    void setup() {
    }


    void teardown() {
        mock().checkExpectations();
        mock().clear();
    }

};

FILE *fopen (const char *__restrict __filename, const char *__restrict __modes)
{
    void * r = mock().actualCall(__func__)
        .withParameter("__filename", __filename)
        .withParameter("__modes", __modes)
        .returnPointerValue();
    return (FILE *)r;
}

int fclose (FILE *__stream)
{
    return mock().actualCall(__func__)
        .withParameter("__stream", __stream)
        .returnIntValue();
}

TEST(IO, simpleTest)
{
    FILE * tmp_log_file = tmpfile();
    mock().expectOneCall("fopen")
          .withParameter("__filename", "/dev/sys/my/io")
          .withParameter("__modes", "w")
          .andReturnValue(tmp_log_file);

    mock().expectOneCall("fclose")
          .withParameter("__stream", tmp_log_file)
          .andReturnValue(0);

    /* Tested function */
    set_io();

    /* Read the unclosed tmp_log_file */
    rewind(tmp_log_file);
    char io_value = 0;
    fread(&io_value, sizeof(char), (size_t)1, tmp_log_file);

    /* check result */
    CHECK_EQUAL('1', io_value);

    /* Real close file */
    fclose(tmp_log_file);

}
```

As you can see, I'm just want to test that my func ```set_io``` write a ```1``` inside a file. So, I also had to mock ```fclose()``` func to prevent my production code to close my temp file to be able to read and check its content.

The problem is that I'm not able anymore to call the real ```fclose()``` function at the very last of my test because it actually calls the mocking fclose() function.

Is there a way to do this ?

Thanks a lot !

**Comment by jgonzalezdr** [comment]
There is no easy way to do what you want, but why do you want to do that on the first place?

Just mock fprintf as you mocked fopen and fclose.

In cases where you just care about the contents written to the file (which might be performed through an arbitrary number of calls to fprintf), replace fprintf with a stub that stores the data in a memory string buffer and check its contents in the test.

**Comment by lchagnoleau** [comment]
@jgonzalezdr thank you for your answer. I will experiment your approach which seems nice.

In fact, I tried to store the ```fclose()``` function pointer before declaring the mock :
```cpp
int (*real_fclose)(FILE *) = &fclose;
```
I thought I could call the real fclose function by calling ```real_fclose()``` but it also a reference of the mocking ```fclose()``` func...
I don't know how the CppUTest library works, but my tricks do not work..

Anyway, the workaround you propose me will do the job, so thanks a lot!

**Comment by basvodde** [comment]
It isn't C++ that does anything tricky, it is just how the C++ compiler works.

If you want to call the real fopen/fclose (which as @jgonzalezdr points out, is probably not the best idea), then one way is to switch from linker stubbing to function pointer stubbing. This means putting the function pointer declaration (like you have) in the production code and use the function pointer to call the real fopen. Then declare the function pointer as an external and change it in the test with a stub (usually using UT_PTR_SET helper)

**Comment by lchagnoleau** [comment]
Thank you guys to taking the time to advise me. I have now a better knowledge of how the C++ works.
Effectively, it's not a good idea to modify the production code.

Thanks again, you rocks
