### ISSUE TITLE
Problem with arm-none-eabi-gcc and qemu semihosting

### ISSUE THREAD

**Issue by asimov-aiz** [cpputest/cpputest#1638]
Hi,

I am trying to use cpputest with my project for cortex-m4 with qemu with my PC.

I create a new project and follow the [Integration as external CMake project](https://github.com/cpputest/cpputest#integration-as-external-cmake-project) and enabled the test build.

After I build the project, I run the `_deps/cpputest-build/tests/CppUTest/CppUTestTests`.

On qemu:

```
qemu-arm -cpu cortex-m4 build/_deps/cpputest-build/tests/CppUTest/CppUTestTests
```

I got:
```
qemu-arm -cpu cortex-m4 build/_deps/cpputest-build/tests/CppUTest/CppUTestTests
......................................
```

If I build with native gcc:
```
 _deps/cpputest-build/tests/CppUTest/CppUTestTests
..................................................
.........!........!..!..!..!..!..!..!..!..!..!....
.............!..!..!..!..!..!..!....!.!........!..
...!..!..!..!..!..!..!..!..!..!..!..!...!...!....!
..!.......!..!...!..!..!..!..!..!..!..!..!..!..!..
!..!.....................!........................
..................................................
..................................................
..................................................
..................................................
..................................................
.......................!..........................
..................................................
..................................................
..................................................
..................................................
..................................................
....................
OK (870 tests, 816 ran, 1536 checks, 54 ignored, 0 filtered out, 39 ms)
```

Also my simple testing:
```
#include "CppUTest/CommandLineTestRunner.h"

TEST_GROUP(FirstTestGroup)
{
};

TEST(FirstTestGroup, Test1) { FAIL("Fail me!"); }
TEST(FirstTestGroup, Test2) { FAIL("Fail me! 222"); }

int main(int ac, char **av) {

  return RUN_ALL_TESTS(ac, av); }
```

The qemu stop on first failure:
```
unit_test.cpp:8: error: Failure in TEST(FirstTestGroup, Test2)
        Fail me! 222
```

I want all tests to run and show me the summary. Does anyone has experiences on this?

FYI, my build and link command
```
arm-none-eabi-g++ -DCPPUTEST_HAVE_GETTIMEOFDAY=1 -DCPPUTEST_HAVE_STRDUP=1 -DHAVE_CONFIG_H -I/project -I/project/build/_deps/cpputest-build -I/project/build/_deps/cpputest-src/include -I/project/build/_deps/cpputest-src/src/CppUTest/../../include -I/project/build/_deps/cpputest-src/src/CppUTestExt/../../include -ffunction-sections -fdata-sections -mcpu=cortex-m4    -include "/project/build/_deps/cpputest-src/include/CppUTest/MemoryLeakDetectorNewMacros.h" -include "/project/build/_deps/cpputest-src/include/CppUTest/MemoryLeakDetectorMallocMacros.h"  -Wall -Wextra -pedantic -Wshadow -Wswitch-default -Wswitch-enum -Wconversion -Wsign-conversion -Wno-padded -Wno-long-long -Woverloaded-virtual -Wno-old-style-cast -Wno-c++14-compat -O2 -g -DNDEBUG -std=c++20 -MD -MT _deps/cpputest-build/tests/CppUTestExt/CMakeFiles/CppUTestExtTests.dir/CodeMemoryReporterTest.cpp.obj -MF _deps/cpputest-build/tests/CppUTestExt/CMakeFiles/CppUTestExtTests.dir/CodeMemoryReporterTest.cpp.obj.d -o _deps/cpputest-build/tests/CppUTestExt/CMakeFiles/CppUTestExtTests.dir/CodeMemoryReporterTest.cpp.obj -c /project/build/_deps/cpputest-src/tests/CppUTestExt/CodeMemoryReporterTest.cpp
```

```
arm-none-eabi-g++ -mcpu=cortex-m4 -mthumb --specs=nano.specs --specs=rdimon.specs -o _deps/cpputest-build/tests/CppUTest/CppUTestTests _deps/cpputest-build/tests/CppUTest/CMakeFiles/CppUTestTests.dir/AllTests.cpp.obj _deps/cpputest-build/tests/CppUTest/CMakeFiles/CppUTestTests.dir/SetPluginTest.cpp.obj _deps/cpputest-build/tests/CppUTest/CMakeFiles/CppUTestTests.dir/CheatSheetTest.cpp.obj ...[all objs]
```

**Comment by asimov-aiz** [comment]
It seems the test crashes on the first fail. So that is why summary is not printed. Any one tried this setup?

**Comment by thetic** [comment]
Note that cmake/arm-none-eabi-gcc.toolchain.cmake is only the bare minimum required to verify that CppUTest _builds_. It is not provided for users and is likely insufficient for your use case. You will need to configure the appropriate startup code, ISR handlers, memory layout, etc. for your specific platform.

**Comment by asimov-aiz** [comment]
I understand "startup code, ISR handlers, memory layout" would be required for whole system simulation. The one I am using is semihosting with qemu. I only want to verify algorithm part.

**Comment by thetic** [comment]
ok, i see what you mean. I've tried reproducing your setup. I've had some luck after disabling exceptions (`-fno-exceptions -fno-rtti`), but my build of nano libc doesn't seem to support `long long` and `double` string format specifiers, so I'm getting a bunch of spurious failures. I'll try to get my environment sorted out. In the meantime see if adding those flags to your toolchain file helps.

**Comment by thetic** [comment]
OK. I've been able to reproduce this issue. I'll see if I can get this running on hardware this weekend to see whether QEMU has something to do with this.

**Comment by asimov-aiz** [comment]
Thank you! Very appreciate!

**Comment by asimov-aiz** [comment]
I tried `-fno-exceptions -fno-rtti`, I cannot build my above code:

```
/project/build/_deps/cpputest-src/src/CppUTest/MemoryLeakWarningPlugin.cpp: In function 'void* threadsafe_mem_leak_operator_new(size_t)':
/project/build/_deps/cpputest-src/src/CppUTest/MemoryLeakWarningPlugin.cpp:134:90: error: exception handling disabled, use '-fexceptions' to enable
  134 | #define UT_THROW_BAD_ALLOC_WHEN_NULL(memory) if (memory == NULLPTR) throw std::bad_alloc()
      |                                                                                          ^
/project/build/_deps/cpputest-src/src/CppUTest/MemoryLeakWarningPlugin.cpp:143:5: note: in expansion of macro 'UT_THROW_BAD_ALLOC_WHEN_NULL'
  143 |     UT_THROW_BAD_ALLOC_WHEN_NULL(memory);
```

Is this the same on your side?

**Comment by thetic** [comment]
Remove `--specs=nano.specs` from your link options. CppUTest depends on a complete C library.

I am working to add QEMU to CI to demonstrate and ensure compatibility moving forward.

**Comment by asimov-aiz** [comment]
Seems works really well after removing nano.specs. Thank you!
Though when I run CppUTestExtTests I got `Long Long type is not supported`. Not sure if I can disable long long type test. 

Thank you!

**Comment by thetic** [comment]
Unset `CPPUTEST_USE_LONG_LONG`, for example from the command line with `-D CPPUTEST_USE_LONG_LONG=OFF`.
