### ISSUE TITLE
Error in src/CppUTestExt/MockNamedValue.cpp:217 when mocking with too many parameters?

### ISSUE THREAD

**Issue by ThePapaG** [cpputest/cpputest#1667]
Hi, I am trying to mock a non volatile store method that would normally write to memory on device.

```c++
int Load(uint8_t section, uint8_t category, uint16_t key, uint8_t* data, uint8_t length)
{
    return mock("nv").actualCall("Load")
            .withUnsignedIntParameter("section", section)
            .withUnsignedIntParameter("category", category)
            .withUnsignedIntParameter("key", key)
            .withOutputParameter("data", data)
            .withUnsignedIntParameter("length", length)
            .returnIntValueOrDefault(length);
}
```

where I am expecting

```c++
mock("nv").expectOneCall("Load")
                            .withParameter("category", category)
                            .withParameter("key", key)
                            .withParameter("length", sizeof(data))
                            .ignoreOtherParameters()
                            .withOutputParameterReturning("data", &data, sizeof(data))
                            .andReturnValue(sizeof(data));
```

However I am getting the error

```
src/CppUTestExt/MockNamedValue.cpp:217: error:
	expected <int>
	but was  <unsigned long int>
	difference starts at position 0 at: <          unsigned l>
```
 If I remove the actual call with parameter length, it will run no worries. I found https://github.com/cpputest/cpputest/issues/686 from 7 years ago but commenting the ignore alone doesn't solve the issue

**Comment by ThePapaG** [comment]
In contradiction to https://github.com/cpputest/cpputest/issues/686 being the error, I use `ignoreOtherParameters()` and `withOutputParameterReturning()` In other places in my code.

**Comment by ThePapaG** [comment]
Appears to have been an auto cast issue on `.andReturnValue(sizeof(data));`, `.andReturnValue((int)sizeof(data));` removed error. The error message was not clear at all as to what the error case was.

**Comment by basvodde** [comment]
I'm glad it is solved. I agree that the error message could have been significantly better

**Comment by thetic** [comment]
I suggest using the typed variants like `andReturnIntValue`.

**Comment by ThePapaG** [comment]
> I suggest using the typed variants like `andReturnIntValue`.

The mock and tests are called from a *.cpp file which looks like only has overloads for different parameter typings of the same call `andReturnValue()`?
