### ISSUE TITLE
Cron are scheduled on forks too

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#1727]
I have noticed that the cron builds are scheduled on forks too.

This should be solved according to [this issue](https://github.com/laravel/framework/issues/34356), but it still happens.
There's a workaround mentioned, but this would require an `if` to each job.

Since disabling the workflow isn't an option, I don't have a solution yet. :man_shrugging:

**Comment by thetic** [comment]
do we need a cron?

**Comment by offa** [comment]
I don't thing so. There are builds for changes (commits, PRs) and there's no value for building master without touching anything.

**Comment by thetic** [comment]
I'm inclined to agree. I suspect the cron is a hold over from a time when it was too expensive to run the whole pipeline on every commit. I don't think that's an issue anymore.

@basvodde?

**Comment by basvodde** [comment]
I do not know enough about it and will go with whatever both of you suggest :)
