### ISSUE TITLE
CppU mocking

### ISSUE THREAD

**Issue by sriharibestha** [cpputest/cpputest#1730]
How to write a test cases for those, Which API's won't take any parameters and it won't return anything.

void add (void)
{
}

**Comment by basvodde** [comment]
What does it do?

**Comment by sriharibestha** [comment]
> How to write a test cases for those, Which API's won't take any parameters and it won't return anything.
> 
> void add (void) { }

**Comment by basvodde** [comment]
If a function doesn't do anything then you don't need to call it either :) You need to ask "what does it do" and then "how can I check that it did that". Not just look at return values.

**Comment by sriharibestha** [comment]
Then what that function will do and then how can I check that it did that or not , for this type of functions can i write mock.

**Comment by basvodde** [comment]
I don't see how your question relates to mocks.
