### ISSUE TITLE
Build failure on CentOS 7

### ISSUE THREAD

**Issue by CiderMan** [cpputest/cpputest#1737]
Firstly some background:

We use C++ exceptions for exploding fakes. The exception is caught in `main()` and a backtrace is produced to help the developer understand the code path that has now caused the exploding fake to be called.

We are updating to a recent version of CppUTest but have to build it with `CPPUTEST_HAVE_EXCEPTIONS` defined as `0`; otherwise the portion of the stacktrace inside the code under test is lost and the backtrace only ever traces down to the `catch(...)` in UTest.cpp.

The problem:

One of the platforms that where we need to use CppUTest is CentOS 7 (yes, it is old but still supported until June 2024) with GCC 4.8.5. When trying to build CppUTest without exceptions, it seems that GCC of that vintage is requiring the correct exception specification for the standard delete overloads. For example:

```
/cue/tm_win32_tools/cpputest/cpputest/src/CppUTest/MemoryLeakWarningPlugin.cpp: In function 'void operator delete(void*)':
/cue/tm_win32_tools/cpputest/cpputest/src/CppUTest/MemoryLeakWarningPlugin.cpp:330:31: error: declaration of 'void operator delete(void*)' has a different exception specifier
 void operator delete(void* mem) UT_NOTHROW
                               ^
In file included from /cue/tm_win32_tools/cpputest/cpputest/include/CppUTest/MemoryLeakWarningPlugin.h:32:0,
                 from /cue/tm_win32_tools/cpputest/cpputest/include/CppUTest/TestHarness.h:45,
                 from /cue/tm_win32_tools/cpputest/cpputest/src/CppUTest/MemoryLeakWarningPlugin.cpp:28:
/cue/tm_win32_tools/cpputest/cpputest/include/CppUTest/MemoryLeakDetectorNewMacros.h:70:10: error: from previous declaration 'void operator delete(void*) noexcept (true)'
     void operator delete(void* mem) UT_NOTHROW;
          ^
```

The solution?

Looking in CppUTestConfig.h, it looks like Clang might have a similar requirement:

```cxx
  #if CPPUTEST_HAVE_EXCEPTIONS
    [...snip...]
  #else
    #define UT_THROW(exception)
    #ifdef __clang__
      #define UT_NOTHROW throw()
    #else
      #define UT_NOTHROW
    #endif
  #endif
```

If I extend the pattern to include GCC, it then builds successfully and cleanly for both the old version of GCC and more recent versions:

```cxx
  #if CPPUTEST_HAVE_EXCEPTIONS
     [...snip...]
  #else
    #define UT_THROW(exception)
    #if defined(__clang__) || defined(__GNUC__)
      #define UT_NOTHROW throw()
    #else
      #define UT_NOTHROW
    #endif
  #endif
```

I will create a PR with this change so that it can be discussed and/or accepted as appropriate.

Thanks,

Steve.

**Comment by basvodde** [comment]
This is now resolved?

**Comment by CiderMan** [comment]
> This is now resolved?

Yes, all good now. Thanks!
