### ISSUE TITLE
Mock: allowing parameter range

### ISSUE THREAD

**Issue by SpuriousInterrupt** [cpputest/cpputest#1761]
Given a fictitious test:
```cpp
TEST(MockHeatingSystem, MockScenario)
{
    MockThermostat therm;
    TestHeatingSystemRunnable runnable(therm);
    
    mock().expectOneCall("setTemp").onObject(&therm).withParameter("temp", 20.0);
    runnable.simulateRTOSTick();
    mock().checkExpectations();
}
```
This test will fail if the runnable under test sets a temperature other than 20C on the thermostat. I imagine most of the time this is exactly what the test designer wants to assert.

Maybe in other types of tests, we cannot be absolutely certain what the system ("runnable") will set on the thermostat, nor would we care for the purpose of the test. We just want to make sure that the function is called.
We can then instead do:
```cpp
mock().expectOneCall("setTemp").onObject(&therm).ignoreOtherParameters();
```
But maybe we want to test that the parameter sits nicely within a certain range, say 0.0 - 40.0.
Can this currently be achieved in some way?

**Comment by basvodde** [comment]
Sure. You still need to do an actualCall call in the fake function, so there you can make whatever check you want. I would probably use something like setData on the mock() and then check the value of the temperature in the test.
