### ISSUE TITLE
Spy some dependencies

### ISSUE THREAD

**Issue by jim-king-2000** [cpputest/cpputest#1781]
Suppose we have a function in my production code.

```C++
void ProductionCode()
{
    do1Thing();
    do2Thing();
    do3Thing();
}
```

Now we need write a unit test for this function. And we want to spy `do2Thing()` and let it throw an exception. Pseudo-code is like this:

```C++
#include "ProductionCode.h"

TEST()
{
    mock("do2Thing", [](){ throw "exception"; });
    ProductionCode();
    mock.assertThrow("exception");
}
```

Is it possible to do this without changing the source code of `ProductionCode`?

**Comment by basvodde** [comment]
In theory, it is possible without changing product code by using linked stubs. It is not recommended because you tend to end up with many different binaries. Usually a function pointer stub is the way to go. I believe this is described in the CppUTest manual.

**Comment by jim-king-2000** [comment]
Sure. I'll follow the rule of CppUTest.
