### ISSUE TITLE
Test result with junit format contains invalid escape character of {newline}

### ISSUE THREAD

**Issue by ChunBoo** [cpputest/cpputest#1809]
in this function SimpleString JUnitTestOutput::encodeXmlText(const SimpleString& textbody),the '\n' will be converted as {newline} which can not be displayed correctly in XML file with the option of -junit, please see below line:
 "failed{newline}	expected &lt;0 (0x0)&gt;{newline}	but was  &lt;1 (0x1)&gt;"
Not very sure it is one bug or not.

**Comment by ChunBoo** [comment]
Seems it already fixed by this PR:https://github.com/AlexisTM/cpputest/commit/8d90f3ff57b0163cdb1d58ee6729578fbfbfd485

**Comment by basvodde** [comment]
You referred to a commit in a fork, but I didn't see the PR back yet, did I miss something?

**Comment by ChunBoo** [comment]
@basvodde [this](https://github.com/cpputest/cpputest/pull/1598) issue reported same issue and which has been closed.

**Comment by basvodde** [comment]
Ok, merged now. It ended up being a bit harder than expected :)
