### ISSUE TITLE
Warning on autoconf build related to macro

### ISSUE THREAD

**Issue by basvodde** [cpputest/cpputest#1813]
@thetic After merging the last changes related to warning, I'm getting a warning on the generated config.h. I've not found any way to rename the symbolic constant yet. Any idea?

#define _GENERATED_CPPUTESTGENERATEDCONFIG_H 1
        ^
1 warning generated.

**Comment by basvodde** [comment]
It probably did. It is a warning and doesn't produce an error, so it didn't fail the build. I guess it was in the build output though. When working locally I suddenly noticed it. It warns on every file :(

**Comment by thetic** [comment]
let's roll it back i guess until I get time to investigate.

**Comment by basvodde** [comment]
Roll back is too much, I think. It relates to this flag reserved-macro-identifier. Perhaps just roll back that one?

**Comment by thetic** [comment]
#1815
