### ISSUE TITLE
Is test group class constructor overriding OK ?

### ISSUE THREAD

**Issue by eMKa94** [cpputest/cpputest#1826]
Hi, Is it ok to override a constructor of the class created under the TEST_GROUP macro?

I want to create an object that will be shared between test cases and I need to call a specific constructor of that object so to avoid the most vexing parse I need to override the test group class constructor and call my specific object constructor in the initializer list like this:

```
TEST_GROUP(MyTestGroupName)
{
   SomeClass someObject; // Default constructor of SomeClass is deleted

    TEST_GROUP_CppUTestGroupMyTestGroupName() : someObject(0x1234)
    {
    }

/*
... Other code
*/
};
```

Is it ok or am I breaking something implicitly?

**Comment by basvodde** [comment]
I think it should be fine. The TEST_GROUP object will be dynamically created and destroyed, so there shouldn't be any scope problems. I personally do not like to use constructors like this and prefer a default constructor in the SomeClass... but that is a different discussion.

**Comment by eMKa94** [comment]
Thank's!
