### ISSUE TITLE
V3.5 on VisualStudio 2010 reports one failed test.

### ISSUE THREAD

**Issue by amanita-citrina** [cpputest/cpputest#196]
One test fails. Also, the exclamation marks seem to indicate that
some tests were skipped (which does not show up in the summary):
1>  .........!........................................
1>  ..................................................
1>  ..................................................
1>  ...................!..............................
1>  ..................................................
1>  ..............................
1>d:\projects\cpputest\tests\cpputestext\testmocksupport_c.cpp(163): error : Failure in TEST(MockSupport_c, NoExceptionsAreThrownWhenAMock_cCallFailed)
1>  	CHECK(!destructorWasCalled) failed
1>  
1>  ...............!....
1>  ..................................................
1>  ...........!......................................
1>  ..................................................
1>  ..................................................
1>  .........................
1>  Errors (1 failures, 525 tests, 525 ran, 957 checks, 0 ignored, 0 filtered out, 0 ms)

**Comment by arstrube** [comment]
@amanita-citrina, @basvodde - We solved this, right?

**Comment by Andne** [comment]
I think that I fixed the failing test in #262 around a year ago.  Granted, the fix was just to mark it ignored since it wasn't working correctly, maybe that needs to be looked at again and changed.

**Comment by arstrube** [comment]
Yes, we ignore the test for vs - I don't think there's more we can do though, as it behaves significantly different from other compilers.

**Comment by arstrube** [comment]
@basvodde I believe this can be closed.
