### ISSUE TITLE
Using the concept of interfaces in C++

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#253]
This isn't an issue - more like a discussion starter. The topic came up regarding my pull request: https://github.com/cpputest/cpputest/pull/248

I couldn't find a better place for it, so I put it here. 

While I totally respect the fact that @basvodde as the owner of this repository would rather not have any "multiple inheritance" in C++, I think there is more to this than meets the naked eye.

Personally, I would like to differenctiate between brute force multiple inheritance (with its well-known problems) and the use of interfaces -- which is entirely safe and a GOOD thing, in my opinion.

**Comment by basvodde** [comment]
Seems closed....
