### ISSUE TITLE
GitIgnore file contents

### ISSUE THREAD

**Issue by Andne** [cpputest/cpputest#261]
Should the build folder be in the gitignore file?  From what I can see, it looks like the contents of this folder are all versioned, so what ends up in it that needs to be ignored?  I can identify most of the contents of that file, but it would be nice if some of the less clear items (especially folders that already contain files) could have an explanation on them.

**Comment by arstrube** [comment]
No, not in the root .gitignore.

cpputest_build/ has its own .gitignore which assures that:

1. cpputest_build/ gets created by cloning / pulling
2. everything but itself in that folder is ignored.

Perhaps, if you have versioned files in there, they got added before this was introduced? There are none on Github.

I do agree about the explanations, but I doubt any single person could supply all of them.

**Comment by Andne** [comment]
I didn't mean `cpputest_build`, I was talking about just `build`.

Looks like @basvodde removed it from .gitignore a while ago, guess I should close this issue.

**Comment by arstrube** [comment]
Ahh now I understand; 'build' actually contains files that are versioned and should _not_ be ignored....
