### ISSUE TITLE
Dependence on CPPUTEST_HOME and MakefileWorker.mk

### ISSUE THREAD

**Issue by emidttun** [cpputest/cpputest#285]
To quote http://cpputest.github.io:

> This is by far the easiest way to install it, via:
> 
> ```
> $ apt-get install cpputest
> ```

I get the include files and the library, but there is nothing that works as CPPUTEST_HOME or path to MakefileWorker.mk. Shell scripts included under /usr/share/cpputest create makefiles that depend on this variable and MakefileWorker.mk. The same is true for the book code in TDD for Embedded C. Because of this I think building CppUTest from source is the easiest.

Is it supposed to be like this, or could the install option be improved?

**Comment by matthewbeckler** [comment]
I was bit by this issue today as well. Ubuntu 15.04 Vivid. Trying to use the TDD for Embedded C book code downloaded from the pragprog website. I'm going to try to build from source since that seems to be the only way to get the book code to work.

**Comment by jwgrenning** [comment]
Hi Matt

Sorry for not replying sooner.

I've put the book code on github and updated the build environment. 
https://github.com/jwgrenning/tddec-code

Some files have moved, but the code is more up to date there  You might 
try that.

Depending on your gcc, you may need to adjust the options in the 
makefile.



James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
Cell: +1 847-630-0998
Office: +1 847-438-9942
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by basvodde** [comment]
I added a Makefile that builds the examples with an installed CppUTest. Closing this for now.
