### ISSUE TITLE
Where is the right place to libraries running on target?

### ISSUE THREAD

**Issue by bortsov** [cpputest/cpputest#295]
I add project to build CppUTest library for ARM7TDMI processor and ARM C/C++ compiler. I build in ./platforms/armcc/objs and place library in ./platforms/armcc/lib
Is it correct?

Other question. I make project based on AT91SAM7A3 chip running in my board. A project run simple test in hardware, using only DBGU interface to out results to PC. I place my project in new directory ./platforms_tests but it is a bad idea because of .gitignore pattern. Where is the right place to this sample projects? Also I plan to add other sample projects for LPC1768, LPC1833, RM48L952 chips.
My branch is armcc in https://github.com/bortsov/cpputest
Project is not in corrects state, I am working on makefile (to build test files to library and link test, CppUTest libraries and other objects together).

**Comment by basvodde** [comment]
I assume this has been resolved by now (sorry for the delay). I'll close this, let me know if that is incorrect.
