### ISSUE TITLE
Memory allocated by strdup and strndup is not tracked

### ISSUE THREAD

**Issue by basvodde** [cpputest/cpputest#3]
Adding strdup support WILL mean need to automake in order to detect strdup is available. See additional comments on sourceforge

From Sourceforge:

When you use the memory leak detector, memory allocated by strdup is not properly tracked. The header files gives this reason why it has not been done:

> strdup was implemented earlier, however it is _not_ an Standard C function but a POSIX function.
> Because of that, it can lead to portability issues by providing more than is available on the local platform.
> For that reason, strdup is _not_ implemented as a macro.

I don't really understand this comment. What kind of problem ?

Despite this I would suggest that you need to enable by default tracking of memory allocated by strdup and doing whatever is required for this. But you should make it possible to disable it for the platforms where it can be problematic. Furthermore, maybe you could add a configure check that detects those platforms and that disables it automatically on those...

Having to manually mock strdup() to get a working memory detector is a pain. Thank you in advance.

Also close:
https://sourceforge.net/tracker/?func=detail&aid=3533980&group_id=199196&atid=968518

**Comment by felipe-lavratti** [comment]
Are we not using automake already? Should this be fixed or left alone? Can I submit a patch?

**Comment by basvodde** [comment]
It should be fixed. Only recently did we implement the ability to install the config.h file, so that this can properly be fixed. Feel free to submit a PR.

**Comment by felipe-lavratti** [comment]
Thanks Bas.
Do you think I should add a platform abstraction pointer for `strlen`, such as `PlatformSpecificStrlen`, or should I make CppUTest's own `strlen` relying on the fact strings are always null terminated for __every__ existent platform?

**Comment by basvodde** [comment]
I think that we can remove the platform specific strlen if we have one that is independent of the platform :)

**Comment by felipe-lavratti** [comment]
Believe PR #1057 implemented this.

**Comment by basvodde** [comment]
Ok, closed then. Thanks!
