### ISSUE TITLE
Add code to the CppUTest tests that verifies all test cases have run.

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#343]
This could be done via a TestCounter plugin, maybe?

Is there a way to count the expected number of test cases other than manually (e.g. with a script?). The script could, for example, write aTestsExpectedNumberOfTests.h, containing:

```
#define EXPECTED_NUMBER_OF_TESTS 270
```

which would be compiled with along with the test code (e.g. #included from allTests.cpp).

**Comment by basvodde** [comment]
Closing this. Let me know if that is incorrect.
