### ISSUE TITLE
Fix cpputest.github.io Size Explosion

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#379]
(carrying on discussion from #372)

**Comment by arstrube** [comment]
We have been ignoring this for over a year, by not deploying anymore...

Couldn't this be a solution:
https://github.com/blog/1986-announcing-git-large-file-storage-lfs

We'd need the LFS extension on Travis CI and anyone pulling/pushing from cpputest.github.io would need it, but that would be very few people who are actively involved in adding new features.

**Comment by basvodde** [comment]
This seems to be solved now... as we use the Travis CI deployment that puts it to Github releases.
