### ISSUE TITLE
Keep a high level changelog for each release

### ISSUE THREAD

**Issue by peplin** [cpputest/cpputest#420]
I was looking for a changelog to know what differences to expect (and possible changes I need to make in my tests) going from v3.6 to the upcoming v3.7, and I was disappointed to find your [changelog](https://github.com/cpputest/cpputest/blob/master/ChangeLog) just points to the Git commit history. 

As someone not intimately immersed in the details of Cpputest, and just a user of the library, the raw Git commit log is not very informative: https://github.com/cpputest/cpputest/compare/v3.6...master

I know it's a little bit of extra work to keep a high level changelog, but I think the consumers of your tools would really appreciate and benefit from it. It would also help us understand the different features of your library, many of which seem to be undocumented.

**Comment by arstrube** [comment]
How about that each of us who contributes a new feature, in the same way as we always have to submit tests to be considered for merging, we also have to add a suitable line to the change log.

That way, when it comes to a new release, we won't have to scratch our heads, or wade through gazillions of pull requests (shudder).

We have had a lot of very useful new features recently, and I am starting to lose track even of my own contributions, let alone those of others. Maybe the "release" change log doesn't need to contain every tiny bug fix. So we should have a detailed log, perhaps, that we are required to write in, and a user-oriented, abbreviated log, which @basvodde  updates with each release.

**Comment by basvodde** [comment]
I'm a bit uncomfortable with updating the change log all the time as features don't always come in one piece but often come gradually. Also, I'm likely to forget it myself all the time :)

Besides, isn't that what we have version control for?

**Comment by peplin** [comment]
Just checking in to see if you would consider this again

>Besides, isn't that what we have version control for?

I don't think so - consider this comment from a developer on my team who recently wanted to update the version of cpputest to see if it would help find a bug in our test suite:

"- There isn't a decent changelog, but we're ~700 commits behind, so let's just jump ahead."

I'll add "...and hope it works". It's really hard to tell from a 700 commit changelog if there were any API changes, and new CLI flags or features we might want to take advantage of, etc. I don't think you need to be militant about updating the changelog every commit, but every so often when you consider making a major or minor release, I think it's worth collecting all of the high-level changes in a concise format for your users.

**Comment by arstrube** [comment]
@peplin I agree. We had loads of great new features added recently and if you asked me to list them I couldn't do it. Going through the commit history would be a daunting task - much easier to update the change log whenever a new feature is finished, or a bug fixed.

**Comment by basvodde** [comment]
High level changelog is in the github releasing now
