### ISSUE TITLE
GccNoStdC

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#429]
```
cpputest\src\Platforms\GccNoStdC\UtestPlatform.cpp|191|error: unused parameter "mtx"
[-Werror=unused-parameter]|
```

Omitting the argument name or adding the line `(void)mtx;` will fix this.

@basvodde The reason I am posting this here is that I would have thought the Travis build compiles this file, and the error should have been picked up by Travis? Why wasn't it?

**Comment by basvodde** [comment]
I made a lot of changes to the travis build, now this should be included.
