### ISSUE TITLE
Exit status of "make test" is 0 if tests segfault

### ISSUE THREAD

**Issue by peplin** [cpputest/cpputest#435]
I noticed that if our tests segfaulted halfway through, the test runner would die but `make test` would return an exit status of 0. I found that because the test runner is piped to `tee` (https://github.com/cpputest/cpputest/blob/master/build/MakefileWorker.mk#L474) the exit status is lost:

```
> ./PIC_tests 
........................[1]    29550 floating point exception (core dumped)  ./PIC_tests
> echo $?
136
> ./PIC_tests | tee
........................[1]    29620 floating point exception (core dumped)  ./PIC_tests | 
       29621 done                                    tee
> echo $?
0
```

**Comment by matthewpiatt** [comment]
+1 -- i am also seeing this. when using "make vtest", piping the output to tee swallows the return code and causes make to assume the result was a success.

**Comment by basvodde** [comment]
I assume this has been fixed by now? (all known builds are green). Closing it, but let me know if that is wrong.
