### ISSUE TITLE
Ignored test in SetPluginTest.cpp

### ISSUE THREAD

**Issue by Andne** [cpputest/cpputest#461]
I was going through the test files and found the following test in SetPluginTest.cpp listed as an ignored test:
Line 99:
IGNORE_TEST(SetPointerPluginTest, installTooMuchFunctionPointer)

Is this something that needs to be fixed?  There doesn't seem to be a comment around it explaining why it's ignored, but based on what I can find, it does appear that something isn't working and needed to be fixed.  I'm willing to try and fix it, but I want to make sure that it's not ignored for a more specific reason than because it wasn't working.

**Comment by basvodde** [comment]
I think it was simply not implemented yet :)

**Comment by Andne** [comment]
Ok, I dug some more and it appears that the test helper that derives from UTestShell doesn't match what the macros normally do, so I think I just need to fix that up a bit.  Apparently the dependency tree between UTest and UTestShell changed at one point?

As a side note, should the intentional IGNORE_TEST usages be called out with a comment or something to help avoid confusion?  It looks like some are intended (TestUTestMacro.h I think) and others are things that just weren't fixed, and telling the difference can be a bit of a guessing game.

**Comment by Andne** [comment]
I submitted a pull request that fixes the test behavior and means that it no longer needs to be ignored.  I also made some changes to the other tests in SetPluginTest.cpp that seemed to be failing without actually reporting a failure.  Please take a look at it and see what you think.

**Comment by arstrube** [comment]
Way to go (me thinks)....

**Comment by basvodde** [comment]
Sorry for delay.

**Comment by Andne** [comment]
No problem, just was starting to wonder if I needed to fix something first
