### ISSUE TITLE
Tests that are not run due to build configuration

### ISSUE THREAD

**Issue by Andne** [cpputest/cpputest#472]
I've noticed that some tests are #ifdef out on certain platforms due to missing features (one I can think of is between 32 and 64 bit builds, related to 64-bit longs).  This means that there is a difference in the number of tests that are executed on these platforms.  I'm wondering if this is the best way to handle these tests, or if they should show as ignored on platforms that don't support them.  I think this also ties a little bit into the discussion on issue #343, since the two would affect each other some even though they are otherwise different ideas/features/etc...

Other people's thoughts on this?

**Comment by basvodde** [comment]
Some of the tests can't compile on other platforms so then it can't be ignored (e.g. 32/64 bit)

**Comment by Andne** [comment]
I guess I didn't quite think that through. I suppose it would be possible to write the macros/ifdefs such that it still got flagged as ignored but was otherwise not built, but that might be more wonky than just not compiling the test in the first place.

**Comment by arstrube** [comment]
Wouldn't it be simple to put an #else with the #ifdef that contains an ignored test by the same name, which is a dummy (possibly with a printed message explaining why a test was ignored)?

**Comment by arstrube** [comment]
Talking about ignored tests -- I noticed CppUTest has a couple of those and it would be helpful to have some sort of message (or at least comment) clarifying why it was ignored. Maybe the reason for ignoring them doesn't even exist any more (who knows) or maybe something should get fixed (again, who knows)?

**Comment by arstrube** [comment]
So, I tend to agree with @Andne and I think it would be quite easy to do.

**Comment by arstrube** [comment]
@Andne -- doing
```c
#ifndef WIN
TEST(foo, something_testing_64bit_longs) 
{
     // actual test here
}
#else
IGNORE_TEST(foo, something_testing_64bit_longs)
 {
      UT_PRINT("64 bit Windows has 32 bit longs");
}
#endif
```
would not be wonky, right? Also, pretty much self-documenting, I think.

**Comment by Andne** [comment]
That would be too bad, except I'm not sure like repeating the test name.  I think we need to go through the list of tests that are ignored and see why, some maybe be able to be tricked out through various things to always build, but thinking more others will need something like this - such as ones that test exception behavior, they don't apply at all without exceptions. Kind of makes me think there should be a distinction between tests that are ignored because they haven't been fixed (ok short term, bad long term) and tests that don't apply to the current platform.  I'd still like to see the later be flagged in results so that they can be accounted for, but they are not passed or failed, and using ignored seems to apply two very different definitions to the term.

**Comment by arstrube** [comment]
It would be too bad ???

You are right about two distinctly different uses for ignored tests. This is only about the one kind -- a test cannot be run at all under certain conditions, but can be run under other / normal conditions.

In this case, I think the exact same test name is not only possible, but beneficial. Because of the #ifdef ... #else ...  #endif involved there will be no error. Only if (by mistake) something is messed up, a compile error would result, which is a GOOD thing, in  my opinion.

At least in case of the 64bit long test case, I would like to see this.

I don't know about other possible applications.

And I certainly agree that some spring-cleaning of ignored tests would be quite desirable...

**Comment by Andne** [comment]
Oops, that's what happens when I'm typing on a tablet and don't proofread...

I agree, the same test name is good, and it won't cause errors due to the #ifdef/#else.  My concern was that someone would change a test name and not change it in both lines.  I know it's a pretty minor edge case, but still seems to be something we wouldn't want.

I agree that your suggestion only makes sense for tests that can't be run due to platform differences.  I was just saying that I wish there was a way to distinguish 'can't run because of the platform' and 'not run because someone said not to'.  Unfortunately, I don't think that most test frameworks or even the other tools that log tests have any support for another category like that.

**Comment by basvodde** [comment]
Maybe a macro such as TEST_IF(bool expression) could actually work. The only pain is that such a macro will need an #endif. But then you can do the ignore there also and get rid of most #ifs.

**Comment by Andne** [comment]
That's an interesting thought.  I'm not sure how well the macros would accept generating a conditional preprocessor tree, but it's something to try and see how it works out.

**Comment by arstrube** [comment]
TEST_IF() would print a dot when executing. If the condition is false, what would it print? A dash, perhaps? Or would IGNORE_TEST() be used if the condition is false and an ! be printed?

**Comment by Andne** [comment]
I'd say probably treat it as an ignored test, since that's all other tools have support for anyways.

Unfortunately, I'm not having much luck figuring out how to match up a conditional compilation block with a macro.  Trying to write it myself causes build errors, # becomes the stringify operator when working inside of macros, so you can't put extra directives inside a macro block.  Searching online turns up few results, but what there is pretty much says no, you can't do that.  While there still probably is a way to make a TEST_IF macro, I don't see how it could disable the compilation of the test code itself.

**Comment by basvodde** [comment]
Yeah, I guess you are right. The only way then would be to have specific TEST_IF_64_BIT-style macros.

That would be too bad though :(

**Comment by arstrube** [comment]
Close this? 

Current approach is to use IGNORE_TEST() with conditional compilation where possible ("possible" meaning a failed test would result, rather than a compiler error). 

I thought I had seen a "TEST_IF"-style macro in the existing tests, but couldn't find it anymore.

**Comment by Andne** [comment]
Sure, I suppose we can close it.  I tried to write a TEST_IF macro, and ran into some issues were you can't have #if inside the macro, so it didn't work.
