### ISSUE TITLE
MinGW build broken

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#475]
It's a long time now that I've used MinGW to build CppUTest. I was hoping to do a 64 bit build but failed for a number of reasons.

Doing so, I discovered that pthread functionality has crept into the GCC platform-specific code. Since MinGW is Windows, not Posix, it can't do that. I moved the #include back inside the ifndef `__MINGW32__` block and then discovered that the new Mutex functionality depends on it (it used to be only the SeparateProcess stuff, which would have been fine, since it has conditional defines. These were neglected for the Mutex code, though.

A couple of thoughts.

1. Strictly speaking, GCC is not a "Platform". Or only, if we apply certain restrictions.
2. Mutex should be implemented differently for Posix and Windows. How?
3. Nobody seems to have built CppUTest with MinGW since the introduction of Mutex
4. If 3.7 was released, maybe there would be more MinGW users, though.
5. Strictly speaking, there should be a platform like Gcc_no_Posix, perhaps? Rather than #ifdefs??

I had some other issues with MinGW / 64 bit but I think those are unrelated to CppUTest.

As an aside, VS2010 Express doesn't do 64 bit out of the box. That eliminated another easy route of testing....

**Comment by Andne** [comment]
I'm using CppUTest with MinGW (32-bit).  I haven't updated that project past the 3.6 release however, and I think the mutex logic was added after that.

To add an extra glitch with MinGW, depending on which version someone has it may or may not support posix threads.  Some versions include libpthread and others use the win32 thread libraries, so I'm not sure that all versions need to use Win32 threading instead of posix threading.

I do agree that GCC is not a platform, though I think that it almost is one, most GCC-based builds would be the same except for a couple of corner conditions I think though.

**Comment by arstrube** [comment]
Hmm. The MinGW homepage goes to great lengths explaining that MinGW is *not* a Posix based, but a Windows based environment. Obviously, add-ons are available.

In any case, it cannot be safely assumed that MinGW contains Posix support.

**Comment by arstrube** [comment]
P.S. I suspect there are more users out there who are using 3.6 and haven't noticed these problems - yet.

**Comment by Andne** [comment]
I just looked - the code tree I used when building MinGW has the pthread calls unprotected.  I'm not sure when the functions actually get called (I've never used -p), but at the very least pthread.h exists and can be built against with MinGW.

I have MinGW-w64 built for 32-bit with win32 threads and the setjump/longjmp exception handling mechanism.  Doesn't seem like pthread should even be able to build with that...

**Comment by arstrube** [comment]
I found a MinGW installation on my machine, based on GCC 4.8.1 and from a package called "x64-4.8.1-release-posix-seh-rev3.7z". I built against that and the build works. Also, if I change `long` to `long long` the 64 bit pointer printing test case succeeds, as it should.

My 4.8.2 installation, on the other hand, lacks Posix support.
