### ISSUE TITLE
Strange ignored test in MockSupporTest

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#476]
I was looking for ignored tests that could be fixed. I don't understand the purpose of this test:
```c++
IGNORE_TEST(MockSupportTest, strictOrderViolatedWithTwoMocks)
{
    //this test and scenario needs a decent failure message.
    mock("mock1").strictOrder();
    mock("mock2").strictOrder();
    mock("mock1").expectOneCall("foo1");
    mock("mock2").expectOneCall("foo2");

    mock("mock2").actualCall("foo2");
    mock("mock1").actualCall("foo1");

    mock("mock1").checkExpectations();
    mock("mock2").checkExpectations();
    CHECK_NO_MOCK_FAILURE();
}
```
1. The comment makes no sense to me.
2. I figure that the expected behavior is for strict order to be limited to a mock scope
3. The test fails, because strict order seems to be considered irrespective of scope

This would be a bug in CppUTest, which needs fixing? Or is it behaving as intended, and the test case ought to expect a failure?

**Comment by basvodde** [comment]
I think some people would want a failure at that point, but right now it doesn't. I'm not sure it should or shouldn't, but I guess it should.

**Comment by arstrube** [comment]
CppUTests current behavior is a mock failure. That is, CppUTest considers strict order globally and not by mock scope.

Is that the intended behavior? If possible, I would like a yes/no answer to this one ;-)

If the behavior is intended, the test should test it as such and pass. At least then the current (intended) behavior would be clearly documented by this test case.

If some people don't like that, they should raise an issue and then the behavior should be changed. 

If it is NOT the intended behavior, the comment should clearly state that CppUTest should consider strict order based on mock scope, but this is not currently the case and needs fixing. 

As for me, my expectation would have been that each mock scope has its own ordering; but I'd rather have a clearly defined behavior that I don't agree with, than an ignored test case that implies the behavior should be the opposite of what it actually is (but maybe not).

**Comment by basvodde** [comment]
Ok :) So, I guess it should.

When you uncomment the test, it fails, right? :)

**Comment by arstrube** [comment]
Yes, when I uncomment it, it the test fails.

**Comment by basvodde** [comment]
Ok, then it means "make me pass" :)

**Comment by arstrube** [comment]
Roger that.
