### ISSUE TITLE
Cleaning up ignored tests.

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#479]
I noticed there is a certain class of ignored tests that test whether something does or doesn't work inside an ignored test. The following seems as good an example of this as any:
```c++
IGNORE_TEST(UtestShell, IgnoreTestAccessingFixture)
{
    CHECK(&fixture != 0);
}
```
I find it hard to see the significance of such tests, since the test body is never run, so the code will never be executed.... except, if by some happenstance, it would execute unintentionally.

But then, we wouldn't need to test all kind of things in ignored tests, but we would only need this one test, something like:
```c++
IGNORE_TEST(UtestShell, IgnoreTestIsNotRun)
{
    FAIL("Code inside ignored test was executed.");
}
```
If this test fails, something is very wrong indeed. Otherwise, there is no reason to "test" code in ignored tests?

**Comment by basvodde** [comment]
The other tests that it compiles in an IGNORE_TEST :)

**Comment by arstrube** [comment]
It would also be nice to be able to distinguish this class of tests (if we do need them) from 'normal' ignored testcases.

**Comment by arstrube** [comment]
huh ?

**Comment by basvodde** [comment]
The test name does that, doesn't it?

**Comment by arstrube** [comment]
If the point is testing whether they compile, why not put them in a separate compilation unit that isn't linked? 

Also, it would be nice for the test name to be something like "CHECK_TRUECompilesInAnIgnoredTest" etc. At least I would find it less misleading.

**Comment by basvodde** [comment]
Putting them separate feels unnecessary. We could improve the name, fair enough :)

**Comment by arstrube** [comment]
Yeah, in this instance, maybe. Although it still can't possibly access the fixture by definition....

Others are called like CHECKWorksInAnIgnoredTest. But it will never "work". It will, at the most, compile.

If IGNORED_TEST meant still running it, but ignoring the results, I would understand these kinds of tests. But that would be somewhat crazy to implement, wouldn't it?

So, how about a separate compilation unit that isn't linked? Otherwise we just see a dozen or so ignored tests in the result, without really knowing whether we are living with 12 known bugs :--/

**Comment by arstrube** [comment]
Improving the name would definitely help for guys who read the tests, like myself.

It wouldn't help much with `..........!.!.!.!.!......`, though

**Comment by basvodde** [comment]
Yeah, I wouldn't really want to put them in a separate unit, we can improve the name though.

**Comment by arstrube** [comment]
Okay. I'll settle for that :)

That leaves the "Performance Test". I remember the issue that was raised. It actually takes around a second to execute, which is truly slow. But it seems unlikely that someone is going to implement some BlazinglyFastCallList algorithm any time soon..... any ideas?

**Comment by basvodde** [comment]
Keep it on ignore. I do want to look into that still :) One day.... when the world stops.

**Comment by arstrube** [comment]
<grin>

**Comment by arstrube** [comment]
About the test I quoted above.

We are already testing that CHECK compiles in CHECKWorksInAnIgnoredTest.

We know it won't run (although it actually succeed when it does).

So exactly what are we testing here?

**Comment by basvodde** [comment]
It checks that CHECK compiles in an IGNORED test and that it is ignored :)

**Comment by arstrube** [comment]
I mean it succeeds when I un-IGNORE it :)

**Comment by arstrube** [comment]
uh-huh. I suppose you love that test dearly ;-)

Because, we have already checked that. And this one is just somehow very odd...

**Comment by Andne** [comment]
We can test IgnoredUtestShell without creating tests that show up in the main results, and put the CHECK functions that would fail inside them still.  So it seems like all we are testing here is that that IGNORE_TEST macro actually creates an IgnoredUtestShell instead of a normal UtestShell.

**Comment by arstrube** [comment]
Magic?

**Comment by basvodde** [comment]
Remember that IGNORE_TEST is actually a different class and the CHECK macros use sometimes some scoped calls (not so much anymore). So, we want to ensure these are also working within the IGNORE_TEST context.

Changing a test to IGNORE_ is like changing a normal test to not IGNORE :) It defeats its purpose :P

**Comment by arstrube** [comment]
@andne that sounds like an interesting idea.

**Comment by arstrube** [comment]
But in order to check that (truly), the ignored test would have to run its body. But it can't run its body because it is ignored?

Besides, the test above is unique in that it tests something that has already been tested elsewhere, and to test whether the fixture is 0 at runtime, it would have to run, which it doesn't..... and so on.... and so forth....

**Comment by arstrube** [comment]
I guess to make this test do what it seems to be meant to do, we would need some mechanism to force the body of an ignored test to be run, and then we could find out whether the ignored test can indeed access the fixture.

(although I fail to see the problem if it couldn't -- it's not run after all)

**Comment by arstrube** [comment]
I think we have cleaned up everything that we agreed on. What's left is there on purpose.
