### ISSUE TITLE
Make error on Mac Yosemite, gcc/g++ 4.9

### ISSUE THREAD

**Issue by KarlWang** [cpputest/cpputest#481]
Hi, 

I downloaded CppUTest 3.6 and tried to compile CppUTest, when I did "make", it gave me the errors as below:

![screen shot 2015-02-08 at 10 02 14 pm](https://cloud.githubusercontent.com/assets/370291/6096384/3d07df80-afde-11e4-99fe-b7be5d50de73.png)

Cheers!
Karl

**Comment by arstrube** [comment]
The current head doesn't give me any such errors. @basvodde do we need a new release, perhaps?

**Comment by arstrube** [comment]
@KarlWang did you run ../configure before make? (Assuming you were building from within the cpputest_build folder)?

**Comment by KarlWang** [comment]
Hi @arstrube, I firstly downloaded source code from here(github), and yes, I **cd** to **cpputest_build**  and tried to run **../configure**, but actually the "configure" is not in the folder (command not found). 

So I downloaded from the official website, and got the "make" error above.

**Comment by basvodde** [comment]
Yes, we might want to push out some new release. Also, I'll need to look at the daily pushing which has not been done for way too long now.

**Comment by arstrube** [comment]
@KarlWang ahh, okay. When you download the head from Github, you need to do
```
cd cpputest_build
autoreconf -i ..
../configure
```
Don't worry about any warnings, in case they show up.

**Comment by arstrube** [comment]
Or try the "daily" build zips. It might have that problem fixed, even though it will not be current.

**Comment by KarlWang** [comment]
Hi @arstrube , for the one downloaded from github: the **cpputest_build** folder is empty.

>autoreconf -i ..
>-bash: autoreconf: command not found

For the one downloaded from official website: there is no **cpputest_build** folder.

**Comment by KarlWang** [comment]
I'll try the daily build zips. Thanks a lot!

**Comment by arstrube** [comment]
Looks like you need to install autotools. Something like:
```sh
% brew install autoconf
% brew install libtool
% brew install automake
```
(sorry, it's been a while)

**Comment by arstrube** [comment]
Used to be part of XCode, formerly...

**Comment by arstrube** [comment]
Of course, the daily zip should work as well.

**Comment by arstrube** [comment]
@KarlWang close this now?

**Comment by KarlWang** [comment]
Yes sure, thanks a lot!
