### ISSUE TITLE
Code coverage for asserts

### ISSUE THREAD

**Issue by gergely-marko** [cpputest/cpputest#485]
I love this framework and want to use it in our professional projects. For this I have to verify it, which involves code coverage measurements.
I was measuring coverage via running the tests shipped with the framework. I got quite nice results, but found some uncovered branches, which I think are tested.
For example:
```
UtestShell::assertCstrEqual
...
    if (actual == 0 || expected == 0)
    {
        failWith (StringEqualFailure (this, fileName, lineNumber, expected, actual), testTerminator);
    }
```
this failWith is never called, although tests are targeting this check, see:
TEST(TestFailure, StringsEqualFailureWithNullAsActual)
TestFailureTest.cpp, line 173

If I write a test, by calling STRCMP_EQUAL("ok", NULL), which fails, because of actual = NULL, then the aforementioned branch gets covered.

Same issue with assertCstrNoCaseEqual, assertCstrContains, assertCstrNoCaseContains.

Is it possible that in similar cases an overwritten method gets called, and not the original assertCstrEqual?

**Comment by Andne** [comment]
If I'm reading things right, the tests in the TestFailure group should never reach that failWith function anyways, I think it's supposed to be tested by the UnitTestMacros group in TestUTestMacro.cpp.  That said, it looks like there aren't any tests for the failure behavior of the STRCMP_EQUAL macro.

**Comment by arstrube** [comment]
I started writing some tests for this. Interestingly, STRCMP(NULL, NULL) passes. One might argue that it should fail, since neither side is a c-string? But then, they are equal as pointers, indeed :P...

**Comment by arstrube** [comment]
```
C:/CppUTest//tests/TestUTestMacro.cpp:136: error: Failure in TEST(UnitTestMacros, FailureWithSTRCMP_CONTAINSAndExpec
        actual <
Generic:1: error: Failure in TEST(Generic, Generic)
C:/CppUtest//tests/TestUTestMacro.cpp:130: error:
        actual <ok>
        did not contain  <>

.
Errors (1 failures, 1 tests, 1 ran, 1 checks, 0 ignored, 0 filtered out, 0 ms)
...
 - 31 ms
```
This looks like "ok" did not contain the empty string (which it should). In reality, "expected" was NULL. Comments?

**Comment by arstrube** [comment]
```
C:/data/00_Dev/05_CppUTest/cpputest/tests/TestUTestMacro.cpp:218: error:
        expected <1 (0x1) 0x1>
        but was  <0 (0x0) 0x0>
```
What is the point of displaying the hex value twice?

**Comment by arstrube** [comment]
Sometimes after a call to FailWith, the final line is covered, as in
```c++
      511:  339:void UtestShell::assertTrueText(bool condition, const char *checkString, const char *conditionString, const char* text, const char *fileName, int lineNumber, const TestTerminator& testTerminator)
        -:  340:{
      511:  341:    getTestResult()->countCheck();
      511:  342:    if (!condition)
       18:  343:        failWith(CheckFailure(this, fileName, lineNumber, checkString, conditionString, text), testTerminator);
      501:  344:}
```
Other times, however, it is not:
```c++
       32:  346:void UtestShell::fail(const char *text, const char* fileName, int lineNumber, const TestTerminator& testTerminator)
        -:  347:{
       32:  348:    getTestResult()->countCheck();
       60:  349:    failWith(FailFailure(this, fileName, lineNumber, text), testTerminator);
    #####:  350:}
```
Why?

**Comment by arstrube** [comment]
Oh, never mind. It can get covered when there's a condition inside, so there are tests for which no failure occured.

**Comment by arstrube** [comment]
Currently killing myself trying to get rid of -O2 in the coverage run...

Where do the other 13500 lines in configure come from, that don't have a counterpart in the 500 lines of configure.ac? Specifically, where does the code come from that set CFLAGS to "-g -O2" (or not)?

Help would be much appreciated. A coverage run really shouldn't be optimized. This makes for very confusing stuff in the .gcov files.

**Comment by basvodde** [comment]
-g -O2 is default when you do not set a CFLAGS or not pass it to automake.

**Comment by arstrube** [comment]
Oookay. Where in configure.ac would I specify that I want otherwise, just when the coverage option is specified?

**Comment by basvodde** [comment]
Easiest is probably to add it to the call of configure. Just add CFLAGS= to there

**Comment by arstrube** [comment]
Sounds good to me -- I don't like messing with configue.ac ;-)

**Comment by arstrube** [comment]
I believe I fixed this?

**Comment by arstrube** [comment]
I think this can be closed. I worked a lot on getting all of CppUTest covered, and used LCOV exclusion in the few places that can't possibly covered (e.g. a return after a FailWith() ).
