### ISSUE TITLE
opencv memory leak detection 

### ISSUE THREAD

**Issue by reneparis** [cpputest/cpputest#487]
I've tried to test some classes which are highly based on opencv. As it seems, cpputest has some issues with the internal allocator structure of opencv (smart reference-counting pointers). 

In my setup call I try load an image using imread (from <opencv2/highgui.hpp>). What I get is either

```
/usr/local/include/opencv2/core/cvstd.hpp:618: undefined reference to `cv::String::allocate(unsigned long)
/usr/local/include/opencv2/core/cvstd.hpp:660: undefined reference to `cv::String::deallocate()'
/usr/local/include/opencv2/core/mat.inl.hpp:534: undefined reference to `cv::fastFree(void*)'
/usr/local/include/opencv2/core/mat.inl.hpp:555: undefined reference to `cv::Mat::copySize(cv::Mat const&)'
/usr/local/include/opencv2/core/mat.inl.hpp:645: undefined reference to `cv::Mat::deallocate()'
```

I've tried to **disable memory leak detection** as described on the website (as command within in the main as well as with the corresponding configured build.

Nevertheless I get some strange errors, I'm not able to fix:
When building my tests the compiler still says:
```
/usr/local/include/opencv2/core/mat.inl.hpp:534: undefined reference to `cv::fastFree(void*)'
/usr/local/include/opencv2/core/mat.inl.hpp:645: undefined reference to `cv::Mat::deallocate()'
```
but also my TEST() Makros fail with
```
blablaTest.cpp:24: undefined reference to `operator new(unsigned long, char const*, int)'
blablaTest.cpp:24: undefined reference to `operator delete(void*, char const*, int)'
```

Can anyone suggest a workaround (or what I'm doing wrong)?

**Comment by arstrube** [comment]
This may be stating the obvious but -- are you sure you are actually linking the opencv library/ies?

**Comment by Andne** [comment]
The last block looks like you still have the includes overriding the new function in your project without having CppUTest itself building in the corresponding functions.

The others look like you may have forgotten a library include.

**Comment by reneparis** [comment]
Now I really feel like a noob :D

Adding a main() to my original project showed (of course) the same missing references, as the compiler trashed all "unused" code *g*. Now it works even with Memory Leak Detection "on".

Thanks a lot!
