### ISSUE TITLE
Switching from TEST to TEST_ORDERED crashes

### ISSUE THREAD

**Issue by tiancovici** [cpputest/cpputest#495]
I'm trying to organize my tests, and just found out  about ordered test header.

I assigned an additionally argument, a priority number.

All tests run smoothly, but before the program ends, it crashes and says it failed to access the memory due to violation reading. 

The stack has the following in it

>   UtestShell::getGroup()  Line 246 + 0x3 bytes    C++
>     TestRegistry::endOfGroup()  Line 76 + 0x45 bytes    C++
>     TestRegistry::runAllTests()  Line 66 + 0xc bytes    C++
>     CommandLineTestRunner::runAllTests()  Line 105 + 0x19 bytes C++
>     CommandLineTestRunner::runAllTestsMain()  Line 80 + 0x8 bytes   C++
>     CommandLineTestRunner::RunAllTests()  Line 62 + 0x8 bytes   C++
>     <CommandLineTestRunner::RunAllTests()  Line 48 + 0xd bytes  C++

Am I missing some sort of group initializer?

**Comment by basvodde** [comment]
Is this on the mainline or the released version? @arstrube did a lot with ORDERED_TEST recently...

**Comment by arstrube** [comment]
@tiancovici True... I fixed one crash related issue and the issue of losing test cases a while ago. Looks like you might have run into the crash... This was after the 3.6 release.

**Comment by tiancovici** [comment]
I think it might be the 3.6, but I'm not sure how to check the current version. 
If the fix was implemented after 3.6 release, does this mean you wouldn't be able to download it off the https://cpputest.github.io/ site?

**Comment by arstrube** [comment]
Yes, the "Latest passing build" -- which is probably far from latest -- should have the fix.

**Comment by basvodde** [comment]
Hrm, yeah we need to fix the latest passing build still :) Anyways, let me know if it is fixed.

**Comment by arstrube** [comment]
@tiancovici fixed?

**Comment by basvodde** [comment]
Assume it is fixed.
