### ISSUE TITLE
Run Visual C++ builds on Appveyor?

### ISSUE THREAD

**Issue by Andne** [cpputest/cpputest#508]
We have gcc building cpputest on travis-ci, and we've had some issues recently with pull requests breaking the Visual C++ builds.  From what I can tell, Appveyor is basically the Windows version of travis-ci, so what do people think about setting up the project build there as well?

I'm not sure how much of this I can or can't set up on my own, I'm willing to work on getting the project to build, but I suspect that some of the integration hooks will project settings that I don't have access to.  Is there interest in getting this set up?

**Comment by arstrube** [comment]
Sounds good to me... Could we build against older VC versions as well? Does it integrate with Github the way that Travis-CI does?

**Comment by Andne** [comment]
Here's the list of installed software, it looks like back to VS 2008, so anything from then on should be pretty easy, earlier versions such as VC6 may not be possible to support, though there is a mention of being able to trigger the install of other software, so there's maybe a way given enough fiddling around. It appears that even MinGW is available, though not cygwin.
http://www.appveyor.com/docs/installed-software

The libgit2sharp project (https://github.com/libgit2/libgit2sharp) appears to have badges for both Appveyor and Travis-CI on their project page, so I would assume that it works pretty similarly to Travis-CI.

**Comment by arstrube** [comment]
MinGW would be great. Cygwin GCC tends to have fewer, if any, differences to Linux GCC. Currently, we cant test MinGW as part of the TravisCI build. Yesterday I fiddled with VC6 on XP. I didn't want the IDE; however, it turns out you need the IDE even for a command line build (or to convert to a .mak file. Maybe we should have the .mak file checked in vor VC6? That would make it somewhat easier.

While we are still supporting VC6, I would find it disappointing if we set up build server and it couldn't do that.

**Comment by basvodde** [comment]
Wow, this would really be good. Does it also integrate with github?

**Comment by Andne** [comment]
Assuming we could get just the VC6 compiler installed, could we use the CMake build to verify the source code works?  It does mean that the project files wouldn't be very well maintained though.  I'd rather not check in the .mak file, things like that always seem dirty to me, and sometimes they have absolute paths that you have to fiddle with/correct before the actual build can be run (a project I use at work does that, makes creating local builds to try fixes out a pain).

As far as I can tell (based on other projects, never used it myself), there is integration with github.

I know what you mean about IDE's.  I set up a TeamCity build network at home a while back, and getting even the current versions of Visual Studio to install the tools only without the IDE isn't really supported (and I'm still not sure I didn't break something in the process).  I find that rather silly, especially now that I don't actually need the IDE to execute the build itself since msbuild is just a command-line tool anyways.

**Comment by arstrube** [comment]
I _suppose_ cmake should be possible. I would prefer that, too. Because the only way to get the .mak files seems to be via IDE export.....

Currently I am trying to help Paul Bussmann and I am looking to install VC6 (VS98) locally. No luck so far finding a download...

**Comment by Andne** [comment]
I got AppVeyor working on a branch in my fork, building vs VS2008 and VS2010.  There's something off with the post-build event in the 2010 build, but I don't think that's related to the AppVeyor configuration itself at all.  I can clean it up a bit and submit a pull request, but I don't know how exactly to configure AppVeyor to connect to the cpputest/cpputest repository.

@basvodde I suspect that you'll need to create an AppVeyor account and do the initial project setup in order to have it connected to the organization account in github correctly.  Creating an account is pretty easy - I just used the connect to github functionality to log in.  I'm not sure if there's a different process for creating a project that part of an organization instead of once that is for a personal repository or not.

Oh, I also added a build status badge to the README.md file, you can see it in my appveyor branch here: https://github.com/Andne/cpputest/tree/appveyor

**Comment by jwgrenning** [comment]
Hi All

There were two post build events that I put in long ago that I think are 
no longer needed and cause problems.

1) Moving the VS build to a subdirectory. - I was trying to keep several 
built VS versions on my machine.  I doubt anyone needs this.  I think it 
should be removed from all builds

2) Running the tests as a post build event It makes it look like the 
build fails when the tests are failing.  - I think this can go away too.

James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - 
pragprog.com/titles/jgade/
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by Andne** [comment]
1) We can keep this behavior without the post-build event if people think that would be helpful.  Instead of using Debug and Release as the output directories, we can set them up to be a directory specific to the version of Visual Studio or the Visual C++ compiler.  We'd probably want to do the same with the intermediate directories as well if we decide to take that route.  Either way, I think that the output configurations in the projects could use some cleanup.

2) I'm torn on this one.  I like the extra control (especially in a build server) that not running the tests as part of the build provides, but I also like the quick feedback that automatically running the tests at the end of the build sequence provides.  Newer versions of visual studio (2012 and up) have a test runner that could be extended to support CppUTest executables for automatic discovery and execution, but that doesn't help the older versions.

**Comment by jwgrenning** [comment]
One of the main problems with "1" is that the target directory has to 
exist to be able to copy to it, unless windows now has mkdir that does 
not error out when the directory exists.

re "2" the command line build can run AllTests.exe upon successful 
completion of the build. I say you should have the most say as a windows 
user.

I usually run via hot key - Run without debugging - and a window pop's 
up.

I am happy to let the windows users decide on these as long as 
everything runs out of the box with no settings changes needed.

Are the window projects setup to stop reporting errors with the first 
error?  That would be a good addition if not already there.

thanks, James

**Comment by Andne** [comment]
What I was thinking was to set the Visual Studio output directory to the location that we want the library to exist it (i.e. lib or lib/vs2010), then the build process will create the directory if it needs to.  My question is how do we want this to work?  Should the different versions all output to the same folder, or should the output to a unique folder for each version?

In reality, I'm not very fond of Visual Studio's default output/intermediate directory structure, and often override it in my own projects.  What do people thinking about changing the intermediate directory to obj and the output directory to lib for CppUTest and something for AllTests?

I'm not very familiar with the cmake or autotools builds, but based on the scripts I assume that the default build command does not run the tests, they have to be specifically requested to be executed at the end of the build?  Failing a build when a test fails becomes very annoying when you start trying to use the debugger to figure out where your test went wrong.  Granted, I'm not sure that's the right way to figure out the problem either, but sometimes it seems to be the easiest.

**Comment by arstrube** [comment]
I would like the output/intermediate dir to be overridden, so it ends up below ./cpputest_build. I would also like (if this is not already the case) for the lib to be written to ./lib, regardless of VS version. I don't like obj, because for the automake build, we cd into ./cpputest_build. I guess ./cpputest_build/obj would be fine though. (Once can use automake from the root, but this would put all the output there, so we started using ./cpputest_build). The seame is true for cmake. Also, the default Debug/Release directories make sense, if one keeps both (but then the libs should end up with different names, too).

If anyone wants/needs to keep around different versions, then they could manyally put them inside subdirectories of ./lib. If its non-existance is a problem, we can put a .gitignore into ./lib that ignores everything but itself. This will cause the directory to be cloned with the rest of the repo.

I like the tests to run as a post-build step, most of the time. In my own codeblocks projects, I have a configuration "test" that does this and a configurration "debug" that does not. I suppose one could do something similar with VS and it would make more sense to me than Debug / Release. I like it that I can double-click to the failed test with the post-build step. Out of ten failed test cases, maybe there is one I need to debug.

With automake, we can run make tdd (which I do most of the time) or just make.

**Comment by Andne** [comment]
Ok, so here's what I'm thinking for layout:
cpputest_build/ <- Build folder
   Debug/  <- Folders per configuration to avoid conflicts
   Release/  <- Folders per configuration to avoid conflicts
   AllTests.exe <- Output the test executable here
lib/  <- Output folder, common to all configurations, only used by the library project outputs
   CppUTestd.lib <- Debug output
   CppUTest.lib <- Release output

This won't require cpputest_build or lib to exist in the repository, Visual Studio will create them as needed.

Unfortunately, I don't think VS really supports multiple build targets, though with a bit of work I could probably embed an option in the UI to enable/disable the post-build test run that could also be controlled via a command-line parameter.  Set it to go to the .user file when changed in the UI and it wouldn't even cause files to appear that they've been written (I actually did this with an old unit test framework at work once).

I'm debating if Debug/Release really matters or not, we've removed most of the differences between the two since we had to disable optimizations.  I'll have to look what options may still be different between the two.  Given how unportable pdb files are, it may make sense to have the Release build use C7 format instead of a pdb file if nothing else.

**Comment by arstrube** [comment]
Sounds good to me. Just to avoid possible misunderstanding:
```
cpputest_build/ <- Build folder
cpputest_build/Debug/ <- Folders per configuration to avoid conflicts
cpputest_build/Release/ <- Folders per configuration to avoid conflicts
cpputest_build/AllTests.exe <- Output the test executable here
lib/ <- Output folder, common to all configurations, only used by the library project outputs
lib/CppUTestd.lib <- Debug output
lib/CppUTest.lib <- Release output
```
Right?

**Comment by arstrube** [comment]
I tried the following with VS2010:
1. Duplicate Debug configuration.
2. Call the duplicate Test
3. In the Properties Dialog for the post build step, set "Use in build" to "false".
4. The IDE contains a bug. You should be able to set "Use in build" per configuration, but it will set it for all configurations, even though the description says otherwise. Therefore,
5. In the XML file, do:
```xml
<PostBuildEventUseInBuild Condition="'$(Configuration)|$(Platform)'=='Test|Win32'">true
</PostBuildEventUseInBuild>
```
We'd need to check about whether the older version will do that. One might have to remove the post-build step instead of setting the flag to false.

**Comment by arstrube** [comment]
Can be done for VC6 (IDEworks fine)

**Comment by arstrube** [comment]
Works correctly in VS2008 (imported von VC6).

Three configurations means more maintenance though. Personally, I have no use for the Release configuration (other than testing that it work, because it is there ;-)

**Comment by arstrube** [comment]
Also, it is quite easy to set "Use in build" to "No" for debugging, so maybe we don't need the extra configuration?

**Comment by Andne** [comment]
Yup, that's what I was thinking for layout.

Setting "Use in build" to false is pretty easy, I just don't like that it will cause the file to show as modified, might accidentally get checked in and change whatever the default is supposed to be (though I suppose reviewing pull requests would make this less likely).  I agree that I'd rather not have the extra configuration to maintain.

Do you guys usually build CppUTest once and use it, or do you pull it into most of your project trees and build it on a per-project basis? I prefer to have it as a library with headers that I can pull into a project rather than pull it in as source code.  However, pdb files for a static library aren't relocatable, so having a build with the debug data either embedded in the library file or without debug data starts to become useful.

**Comment by arstrube** [comment]
I build it once and use it. That is, I don't do CppUTest on a per-project basis, at least not when using it in actual projects.

All my actual projects use Gcc / Clang though. So I don't have the problem with pdb files.

I did have a problem once transferring the library to another machine, because the debugger couldn't locate files, as the file paths of my original machine were embedded in the debug info. I solved this by mirroring the file structure of the target system(s) when building the library with debug info.

**Comment by Andne** [comment]
Yeah, that's always an issue with debug info, though some debuggers can figure it out if you can point to a base path that a compiler ran from.

@basvodde Now that you've merged the pull request, can you create a project on appveyor so that it's tied to the cpputest organization and the url is correct?  Currently if I create a project the URL shows it under my name.  Thanks.

**Comment by basvodde** [comment]
Will do soon, first trying to close the other -v -ojunit thread that has been going on forever :)

**Comment by basvodde** [comment]
Oh, added it, but the VS2010 build failed :)

**Comment by Andne** [comment]
Yeah, the lib folder and the copy post-build event are breaking that build currently.

**Comment by basvodde** [comment]
Ok, anything I still need to do related to the Appveyer? Can the people who do more Windows work fix it now?

**Comment by Andne** [comment]
It should be fixable in the project files, I just need to apply some of the changes arstrube and I were talking about earlier related to folder structure.

Not sure if you care about this or not - the path on appveyor appears to be basvodde/cpputest, would that be better off being cpputest/cpputest, if possible?  That was part of the reason that I was asking you to set up the project, but it's largely just a matter of semantics.

**Comment by basvodde** [comment]
It pulls it from: git clone -q --branch=master git://github.com/cpputest/cpputest.git C:\projects\cpputest

I don't think I can login with an organizational account to Appveyer. I think its the same with Travis.

**Comment by Andne** [comment]
Yeah, but for some reason travis has cpputest/cpputest as the URL and appveyor doesn't.  I thought I saw other projects that had an organizational account as part of the base url, but I maybe they weren't really organizational accounts.

**Comment by Andne** [comment]
I did some digging and I think these two links explain some of what needs to be done to get the URL to match github and travis-ci's:
http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations
http://help.appveyor.com/discussions/questions/591-appveyor-for-teams

So I think what needs to be done is to create a cpputest account on appveyor that is not tied to github, then add whoever as team members to that account.

**Comment by basvodde** [comment]
Ok, for not, I don't think that would be worth it. Especially as it seems to require a new account, which it doesn't now.

**Comment by Andne** [comment]
Ok, so then I think we can close this since appveyor is functional.
