### ISSUE TITLE
Question: To Clear Or Not To Clear - mock().clear()

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#515]
In my own testing experience, I have usually been penalized for forgetting to call `mock().clear()` - mostly in the form of getting failed tests because of memory leaks. So far, so good. That was to be expected.

A bit more strange was that I ran into situations where `mock.clear()` called from `teardown()` did not seem to do the trick; I had to call it from the test case directly. At one point, I believed that mock calls from within setup() could be handled by teardown(), but mock calls from within test cases could not. It doesn't seem likely though.

Now I ran into both problems with CppUTest's own tests when fixing up the VC6 compile. To my surprise, there were a lot of places in MockSupportTest where `mock().clear()` should have been called, but wasn't.

Under VC6, this lead to crashes (trying to read non-existing parameters from an invalied stack location) - VC6 actually segfaults on that. It also lead to failing test cases due to previous test's expectations still being around somehow.

I fixed the problems for VC6, and in order to do so, there were places where I had to call `mock().clear()` from the testcase, even though it was already in `teardown()`. 

Also, this begs the question, how come not cleaning up properly was "alright" in virtually every version of GCC, Clang, and subsequent versions of MSVC, too?

What is the reason why `mock().clear()` sometimes has to be called from the testcase? There shouldn't be any difference, really?

**Comment by basvodde** [comment]
Are you sure the segfault is caused by clear()? Thinking it over, it should be caused by checkExpectations(), as the clear() won�t use the stack objects.

**Comment by arstrube** [comment]
Err, no. Rather, it  was caused by NOT calling clear().

I found since I posted this that once I called clear() in teardown(), certain individual conditions had to be "cleared" before teardown() was called (e.g. a pending expectation) so the test wouldn't fail on the check in teardown().

Hence I resolved to always call clear() from teardown(), but to clear individual conditions in the testcase by other means than clear(). Although there would be no harm in calling clear() twice; just confusing.

**Comment by arstrube** [comment]
I don't like the check in teardown() very much, but I have occasionally done it myself, it is convenient, and I have no better solution to offer ;-)

**Comment by arstrube** [comment]
I think not calling clear() caused just failures, though. The segfault was caused by not resetting something that clear() doesn't take care of.

**Comment by arstrube** [comment]
1. It might be worth your while looking at the commits in VC6-2 (#517) individually, and in sequence.

It was a learning experience.

**Comment by basvodde** [comment]
But the MockSupportPlugin is installed, thus no need to clear in teardown as that happens automatically

**Comment by basvodde** [comment]
Or is there something wrong with the main?

**Comment by arstrube** [comment]
Oo-kay. Never used that much in my tests. Will check this out. 

With the tests being the way they are now, I should be able to remove mock().clear() from teardown(), and no failures / crashes ought to occur, right?

**Comment by basvodde** [comment]
Right :)

**Comment by arstrube** [comment]
Done: --> CRASH

**Comment by basvodde** [comment]
But why :)

**Comment by arstrube** [comment]
It's the main(). VS uses only one of the two AllTests.cpp. Guess it will have to be the one from tests/CppUTestExt/ and all should be well.

**Comment by basvodde** [comment]
Oki! So maybe none of the other fixes is needed as the Plugin tried to do cleanups :)

**Comment by arstrube** [comment]
Correct. Will submit new pull request for the change to AllTests.dsp

**Comment by basvodde** [comment]
Good :)

The MockSupportPlugin saves tons of work, but when it isn't there it does lead to nasty crashes.

**Comment by arstrube** [comment]
Roger that.
