### ISSUE TITLE
Drop'em Or Test Them?

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#541]
```c++
129  0 : bool CommandLineTestRunner::isVerbose()
130    : {
131  0 :     return arguments_->isVerbose();
132    : }
133    : 
134  0 : bool CommandLineTestRunner::isColor()
135    : {
136  0 :     return arguments_->isColor();
137    : }
138    : 
139  0 : int CommandLineTestRunner::getRepeatCount()
140    : {
141  0 :     return arguments_->getRepeatCount();
142    : }
```

**Comment by basvodde** [comment]
Drop them ? :)

**Comment by arstrube** [comment]
Okay. Let's see if anyone will miss them..... ;-)

**Comment by basvodde** [comment]
I miss them already!

**Comment by arstrube** [comment]
Oh no.... :-( 
Test them?

**Comment by basvodde** [comment]
No was j/k :)

**Comment by arstrube** [comment]
Ohhh.... Joe King....

**Comment by arstrube** [comment]
Actually just realized they are private. So we couldn't make use of them or test them, even if we wanted to ;-). Funny actually, there seems to be no compiler warning for unused private methods.... though they are no more useful than unused static functions, actually....
