### ISSUE TITLE
Printing out all available unit test group names without running them

### ISSUE THREAD

**Issue by mmidor** [cpputest/cpputest#563]
It would be very helpfull to generate list of all test groups in executable. Space-separated I think is the best choice.
Then I could fetch list of groups by passing eg. -pg parameter to executable, and then run every group of test passing -g <groupname> to the executable.
Will be very helpfull when working with CMake and CTest.

I have already looked into the code and it looks to be quite easy to implement.
Even I can do this ;)

**Comment by basvodde** [comment]
It would probably need to be 3 options then:
-> Print test case names
-> Print test group names
-> Print test group and test case names.

Waiting for the pull request ;P

**Comment by mmidor** [comment]
As you suggested, I have created two switches:
-lg to list all group names
-lt to list all group::test cases
Listing only test cases names has no sense to me...

One more idea apperaed in the meantime:
ability to run tests within a group in reverse order. We have discovered that uninitialized pointers may still allow program to run correctly, depending of previously executed code. The randomization of the execution order may be helpfull. I'll try to implement simple reversed test execution order.

**Comment by basvodde** [comment]
Yup, sounds good. Lets try to do small features at the time and don't forget to test-driven them, please :)

**Comment by arstrube** [comment]
Maybe, if we go for this, we should name the switches `-lg` and `ln`as we currently have `-g` and `-n`already, not `-t`.

I am a little hesitant about a feature like that as this is not really the job a unit testing framework. In my opinion this is where someone might create a supporting script rather than add a feature to CppUTest.

For example, the CppUTest Eclipse plugin does this very nicely. The important feature in CppUTest is that it can take an arbitrary list of tests and groups as input, and that already exists. My suggestion would be to share a supporting script rather than add this feature to CppUTest itself.

Remember also that we have the (lesser know) feature of feeding the -v ouput directly back to a test run, e.g. TEST(group1, test1) TEST(group1, test2) TEST(group4, test1). For example, one can use this to re-run all failed tests.

Since a script would be needed in any case to extract from the lists of tests and the list of groups which tests to run, I think that script could be based on -v output instead.

**Comment by basvodde** [comment]
I think we don't have the support to get a list of tests and test groups without running them. I think that feature is potentially quite useful!

**Comment by arstrube** [comment]
No, not without running them... How about something like --dryrun that simply produces -v output?

**Comment by basvodde** [comment]
Why not just produce a list of test groups and test names as suggested? It is unlikely to confuse people and would be making scripting a lot easier...

**Comment by arstrube** [comment]
Okay, you guys win ;-). Maybe `-ln` would be preferable though to `-lt`?

**Comment by arstrube** [comment]
Having said that, it took me a while to get used to `-n` for starters. I often typed `-t` and got an error. :-(

**Comment by basvodde** [comment]
Yes

**Comment by mmidor** [comment]
Yes! I like your approach basvodde :) Thank you!
@arstrube:
I don't understand your hesitating about this - sounds like someone from Microsoft "Cool feature, let's NOT do this to prevent peoples being too happy" ;p
We know about -v switch but how can it help us preparing to run list of tests? If some test fails I'll not get list of the others. I don't know how Eclipse plugin works but probably, as a IDE plugin, is has access to the sources and thus can search for them. We are running blackbox executable built previously by Jenkins on remote computer. The rule is to not trust programmer that he modify testing script for CMake every time he add a new test. Just like CppUTest which doesn't require to run each test manually but runs all of them automatically. 
CTest requires to run each test group separately from single executable or prepare separate executable for each of them, which takes to much time (a lot of targets to define for CMake, manually of course). I would like to build single executable containing all of tests, and then ask it for test groups it contain (-lg), and as a final step run them one by one (-g <gname>) gathering results to prepare report.
I agree about switch naming - good point.
Also the feature you mentioned, feeding output to test run, may me useful. However we are trying to use CTest feature to detect and rerun tests that failed.

Regards, Mariusz Midor

**Comment by arstrube** [comment]
@mmidor haha, Microsoft ;-). No, you go ahead, it's fine with me :)

As for CTest, I saw it in the CMake Travis build and I guess I wasn't too impressed with CTest. I think that your approach is a great way of working around its limitations.

Once the generation of lists is working, maybe you wouldn't mind putting that in the CMake build of CppUTest itself, also? That would make the CTest run more meaningful and folks using CTest could use it as a model for their own testing....

**Comment by basvodde** [comment]
I think we have this now, closing this issue. -ln and -lg
