### ISSUE TITLE
Handling of Platforms Without fork()

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#567]
Currently, Win32/MinGW is considered the only platform without fork(), reflected by `__MINGW32__` (or some such) being defined. I thinke VC is excluded via __MSC_VER.

As I am revisiting the TI CL2000, I realize this is a platform without fork() also. And in fact, the majority of embedded platforms (e.g. that are not running some sort of OS) will be like that. So it doesn't really make sense to include ever more platforms in these conditional compilations.

As a workaround, I can of course define `__MINGW32__` when compiling for such platforms, or live with the failures. However, wouldn't it more elegant to have a definition such as `__CAN_FORK__` and set this via configuration?

**Comment by basvodde** [comment]
Agree. Should be tested in the autoconf files. Still a lot to do there :(

**Comment by arstrube** [comment]
I am always a bit weary of touching the autoconf stuff myself :-/. But you are right.

Also, we have now tests that require to be run in a separate process in various test sources. I was wondering whether it would be better to have these tests all in one place, even though they test different things? Not sure I have a concrete idea how to do this though...

I recall there was an issue with spreading test groups over several sources?

**Comment by basvodde** [comment]
There is still a potential issue with that, which is the discussion related to making TestGroup an actual class.

Anyways, I'd prefer not to put all tests that run in a seperate process in one file, but keep them in the place where they belong.

**Comment by arstrube** [comment]
Okay, agreed. With something like  `__CAN_FORK__`that will be much easier to handle.

**Comment by KisImre** [comment]
I have a problem which is related to this issue. When I'm compiling CppUTest on an ARM based, Linux running devboard the ```TEST(UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess, DummyFailsWithMessage)``` fails.
After examining the problem I've found out that the ```cpputest/src/Platforms/Gcc/UtestPlatform.cpp``` file checking the availability of the ```fork()``` function only using the ```__MINGW32__``` macro, but the ```cpputest/tests/UtestPlatformTest.cpp``` runs the dummy test on this condition: 
```
#if defined(__MINGW32__) || defined(_MSC_VER) || defined(__IAR_SYSTEMS_ICC__) || defined(__arm__) || defined(__TMS320C2000__)
```
Clearly the ```__arm__``` macro caused the trouble.
I'm not so confident with the autoconf but I've found a ```HAVE_FORK``` macro in the ```config.h```. Maybe this can be used for determining ```fork()``` availability.

**Comment by arstrube** [comment]
I was afraid something like that might happen.... 

__arm__ is far too generic here, but I couldn't find anything better for the Keil compiler it was meant for (I am not using it myself).

Doing this via autoconf would be much cleaner. However, we'd also need to take into consideration that for most targets that actually do NOT have fork, we won't be running autoconf. Can we be sure that HAVE_FORK will be set correctly in all cases? It should be undefined or 0 by default. Then only Automake should set it to 1. If automake works right, it shouldnt be set even for MinGW and we should be fine.

**Comment by arstrube** [comment]
PR #724 should fix this, without breaking the Keil stuff.

**Comment by KisImre** [comment]
Thank you for the quick fix. I used to use the ```__ARMCC_VERSION``` macro for checking if it's a Keil environment as well.

**Comment by arstrube** [comment]
I checked out HAVE_FORK and found it to work fine with Automake and other platforms (where it would be manually set, either via IDE or via config.h).

I am having trouble to get cmake to recognize the presence of fork(), though, resulting in build without fork that should actually be with fork, like on Ubuntu or OSX. 
```
check_function_exists(fork HAVE_FORK) 
```
always fails :-(. Anyone with Cmake expertise who can help out? Googling doesn't help, either. Usually you get hits of people failing to find fork under MinGW or Visual Studio. We _know_ that. But how come it is not found under Ubuntu?

**Comment by arstrube** [comment]
@KisImre in your particular case, are you actually using the `-p` switch on CppUTest, or is it just that you need a clean build (no matter whether running in a separate process is enabled)? Also, which build system are you using?

**Comment by arstrube** [comment]
@basvodde I'm submitting a PR; however, even though it appears to work fine (and will work fine for most people) it needs to be fixed.

**Comment by basvodde** [comment]
@arstrube A key problem that isn't solved related to HAVE_FORK and automake is that automake should generate a distributable config.h, so that when using make install it will install the generated file. It should then not be called config.h but generate something like CppUTestConfig.h. This is a long standing open issue which prevents the serious use of automake (or CMake) for things like this.

**Comment by basvodde** [comment]
Generated config is installed, so this ought to be closed?
