### ISSUE TITLE
Coverage reports not easy to come by

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#568]
+ Reports are produced on Travis CI but I doubt anyone bothers to sift through gazillions of lines of log text to find them ;-)

+ Probably the easiest practical way to get coverage reports (plus Lcov reports, if Lcov is available) would be to do: `../configure --enable-coverage CFLAGS= CXXFLAGS=` followed by `make check_coverage`. But then, you have to dig somewhere to find this.

+ Where would be a good place to document the second point?

+ Wouldn't it make sense to put the Lcov report on cpputest.github.io? Currently, Lcov is not present for the Travis build though.

Oh and here's the bad news: Included with the ability to generate reports is an __"inbuild" command that will erase them as soon as the report is finished__ :-(

**Comment by arstrube** [comment]
Removing the files may make sense for the Travis CI build, but even though, shouldn't there be a
```bash
clean_coverage:
```
target to do this job, to be invoked separately?

**Comment by arstrube** [comment]
I have prepared a pull request to fix this. However, __why__ do the reports need to be deleted immediately? It feels a bit counterintuitive to make `remove_coverage_results` part of the `check_all` target. I did this so as to not change the current behavior, but it does feel a bit strange.

**Comment by basvodde** [comment]
I think the test reports were already uploaded by the github_deployer, which is still broken and that is probably because of me :) I still need to look at your earlier work on this.

**Comment by arstrube** [comment]
I added documentation on how to generate a coverage report locally to cpputest.github.io

**Comment by arstrube** [comment]
Has this Issue been addressed by Coveralls? If so, how would Coveralls results be made available to (prospective) users?

**Comment by arstrube** [comment]
I just noticed that the coveralls report doesn't cover some lines that should have been covered, e.g. MockIgnoredCall methods. This might be due to optimization setting, or due to tests not being compiled. I think I ruled out the latter.

TravicCI is giving me grief right now. It runs most of the jobs within 15 minutes or so, then it leaves the remaining three just hanging in the queue for an hour...

**Comment by basvodde** [comment]
Yeah, not sure whats going on with Travis. Perhaps we ought to contact them. The mainline travis hasn't finished for quite a while :(

**Comment by arstrube** [comment]
I'll try and move the coverage build up so it gets executed, at least while I am fiddling with it...

**Comment by arstrube** [comment]
In this case, we also wouldn't know in case the Dos build broke at some point :-(

**Comment by arstrube** [comment]
I got the coverage job to run by eliminating the build matrix and all other jobs entirely. So I can at least maybe figure out why there are lines not covered on Coveralls that should be.....

**Comment by arstrube** [comment]
I think that Coveralls has pretty much solved this.
