### ISSUE TITLE
Mock expectations are not counted as checks

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#572]
As far as I can see, mock expectations do not contribute to the number of checks listed at the end of a test run. So you can have: 
```bash
OK (5 tests, 5 ran, 0 checks, 0 ignored, 0 filtered out, 58 ms)
```
Unfortunately, this result will be the same, regardless of whether these 5 tests are devoid of any checks, or have in fact 20 mock expectations.

Wouldn't it make sense to have mock expectations counted as checks, too?

**Comment by basvodde** [comment]
Sure, I guess so

**Comment by arstrube** [comment]
The easy route would be to put `CHECK(true)` into `MockSupport::expectOneCall()` & friends ;-)...

I'll experiment with that a bit.

Since `UtestShell::getTestResult()` is protected, a more appropriate approach would require that UtestShell had an additional public method such like `countCheck()`, which would do `getTestResult()->countCheck()`

Then we could do `UtestShell::getCurrent()->countCheck()`. The same call could be used to fix `CHECK_THROWS`, which currently has my `CHECK(true)` workaround.

**Comment by basvodde** [comment]
Yeah, calling countCheck would be better than doing CHECK

**Comment by arstrube** [comment]
Hmmm. I did that, only to find that I disliked making this part of the UtestShell interface, breaking encapsulation of the check count. Anything and anyone could now increase the check count something linke this:
```c++
TEST(foo, gimme_a_check) {
    UtestShell::getCurrentShell->countCheck();
}
without ever having checked anything.

Therefore, I settled to make `checkCount()` as a protected method to MockSupport (where it is needed).
Internally, it does CHECK(true), which I find clearer, but I could call the underlying assert instead. And yeah, a user can call CHECK(true) anywhere to increase check count anyway ;-). So if you prefer adding checkCount to UtestShell, I'll go with that.

**Comment by basvodde** [comment]
Yeah, if people want to artificially increase their check count, so be it :)

**Comment by arstrube** [comment]
The current pull request has it in MockSupport. Will change it shortly...

**Comment by arstrube** [comment]
Oops. Not anymore?

**Comment by basvodde** [comment]
Sorry, merged it too quickly :(

**Comment by arstrube** [comment]
No problem. I'll make the change on a new pull request then.

**Comment by arstrube** [comment]
I would have liked to put a few lines of documentation at cpputest.github.io.

However, we don't have a page on building and installing CppUTest there. That's where I would want to put it, really.

**Comment by arstrube** [comment]
Solved
