### ISSUE TITLE
Yosemite strange test failure

### ISSUE THREAD

**Issue by basvodde** [cpputest/cpputest#608]
After upgrade to Yosemite:

/tests/UtestPlatformTest.cpp:105: error: Failure in TEST(UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess, DivisionByZeroInSeparateProcessWorks)
../include/CppUTest/TestTestingFixture.h:112: error:
	actual <.
OK (1 tests, 0 ran, 0 checks, 0 ignored, 0 filtered out, 1 ms)

>
	did not contain  <Failed in separate process - killed by signal 8>

@arstrube Doesn't seem the division by zero works...

**Comment by arstrube** [comment]
That's an interesting finding. The funny thing is I've been using Yosemite all along. BUT I've shyed away from 10.10.3 and the new version of Xcode that comes with it, for a number of reasons. Seems to be related to the version of Xcode. Still strange...... What version compiler did you use?

**Comment by basvodde** [comment]
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by arstrube** [comment]
Will check it out tonight.

**Comment by arstrube** [comment]
Mine is:
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
Might it depend on the target, rather than the compiler? I always thought that behavior when dividing by zero depended on the OS / processor, rather than the compiler....

**Comment by Andne** [comment]
I suspect it may be a bit of both, the OS and processor are what create the error in the first place, but it's probably up to the compiler (and to a certain extent the standard library it comes with) to determine how to handle that error.

Unfortunately, I don't have a Mac, so I don't know if it's possible to update the OS without the compiler or the other way around, so narrowing it down is likely to be tricky.

If memory serves, there's a divide by zero in order to create NaN in a different test, so shouldn't that test be crashing too?  Does the divide by zero need to be there, or is it just to cause a crash in order to test other behaviors?

**Comment by arstrube** [comment]
Hi Andy. 

Interesting point about the NaN... Apparently, 0.0F / 0.0F -> NaN, whereas 0x0L / 0x0L is supposed to raise the signal.

We can of course simply remove the test case... signal 8 is typical of Unix-type systems (which the Mac is supposed to be, and which do happen to support fork() ;-).

**Comment by arstrube** [comment]
I looked at the test and it appears that clang always took a bit more to actually swallow the division by zero thing:
```c++
static int _divisionByZeroTestFunction()
{
    volatile int a = 1;
    return 1 / (a - a);
}
```
Is there a better way, that will also work for Mac OS 10.10.3? 

One could kill the process with signal 8 directly, but I think that's pointless because I already do that for another signal, so I would be more inclined to remove the test in that case.

**Comment by basvodde** [comment]
I think the problem is worst. If I run the tests in the debugger, then all the tests which run in a separate process fail. If that can't be fixed, then that is not really acceptable and I would vote for removing them all.

**Comment by basvodde** [comment]
I guess this is fixable with:
http://stackoverflow.com/questions/21554195/why-waitpid-return-1-when-run-in-debugger

**Comment by arstrube** [comment]
You can't really debug the part that runs in a separate process. This is no reason to remove the tests (besides, they did not fail)

If you want to debug the _divisionByZeroTestFunction(), the best way to do so is thus:
```c++
TEST(UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess, DivisionByZeroInSeparateProcessWorks)
{
    // fixture.registry_->setRunTestsInSeperateProcess();
    fixture.setTestFunction((void(*)())_divisionByZeroTestFunction);
    fixture.runAllTests();
    fixture.assertPrintContains("Failed in separate process - killed by signal 8");
}
```
If it is working right, you should get terminated with a signal in the current process

**Comment by arstrube** [comment]
As I said above, if we can't get a "genuine" division by zero on OS X anymore, maybe I'll use:
```c++
kill(getpid(), SIGSTOP);
```
instead. Or we drop the test case, as this is basically covered by the one that expects signal 11.

**Comment by arstrube** [comment]
If I let those 6 test cases run in the debugger under Cygwin, and put a breakpoint at the end of main(), they all pass. 

However, a break point inside the test functions would be ignored, as they run in a child process, not the one the debugger is attached to.

**Comment by basvodde** [comment]
They all fail on MacOSX but the Stackoverflow link gives a hint on how to fix it.

**Comment by arstrube** [comment]
You mean, they all fail, no matter whether run in the Debugger or not? This is very strange behavior indeed.

**Comment by basvodde** [comment]
No, only one fails outside debugger. All fail when running in the debugger.

**Comment by basvodde** [comment]
And I don't need to debug, just run them in the debugger :)

**Comment by arstrube** [comment]
I am more worried about the one that fails outside the debugger. As I cannot reproduce this, I still need to know:

If you comment out running in a different process, does the test case crash, or doesn't it ? Please do NOT run this in the debugger (unless you want to actually debut it).

Thanks

**Comment by basvodde** [comment]
Well, having cases fail by default in the debugger isn't really an option. The cases fail due to waitpid failing, as pointed out in the stackoverflow link.

**Comment by arstrube** [comment]
Thank you for the information. I was about to ask you for the failure message.

You are aware that the debugger thingie has nothing to do with the test cases, but with the way that PlatformSpecificRunInSeparateProcess() works, so the fix will have to go there.

It is not that test cases fail in the debugger. It is that PlatformSpecificRunInSeparateProcess() does.

So, how many times ought it to keep trying? And how long ought it to wait between attempts?a

**Comment by arstrube** [comment]
Or should we rather close our eyes to the failures and remove the test :-P

**Comment by basvodde** [comment]
The StackOverflow article suggests we have missing code to deal with EINTR.

**Comment by arstrube** [comment]
Exactly. Involving restarting waitPid() in a loop if (or while) it is 4.

**Comment by basvodde** [comment]
Forever?

**Comment by basvodde** [comment]
Lemme check, quickly

**Comment by arstrube** [comment]
My hope is once would be enough. Forever is out, no?

**Comment by basvodde** [comment]
It is already forever :)

**Comment by basvodde** [comment]
Ok, the problem is this:

            if (w == -1) {
                result->addFailure(TestFailure(shell, "Call to waitpid() failed"));
                return;
            }

Because the manual says:

     If wait() returns due to a stopped or terminated child process, the process ID of the child is returned to the calling process.
     Otherwise, a value of -1 is returned and errno is set to indicate the error.

And, the errno:

     [EINTR]            The call is interrupted by a caught signal or the signal does not have the SA_RESTART flag set.

----------------
So, the waitpid is interrupted, but it isn't restarted when it is. There is no code to properly deal with this.

**Comment by arstrube** [comment]
Right.

As the debugger issue is quite different to the original one, I opened #615 to deal with it there.

**Comment by arstrube** [comment]
As for the original issue, could you please find out for me how to provoke a real division-by-zero-signal (using volatile in the declaration doesn't seem to do the trick anymore with the new version of LLVM.

**Comment by arstrube** [comment]
As for looping "forever" -- actually we are talking about a new loop here, not the existing one.

The existing one will end when the child process returns.

The new "forever" loop would end when fork() doesn't return -1 with errno==EINTR. Which may or may not happen.... We'll see.

**Comment by basvodde** [comment]
Its -o2. Without optimization it works.

**Comment by arstrube** [comment]
The division by zero was optimized away... Crash prevention by optimization :-P

So, what should we do about this?

**Comment by basvodde** [comment]
Fixed it in upcoming pull request.
