### ISSUE TITLE
PlatformSpecificRunInSeparateProcess() Fails in Debugger under Mac OS X

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#615]
@basvodde reports that, when run in the debugger under Mac OS X Yosemite, all test cases that actually run in a separate process fail, with waitpid() returning -1 and ERRNO set to EINTR

The beginning of the discussion can be found in #608.

As this bug will involve fixing PlatformSpecificRunInSeparateProcess(), I started a new issue.

**Comment by arstrube** [comment]
As for looping "forever" -- actually we are talking about a new loop here, not the existing one.

The existing one will end when the child process returns.

The new "forever" loop would end when fork() doesn't return -1 with errno==EINTR. Which may or may not happen.... We'll see.

**Comment by arstrube** [comment]
@basvodde -- as an aside, how do you actually debug on your Mac? I tend to use the Code::Blocks IDE under Windows, but the Mac version has a bug preventing it from starting the debugger properly. Using the commandline debugger to me feels a bit like driving a car over a bumpy road in the dark with no headlights on ;-).

**Comment by basvodde** [comment]
I use a command line debugger :) I love it :)

**Comment by arstrube** [comment]
Oookaaay.... I use the command line for quite a few other things, so ... any good place to get started?

**Comment by basvodde** [comment]
Uhm, donno actually. Cheat sheet? I've used it for so long, it is quite automatic for me. But there is only like 10 commands you frequently use.

**Comment by arstrube** [comment]
Fixed by #616.

**Comment by arstrube** [comment]
Now you mention it -- how come you've even got gdb on your Mac? Mine only has lldb. The little I tried, I definitely find standalone gdb a lot more useful than standalone lldb (tried the Cygwin one).

**Comment by arstrube** [comment]
Okay. I got gdb running. Quite a performance.

**Comment by arstrube** [comment]
which one is your debugger?

**Comment by basvodde** [comment]
gdb
