### ISSUE TITLE
Build on Appveyor using Autotools

### ISSUE THREAD

**Issue by Andne** [cpputest/cpputest#633]
Need to add a configuration to appveyor that runs a MinGW build using autotools.

**Comment by arstrube** [comment]
Am I right that the cmake build which was merged is 32 bit?

I think we should have at least one Windows 64 bit build (and the Cmake MinGW build seems a good candidate) because weird things can happen with I32L32P64 that none of the other builds will pick up.

**Comment by arstrube** [comment]
Sorry for venting my feelings against that architecture ;-). I do think CppUTest needs to be tested against it, though

**Comment by Andne** [comment]
Right, the later changes that got merged after your PR was to make it  32bit.  I've been working on having both builds included, and should have a pull request soon.

**Comment by arstrube** [comment]
@Andne Hi Andy, I was just updating the VC projects to match our latest pull when I notice problems with building the Debug configuration. Isn't this included in the Appveyor build? Shouldn't we have both Release and Debug configurations built (or get rid of one?), in order to avoid this kind of bad surprise?

For example, way back in 3.7.2 I noticed that the Debug build is trying to link the release library in VC60.

**Comment by Andne** [comment]
I think I may have asked about Release vs. Debug at one point.  It wouldn't take much to run both through Appveyor.  I don't remember what I did by default though, if it was both configurations or just one (Guessing the later based on what you're seeing).

So, what do you think - should we have a Debug and Release build, or strip one out and have a Release build only?  The biggest challenge with the two is which version of the C library to link against, because if CppUTest doesn't agree with the code that's under test, it tends to cause some warnings.  I think I tried to look for how to avoid that, but I didn't find anything obvious or simple.

**Comment by arstrube** [comment]
I guess if we can run both in Appveyor, I would prefer doing so. I fixed the libraries in the .dsp, however, for the life of me I can't find where the libraries are defined in the 201x version. They both link the Debug version (which seams to be the lesser evil) but I don't see it specified anywhere. It seems to come from the "Defaults", but where do the "Defaults" come from?

**Comment by basvodde** [comment]
This is done and can be closed, right?

**Comment by arstrube** [comment]
MinGW on AppVeyor is alive and kicking :D. Apart from the occasional hickup....
