### ISSUE TITLE
Appveyor MinGW test results need improvement

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#637]
Currently, when a test fails, the build fails, without any clue which test failed and why. This is probably due to the -junit switch being used.

We either need to use -v -junit, or use gtest the way it now works on Travis.

**Comment by basvodde** [comment]
I'm puzzled about the "or use gtest" comment? What do you mean by that?

**Comment by arstrube** [comment]
I looked at the yml, and it may not be the way to go here -- but remember that @mmidor added the `-lg` option? He also added to the travis script the following lines:
```bash
    ctest -V || exit 1
```
as well as code in the CMakeList.txt to run the tests group by group. The output of this can be seen on the Travis CI cmake build.

**Comment by arstrube** [comment]
In the case of Appveyor, it has its own way of running the tests, based on xml junit output, but the script is malfunctioning / incomplete in that failures are not printed to the console. Maybe just a line is missing.

**Comment by arstrube** [comment]
Correction: I think `ctest -V || exit 1` has always been there, but the code in CMakeLists.txt has been improved.

**Comment by arstrube** [comment]
@basvodde - you were so fast doing 3.7.1 :P

In my thinking, the MinGW / Appveyor stuff is still in the middle of being put together...

**Comment by basvodde** [comment]
Fast is different for a change. I'll go back to being slow soon again :)

The Appveyor things aren't needed for the release. The MinGW is now compiling, and that was the main reason for putting out 3.7.1. Now I can update the homebrew scripts :)

**Comment by arstrube** [comment]
I didn't realize that information about (failing) tests is displayed on a separate "Test" tab in AppVeyor. Very nice, actually.

**Comment by mmidor** [comment]
@arstrube I did not modified Travis script. I added more code to tests/CMakeLists.txt to run each group of test separately and to get more verbose output from CTest.

**Comment by arstrube** [comment]
@mmidor Yeah, I realized that when I looked more closely. Either way, the output is better than before. Could you pls have a look at issue #638? It is really a problem in the TestRegistry; just happened to show up in ctest unexpectedly...

**Comment by arstrube** [comment]
@basvodde oh, I only noticed now that I seem to have a thing mixing up gtest and ctest. I meant ctest -- but actually, the Appveyor script does it much better.
