### ISSUE TITLE
Debian build failed due to division by zero test

### ISSUE THREAD

**Issue by basvodde** [cpputest/cpputest#645]
@arstrube :)

https://buildd.debian.org/status/package.php?p=cpputest&suite=sid

---

It seems that on arm64 the explanation in test-suite.log is:
# FAIL: CppUTestTests

....
tests/UtestPlatformTest.cpp:128: error: Failure in TEST(UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess, DivisionByZeroInSeparateProcessWorks)
./include/CppUTest/TestTestingFixture.h:112: error:
       actual <
Generic:1: error: Failure in TEST(Generic, Generic)
       Failed in separate process

.
Errors (1 failures, 1 tests, 0 ran, 0 checks, 0 ignored, 0 filtered out, 1 ms)

```
   did not contain  <Failed in separate process - killed by signal 8>
```

**Comment by basvodde** [comment]
http://nominolo.blogspot.sg/2012/07/arms-new-64-bit-instruction-set.html

Especially this section:

There is now an integer division instruction. However, it does not generate an exception/trap upon division by zero. Instead (x/0) = 0. That may seem odd, but I think it's a good idea. A conditional test before a division instruction is likely to be cheaper than a kernel trap.

**Comment by arstrube** [comment]
Neat ;-)

I will remove the test case. I will start my own collection of "CppUTest XXtreme" testcases from now on. I find such test cases interesting, but they shouldn't be part of the tests that get always executed. In this particular case, nothing is going to be lost, not even test coverage ;-)

I never knew how different some things can be handled by some compilers / architectures.
