### ISSUE TITLE
Erroneous code on cpputest.github.io

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#646]
```c++
class MyTypeComparator : public MockNamedValueComparator
{
public:
    virtual bool isEqual(void* object1, void* object2)
    {
        return object1 == object2;
    }
    virtual SimpleString valueToString(void* object)
    {
        return StringFrom(object);
    }
};
```
Correct is: 'virtual bool isEqual(**const** void* object1, **const** void* object2)`
And: 'virtual SimpleString valueToString(**const** void* object)'

**Comment by arstrube** [comment]
Not sure when this changed; it is true in v.3.7.1

**Comment by basvodde** [comment]
Fixed?

**Comment by arstrube** [comment]
We did fix it. But I'm not sure the fixed version is on github.io; would need to check.

**Comment by basvodde** [comment]
Ok, let me know :)

**Comment by arstrube** [comment]
Well, it has been fixed, but there's a small typo on cpputest.github.io. The third line now reads `virtual SimpleString valueToString(cont void* object)`

**Comment by arstrube** [comment]
Also, why is 3.7.1 on cpputest.github.io for download, when we have 3.7.2?

**Comment by arstrube** [comment]
@basvodde the typos have all been fixed

Types fixed. I think we can close this issue since 3.8 is coming Real Soon Now.
