### ISSUE TITLE
Bug: Annoying inconsistencies Using Comparators

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#650]
The online manual hints as much.... Here's my experiences

1. Without MockSupportPlugin, installing in setup():
    + mock().removeAllComparators() or equivalent has has to be called explicitly in teardown(), or a memory leak will occur. 
    + This is counter intuitive, I expected it to be cleared up with clear().
2. With MockSupportPlugin, installing in main():
    + The comparator will not be found
    + It will be cleaned up automatically, which is nice
    + This is useless though, because it is not possible to use the comparator. I consider this a bug
3. With MockSupportPlugin, but installing comparator in setup():
    + Will work as expected, but
    + Will crash, unless you call removeAllComparators() in teardown(), **as well as** calling mock.clear()

I think this needs fixing, rather than documenting.

**Bug 1** Plugin installed in main() is not found.
**Bug 2** Crash when installing from setup().

Perhaps we could start by stating clearly how it is supposed to work.

**Comment by arstrube** [comment]
Okay. **Bug 1** isn't a bug. I overlooked that when installing from `main()` you have to install from `MockSupportPlugin`, not from `mock()`.

**Comment by Andne** [comment]
I was wondering about that one, hadn't encountered it.

I have run into **Bug 2** myself, but haven't really looked at it at all, just moved all of my comparators to be installed through `MockSupportPlugin` instead.

**Comment by arstrube** [comment]
Well, I had a good look at what happens with **Bug 2**. Strictly speaking, this isn't a bug either, but it is unexpected behavior that can be very hard to track down. It's all documented on cpputest.github.io, but the details are easy to miss.

Also, what is nasty about this is that all seems to be well as long as no test case involving comparators fails. The crash only occurs on failure.

I wish there was a better way of handling this, but currently, these are the options:
+ Not to use MockSupportPlugin
+ Install all comparators via MockSupportPlugin from main() - preferred.
+ If installing comparators via Setup() or inside the TEST(), call mock().checkExpectations() from the same scope (even if using MockSupportPlugin
+ Instantiate comparators in global space

@basvodde one solution would be to actually copy the comparators when installing them. Shouldn't that be relatively easy to implement?

**Comment by basvodde** [comment]
Because the comparators can be created by users and they might have complex objects inside, therefore I never wanted to copy them.

I basically always install my comparators in Main via the MockSupportPlugin.

**Comment by arstrube** [comment]
Hmmm. Makes sense. I will do the same from now one, and instruct my colleagues to do the same. I must admit, I haven't done any serious work with comparators so far, but I can see it coming ;-)

**Comment by arstrube** [comment]
So, since we are not going to change anything, I am closing this now.
