### ISSUE TITLE
Build fails with GCC 5

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#661]
Building with ***GCC 5.1.0 (x86-64)*** fails with two errors:
```
MockExpectedCallTest.cpp:531:46: Format %p expects argument of type void, but argument 2 has type »MockExpectedCallComposite*« [-Werror=format=]

     info += StringFromFormat("%p", &composite);
                                              ^
```

and
```
Unknown commandlineoption »-Wno-c++98-compat« [-Werror]
```

*(Both translated from my system language)*

Tested with current git version and v3.7.2 (using `cmake -DC++11=ON ..`)

With GCC 4.9.x everything was ok.

**Comment by offa** [comment]
Seems the root cause is the first error, I'll open a PR with a fix.

**Comment by offa** [comment]
Autotools will need some more years, here it is ...

**Comment by basvodde** [comment]
Should the second one be fixed too still? We should be able to do that within the configure.ac

**Comment by offa** [comment]
> Should the second one be fixed too still?

I don't think so, it looks like the error was caused by the type mismatch only. With the cast added the second error is gone.

**Comment by basvodde** [comment]
Ok, strange. Anyways, your other PR is merged.

**Comment by offa** [comment]
Thanks, issue is solved then.
