### ISSUE TITLE
Valgrind detects memory leak in CppUTest

### ISSUE THREAD

**Issue by sbellus** [cpputest/cpputest#665]
We found out memory leak in CppUTest version 3.7.2 in function SimpleString::split.
See comment how we fix it.

```cpp
void SimpleString::split(const SimpleString& delimiter, SimpleStringCollection& col) const
{
    size_t num = count(delimiter);
    size_t extraEndToken = (endsWith(delimiter)) ? 0 : 1U;
    col.allocate(num + extraEndToken);

    char* str = buffer_;
    char* prev;
    for (size_t i = 0; i < num; ++i) {
        prev = str;
        str = StrStr(str, delimiter.buffer_) + 1;
        size_t len = (size_t) (str - prev) + 1;
        deallocStringBuffer(col[i].buffer_); // this is fix of memory leak
        col[i].buffer_ = copyToNewBuffer(prev, len);
    }
    if (extraEndToken) {
        col[num] = str;
    }
}
```

**Comment by basvodde** [comment]
Interesting! Especially as we also run valgrind in the build.

Thanks for this interesting bug. I couldn't figure out how it could *ever* actually leak memory as the allocate in the beginning removes all allocated memory. But, I do agree... it is wrong. The fix is not a good fix though as you don't want to deallocate another buffer_ in this method. I changed the fix to #667 which ought to fix it too. Could you check it, and I'll merge it in a couple days.

Thanks!

**Comment by sbellus** [comment]
...beginning removes all allocated memory...
I don't see it there.

Function  `col.allocate(num + extraEndToken);` allocates array of `SimpleString`s. Default constructor `SimpleString(const char *value = "");` is called for each one. Because default parameter is valid pointer, constructor allocates memory in function `copyToNewBuffer`.
Then in `buffer_` is pointer to allocated memory and this pointer is overwritten in `SimpleString::split` and definitely lost.

Am I miss something?

**Comment by sbellus** [comment]
I guess your fix `col[i] = copyToNewBuffer(prev, len);` will not remove memory leak. But may be I got it wrong.

Function `col[i] = copyToNewBuffer(prev, len);` allocates memory and returns pointer to allocated memory. Assignment operator `SimpleString& operator=(const SimpleString& other);` will be called. Temporary object `SimpleString` is created from return value of function `copyToNewBuffer(prev, len)`. Temporary object allocates and copy string from return value of function `copyToNewBuffer(prev, len)`. This newly allocated string is then copied to `col[i]` (old `col[i]` is deleted and new one is allocated), temporary object is deleted.
Pointer from allocation in function `copyToNewBuffer(prev, len);` in expresion `col[i] = copyToNewBuffer(prev, len);` is definitely lost.

**Comment by basvodde** [comment]
@sbellus 

To your first comment re the leak. Think you are right, let me look into it. I'm especially interested in why it wasn't discovered earlier... 

To my fix. The fix I did should cause the leak to go away as the operator= will deallocate the previous buffer.

**Comment by sbellus** [comment]
...operator= will deallocate the previous buffer...
Yes it will deallocate `buffer_` in `SimpleString`. But where/how is dealocated memory that was allocated in `col[i] = copyToNewBuffer(prev, len);` by function ` copyToNewBuffer(prev, len);`?

**Comment by basvodde** [comment]
Ah, yes :) You are right.

Let me look at it again. I'm not comfortable with your suggested fix as I'd prefer the function to not play with the member variables of other SimpleStrings. And I'd like to understand why it wasn't caught earlier.

Thanks for this!

**Comment by sbellus** [comment]
Welcome.

I know that it is dirty fix. But as usual, we needed fix it in hurry to save our delivery :).

**Comment by basvodde** [comment]
Fixed with #677

**Comment by arstrube** [comment]
@basvodde - did you find out why this one wasn't caught?

**Comment by basvodde** [comment]
Yes, memory leak detector is not used in SimpleString as SimpleString is user in the MemoryLeakDetector.

I've fixed that, now the SimpleString tests *do* use the memory leak detector

**Comment by arstrube** [comment]
Ahh. Catch-22 :)
