### ISSUE TITLE
Build error with CMake and MSYS2 mingw-w64

### ISSUE THREAD

**Issue by somemetricprefix** [cpputest/cpputest#669]
If attempt to use cmake to build CppUTest on msys2 I get following compiler errors:

    ../src/Platforms/Gcc/UtestPlatform.cpp: In function 'int IsNanImplementation(double)':
    ../src/Platforms/Gcc/UtestPlatform.cpp:237:12: error: conversion to 'float' from 'int' may alter its value [-Werror=conversion]
         return isnan((float)d);
                ^
    ../src/Platforms/Gcc/UtestPlatform.cpp:237:12: error: conversion to 'float' from 'int' may alter its value [-Werror=conversion]
    ../src/Platforms/Gcc/UtestPlatform.cpp:237:12: error: conversion to 'float' from 'int' may alter its value [-Werror=conversion]
    ../src/Platforms/Gcc/UtestPlatform.cpp:237:12: error: conversion to 'int' from 'float' may alter its value [-Werror=float-conversion]

Note that while cmake fails the autotools build works fine on msys2.

### Steps to reproduce:

1. Get [MSYS2](https://msys2.github.io/) and follow their install intructions
2. Install mingw-w64, cmake and ninja with `pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja`
3. Open MinGW-w64 Win64 Shell and execute `cmake -G Ninja . && ninja` in the CppUTest folder

**Comment by arstrube** [comment]
For a conversion to / from float to int to occur at all, you must be attracting a very weird implementation of isnan(). Personally, I doubt that is anything to do with CppUTest.

For example, the "normal" declaration would be something like:
```c
#define isnan(x) (sizeof (x) == sizeof (float) ? __isnanf (x)	\
		  : sizeof (x) == sizeof (double) ? __isnan (x)	\
		  : __isnanl (x))

```
according to this [page](http://sourceforge.net/p/mingw/mingw-org-wsl/ci/5c582dfd1a0d8471477ffa3a6389cccf4928df34/tree/include/math.h#l348)  (so, strictly speaking, the cast to double is unnecessary), which resolves to something like:
```c
__CRT_INLINE int __cdecl __isnan (double _x)

```
which is a lean match to the call within CppUTest. Could you please dig up your math.h and check the definition of isnan()?

**Comment by arstrube** [comment]
P.S. Unfortunately, I can't personally take the time to set up an entire build environment to reproduce your problem.

**Comment by somemetricprefix** [comment]
The [definition for isnan()](http://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/crt/math.h#l608) for mingw-w64:

```c
#define isnan(x) \
__mingw_choose_expr (                                         \
  __mingw_types_compatible_p (__typeof__ (x), double),            \
    __isnan(x),                                                 \
    __mingw_choose_expr (                                     \
      __mingw_types_compatible_p (__typeof__ (x), float),         \
        __isnanf(x),                                            \
    __mingw_choose_expr (                                     \
      __mingw_types_compatible_p (__typeof__ (x), long double),   \
        __isnanl(x),                                            \
    __dfp_expansion(__isnan,(__builtin_trap(),x),x))))
```

The according function is resovled with C++ templates defined in [line 75](http://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/crt/math.h#l75).

Like you said it should resolve to `extern int __cdecl __isnanf (float)` because the parameter for `isnan()` is casted to float in UtestPlatform.cpp like `return isnan((float)d);`

I don’t really know why the compiler throws those conversion errors when calling `isnan()` like that. A simliar error occurs if I change the line to `return isnan(d);`:

```
../src/Platforms/Gcc/UtestPlatform.cpp: In function 'int IsNanImplementation(double)':
../src/Platforms/Gcc/UtestPlatform.cpp:237:12: error: conversion to 'float' from 'double' may alter its value [-Werror=float-conversion]
     return isnan(d);
            ^
../src/Platforms/Gcc/UtestPlatform.cpp:237:12: error: conversion to 'int' from 'double' may alter its value [-Werror=float-conversion]
```

I wonder why the autotools build works flawlessly. It should be using the exact same header file.

**Comment by arstrube** [comment]
Very strange indeed. The first error in particular, since the macro would imply that it chooses the correct version if its three internal isnan definitions. As for the 'double' to 'int' conversion, I have no idea. It is almost as if it it is digging up some strange definition elsewhere. But where, and why?

**Comment by arstrube** [comment]
It might be interesting to compile with -E instead of -c to see what is the actual preprocessor output....

**Comment by arstrube** [comment]
What happens if you `#include <cmath> and call std::isnan() ?

**Comment by somemetricprefix** [comment]
```diff
diff --git a/src/Platforms/Gcc/UtestPlatform.cpp b/src/Platforms/Gcc/UtestPlatform.cpp
index 447b801..809fdad 100644
--- a/src/Platforms/Gcc/UtestPlatform.cpp
+++ b/src/Platforms/Gcc/UtestPlatform.cpp
@@ -38,7 +38,7 @@
 #include <stdarg.h>
 #include <setjmp.h>
 #include <string.h>
-#include <math.h>
+#include <cmath>
 #include <ctype.h>
 #include <unistd.h>
 #include <signal.h>
@@ -232,13 +232,8 @@ void (*PlatformSpecificFree)(void* memory) = free;
 void* (*PlatformSpecificMemCpy)(void*, const void*, size_t) = memcpy;
 void* (*PlatformSpecificMemset)(void*, int, size_t) = memset;

-static int IsNanImplementation(double d)
-{
-    return isnan((float)d);
-}
-
 double (*PlatformSpecificFabs)(double) = fabs;
-int (*PlatformSpecificIsNan)(double) = IsNanImplementation;
+int (*PlatformSpecificIsNan)(double) = std::isnan;
 int (*PlatformSpecificAtExit)(void(*func)(void)) = atexit;  /// this was undefined before

 static PlatformSpecificMutex PThreadMutexCreate(void)
```

This change fixes the cmake build and at the same time breaks the autotools based build:
```
../src/Platforms/Gcc/UtestPlatform.cpp:41:17: fatal error: cmath: No such file or directory
 #include <cmath>
                 ^
```
Is UtestPlatform.cpp compiled as C code here?

**Comment by arstrube** [comment]
1. You'd have to keep the `IsNanImplementation(double d)` wrapper, because using the function pointer breaks template-based Clang (sigh).
2. Nice that it fixes cmake :-)
3. Now that's one weird error again. I don't know what to say... It is compiled as C++.

**Comment by somemetricprefix** [comment]
I get the same error (cmath not found) with autotools and clang(++).

**Comment by somemetricprefix** [comment]
Looks like -nostdinc++ compiler flag in CPPUTEST_CXXFLAGS causes this behavoir. When I remove it everything builds fine.

**Comment by arstrube** [comment]
This one happens when the -nostdinc++ option is present on the compiler command line. This is strange, since it is not the default. Running ../configure without arguments should remove it

**Comment by arstrube** [comment]
Too bad though, because CppUTest needs to be able to build with the  -nostdinc++ flag also -- so we can't use this solution, unfortunately.

**Comment by somemetricprefix** [comment]
The only fix I could come up with would be to use ugly #ifdef code, which I don’t think is the right way.
As this is clearly a mingw-w64 bug I’ll close this issue and file a bug report at their issue tracker.
Thank you very much for your help! :-)

**Comment by arcadien** [comment]
Hello,
I have the same problem.
@somemetricprefix, did you opened a bug on the MinGW side? I'm using 4.9.2-posix-sjlj.
Can you give more explanation about your "ugly #ifdef code" solution? thanks!

**Comment by somemetricprefix** [comment]
@arcadien 
The MinGW bug is [here](https://sourceforge.net/p/mingw-w64/bugs/481/).
Unfurtunalety don’t have the code for a workaround anymore. All I remember is that I got it compiling for MinGW but breaking other platforms at the same time.
