### ISSUE TITLE
Question: What is "make tdd" supposed to do when

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#672]
`--disable-std-c --disable-std-cpp` is configured?`

We know the tests will definitely throw failures when run. Should they compile, though?

`make all` compiles fine. I recently noticed that `make tdd` contains an error; but is it really worth fixing a compile error in tests that we know won't run?

**Comment by arstrube** [comment]
I guess this question goes mostly to @basvodde :-)

**Comment by basvodde** [comment]
The idea is that it should compile. The -no-std-c will never work as we do use std-c. But we want to minimize the std-c dependencies, and compiling with -no-std-c will ensure that we do not accidentally introduce new dependencies.

If someone would implement all of std-c in CppUTest, then it would also link and run. That isn't likely to happen nor be beneficial. But keeping the dependencies to std-c low will enable porting easier to platforms that have no or little stdC support (e.g. Linux Kernel)

**Comment by arstrube** [comment]
What I mean is that I accidentally introduced a dependency in one of the tests (`errno.h`), but this doesn't affect CppUtests. Since the tests are not expected to link and run, this shouldn't be a problem, right?

**Comment by basvodde** [comment]
Not sure, we wouldn't want dependencies in the CppUTest tests either :)

**Comment by arstrube** [comment]
I'll look into it. 

In this case we would probably want Travis to compile and link the tests without std c lib as well, to pick up that sort of thing. Is there any reason why they wouldn't link? They definitely can't be run, though.

**Comment by basvodde** [comment]
Linking will fail :)

**Comment by arstrube** [comment]
How so? Aren't we stubbing all platformspedific calls, and aren't all stubs dummies?

**Comment by arstrube** [comment]
Not that it matters, but I thought it might be easier to add compiling and linking the tests then it would be to just add compiling them

**Comment by basvodde** [comment]
True. Then yes :)

**Comment by arstrube** [comment]
Okay, it won't (and it definitely won't after I tried to fix the dependencies...

Properly fixing them though would necessitate platform specific solutions for the following, namely:

```c++
#define EINTR 4
PlatformSpecificErrno()
#define SIGSTOP 19  // some systems use 17
typedef size_t pid_t;
PlatformSpecificGetpid(void);
PlatformSpecificKill()
```
(I hacked these for the experiment, but its very not portable)

**Comment by arstrube** [comment]
One of the reasons it doesn't link is it also hasn't been updated to use the new function pointer interfaces :-(

**Comment by arstrube** [comment]
MemoryOverloadTests & co also use malloc / free / new / delete directly, it seems

**Comment by arstrube** [comment]
You were right. But the tests should compile, actually.

**Comment by arstrube** [comment]
I did a "quickfix" for the <errno.h> & Co. problem. I suggest to leave things as is. It's not used and it won't hurt anyone.

IF I were to submit the fix, I would also have to change the Travis build so tests get compiled and not linked without std c (for otherwise I wouldn't know that it works outside of MacOs and Cygwin).

I am not keen on doing this, especially, since at least one signal is defined differently between Linux and BSD so the quick fix is sure not to work properly :-(
