### ISSUE TITLE
Question: How to properly fail a test from postTestAction()

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#699]
I want to write a test plugin that fails any test, if a floating point exception flag is set. This seems easy enough - but I found there is no good example for how to do this.

* SetPointerPlugin -- here, the macro UT_PTR_SET() really just calls a C function, so when FAIL() is called, the failure actually occurs in the test case. This approach is not suitable for me.

* MockSupportPlugin -- this is just way too complicated; I can't see the relevant parts in here easily.

* Simply calling CHECK() -- seems to do everything I need here, however, it will cause a failure outside a test case, which is not the intended result.

**Comment by arstrube** [comment]
* MemoryReporterPlugin also didn't prove useful. There is no plugin that simply fails tests in the postTestAction if a certain condition isn't met.

**Comment by arstrube** [comment]
Hm. Looks like I have to answer my own question =/.

So, the issue here is that we can't "fail" the test, because at this point, it is already finished. I gleaned from the MockPlugin code that instead, we can use a simple flag to keep track of whether we are already failed.

So I came up with the following macro:
```c++
#define IEE754_CHECK_FALSE(condition) { \
    if(!hasFailed_) { \
        result_->countCheck(); \
        if(condition) { \
            CheckFailure failure(test_, __FILE__, __LINE__, "CHECK_FALSE", #condition); \
            result_->addFailure(failure); \
            hasFailed_ = true; \
        } \
    } \
```
This is used repeatedly to check for all possible floating point exception flags:
```c++
void IEEE754ExceptionFlagsPlugin::postTestAction(UtestShell&, TestResult&)
{
    IEE754_CHECK_FALSE(std::fetestexcept(FE_DIVBYZERO));
    IEE754_CHECK_FALSE(std::fetestexcept(FE_OVERFLOW));
    IEE754_CHECK_FALSE(std::fetestexcept(FE_UNDERFLOW));
    IEE754_CHECK_FALSE(std::fetestexcept(FE_INVALID));
    IEE754_CHECK_FALSE(std::fetestexcept(FE_INEXACT));
}

```

**Comment by arstrube** [comment]
@basvodde this may look like pull request material at the first glance, and it certainly is going to be useful for anybody working with floating point math.

But, because these exception flags are only available in C++11 (and partially, C99) and the plugin also require a special flag `-frounding-math` (for `FE_INEXACT`), the easiest way to use it is to compile it into a library of its own and link it with CppUTest when needed, rather than to include it with CppUTest itself.

**Comment by arstrube** [comment]
Another issue is that not everybody may want inexact results (like 2/3) to be flagged. I'm not sure how to handle this, as the `-frounding-math` compiler option doesn't seem to have a corresponding predefined value. Then again, it doesn't really matter because, when it isn't set, the flag will just never be set, so it won't do any harm.

**Comment by basvodde** [comment]
I'm a bit lost in the monologue :) But you can add a failure in postAction. The MemoryLeak Plugin and the MockPlugin do that...

**Comment by arstrube** [comment]
Hehe. Yeah, I managed to solve the original question. 

Maybe you could comment on the pull request angle? The general idea is that this plugin will check for floating point exception flags after each and every test case, so for code involving a lot of floating point math, these kinds of errors can be caught before hitting silicon (where they would likely cause a reset).

**Comment by basvodde** [comment]
Ok. Wouldn't it be a very specific plugin that shouldn't be in the CppUtest codebase, or is it generic enough?

**Comment by arstrube** [comment]
Good question.
1. Yes, it is quite generic
2. Obviously, it is of interest only to those doing floating point math
3. It does require C++11. So for that reason, it probably can't be in the code base

**Comment by basvodde** [comment]
Yup, #3 isn't an option now. It could be in the Ext but definitively not in the core.

**Comment by arstrube** [comment]
Note: It doesn't require everything to be C++11. The code to be tested can be vanilla C. And the rest of CppUTest doesn't need to be compiled with C++11.

That's why for the project I'm writing this for, it will be a separate library that gets linked with every test and installed via main().

**Comment by arstrube** [comment]
> Yup, #3 isn't an option now. It could be in the Ext but definitively not in the core.

It would live in the Ext, if anywhere.

**Comment by arstrube** [comment]
We could have a _IEEE754ExceptionPlugin_ folder, separate from everything else. Later, when another plugin is added, we could name the folder to _IEEE754ExceptionPluginAndYouNameItPlugin_. Then still later, when we have a third plugin, we rename it to _UserPlugins_ or some such thing... hehe.

It has a simple Makefile; it could quite probably live on its own.

**Comment by basvodde** [comment]
Ok, but I think the Ext is made for that. I want to pull out the mocking stuff in the future to a CppUMock library.

**Comment by arstrube** [comment]
Ah, I see. That would make a lot of sense, having CppUMock in its own library.

**Comment by arstrube** [comment]
I'll submit a PR just for you to take a look. I think there is no hurry to merge. 

First, we still need to wrap up the Copier stuff (Cmake, VS...)

**Comment by basvodde** [comment]
Ok

**Comment by arstrube** [comment]
I have answered my own question =). See #700 for follow-up.
