### ISSUE TITLE
Failed float/double cast prevents build on GCC 5.1

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#709]
The current snapshot (b8f5ce0) fails to build by a conversion to float from double (`Werror=float-conversion)`.

 The cause is the function `int IsInfImplementation(double)` (`src/Platforms/Gcc/UtestPlatform.cpp:242:12`):

```cpp
static int IsInfImplementation(double d)
{
    return isinf(d); // Casting to d to float solves the issue
}
```
However, i'm not sure if this is cast safe.

--------------

`isinf()` is implemtend like this on GCC 5.1:

```cpp
#  define isinf(x) \
     (sizeof (x) == sizeof (float)					      \
      ? __isinff (x)							      \
      : sizeof (x) == sizeof (double)					      \
      ? __isinf (x) : __isinfl (x))
```

**Comment by arstrube** [comment]
That is strange, for two reasons:

1. It's gcc, which means it already passed the build in various forms and contortions, including Clang (okay, I don't know the exact version of gcc on Travis CI -- I am using 4.8.3).
2. As you have pointed out, isinf() is implemented as a macro, designed to handle both float and double. No cast should actually occur.

That aside, the cast would be a very bad idea, as infinity is probably defined as the largest value that can be represented, which would be very different between float and double indeed.

**Comment by arstrube** [comment]
I suggest you compile with -E to see whether the `isinf()` macro implementation you outlined above is indeed the one that `isinf()` resolves to (somehow I doubt it).

If the compiler lets you do:
```c++
int (*PlatformSpecificIsInf)(double) = isinf;
```
then it is a function implementation, not the one above.

**Comment by arstrube** [comment]
P.S. If you don't need this functionality, as a quick and safe workaround you can always define a dummy that just returns 0 (false) always.

**Comment by offa** [comment]
> That is strange, for two reasons:

For **three** reasons: It was compiling with version from yesterday (or possibly the day before yesterday ...). To be safe i'll check on another system.

Btw. if that matters, i have compiled with C++11 enabled (`C++11=ON`).

> It's gcc, which means it already passed the build in various forms and contortions, including Clang 

Yes, that's strange; btw. CI has *gcc 4.6.3*.

**Comment by offa** [comment]
Tested on another system:

**GCC 5.1.0** fails just as
**Clang 3.6.2** fails also (but with another cause!?)

Both times C++11 enabled.

**Comment by offa** [comment]
According to `git bisect` the cause is 201816ce4b0123e9e178c1a4a0a9496bcd245674.

**Comment by arstrube** [comment]
Yes, basically it started when we added the PlatformSpecificIsInf() functionality. It wasn't there before.

**Comment by arstrube** [comment]
In other words, the problem didn't show because there wasn't a call to isinf() before.

**Comment by offa** [comment]
I've opened an issue for the clang build failure( #710).

**Comment by arstrube** [comment]
With Cygwin gcc 4.8.3, I can activate C++11 and it compiles without a hitch.

Did you manage to find out whether the macro is actually used?

**Comment by offa** [comment]
> In other words, the problem didn't show because there wasn't a call to isinf() before.

Indeed.

 But i don't see the real cause since `isinf()` seems to handle both types so there shouldn't be such an issue!?

**Comment by arstrube** [comment]
Try `#include <cmath>` instead of `#include <math.h>`

One shouldn't do that latter anyway; maybe it's finally become obsolete?

**Comment by offa** [comment]
> Did you manage to find out whether the macro is actually used?

Yes, `PlatformSpecificIsInf(double)` - that's the function pointer to the - implementation is used in `Utest.cpp` (line 38).

**Comment by offa** [comment]
> Try #include <cmath> instead of #include <math.h>
>
> One shouldn't do that latter anyway; maybe it's finally become obsolete?

The the C++ header instead works! Great!

I'll test on a 2nd system and open a PR if successful.

**Comment by jgonzalezdr** [comment]
The actual implementation for checking NaN is:

```C++
static int IsNanImplementation(double d)
{
    return isnan((float)d);
}
```

I was wondering why the parameter was cast to a float, now I know why. It must be a matter that with some compilers isnan/isinf are functions that accept a float, and with others they are macros.

If the cast for NaN works, it should work with Inf also.

**Comment by jgonzalezdr** [comment]
With that fix, IsNanImplementation should be also modified to remove the cast then.

**Comment by offa** [comment]
Ok, one moment ...

**Comment by jgonzalezdr** [comment]
BTW, gcc 5.1.0 could be added to travis

**Comment by arstrube** [comment]
@jgonzalezdr Right! The isnan() cast shouldn't have been there, either.

**Comment by offa** [comment]
Hmm, build fails using autotools (gcc and clang).

**Comment by arstrube** [comment]
"File not found" -- that's really weird. Must be a problem with the build system.

**Comment by offa** [comment]
Reran the travis build, same failure.

**Comment by arstrube** [comment]
It's because Autotools does a build with no standard c++ library. In this build, the flag `-nostdinc++` is set. This is kind of at cross purposes with standard practice of using the c++ wrappers for c headers... This is why only the Autotools build fails. And probably the only reason why we never included <cmath> to start with.....

@basvodde what do we do now?

**Comment by arstrube** [comment]
One option would seem to be simply comparing d with 0.0 / 0.0 and 1.0 / 0.0, respectively

**Comment by jgonzalezdr** [comment]
IMHO, just put the cast into the isinf like in the isnan. It's really not problematic, because it's just a check, there is no comparison with other numbers.

**Comment by arstrube** [comment]
So the cast would correctly convert Infinity (double) to Infinity (float), right?

**Comment by jgonzalezdr** [comment]
#713 should solve the issue.

**Comment by arstrube** [comment]
At least on gcc, this seems to work quite well:

```c++
#include <ieeefp.h>
#include <math.h>
//....
int (*PlatformSpecificIsNan)(double) = isnan;
int (*PlatformSpecificIsInf)(double) = isinf;
```
It uses the "old" function definitions, which are still around in <ieeefp.h> for compatibility reasons.

**Comment by arstrube** [comment]
Gets me though, why the macro implementation obviously doesn't work as intended :-(

**Comment by jgonzalezdr** [comment]
From my undestanding, the original implementation was done via a intermediate function because sometimes isinf/isnan are implemented as macros, and sometimes as functions. So I'd bet to leave it as is, and replicate for infinity was was done with NaN, because it has proven to work in the past and no one complained... :-)

**Comment by offa** [comment]
> because it has proven to work in the past and no one complained... :-)

At least there should be a test for this.

Although the cast is something not very nice, removing the flag from autotools isn't an option, isn't it?

**Comment by arstrube** [comment]
@offa yes there is a test. And no, it can't be removed (because we offer the option of compiling entirely without the C++ library)

**Comment by offa** [comment]
Ok, then i guess we wont come around @jgonzalezdr solution and add those casts.

**Comment by offa** [comment]
> #713 should solve the issue.

I can confirm this works on Gcc 5.1. :+1: 
I'll close my PR with reference to this.
