### ISSUE TITLE
Clang failure because of const to non-const cast

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#728]
Building with clang 3.6.2 fails with this error:

```
tests/CppUTestExt/MockSupport_cTestCFile.c:38:20: error: cast from 'const void *' to 'char *' drops const qualifier [-Werror,-Wcast-qual]
    return (char*) object;
                   ^
```
The error is caused by the `MockTypeValueToStringFunction_c` implementation, which requires a return value of `char*`.

```
static char* typeNameValueToString(const void* object)
{
    return (char*) object;
}
```

**Comment by arstrube** [comment]
I could have sworn I fixed this one :P . Probably as part of some other pull that was ultimately rejected...

**Comment by arstrube** [comment]
Needs to be `const char` throughout. There's another, related place, which is currently something like
```c+
return (char*) "something";
```
where the cast can go once it returns `const char*`.

**Comment by offa** [comment]
So it's safe to change 

```
typedef char* (*MockTypeValueToStringFunction_c)(const void* object1);
```
to
```
typedef const char* (*MockTypeValueToStringFunction_c)(const void* object1);
```
?

If so, i'll test again with Gcc / Clang and open a PR.

**Comment by arstrube** [comment]
Yes, it's safe to change. PR on the way...

**Comment by offa** [comment]
Works with clang.
