### ISSUE TITLE
The Being-Compatible-From-16bit-Through-64bit Problem... Again

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#732]
Fixing this thing for 16 bit systems (so that it also works on 32/32/64 windows) leads to problems with 64 bit Linux:
```bash
../tests/TestUTestMacro.cpp:1208: error: Failure in TEST(UnitTestMacros, FailureWithBITS_EQUAL_TEXT)
actual <
Generic:1: error: Failure in TEST(Generic, Generic)
../tests/TestUTestMacro.cpp:1201: error:
Message: Failed because it failed
expected <xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx 00000000>
but was <xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx 11111111>
.
Errors (1 failures, 1 tests, 1 ran, 1 checks, 0 ignored, 0 filtered out, 1 ms)
>
did not contain <expected <xxxxxxxx xxxxxxxx xxxxxxxx 00000000>>
```
This kind of problem keeps cropping up in many forms, whenever numeric values are printed. In this case, the code was changed as follows (to work with 16 bit):
```diff
 static void _failingTestMethodWithBITS_EQUAL_TEXT()
 {
-    BITS_EQUAL_TEXT(0x00, 0xFF, 0xFF, "Failed because it failed");
+    BITS_EQUAL_TEXT(0x00, (unsigned long) 0xFF, 0xFF, "Failed because it failed");
     lineOfCodeExecutedAfterCheck = true; // LCOV_EXCL_LINE
 } // LCOV_EXCL_LINE
```
The cast to long makes it work on 16 bit and on Windows, because `long` is 32 bit on either system. The failure on Linux was to be expected. If I casted it to (unsigned), however, it would be 16 bit on 16 bit systems. The same thing happens when not casting at all.

Since we are not supposed to use the fixed-bit-width definitions like uint32_t in CppUTest, we have a problem. What gives?

**Comment by arstrube** [comment]
How about macros like this (and rather than hiding them away in test cases, maybe define them in UtestMacros.h: 
```c++
#define UINT32(n) ((unsigned long)-1 > (unsigned)-1) ? (n) : (unsigned long) (n)
 ```
Then, we could say:
```diff
static void _failingTestMethodWithBITS_EQUAL_TEXT()
 {
-    BITS_EQUAL_TEXT(0x00, 0xFF, 0xFF, "Failed because it failed");
+    BITS_EQUAL_TEXT(0x00, UINT32(0xFF), 0xFF, "Failed because it failed");
     lineOfCodeExecutedAfterCheck = true; // LCOV_EXCL_LINE
 } // LCOV_EXCL_LINE
```

**Comment by basvodde** [comment]
I don't really understand why the cast is needed? Isn't it a bug in the BITS_EQUAL method itself?

**Comment by arstrube** [comment]
I should close this. Nice idea, but doesn't work. Things are not as easy as that. :-(

**Comment by jgonzalezdr** [comment]
@arstrube I was just thinking that if you've got to struggle too much to fix code such that it's compatible with all platforms word sizes, you could just add a configuration option like "PLATFORM_16BITS" that would go into config.h, so the user can select with autoconf/cmake the right platform. Maybe it is even possible to detect the compiler during autoconf/cmake configuration and set this options automatically. Just my 2 cents.

**Comment by arstrube** [comment]
@jgonzalezdr That would ease a _lot_ of trouble. Spanning 16..64 bit is really tough (reconciling 32/32/64 with 32/64/64 can be troublesome as it were).

@basvodde How would we go about this?

**Comment by basvodde** [comment]
I'm still unclear what the problem is :)

**Comment by arstrube** [comment]
The problem is that
1. We mustn't use fixed width integers such as uint8_t etc. from <stdint.h>
2. Integer sizes are pretty much not-reconcilable between 16bit and 32 bit platforms
3. We have to imploy weird fixes in many places to make it work.

If we followed @jgonzalezdr suggestion, we'd just have a PLATFORM_16BITS macro and in all those troublesome places, conditionally compile with the appropriate casts _just for 16 bit platforms_.

We would have one consistent way to deal with the problem. Because, especially when printing, you have to know what size "int" you are getting.

**Comment by arstrube** [comment]
If we allowed <cstdint> in UtestPlatform.cpp, we could probably make `PlatformSpecificVsnprintf()` more like a wrapper, that does the appropriate checks and castings. Just an idea; not sure that it would be realistic. Probably not so much, because it does not control the format strings.

**Comment by basvodde** [comment]
It is fixed now, right?
