### ISSUE TITLE
Unable to compile test under OSX

### ISSUE THREAD

**Issue by dlindelof** [cpputest/cpputest#742]
I'm unable to compile a test file under OSX. I've narrowed the problem down to this minimal file named `sstream.cpp`:

    #include "CppUTest/TestHarness.h"
    #include <sstream>

When I run `cc -c -o sstream.o sstream.cpp` the compiler yields many errors beginning with:

    In file included from sstream.cpp:2:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/sstream:174:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:131:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:18:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/mutex:177:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1203:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_03:340:12: error: unknown type name '__hold'
        ::new (__hold.get()) __func(__f_.first(), _Alloc(__a));
               ^

I'm using CppUTest version 3.6 managed by brew, compiling with clang 6.1.0.

**Comment by basvodde** [comment]
Can you switch the include sstream and TestHarness ?

**Comment by dlindelof** [comment]
Switching the `#include` directives removes the error message.

**Comment by basvodde** [comment]
Ok :)

It is because the sstream overloads operator new and the CppUTest file will #define it. It is a known problem without a good solution other than paying attention to your include order.

**Comment by dlindelof** [comment]
Duh. We even had a comment right there saying that these includes should
come last. Thanks for your help anyway ;-)


On Sat, Aug 1, 2015 at 1:44 PM Bas Vodde <notifications@github.com> wrote:

> Ok :)
>
> It is because the sstream overloads operator new and the CppUTest file
> will #define it. It is a known problem without a good solution other than
> paying attention to your include order.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cpputest/cpputest/issues/742#issuecomment-126905060>.
>
-- 
-------------------------------
David Lindelöf, PhD
Chief Technology Officer
M +41 (0)79 415 66 41
T +41 (0)22 552 11 62
F +41 (0)22 552 11 60
david.lindelof@neurobat.net
http://neurobat.net
http://computersandbuildings.com
-------------------------------
