### ISSUE TITLE
TEST_ORDERED in MockSupportTest

### ISSUE THREAD

**Issue by basvodde** [cpputest/cpputest#756]
@arstrube Do you have any idea why? It doesn't seem needed, right?

**Comment by arstrube** [comment]
Look at the test case name of the second test case ;-). It is to check whether the test case after the one we want to crash doesn't crash. So it has to run after the one that is supposed to be crashed.

**Comment by basvodde** [comment]
So, the second one then doesn't do anything as when it crashed it crashed, right? I'd like to find a way to remove the dependency with TEST_ORDERED :)

**Comment by arstrube** [comment]
Not quite so, as the tests don't actually crash. But you are right that, outside of a test, the test case after a crash would not very likely run :)

**Comment by basvodde** [comment]
Thanks!
