### ISSUE TITLE
Break up MockSupportTest.cpp in smaller files

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#769]
I know, it's all but done. But I was surprised that there doesn't seem to be a (possibly ancient) issue for this one?

**Comment by arstrube** [comment]
TODO:

+ Add quite a few missing new test sources to CMakeLists.txt
+ Add missing new test sources to Makefile.am
+ Update Visual Studio project files accordingly
+ Update other project files (such as C2000, Dos)
+ Make sure the total number of tests adds up (how?)

For the last point it would be important that every test that is \#ifdef'ed away for any particular platform / configuration, there is an IGNORE_TEST() counterpart.

**Comment by arstrube** [comment]
This is of highest importance, because new tests sources which we overlooked will simply never be run!

**Comment by arstrube** [comment]
Forget about it. If it was Monday morning, I'd blame it on that....

**Comment by basvodde** [comment]
The VS and other project files need to be updated. But it isn't done yet. I'm still waiting for your input on the stupid ORDERED_TEST that I want to remove. Especially when we pull out CppUMock, we don't want it to depend on Ext.

**Comment by arstrube** [comment]
Okay, okay I'll check it out a.s.a.p

**Comment by arstrube** [comment]
Right. As the name of the test implies, it tests whether the next test after a "crashed" test does not crash (because it shouldn't, because of `resetCrashMethod()` ). I guess there is no danger of this happening after an actual crash ;-). However, we would still want to test the correct function of  `resetCrashMethod()`.

So I think one alternative would be to provide such as test, set the dummy crassh method, call  `resetCrashMethod()` and then check that no crash occurs. Correct?

**Comment by arstrube** [comment]
I think we completed the process of breaking up the tests into smaller units.

Have all project files been updated (VS, Cmake, Autotools, old-school Makefile, not to mention various targets by other contributors)? 

Can we close this, or do we still need to take action?

**Comment by basvodde** [comment]
Uh, I forgot. I guess it was done ?

**Comment by arstrube** [comment]
CMake looks ok. The Dos build does (naturally) does, too. I'll take a look at the the VS projects and Autotools and C2000 if I find time. As for other platforms, I would be hesitant to attempt to make changes blindly.

**Comment by Andne** [comment]
I've got the VS2010 project file done, just checking the 2005/2008 file yet.  Should be able to submit the pull request later this morning.

**Comment by Andne** [comment]
VS201x and VS2005/2008 are updated in PR #814.  I can't update the VS6 project file, only have the tools to run builds, not the IDE to edit them.  Looks like it's been broken for a while though too.

**Comment by arstrube** [comment]
I will take care of VS6.

**Comment by arstrube** [comment]
I think this has finally been done.

I made a new issue for specialty platforms in case someone wants to fix those.
