### ISSUE TITLE
Error when trying to build using Visual Studio 2015 (community)

### ISSUE THREAD

**Issue by Adnn** [cpputest/cpputest#780]
Hi,

  I tried to build CppUTest for my Windows 10 environment. I followed the listed steps:
- Download and extract the release V3.7.2 (from github)
- Generate an out-of-source build tree with cmake (only changing the CMAKE_INSTALL_PREFIX to install not-system-wide).

This is giving me the CppUTest.sln solution in my out of source build folder. Opening it and trying to build ALL_BUILD target gives the following issue:

```
2>------ Build started: Project: CppUTestExtTests, Configuration: Release Win32 ------
3>------ Build started: Project: CppUTestTests, Configuration: Release Win32 ------
3>LINK : fatal error LNK1181: cannot open input file '..\src\CppUTest\Release\CppUTest.lib'
2>LINK : fatal error LNK1181: cannot open input file '..\..\src\CppUTest\Release\CppUTest.lib'
```

Did I miss a configuration step ?

**Comment by Adnn** [comment]
Hi,

  Sorry, my first message was not really pointing in the right direction for the error: the library does not compile properly because the CMake generation step does not define the symbol **STDC_WANT_SECURE_LIB**
Forcing its defintion in CMake gui solves this problem. Perhaps it should be defined by default when the generator is VC ?

Thank you for reading,

**Comment by basvodde** [comment]
This should be resolved by now. Closing it.
