### ISSUE TITLE
compilation fails on Mac OSX

### ISSUE THREAD

**Issue by jcw** [cpputest/cpputest#782]
After updating the Xcode tools to 7.0, I get warnings which then fail due to `-Werror`. Things like:

    CppUTestConfig.h:180:9: warning: macro name is a reserved
      identifier [-Wreserved-id-macro]
    MemoryLeakDetectorNewMacros.h:48:9: warning: keyword is
      hidden by macro definition [-Wkeyword-macro]

The gcc version is:

    $ gcc -v
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 7.0.0 (clang-700.0.72)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix

A workaround is to add the following line to `build/MakefileWorker.mk` for clang:

    CPPUTEST_CXX_WARNINGFLAGS += -Wno-reserved-id-macro -Wno-keyword-macro

**Comment by basvodde** [comment]
Thanks! Also will need to be added to the automake and cmake files.

**Comment by charlesnicholson** [comment]
I hit this too, pull request open here https://github.com/cpputest/cpputest/pull/787

**Comment by basvodde** [comment]
And merged, so closed.
