### ISSUE TITLE
Memory leak with std::ofstream compiled with MSVC

### ISSUE THREAD

**Issue by azias** [cpputest/cpputest#786]
Hello,

We are migrating the compilation process of our Windows product from GCC (MinGW) to Visual Studio 2015 and  I experience some memory leak errors that I a do not have when I compile using GCC.

Here is a minimal example that reproduce the problem using a std::ofstream

```
#include "CppUTest/TestHarness.h"
#include "CppUTest/CommandLineTestRunner.h"
#include "CppUTest/UtestMacros.h"

#include <fstream>

TEST_GROUP(group_test)
{

};

TEST(group_test, test) {
	std::ofstream fout("afile.txt");
	fout << "write someting" << std::endl;
	fout.close();
}

int main(int ac, char** av)
{
	return RUN_ALL_TESTS(ac, av);
}
```

The output is

```
ConsoleApplication1.cpp(16): error: Failure in TEST(group_test, test)
        Memory leak(s) found.
Alloc num (10) Leak size: 8 Allocated at: <unknown> and line: 0. Type: "new"
        Memory: <00F2C590> Content:
    0000: 00 c6 f2 00 58 c5 f2 00                          |....X...|
Alloc num (9) Leak size: 8 Allocated at: <unknown> and line: 0. Type: "new"
        Memory: <00F2C558> Content:
    0000: f0 4f 13 01 01 00 00 00                          |.O......|
Alloc num (7) Leak size: 8 Allocated at: <unknown> and line: 0. Type: "new"
        Memory: <00F2C600> Content:
    0000: 00 00 00 00 e8 0f f3 00                          |........|
Alloc num (5) Leak size: 32 Allocated at: <unknown> and line: 0. Type: "new"
        Memory: <00F30F98> Content:
    0000: d0 43 13 01 02 00 00 00  00 00 00 00 00 00 00 00 |.C..............|
    0010: 3f 00 00 00 00 6e 74 65  a0 52 f2 00 00 53 20 43 |?....nte.R...S C|
Alloc num (6) Leak size: 24 Allocated at: <unknown> and line: 0. Type: "new"
        Memory: <00F30FE8> Content:
    0000: c0 4f 13 01 01 00 00 00  00 00 00 00 b0 11 f3 00 |.O..............|
    0010: 01 00 00 00 00 00 00 00                          |........|
Total number of leaks:  5
```

Thank you

**Comment by olreak** [comment]
Notice that i have the same behaviour using std::stringstream

Here is a minimal example:

```
#include "CppUTest/TestHarness.h"
#include "CppUTest/CommandLineTestRunner.h"
#include "CppUTest/UtestMacros.h"

#include <sstream>

TEST_GROUP(group_test)
{

};

TEST(group_test, test) {
	std::stringstream stream;
	stream << "message ";
}

int main(int ac, char** av)
{
	return RUN_ALL_TESTS(ac, av);
}
```

and its ouput

```
ConsoleApplication1.cpp(12): error: Failure in TEST(group_test, test)
        Memory leak(s) found.
Alloc num (7) Leak size: 8 Allocated at: <unknown> and line: 0. Type: "new"
        Memory: <00ECE4E0> Content:
    0000: 00 00 00 00 98 af ec 00                          |........|
Alloc num (6) Leak size: 24 Allocated at: <unknown> and line: 0. Type: "new"
        Memory: <00ECAF98> Content:
    0000: 18 2f df 00 01 00 00 00  00 00 00 00 68 f0 ec 00 |./..........h...|
    0010: 01 00 00 00 00 00 00 00                          |........|
Alloc num (5) Leak size: 32 Allocated at: <unknown> and line: 0. Type: "new"
        Memory: <00EC6F30> Content:
    0000: d0 23 df 00 02 00 00 00  00 00 00 00 00 00 00 00 |.#..............|
    0010: 3f 00 00 00 00 f7 af 00  30 fa ec 00 00 34 ec 00 |?.......0....4..|
Total number of leaks:  3
```

**Comment by olreak** [comment]
I did not have mentionned it: I use cpputest v3.7.1

**Comment by basvodde** [comment]
You ought to solve these by putting the same in the main method, or doing something there. What happens usually is that there is a cache in the stream library, thus CppUTest complains about the cache. You'll need to make your test program allocate the cache before the test, then it works fine.

**Comment by azias** [comment]
Thank you for your answer.

I now understand why a memory leak is detected. However I do not understand how to do the correction you suggest:  "make your test program allocate the cache before the test". How can I allocate the cache, I have googled bu found nothing about that.

Thank you.

**Comment by arstrube** [comment]
Something along the lines of:
```c++
int main(int ac, char** av)
{
    std::stringstream dummy;
    dummy << "";
    return RUN_ALL_TESTS(ac, av);
}
```

**Comment by azias** [comment]
Thank you for your answers.

I have finally made the choice to add some lines in my tests to disable memory leak detection on lines where I know this is this problem.

I add the following lines:
```
#ifdef _MSC_VER
	MemoryLeakWarningPlugin::turnOffNewDeleteOverloads();
#endif
	// call to my library function under test here
	// that I know it create a "fake" memory leak
	// (OS functionality or bug in MSVC standard library ?)
#ifdef _MSC_VER
	MemoryLeakWarningPlugin::turnOnNewDeleteOverloads();
#endif
```

I do the test #ifdef _MSC_VER such that memory leak is not  disable when I compile with  gcc that seems to not have problem of cache on stream (for the moment, we continue to compile both on a Jenkins server)

**Comment by basvodde** [comment]
The turning off the memory leak detector won't work, you'll still have the leak if you run a single test or a test group

**Comment by azias** [comment]
Finally my solution does not work completely as expected: when there is an allocation inside the block where I disable memory leak detection, and then the deallocation is done outside, I have an error *Deallocating non-allocated memory*

I did not found usable solution, I think I must disable any memory leak detection.

**Comment by arstrube** [comment]
@azias Did you try my suggestion above?

**Comment by azias** [comment]
I am not sure to understand your suggestion, you seem to suggest to copy the code in the main method of the test executable but i cannot do that, i need to test functions of my libraries by calling them.

**Comment by azias** [comment]
If you suggested just to add the 2 lines in my existing test code, I did not see any difference,  i did not try on the minimal example but directly on a test executable that fails with memory leak reading files (using OpenCV, test that do not fail when compiled with gcc)

**Comment by arstrube** [comment]
Just add those two lines in your main(). Literally.

That's all. Nothing to do with what or where you are testing. :)

Then just write your test normally with memory leak checking enabled the way you did originally when the problem first occured; don't try to do anything fancy.

Don't try to understand what it does; just do it anyway ;-).

**Comment by azias** [comment]
With this two version, no more memory leaks detected.

```C++
#include "CppUTest/TestHarness.h"
#include "CppUTest/CommandLineTestRunner.h"
#include "CppUTest/UtestMacros.h"

#include <sstream>

TEST_GROUP(group_test)
{

};

TEST(group_test, test) {
	std::stringstream stream;
	stream << "message ";
}

int main(int ac, char** av)
{
	std::stringstream dummy;
	dummy << "";
	return RUN_ALL_TESTS(ac, av);
}
```

```C++
#include "CppUTest/TestHarness.h"
#include "CppUTest/CommandLineTestRunner.h"
#include "CppUTest/UtestMacros.h"

#include <fstream>

TEST_GROUP(group_test)
{

};

TEST(group_test, test) {
    std::ofstream fout("afile.txt");
    fout << "write something" << std::endl;
    fout.close();
}

int main(int ac, char** av)
{
	std::ofstream fout("anotherfile.txt");
	fout << "write someting" << std::endl;
	fout.close();
	return RUN_ALL_TESTS(ac, av);
}
```

I will try with this on my real tests, do you have a beginning of explanation ?

**Comment by arstrube** [comment]
Hi there,

Glad to hear ;-).

The beginning of an explanation is actually in @basvodde's post above:

>You ought to solve these by putting the same in the main method, or doing something there. What happens usually is that there is a cache in the stream library, thus CppUTest complains about the cache. You'll need to make your test program allocate the cache before the test, then it works fine.

When you first use the stream library, a cache is allocated internally. It is never deallocated until the program exits. If the first call is within the scope of a test, you have a problem.

By using it in main() for the first time, you stay out of trouble with checking memory leaks. I feel a bit stupid repeating this, because I couldn't say it any better than Bas already did......

**Comment by azias** [comment]
Ok, I have tried with some of my real test and its works.

For some tests (that use external libraries to read/write some files), I did not found the minimum code to add in order to avoid the memory leak, but I have copied the problematic bloc of test in the main() function and it works.

Not very simple to use but it works, thanks a lot, I close the issue
