### ISSUE TITLE
Travis CI stuck?

### ISSUE THREAD

**Issue by Andne** [cpputest/cpputest#809]
I noticed that my last pull request was still pending for Travis CI so I went to see what it was doing.  It looks like a build from a couple weeks ago never finished all of the configurations and is holding up any other builds from completing.  Some of the configurations have completed, but the next configuration isn't starting for some reason.

From what I can tell, builds 2099 and 2100 are both waiting to start a gcc/cmake build with coverage, but for some reason that build isn't starting.  2099 seems to be trying to build a commit that doesn't exist, so maybe 2100 is just waiting for that particular configuration to complete before it starts it's build with that configuration?  Maybe someone just needs to cancel the hung build and everything will catch back up to itself again.

**Comment by basvodde** [comment]
Cancelled. Let me know if it is ok now?

**Comment by Andne** [comment]
The next build started, but looks like it's blocked again.  I think you need to cancel build 2099.

**Comment by Andne** [comment]
That got another build to try and run, but it still isn't running the last 3 configurations.  Maybe it's related to the conflicts between the excludes and includes in `.travis.yml`?  Kind of seems like it doesn't like being told to exclude a group of builds and then include a specific instance from that group later on.  Maybe this is a bug in travis-ci?

**Comment by Andne** [comment]
I set up travis-ci on my fork and ran a branch that's changed to be excludes only without any includes and all of the builds appear to run now.  Looks like mixing includes and excludes causes trouble.  Odd, because it doesn't appear to me at a quick glance that the travis.yml file was changed recently, so why did some older builds run successfully with that configuration?

If you want, I'll submit my change as a pull request, but it seems like this should be fixed on the travis-ci side instead.

**Comment by arstrube** [comment]
I submitted this issue https://github.com/travis-ci/travis-ci/issues/5409.

I think it might be related to the change in infrastructure, but was unsuccessful so far in getting to run the CppUTest build on the old infrastructure ("Blue Box"), so I can't be sure. Travis CI documentation (https://gist.github.com/meatballhat/d0c8aab9e3bd8a8bcacd#file-01-matrix-include-travis-yml-L3-L6) is unclear on how to force the old infrastructure.

**Comment by arstrube** [comment]
@Andne - did you manage to get the same run by using includes only? If so, we should use your setup. The reason we are using both include and exclude is that it seemed the only / easiest way to get the exact combination of builds we want from the matrix.

And yes, the current setup did work for several months, presumably until they changed the underlying infrastructure.

**Comment by arstrube** [comment]
Much of the current setup was arrived at by trial and error. I find the documentation on setting up a (sparse) build matrix highly unsatisfactory. 

Which is strange, because NOT setting up a build matrix with as few entries as possible is directly related to more system load, which is directly related to cost, so I am a bit suprised that the people at Travis CI don't seem to pay attention to this.

**Comment by Andne** [comment]
I did it by modifying the exclude block and removing the include block.  However, it'd probably be easier to read just the include block, so I think I'll set it up that way instead.

**Comment by arstrube** [comment]
That would be great. I must have missed something there, because I never got it to _only_ include those combinations that we need.

**Comment by Andne** [comment]
Well, I got the matrix to only generate those configurations on include that we wanted - had to remove the `compiler`, `env`, `rvm` and `os` sections from earlier in the file.  However, it doesn't work.  The list of builds to run is correct, but for whatever reason, they aren't starting.  Looks like travis-ci may have introduced a bug where anything defined through `matrix.include` can't start running for some reason.

**Comment by arstrube** [comment]
How strange - but probably consistent with the problems we encountered lately....
So, since your "exclude" version seems to work, maybe we just just go with that for now?

**Comment by Andne** [comment]
Oops, includes do work, I just had a build stuck in the queue that I couldn't see.

**Comment by arstrube** [comment]
I've seen some builds working, but right now, Travis CI appears to be "stuck" again...

**Comment by arstrube** [comment]
...well, let's call it extremely sluggish (queued for hours) :-(

**Comment by offa** [comment]
Agreed, my last build took 40 min (11 min of it are actual build time).

**Comment by arstrube** [comment]
There was a related issue with all jobs erroring when for some reason Dosbox could not be installed.

Dosbox shouldn't be installed for any but the `make_dos` job.

**Comment by offa** [comment]
My fork starts normal now.

**Comment by basvodde** [comment]
Issue can be closed, I assume.
