### ISSUE TITLE
is adding expect no call check reasonable?

### ISSUE THREAD

**Issue by cuitoldfish** [cpputest/cpputest#817]
Hi,
I have been used CppUTest in my daily CI for a long time, and the requirements pop out from time to time that I need to check one mock function is not invoked in some case. I would like devote some time to add this functionality, do you guys think it's valuable?

**Comment by arstrube** [comment]
Hi there,

Actually, this check is standard. Perhaps a call to `mock().checkExpectations()` might be missing, if an unexpected call does not cause a failure.

Simply _not_ specifying an expectation is sufficient.

In my own work, I sometimes use:
```
mock().expectNcalls(0, "Somefunction");
```
rather than a comment, to make explicit in my test case that this call is not supposed to occur. This is purely for the benefit of the reader; it is not necessary for an unexpected call to "Somefunction" to fail the test.

**Comment by arstrube** [comment]
Hi there,

Actually, this check is standard. Perhaps a call to `mock().checkExpectations()` might be missing, if an unexpected call does not cause a failure.

Simply _not_ specifying an expectation is sufficient.

In my own work, I sometimes use:
```
mock().expectNcalls(0, "Somefunction");
```
rather than a comment, to make explicit in my test case that this call is not supposed to occur. This is purely for the benefit of the reader; it is not necessary for an unexpected call to "Somefunction" to fail the test.

**Comment by cuitoldfish** [comment]
Hi arstrube,
I think sometimes it's necessary to fail the test if an unexpected call happens.

say, I have a decorator class, and also there is a delegation class inside that decorator.

```.cpp
decorator::functionA(Interface *pInterface)
{
    if (NULL == pInterface)
            return;
    //some decoration here
    .....
    //delegate call to delegation class
    delegator->functionA(pInterface);

    //may be some decoration also here
    .....
}
```
in my decorator class's unit test, I should have one NULL test to ensure that, if one exceptional NULL value is passed as the parameter, then the decorator will not call the delegator's functionA. 

In this case, in the decorator mock class, if I use one *expect no call*,  when someone modify my codes and remove the guard clause for NULL by mistake, the NULL test will fail, this will help me to protect my decorator class always has correct behavior.

if i use expectNcalls with number 0, , NULL test will still pass but functionality of this decorator::functionA is break.

**Comment by arstrube** [comment]
Sure, but my point is that your NULL test _will_ fail, in that case. It should be simple for you to try out, no? E.g. remove the guard clause and see what happens.

**Comment by arstrube** [comment]
You might include the expectation below for the benefit of the reader, but it is not even necessary to make the test fail:
```
mock().expectNcalls(0, "functionA"); // functionA() must not be called
```

**Comment by cuitoldfish** [comment]
I have a CI server which hold many many test cases from different component and different author in one software system, it is easy for me to try that out, but isn't easy for the automatic CI since it just run the test cases and report if pass or not. If one case pass even with problem, may be no one will find it until it bomb.

**Comment by arstrube** [comment]
The only reason that I can possibly imagine (if at all) for an unexpected mock call NOT to fail a test is, if you don't call `mock().checkExpectations()` in teardown().

Now, if that's a concern with your many components and different authors, you might (if you are not already doing so) make use of the Mock Plugin, which will do this call for you and everybody else. There is _no way_ an unexpected call wouldn't fail the test under those circumstances.

You still need to get everybody else to write the NULL test case consistently - no test case, no failure :P. By monitoring condition coverage, it should be easy though to spot offenders.

I'm not entirely sure I am answering your question, but in my world, tests do the same thing on our CI server that they do for me, and they work the same for 30 other colleagues than they do for me, if I couldn't  trust CppUTest for that it would be, well, kind of pointless....

**Comment by arstrube** [comment]
P.S. In the project I work for, we use the same main() for all tests. Nobody has their 'own' main(). In this way, if we decide to use a plugin (such as the Mock Plugin), it is guaranteed that it is used by everyone.

**Comment by ryanplusplus** [comment]
@arstrube Unexpected calls fail immediately and will fail even if a call to `mock().checkExpectations()` is omitted.

@cuitoldfish Can you provide some code that shows that an unexpected call is not treated as a failure? I am not able to reproduce this issue, and it is unclear to me whether you have actually seen this happen or whether you are making guesses about the behavior of CppUTest simply by looking at the API.

**Comment by cuitoldfish** [comment]
Hi,
I mean, if I set 
```.cpp
void teardown()
{
     mock().checkExpectations()
}
```
and
```.cpp
void setup()
{
    mock().ignoreOtherCalls()
}
```
then for following test
```.cpp
mock("delegator").expectNcalls(0, "functionA");
```
will always pass no matter the funcionA in delegator mock is invoked 0 times or more than 0 times.

I do not know if your guys actually had try and met this case, but at least in my case it is.

**Comment by basvodde** [comment]
Why would you put ignoreOtherCalls in the setup?

**Comment by cuitoldfish** [comment]
Actually in my real unit test environment, there are still other unit tests existed, and I use ignoreOtherCalls to ensure that only the mock functions I care about are checked, rather check every mock function. In my example above, I am still checking the functionA while not check others what is specified to be ignored.

So is using both ignoreOtherCalls and expectNCalls with 0 at the same time unreasonable and should be deposed?

**Comment by basvodde** [comment]
Ok.. uhm, well it is rather unusual to have "ignoreOtherCalls" but fail if these happen. It would suggest some serious trouble in your tests.

That said, when you do ExeptNCalls(0, "xx") with ignoreOtherCalls on, I would indeed expect that to fail, and if it doesn't, then it would be good to fix that.

**Comment by cuitoldfish** [comment]
I think "ignoreOtherCalls" should only ignore other mock call check, not to ignore the actual call whose check is specified as "ExeptNCalls(0, "xx"),  so your point of view is, this is a valuable finding and can be enhanced?

**Comment by basvodde** [comment]
Yes

**Comment by cuitoldfish** [comment]
I will  try to do that.

**Comment by arstrube** [comment]
@cuitoldfish Having seen your test code, I would try not to use `ignoreOtherCalls()` in the test case that should fail on the unexpected call to `functionA()`. Then you can be sure to receive a failure.

**Comment by arstrube** [comment]
@basvodde When I saw the `ignoreOtherCalls()` I realized what the trouble is. I guess the semantics of `ExpectNCalls(0, "xx")` has never been defined or documented. As I mentioned above, I used it as a convenience for the reader. 

Currently, I believe the semantics of  `ignoreOtherCalls()` is something like:

"Ignore each and every call beyond explicit expectations, no matter what, including additional calls to existing expectations". That is, if I expect 3 calls, and get 5, the remaining 2 will (and should) be ignored."

Given those semantics the current behavior of `ExpectNCalls(0, "XX")` is indeed correct, and a method like `expectNoCalls("XX")`, with the semantics that even in the presence of `ignoreOtherCalls()` a call to `XX()` would result in failure, is very desirable.

**Comment by arstrube** [comment]
@basvodde I would go with the additional method; changing the behavior of `expectNCalls(0, "XX")` does not seem like a good idea to me. It could be messy and/or break existing test code.

**Comment by basvodde** [comment]
If I would conceptually think about what exceptNCalls(0, "XX") would do, then I would assume that it wouldn't be ignored by ignoreOtherCalls.

I wouldn't recommend ever using it, I think it is bad test writing, but I do think it should behave properly when people do do that.

**Comment by arstrube** [comment]
Not so sure. I would rather be penalized for bad test writing and have `expectNoCalls()` to let me write better tests in the future ;-). 

Besides, if we have `expectNoCalls()`, there is really no reason to do `exceptNCalls(0, "XX")` and we can officially discourage the latter as bad test writing :)

**Comment by arstrube** [comment]
How hard would it be to implement?

**Comment by basvodde** [comment]
No so hard, I guess... but lets see. If it is too much changed, it wouldn't be good.

**Comment by arstrube** [comment]
To me (up to now), using `ignoreOtherCall()` when wanting to assert the absence of a call, would have been bad test writing... 

But actually, conceptionally, it should be possible and I can think of situations where it would be handy to do (actually not the NULL test example, because no other calls are supposed to happen after that at all anyway).

I have also felt the need to _explicitly_ say in a test that I expect a call NOT to happen, short of using one of those hateful comments ;-)

**Comment by basvodde** [comment]
Well, lets see. If we got the 0 case, it should be easy to add NotExpect.

Not sure we want that in the interface though :)

**Comment by arstrube** [comment]
Why not?

**Comment by basvodde** [comment]
Not know yet :) If we wouldn't recommend it, should it be in the interface?

**Comment by arstrube** [comment]
Would you recommend
```c++
/* call to xyz() must not occur here */
```
rather?

**Comment by basvodde** [comment]
No, if its not there, then why put a comment that its not there :)

**Comment by basvodde** [comment]
/* The next line won't say: a = b + c; */

**Comment by arstrube** [comment]
The whole point of the test case is, that the call should not occur.

**Comment by arstrube** [comment]
The whole 0 case idea was mine, that we use in our project to document that fact. But I thought that is bad test writing :-(

**Comment by arstrube** [comment]
> /* The next line won't say: a = b + c; */
That's not a fair comparison; as far as the test is concerned, a mock() call happens (or doesn't happen) asynchronously.

**Comment by arstrube** [comment]
That's why I want to say "I expect it not to happen".

**Comment by basvodde** [comment]
Sure, but *any* other call is not expected to happen, so calling out one doesn't feel right to me :) But lets see after the implementation, we can decide to add it anyway.

**Comment by cuitoldfish** [comment]
agree with arstrube, add a new method "expectNoCall". I have implemented simple codes to change correct behavior of "expectNCalls(0, "")", but that must result in changed semantic of "ignoreOtherCall", which might easily break existed codes.

So leaving what's has already existed, and extend one new method seems best solution.

**Comment by Andne** [comment]
I agree, this should add a new function.

If someone is using a helper function with a parameter for call count, they may be calling `expectNCalls(count, "func")` where `count = 0`.  In that case, if `ignoreOtherCalls()` is set, then they may not be looking for no calls, they are instead just not looking for any calls.  It's a pretty specific corner case I know, but it's still something that I think is probably valid currently that would break if we treat 0 differently.  I generally assume that `expectNCalls()` is equivalent to calling `expectOneCall` N times, just less work/code because the function handles calling it the right number of times for me.

**Comment by cuitoldfish** [comment]
have a try in the **pull request**, let's review and see if it can be the resolver candidate

**Comment by cuitoldfish** [comment]
@basvodde and @arstrube ,what's your comments and proposal for my pull request?
