### ISSUE TITLE
strictOrder() not honored when using Mock Name (aka namespace, scope)

### ISSUE THREAD

**Issue by matthewpiatt** [cpputest/cpputest#829]
Hey Bas / James / others:

In the midst of authoring some tests, I came across an unexpected situation. It seems as though strictOrder() is not honored when a mock name is supplied. (And yes, I am installing the MockPlugin in my main).

Is this expected behavior?

If this is a bug, I'd even be willing to help fix this, if that is of interest. Is there something you can point me to as a place to start?

I'll let my tests do the talking from here:

```
TEST_GROUP(FooTests)
{
};

TEST(FooTests, StrictOrderViolatedWhenNotUsingMockName)
{
	mock().strictOrder();

	mock().expectOneCall("A");
	mock().expectOneCall("B");

	mock().actualCall("B");
	mock().actualCall("A");

	// THIS FAILS AS EXPECTED
}

TEST(FooTests, StrictOrderViolatedWhenUsingMockName)
{
	mock("foo").strictOrder();

	mock("foo").expectOneCall("A");
	mock("foo").expectOneCall("B");

	mock("foo").actualCall("B");
	mock("foo").actualCall("A");

	// THIS DOES NOT FAIL AS EXPECTED
}
```

**Comment by matthewpiatt** [comment]
Update:

Just to clarify, I don't leave failing tests laying around or anything -- I just always start my TDD cycle with a failure :)

So I actually just tried the following (see below), and things now work. Perhaps the issue is with the mock plugin not checking certain expectations for things that use mock names?

I poked around in tests/CppUTestExt/MockSupportTest.cpp and actually saw that CppUTest covers itself for similar behavior. Not sure what I am missing. The [MockPlugin section of the docs] (https://cpputest.github.io/mocking_manual.html#mock_scope) state that using the MockPlugin calls "checkExpectations at the end of every test (on global scope, which goes recursive over all scopes)".

```
TEST_GROUP(FooTests)
{
};

TEST(FooTests, StrictOrderViolatedWhenNotUsingMockName)
{
	mock().strictOrder();

	mock().expectOneCall("A");
	mock().expectOneCall("B");

	mock().actualCall("B");
	mock().actualCall("A");
}

TEST(FooTests, StrictOrderViolatedWhenUsingMockName)
{
	mock("foo").strictOrder();

	mock("foo").expectOneCall("A");
	mock("foo").expectOneCall("B");

	mock("foo").actualCall("B");
	mock("foo").actualCall("A");

	mock("foo").checkExpectations();	// <-- added this line, test now fails as expected
}
```

**Comment by basvodde** [comment]
I think the strictOrder only works on the same namespace. It is the same with other calls...

**Comment by cuitoldfish** [comment]
yes, but the guide statement `After installing the plugin, you don’t have to worry too much anymore about calling checkExpectations or cleaning your MockSupport.` still might lead the confusion, may be adding some additional remarks is good.

**Comment by arstrube** [comment]
@basvodde I suspect this might be a bug in the Plugin; does it really call checkExpectations on all namespaces? Or just on the gloabl namespace?

**Comment by matthewpiatt** [comment]
For now, my workaround is to simply place mock("foo").checkExpectations(); after each test that i care about strict ordering for a certain namespace.

**Comment by cuitoldfish** [comment]
@arstrube , the code inside MockSupportPlugin::postTestAction() has said the check expectations only for the global namespace, no?
```.cpp
    if (!test.hasFailed())
        mock().checkExpectations();
```
I think you can omit using checkExpections explicit by creating the same namespace mock plugin with your test and install it.

**Comment by basvodde** [comment]
Yeah, you guys are right. This is definitively wrong.

**Comment by arstrube** [comment]
@basvodde - I took a look at the code. In the case of `mock().clear()`, simple recursion is taking place.
 
In the case of `mock().checkExpectations()` though, yes, it is called recursively across namespaces, but it's all somehow tied to and conditional on `lastActualFunctionCall` so it's easy to see that it might not work across namespaces for some reason.

However, I find it hard to understand this whole lastActualCall business -- I mean, why not simply check expectations across namespaces recursively and be done?

**Comment by arstrube** [comment]
@matthewpiatt I believe this has been fixed and can be closed?

**Comment by matthewpiatt** [comment]
@arstrube yes. I tested my original snippets against a pull of 434496a and things run as expected. thanks for fixing this!
