### ISSUE TITLE
Inconsistency in shipping build instructions?

### ISSUE THREAD

**Issue by gareth8118** [cpputest/cpputest#830]
Hi there,

Just regaining my bearings with CppUTest after a wee while away from using it.

The file `README_InstallCppUTest.txt` says to build CppUTest inside the `cpputest_build` directory; however, the `README.md` file says to build it in the top level directory. 

Is the cpputest_build directory obsolete? I found that when I built in there, building the example failed because it couldn't find the built library (since that's being looked for in `<top_level>/lib`, not `<top_level>/cpputest_build/lib`)

Thanks
Gareth

**Comment by cuitoldfish** [comment]
Hi there,
I just build several times in  `cpputest_build` path for one fix, so that directory is on duty with no doubt.

You can build with the following guide in [here](http://cpputest.github.io/)

>$ cd cpputest_build
$ autoreconf .. -i
$ ../configure
$ make

**Comment by gareth8118** [comment]
I didn't say it didn't build in cpputest_build; I said that if I built the library in there then the example won't build.

**Comment by Andne** [comment]
It seems to depend on how you're building.  The `MakefileWorker.mk` logic and the Visual Studio projects all assume that outputs go into the top-level directory.  Autotools and CMake seem to be more set up to build in `cpputest_build`.

**Comment by gareth8118** [comment]
I guess that could be the case - does this mean that the real issue is that there is no autotools or cmake build process for the example subdirectory?

**Comment by cuitoldfish** [comment]
It seems the hand-written makefile for these examples has not been compliant with the autoconf makefile for CppUTest library and tests, why not just change the line `CPPUTEST_LIB_LINK_DIR = $(CPPUTEST_HOME)/lib
` in `MakefileWorker.mk` to its real location? what's your guys opinion?

**Comment by basvodde** [comment]
I updated the readme to have cpputest_build dir. Though the examples probably don't link unless you install it. I added a new Makefile for using the installed version. Closing this.
