### ISSUE TITLE
Add missing sources and pull out MockFailureReporterForTest.cpp for remaining platforms

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#833]
New sources (split-up mock files; TeamCityTestOutput) probably still need to be added to the following platforms:
- armcc (@bortsov?)
- iar (me)
- Eclipse / Cygwin (me)

I propose to postpone these until someone using those platforms needs / wants them.

**Comment by dangu** [comment]
I think TeamCityTestOutput is now fixed in the IAR platform (#1032)
