### ISSUE TITLE
Calling a mocked member function on a nullptr doesn't fail the test

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#838]
If a `std::unique_ptr<T>` is assigned a `nullptr` and a mocked member function is called, there's no test failure.

This issue has been tested with *GCC 5.3.0* and *GCC 5.2.1* on Linux using the current `master` of CppUTest (C++11 enabled).

# Reproduction

1. Create a `std::unique_ptr<T> p` where `T` is a class with a mocked member function
1. Assign `nullptr` to `p`
1. Call a mocked function on `p`
1. Mock is executed; no `SIGSEV` is raised

# Expected behaviour

Calling a member function on a `nullptr` should fail the test.
 

# Example

*Full code: [nullptr_deref.zip](https://github.com/cpputest/cpputest/files/99302/nullptr_deref.zip)*

- (1) SimpleTest
- (2) Test

### (1) "Plain" C++ code (no test)

This fails with a `SIGSEV`, since `ptr` points to `nullptr`.

```c++
class Example
{
public:
    void func(int value)
    {
        m_value = value;
    }
    // ...
};

int main(int argc, char** argv)
{
    // ...
    std::unique_ptr<Example> ptr = nullptr;
    ptr->func(123); /* <--- SIGSEV here */
    // ...
}
```

## (2) Test case 

Unlike the code above, this test succeeds. Even though a `nullptr` is dereferenced, the mock is called and the expectations are fulfilled. The debugger confirms `ptr` as a `nullptr`.

```c++
class Example
{
public:
    void func(int value)
    {
        mock("Example").actualCall("func").withParameter("value", value);
    }

    // ...
};


TEST_GROUP(MockTest)
{
    void teardown() override
    {
        mock().checkExpectations();
        mock().clear();
    }
};

TEST(MockTest, withNullPtr)
{
    mock("Example").expectOneCall("func").withParameter("value", 17);
    std::unique_ptr<Example> ptr = nullptr;
    CHECK_TRUE(ptr == nullptr);
    ptr->func(17); /* <--- Doesn't fail */
}
```

**Comment by arstrube** [comment]
Mine segfaults as expected - gcc 4.8.3 / Cygwin.

**Comment by arstrube** [comment]
As a matter of interest, assigning nullptr to a unique_ptr does not seem to me like an intended use of unique_ptr?

**Comment by offa** [comment]
It's safe to assign a `nullptr` since `std::unique_ptr` has a special `operator=` to handle that case  ([`operator=(nullptr_t)` marked with (2)](http://en.cppreference.com/w/cpp/memory/unique_ptr/operator%3D))

**Comment by offa** [comment]
> Mine segfaults as expected - gcc 4.8.3 / Cygwin.

So maybe it's a compiler related issue? Unfortunately i have only Gcc 5.x around at the moment ... i'll try to validate using some others. 

Did you compile CppUTest using C++11 Libs?

**Comment by arstrube** [comment]
Actually, not so sure that my observation is of any use at all... it turns out that my example crashes all over the place, even with a valid ptr :-(

**Comment by arstrube** [comment]
And no, I didn't compile CppUTest with c++11 libs. I linked 'normal' CppUTest. That should be okay though?

**Comment by offa** [comment]
> And no, I didn't compile CppUTest with c++11 libs. I linked 'normal' CppUTest. That should be okay though?

Yes, I think so. But I'll check with normal libs too (just in case ...).

**Comment by arstrube** [comment]
On my Mac, I can reproduce what you got. I haven't done the first example yet though.

**Comment by arstrube** [comment]
I think the unexpected behavior is due to the semantics of unique_ptr, rather than a problem with CppUTest. It turns out calling func() on the "nulled" ptr is okay. But accessing m_value is not. Therefore, the call on mock() is okay, because that is an entirely separate object.

I did this:
```c++
#include "CppUTest/CommandLineTestRunner.h"
#include "CppUTest/TestHarness.h"
#include "CppUTestExt/MockSupport.h"
#include <memory>

#if 0
class Example {
public:
    void func(int value) {
        mock("Example").actualCall("func").withParameter("value", value);
    }
};
#else
class Example
{
private:
   // int m_value;
public:
    void func(int )
    {
        // m_value = value;
    }
    // ...
};
#endif
TEST_GROUP(MockTest)
{
    void teardown() _override
    {
        mock().checkExpectations();
        mock().clear();
    }
};

TEST(MockTest, withNullPtr)
{
    mock("Example").expectOneCall("func").withParameter("value", 17);
    std::unique_ptr<Example> ptr = nullptr;
    //std::unique_ptr<Example> ptr(new Example);
    CHECK_TRUE(ptr == 0);
    ptr->func(17); /* <--- Doesn't fail */
}

int main(int argc, char** argv) {
    return RUN_ALL_TESTS(argc, argv);
}
```
and got an ordinary failure, because obviously there was no actualCall().

**Comment by arstrube** [comment]
![screen shot 2016-01-21 at 18 05 14](https://cloud.githubusercontent.com/assets/4686469/12487976/b8a3a880-c069-11e5-9974-694ebab51162.png)

**Comment by offa** [comment]
After reading through the C++11 standard, it's possible undefined behaviour at all? 

§ 20.7.1.2.3 (`operator=(nullptr_t) `) has postcondition `get() == nullptr`, but § 20.7.1.2.4 (`operator->() ` and `operator*()`) requires `get() != nullptr`.

So finally all this is UB?

**Comment by arstrube** [comment]
Hmm. If you really need to crash in your tests, you could put some attribute in your mock class and access it before calling mock().actualCall()... but who need crashes anyway :-p

**Comment by offa** [comment]
I don't want to crash my Test X-D
My test should prevent that; check if the method is called before the object itself is valid.

The whole thing is just about to test drive something like this:

```c++
if( ptr != null ptr )
{
    ptr->callMethod();
}
```
I came over this issue, because my test didn't fail. But there are other solutions to get this (really) right.

So finally, since this is issue comes from UB (maybe?), and i've implemented a clean solution - i think we can close this.
