### ISSUE TITLE
Export missing parts of C++ interface to C

### ISSUE THREAD

**Issue by ykaliuta** [cpputest/cpputest#840]
I've checked MockSupport_c.h and it looks like some part of feature set is not available for C. In particular I'm missing ignoreOtherCalls() and ignoreOtherParameters(), but expectNoCall or expectNCalls would be nice to have too. Would it be possible to make all the features available?

Thanks!

**Comment by arstrube** [comment]
Hi there, I just discovered the same thing when checking test coverage. However, I don't know yet whether I'll be able to add ALL of the interfaces you mention... I am currently working on `withOutputParameterOfType()`. I am not sure how come the `ignore...` interfaces aren't there or whether there was a problem with `expectNCalls()`. I'll look into that while I am busy with it anyway.

**Comment by arstrube** [comment]
I am busy with PR #846. It's taking longer as expected because I'm also adding some niceties such as being able to write
```c++
mock_c()->returnIntValueOrDefault(5)
mock_c()->intReturnValue();
```

**Comment by arstrube** [comment]
@ykaliuta  All should be taken care of now - close this?

@basvodde Shouldn't this Issue have auto-closed when the associated PR was merged?

**Comment by ykaliuta** [comment]
Thanks a lot! Sorry, I'm travelling and have limited internet access.
