### ISSUE TITLE
[Question] What is the point of having Mocksupport::returnValue() interfaces

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#844]
Semantically, this seems rather pointless to me. An actual function call can have a return value; a Mocksupport object does not have a return value.

Looking at the implementation, I see that this value defaults to the empty string, or the return value of the last actual call, if there was any.

Why would I care to know, as a user who writes tests with mocks? Or is this something that is somehow important for the workings of CppU mocking internally?

IF this is useful for something, then names like `returnValueOfLastCall()` or `lastCallHasReturnValue()` would at least convey the proper semantics of these methods. As far as I remember, this is not documented anywhere, either.

@basvodde @jwgrenning could you perhaps shed some light on this?

(I came across this looking at missing interfaces in MockSupport_c).

**Comment by basvodde** [comment]
It allows you to write:

mock()->actionCall()
if (mock()->returnValue()) ...

It makes nice code.

**Comment by arstrube** [comment]
Umm, not really with you. I guess I'd need a proper worked example to understand. I don't see why I would want the above nice code anywhere?

Also, the `...OrDefault()` versions of these methods seem even more out of place. Why would I want tos specify a default, when looking at the return value of the last actual call?

**Comment by arstrube** [comment]
I mean, in the test I care whether expectations are met. I don't care whether some call that happened to be the last call with a return value, had a return value. Or, more sensibly, if any call had a return value. I should know that by looking at my expectations.

If the code were inside the mock itself, again, why would I care? I'd work with the actual call instead.

**Comment by arstrube** [comment]
You need to convince me that it is more than nice, self-serving code :)

**Comment by basvodde** [comment]
Well, it came there because I frequently needed it :P

**Comment by arstrube** [comment]
For example, no test in all of CppUTests close to 400 mocking tests uses this construct, except for the tests that test that the construct works.

**Comment by arstrube** [comment]
Okay, you needing it makes sense, of course. But neither I nor the 25+ people I work with ever seem to have needed it, so something must be different? We did some really fancy mocking stuff, too :p. And we needed output parameters and stuff, oh yes....

**Comment by basvodde** [comment]
Ok, so the construct works when you stub out a method and you want to set a potential return value, or the default.

So, the code would look like:

mock()->actualCall("function")
return mock()->returnValueStringOrDefault("default")

The returnOrDefault were created because the construct happened so often. It allows you to set the return value only when it matters.

**Comment by arstrube** [comment]
Oh, now I get it..... you use it inside the actual call. Yes, I remember that now :D. I even plead guilty to having used it. My bad...
