### ISSUE TITLE
Release of CppUTest Version 3.8

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#860]
Since version 3.7 of CppUTest rather a lot of improvements, new features, and bug fixes have been added- too many in fact for me to remember all.

I propose that we make a release of version 3.8 in the near future. Perhaps we can use this issue as  "To-Do List" for what needs to be done before this can happen.

**Comment by basvodde** [comment]
Create 36-hour days.

**Comment by arstrube** [comment]
Hey, once we're at it, lets make it 48-hour days ;-).

On a more serious note, would a time frame of 4 to 8 weeks seem possible?

**Comment by basvodde** [comment]
Hopefully. I'm in the process of finalizing a book (somewhat unrelated to CppUTest) thus limiting my time somewhat. When that is wrapped up (should be 4-8 weeks), then I'll look at this more seriously and at some of the open pull requests that I delayed too long.

**Comment by offa** [comment]
:+1:  a new release would be great.

**Comment by offa** [comment]
> Perhaps we can use this issue as "To-Do List" for what needs to be done before this can happen.

Or use a Milestone and Labels, which give a better overview.

**Comment by arstrube** [comment]
The way I see it, the current head is brimming with new features and bug fixes. I would rather see a release sooner, than making a to-do list of what we still also want in there.

I see a few to-do items that are directly related to the release, though. 

+ Make sure the change log is complete
+ Add missing documentation on github.cpputest.io
+ With more and more new features, can we find a consistent way of indicating which version of CppUTest is required for a particular feature? Or do we just document the current version (meaning we release first and then document)?

**Comment by arstrube** [comment]
@basvodde which ones are the PRs that have been delayed too long? Can you label them in some way, so they stand out from the ones we just have ignored so far?

**Comment by basvodde** [comment]
I think all of them?

**Comment by arstrube** [comment]
All 117? Oh, wait, we are talking about PRs not Issues. My bad.

**Comment by arstrube** [comment]
Okay, in this case maybe mark the all-but-rejected ones? I spot 3 PRs that I believe you weren't really all that keen on integrating, if memory serves me right.

**Comment by arstrube** [comment]
Maybe label the ones you want in 3.8 would be a good idea (as new ones will keep coming in, too)

**Comment by BillDenton** [comment]
Any chance of a 3.8 release soon? We would like to use the TEST_EXIT macro and a released version rather than just taking the latest version from GitHub.

**Comment by arstrube** [comment]
I too would rather have a released version 3.8 of what we is now, soon.

**Comment by BillDenton** [comment]
I have rewritten one of my tests of code that uses asserts to use the TEST_EXIT. It is much cleaner and clearer than the original using setjmp/longjmp inside the unit test code. Hence, we would really like to use  the newer version of CppUTest. For our internal traceability it would be much better if we could use a released version.

**Comment by BillDenton** [comment]
Any progress towards 3.8?

**Comment by basvodde** [comment]
Nope, I think it'll take at least a couple more weeks. I'll need to package it up and won't be able to do that right now. Sorry. It will come!

**Comment by arstrube** [comment]
@basvodde Any progress? Anything I can help with (besides creating 36 hour days)?

**Comment by basvodde** [comment]
Nope, sorry. couple more weeks not passed yet. :) It will come!

**Comment by BillDenton** [comment]
Any update? I noticed a lot of discussion about bool and long long support on the in the issues. Is this likely to hold up a release?
Thanks.

**Comment by basvodde** [comment]
Eheh, nope :)

But, I think it would be good to get the most obvious pull requests closed before release.

Also, for people who want to help, we could put some release notes in here, that would make releasing easier and others can help with that.

**Comment by BillDenton** [comment]
Any updates? Will the release have support for 64bit integer comparisons, e.g. CHECK_EQUAL_TEXT(U64Expected, U64Actual, "something"); At the moment I'm using MEMCMP_EQUAL_TEXT.
Thanks.

**Comment by basvodde** [comment]
Eh, perhaps these weeks. Now merging some open pull requests. We'll need more thorough release notes though:P

**Comment by BillDenton** [comment]
Any update? Thanks.

**Comment by basvodde** [comment]
Yup, as you might have noticed, there has been more changes for integrating long long properly. So, this will need to go on for another couple of weeks. Sorry about that.

**Comment by rhertzog** [comment]
Please include a fix for #961 in the next release. TIA.

**Comment by BillDenton** [comment]
Would it be possible to triage the many open issues using labels and milestones to allow progress towards a release? Any idea of time frame?

**Comment by BillDenton** [comment]
Any ETA? Thanks.

**Comment by itavero** [comment]
Just wondering: isn't it possible to (automatically) release a new version every month or so (if the code has changed of course)?
I would expect the master branch always to be in a 'releasable` condition, because PRs get checked before being merged.
The only question is how the version number should be increased (I guess it's rather difficult to automatically decide whether a change introduces is a patch, introduces new functionality or breaks old interfaces).

**Comment by arstrube** [comment]
> I would expect the master branch always to be in a 'releasable` condition, because PRs get checked before being merged.

Exactly my way of thinking. A release could be made at any time (except perhaps those very rare situations, where a more complex change is in progress, that involves more than one PR). Which is why I find it difficult to understand why @basvodde would only make a release after certain open PRs have been delt with.

We have a lot of excellent contributors and, in my experience, there will always be around a dozen open pull requests, at any given point in time, because we keep them coming :-)

Personally, I feel that not releasing keeps back a lot of fixes and improvements from those who rely on released packages, while those open issues could simply go into the next release.

We do have to deal with the copyright issue though, or there will be no Debian package....

**Comment by jwgrenning** [comment]
On 20 May 2016, at 1:30, arstrube wrote:

>> I would expect the master branch always to be in a 'releasable` 
>> condition, because PRs get checked before being merged.
>
>
> We do have to deal with the copyright issue though, or there will be 
> no Debian package....
>

I edited out the Pragmatic Programmer copyright text.  Was there 
something else needed?

**Comment by arstrube** [comment]
@jwgrenning no, no, nothing from your side. All is well :)

There are other files, however, that we will have to remove, because copyright infringement (NXP, Keil, etc. etc.)

**Comment by BillDenton** [comment]
@itavero the automated tests do ensure that the master branch is in good shape to release. However, they don't cover everything, especially all the compilers used by CppUTest users. Hence it is necessary to do some manual work to manage releases. Using labels/milestones would allow planning of the releases. Also an issue (like this one) should be raised to discuss any issues around the release. It would good to get more regular releases.

**Comment by arstrube** [comment]
@BillDenton well, as for "all the compilers", I am not aware of any mechanism to check those _before_ a release. For example, up to now I have looked after the Cl2000 compiler for TI. Right now, It's working. It will probably be broken by the time the release comes around, and by then I won't have access to it anymore. Some things are only picked up and reported immediately after a release, which is why we have 3.7.1 and 3.7.2. Agreed tough that for various reasons, a release involves more manual work than we'd like to see.....

**Comment by itavero** [comment]
Is there a release procedure?
If not, how is Cpputest verified with these compilers?
I can _not_ imagine that this can't be automated.

Sure, there might be licensing issues, but that does not mean that it can't be done.
It only makes things a bit more complicated.

PS: Where can I find the compilers that are currently "supported"?

**Comment by arstrube** [comment]
I think that the compilers we suport are pretty much the ones tested on Appveyor and TravicCI, plus MacOs, which could now be automated on TravisCI (needs to be done though).

**Comment by basvodde** [comment]
Sorry people. I've been the reason for not making a release yet, and it mostly has to do with too much other stuff. Then when looking at it, the 64 bits took a while to merge and get working on all compilers, then the copyright notice things came up. I believe they are both now closed, so I'll try to put it out next week. I won't be having time to write any good release notes, so instead of speculating about why we didn't release, I'd propose all the people in this thread fix up a good release notes ;)

**Comment by offa** [comment]
We should also collect those issues / PR's, that are relevant for v3.8.

-------

Since GCC 6 is now widely available, it would be good to see these two fixed in an upcoming 3.8: #958 and #957

**Comment by basvodde** [comment]
The #958 should be relative simple as it is probably the CMake variant of the change I just made in configure.ac. The other in is hard and will need to be tried as it might affect other compilers. I'll have a look at it later.

**Comment by basvodde** [comment]
Release at: https://github.com/cpputest/cpputest/releases/tag/v3.8

**Comment by BillDenton** [comment]
Thanks.
