### ISSUE TITLE
Can't build examples under OS X

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#864]
```
$ make -f ./Makefile_using_MakefileWorker clean examples
```

yields:

![screen shot 2016-02-11 at 21 13 06](https://cloud.githubusercontent.com/assets/4686469/12989200/91583736-d104-11e5-870e-ced2bf181268.png)

The same works fine in Cygwin.

**Comment by basvodde** [comment]
This should be fixed. The examples are now also in the build.
