### ISSUE TITLE
Appveyor / mingw problem

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#869]
Appveyor now loads mingw with Gcc 5.3.0 instead of 4.8.3.

A "new" familiar, strange compiler error is showing up. I don't have 5.3.0 so it's a bit difficult to know what is going on.

**Comment by Andne** [comment]
@arstrube How do you want to treat this, do you want to fix the compiler error or do you want to force a different version of GCC?

**Comment by arstrube** [comment]
Fixing seems impossible - some compiler always barks at something. The cleanest way would be via \<cmath\> but can't be done because requires std c++ lib. I actually consider this a bug in GCC, there's supposed to be a macro which determines whether it's being passed a float or a double and compile the correct code.

I am busy experimenting with a suitable #pragma (got it wrong several times, but now probably correct. This way, we could actually use GCC 5.3.0.

Forcing the old version would probably be the easiest (or at least a version that doesn't exhibit this annoying problem).

An unrelated point is that since the change, unzip spits out about 1MB of useless messages, making it very hard to scroll to the lines that are actually interesting. Perhaps this could be suppressed.

Maybe by tomorrow, the pragma will work. Let's perhaps also hear out @basvodde on this. It seems pretty much a choice between pragma (if that works) or forcing the old version.

(This is one of those annoying things where it is notoriously difficult to find information or be heard on StackOverflow and the like, because most people getting these error get them for a good reason, not like here. The errors are also strange. double is converted to float, not the other way round, and how come the compiler is whining about int totally escapes me. It did that some time ago, and at that time, casting to float for some reason made it shut up (also rather a hack, really, because isnan() should take a double without complaining).

**Comment by arstrube** [comment]
P.s. apologies for my rambling, and your help is much appreciated!

**Comment by Andne** [comment]
The install has been spitting out a huge log for a while now, looks like chocolately has changed that behavior recently but there's not a new version to use yet.  I can probably suppress the output from the command in general, but I'm not sure I want to lose the normal information or any error messages.

I've force GCC to 4.8.5 and it appears to build correctly now, I'll have a pull request soon, not sure if you want to fix the code or just use the older GCC version.

**Comment by basvodde** [comment]
Fix the code so it works with both versions, please ;)

**Comment by arstrube** [comment]
@basvodde it seems the #pragma is now doing its magic right with 5.3.0

@Andne I was hoping Chocolatey had a -q switch or something that you could turn on. Now we have 15000 lines with irrelevant information with maybe 30 lines of interesting stuff that is hard to scroll to, even with good speed internet and a fast computer.

**Comment by arstrube** [comment]
A bug report should actually be filed against mingw-gcc 5.3.0. I can't reproduce it locally though because I don't use it anymore.

**Comment by arstrube** [comment]
I think this has been fixed - at least we routinely test against Mingw / Gcc 5.3.0 on Appveyor and there are no errors.
