### ISSUE TITLE
Mock failures with repeat count > 1 do not cause failure

### ISSUE THREAD

**Issue by hbock** [cpputest/cpputest#879]
Hi,

We noticed in internal testing that with the MockSupportPlugin, any mock failure (e.g., mock().actualCall() without an expectOneCall()) that occurs in multiple runs in the same process - i.e., -r2 or higher, is only reported on the first run:

```
hbock@whiskey-dev ~/development/scratch/cpputest-mock-repeat-test $ ./main -r4
Test run 1 of 4

testgroup.cpp:8: error: Failure in TEST(MyGroup, First)
	Mock Failure: Unexpected call to function: Foo
	EXPECTED calls that did NOT happen:
		<none>
	ACTUAL calls that did happen (in call order):
		<none>

.
Errors (1 failures, 1 tests, 1 ran, 0 checks, 0 ignored, 0 filtered out, 0 ms)

Test run 2 of 4
.
OK (1 tests, 1 ran, 0 checks, 0 ignored, 0 filtered out, 0 ms)

Test run 3 of 4
.
OK (1 tests, 1 ran, 0 checks, 0 ignored, 0 filtered out, 0 ms)

...
```
It seems like the failure should be reported on all test runs.  Running through the debugger, I notice that the failure is detected, but we never get to actually terminate the test or report the failure because UTestShell::hasFailed() returns true.  See the logic in MockFailure.cpp:

https://github.com/cpputest/cpputest/blob/2e32dd0aed2cc4429455e70f148a1865842ba0a6/src/CppUTestExt/MockFailure.cpp#L59-L60

If I remove the conditional on line 59, the failure is reported as expected.  It doesn't seem to affect the outcome of any CppUTestExt unit tests.   I'm not sure if the check is not valid, or if UTestShell's failure state needs to be reset between repeats, or something else.  

I'm happy to fix it if I can get some guidance on what the correct operation of MockFailure is.  :)

**Comment by hbock** [comment]
Attached is a small repeatable test group that exhibits the issue.  Run on the command line with -r2.

[cpputest-mock-repeat-test.zip](https://github.com/cpputest/cpputest/files/135525/cpputest-mock-repeat-test.zip)

**Comment by cuitoldfish** [comment]
Hi hbock,
I think the overall guideline of TDD is that try best to match one test failure to only one test, and only fix one test failure at one time. 
So CppUTest only report the first failure and also only report once to make you focus on fixing that sole failure, then next.   I have met several similar case in other usage. and, 

`OK (1 tests, 1 ran, 0 checks, 0 ignored, 0 filtered out, 0 ms)`

has showed no check take place.

**Comment by arstrube** [comment]
That is a very intersting bug. hasFailed() should be reset on subsequent runs. @hbock I agree that, within a test case, only the first failure should be reported (that's what hasFailed() is for) but, repeated test runs should fail in the same way (unless a bug in the software you test caused "random" failures).

**Comment by cuitoldfish** [comment]
@arstrube, if already one test is failed, then still need to let all repeated test to report the same failure?
isn't that a messy( because you have already known what goes wrong )?  Now following tests actually do not  check anything anymore because there has been one capture that failure.

**Comment by arstrube** [comment]
@cuitoldfish Yes, absolutely. The point of running -r is to find inconsistencies between runs in the behavior of the SUT. To find those inconsistencies, it is of utmost importance from my point of view that the test tool (CppUTest in this case) behaves identical between runs.

@basvodde how come this is not initialized between runs? Looks like some object is reused that should be destroyed and recreated. Or, at least, re-initialized?

**Comment by arstrube** [comment]
Looking at your example, I suspect the problem might be related to the MockSupportPlugin.

If you did not use the plugin and wrote your test in the following way, the problem might go away (no chance to test yet):
```c++

TEST_GROUP(MyGroup)
{
};

TEST(MyGroup, First)
{
  mock().actualCall("Foo");
  mock().checkExpectations();
  mock().clear();
}
```

**Comment by arstrube** [comment]
Wrong. Behavior stays the same :-(

**Comment by arstrube** [comment]
@cuitoldfish - does the fix work for you?

**Comment by hbock** [comment]
I totally spaced on this as well.  The fix worked great for me and we have backported it to 3.7.2 in our production codebase.
