### ISSUE TITLE
Dead link at Manual --> Test Plugins

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#905]
The link the the plugins manual is dead.

> http://cpputest.github.io/plugins_manual.html

Ends in a 404.

Here's where to find it:

> Complete Documentation for provided plugins can be found on the [Plugins Manual](http://cpputest.github.io/plugins_manual.html) page.

http://cpputest.github.io/manual.html#test_plugins

**Comment by arstrube** [comment]
@offa thanks for noticing this.

@basvodde fixed this and changed the Coveralls badge to point to cpputest/cpputest in 
https://github.com/cpputest/cpputest.github.io/pull/32

**Comment by offa** [comment]
Fixed by PR mentioned above.
