### ISSUE TITLE
Fix line endings

### ISSUE THREAD

**Issue by BillDenton** [cpputest/cpputest#914]
Could you fix line endings and trailing spaces. When using the code our version control system one some files noticed that the line endings were UNIX when under Windows. I'm not sure if there are trailing spaces but there are mixed line endings.
The line endings have been cleaned up previously:
https://github.com/cpputest/cpputest/commit/e674cfe759b20c6b78becbc50d8f9f644d32ea8a

**Comment by basvodde** [comment]
Stange, this ought to be taken care of by the git config files...

**Comment by BillDenton** [comment]
I downloaded the latest zip (was 20e53b7) and unzipped it to the target directory (to replace version 3.7.1). When checking into our version control which has line ending & trailing space checks during check in a lot of files where blocked. I got around this by turning off the checking for the directory.

**Comment by arstrube** [comment]
I got some mysterious messages when pulling the last merge. But as far as I remember it was about changed permissions, not line endings.

@BillDenton I take it you know this already, but there are some files that are supposed to have Unix endings, even under Windows, such as Makefile, configure scripts, *.sh to mention but a few.

**Comment by arstrube** [comment]
Also, files that are zipped / unzipped can be different to what they would be if pulled from the repository.

**Comment by arstrube** [comment]
@basvodde can we have a trailing-whitespace-killer? I mostly use commandline git, which hightlights trailing whitespace in red, but other tools (e.g. SmartGit) don't, and I think they are hard to notice, if at all visible, in the Github diff.

**Comment by BillDenton** [comment]
Unfortunately I don't have a list now (and can't easily get one), but I'll get a list next time I update it.

**Comment by BillDenton** [comment]
I've got a list of files that **appear** to have either UNIX line endings or trailing spaces:
\examples\AllTests\AllTests.cpp
\examples\AllTests\EventDispatcherTest.cpp
\examples\AllTests\MockDocumentationTest.cpp
\include\CppUTest\CommandLineArguments.h
\include\CppUTest\CommandLineTestRunner.h
\include\CppUTest\CppUTestConfig.h
\include\CppUTest\JUnitTestOutput.h
\include\CppUTest\MemoryLeakDetectorNewMacros.h
\include\CppUTest\PlatformSpecificFunctions_c.h
\include\CppUTest\SimpleString.h
\include\CppUTest\TestFailure.h
\include\CppUTest\TestFilter.h
\include\CppUTest\TestHarness_c.h
\include\CppUTest\TestMemoryAllocator.h
\include\CppUTest\TestOutput.h
\include\CppUTest\TestPlugin.h
\include\CppUTest\TestTestingFixture.h
\include\CppUTest\Utest.h
\include\CppUTest\UtestMacros.h
\include\CppUTestExt\MockActualCall.h
\include\CppUTestExt\MockCheckedActualCall.h
\include\CppUTestExt\MockCheckedExpectedCall.h
\include\CppUTestExt\MockExpectedCall.h
\include\CppUTestExt\MockExpectedCallsList.h
\include\CppUTestExt\MockFailure.h
\include\CppUTestExt\MockNamedValue.h
\include\CppUTestExt\MockSupport.h
\include\CppUTestExt\MockSupport_c.h
\include\CppUTestExt\MockSupportPlugin.h
\src\CppUTest\CommandLineArguments.cpp
\src\CppUTest\CommandLineTestRunner.cpp
\src\CppUTest\JUnitTestOutput.cpp
\src\CppUTest\MemoryLeakDetector.cpp
\src\CppUTest\SimpleString.cpp
\src\CppUTest\TestFailure.cpp
\src\CppUTest\TestFilter.cpp
\src\CppUTest\TestHarness_c.cpp
\src\CppUTest\TestMemoryAllocator.cpp
\src\CppUTest\TestOutput.cpp
\src\CppUTest\TestPlugin.cpp
\src\CppUTest\TestRegistry.cpp
\src\CppUTest\TestResult.cpp
\src\CppUTest\Utest.cpp
\src\CppUTestExt\MemoryReportFormatter.cpp
\src\CppUTestExt\MockActualCall.cpp
\src\CppUTestExt\MockExpectedCall.cpp
\src\CppUTestExt\MockExpectedCallsList.cpp
\src\CppUTestExt\MockFailure.cpp
\src\CppUTestExt\MockNamedValue.cpp
\src\CppUTestExt\MockSupport.cpp
\src\CppUTestExt\MockSupport_c.cpp
\src\CppUTestExt\MockSupportPlugin.cpp
\src\Platforms\armcc\UtestPlatform.cpp
\src\Platforms\C2000\UtestPlatform.cpp
\src\Platforms\Gcc\UtestPlatform.cpp
\src\Platforms\GccNoStdC\UtestPlatform.cpp
\src\Platforms\Iar\UtestPlatform.cpp
\src\Platforms\Symbian\UtestPlatform.cpp
\src\Platforms\VisualCpp\UtestPlatform.cpp
\tests\CommandLineArgumentsTest.cpp
\tests\CommandLineTestRunnerTest.cpp
\tests\CppUTestExt\MemoryReportFormatterTest.cpp
\tests\CppUTestExt\MockActualCallTest.cpp
\tests\CppUTestExt\MockExpectedCallTest.cpp
\tests\CppUTestExt\MockFailureTest.cpp
\tests\CppUTestExt\MockPluginTest.cpp
\tests\CppUTestExt\MockSupport_cTest.cpp
\tests\CppUTestExt\MockSupport_cTestCFile.c
\tests\CppUTestExt\MockSupport_cTestCFile.h
\tests\CppUTestExt\MockSupportTest.cpp
\tests\JUnitOutputTest.cpp
\tests\MemoryLeakDetectorTest.cpp
\tests\MemoryLeakWarningTest.cpp
\tests\PluginTest.cpp
\tests\SimpleStringTest.cpp
\tests\TestFailureNaNTest.cpp
\tests\TestFailureTest.cpp
\tests\TestFilterTest.cpp
\tests\TestHarness_cTest.cpp
\tests\TestMemoryAllocatorTest.cpp
\tests\TestOutputTest.cpp
\tests\TestRegistryTest.cpp
\tests\TestUTestMacro.cpp
\tests\UtestPlatformTest.cpp
\tests\UtestTest.cpp

**Comment by arstrube** [comment]
\examples\AllTests\AllTests.cpp - contains trailing spaces
../examples/AllTests/EventDispatcherTest.cpp couldn't see anything

**Comment by BillDenton** [comment]
Our pre-check in script picks up line endings and trailing spaces. I agree "\examples\AllTests\AllTests.cpp" contains trailing spaces. Also, I can't see anything in "/examples/AllTests/EventDispatcherTest.cpp". Its probably a file that I didn't check in yesterday before disabling the pre-check in script, so it got included in todays check in. I created the above list from files checked in today, which should only be those with line endings and trailing spaces. However, there may be some which I didn't check in yesterday. Hence, the list may contain files that don't have issues. Sorry, I don't have a tool to identify the files.

**Comment by arstrube** [comment]
```bash
$ find include -type f -exec egrep -l " +$" {} \;
include/CppUTest/Utest.h
include/CppUTestExt/MockExpectedCallsList.h
include/CppUTestExt/MockSupport.h
include/Platforms/c2000/stdint.h
$ find src -type f -exec egrep -l " +$" {} \;
src/CppUTest/SimpleMutex.cpp
src/CppUTest/Utest.cpp
src/CppUTestExt/MockSupport.cpp
src/Platforms/Keil/UtestPlatform.cpp
src/Platforms/Symbian/README_Symbian.txt
src/Platforms/Symbian/SymbianMemoryLeakWarning.cpp
src/Platforms/Symbian/UtestPlatform.cpp
$ find tests -type f -exec egrep -l " +$" {} \;
tests/AllTests.dsp
tests/AllTests.mak
tests/AllTests.plg
tests/CppUTestExt/MockCallTest.cpp
tests/CppUTestExt/MockStrictOrderTest.cpp
tests/SimpleMutexTest.cpp
tests/TestUTestMacro.cpp
```

**Comment by arstrube** [comment]
I fixed most trailing whitespace, because it ought to be gone anyway, but I'm not sure this will really help you in  your situation, because....
- all source files are checked in consistently with Unix (and not Windows) line endings.
- some Visual Studio files have trailing blanks quite consistently, so VS might break without them, or, more likely, the next time files get saved, the whitespace will be back
- there were some tabs floating around also; not sure I caught all of those

**Comment by BillDenton** [comment]
Thanks. I'll close this issue once the updates are in checked in. I'll have a look next time I update our local copy of CppUTest.

**Comment by arstrube** [comment]
I'm going to prepare a PR for the trailing spaces. But the Unix line endings are consistent, and they are no problem for any IDE or compiler I know of. Also, I am not touching any of the *.mak and *.dsp because those are Visual Studio files and I'd rather not interfere with their formatting.

**Comment by itavero** [comment]
I think this can be prevented in the future by defining guidelines and enforcing them (so this is related to #293 in my opinion).
