### ISSUE TITLE
Test executable location incorrect when CppUTest used via CMake add_subdirectory()

### ISSUE THREAD

**Issue by jerryryle** [cpputest/cpputest#919]
I have a CMake project that has its own copy of CppUTest in a subfolder, and the project uses it via `add_subdirectory()`. When building, the CppUTest build fails at the "Discovering Tests in CppUTestTests" step, when it attempts to execute the test executable. The failure is "No such file or directory" because the test executable is not where the discovery script is looking for it.

I believe this is caused by the fact that the executable output location is set via:
`cpputest_set_test_output_location(CppUTestTests "${CMAKE_BINARY_DIR}/tests")`

While the test discovery script (CppUTestBuildTimeDiscoverTests.cmake) attempts to change the working directory via:
`WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}`

This normally works because `${CMAKE_CURRENT_BINARY_DIR}` equals `${CMAKE_BINARY_DIR}/tests` when CppUTest is built by itself, but not when it's included in a subfolder of a different project.

I'm not sure why the `cpputest_set_test_output_location()` is required. If I remove it, the test executables always wind up where the test discovery looks for them (in `CMAKE_CURRENT_BINARY_DIR`) & it builds fine (both standalone and when CppUTest is included as a sub-folder). It seems like the solution is to remove the `cpputest_set_test_output_location()` lines, but I'm not completely comfortable with CMake yet & I'm worried I'm missing some scenario where this is useful.

**Comment by jerryryle** [comment]
Ahh. Found @charlesnicholson's commit that explains why the test output folder is forced. Perhaps the "cpputest_buildtime_discover_tests()" function should be updated to allow the caller to pass in the output folder so that these can be kept in sync.

**Comment by charlesnicholson** [comment]
Seems like just changing `cpputest_set_test_output_location(CppUTestTests "${CMAKE_BINARY_DIR}/tests")` to `cpputest_set_test_output_location(CppUTestTests "${CMAKE_CURRENT_BINARY_DIR}/tests")` should fix it?

**Comment by jerryryle** [comment]
When, I tried that, the effective link location became "/tests/tests/CppUTestTests" instead of "/tests/CppUTestTests" but the discovery was still looking for "/tests/CppUTestTests". Using `cpputest_set_test_output_location(CppUTestTests "${CMAKE_CURRENT_BINARY_DIR}")` works, but I'm not sure that does anything useful.

**Comment by charlesnicholson** [comment]
Do you have a fork up on github somewhere I can mess around with? Happy to take a look...

**Comment by jerryryle** [comment]
I'm on mobile, but I can post a fork and example project this evening. I'll shoot you an email when it's up. Thanks for checking it out! Not urgent though, I'm just playing around with coming back to CMake. : ) So, enjoy your weekend.

**Comment by charlesnicholson** [comment]
Funny running into you here, lol.

BTW, for what it's worth, I prefer to pull in CppUTest via CMake's "ExternalProject_Add" command. That way you don't end up with the CppUTest sources in your IDE tree, if you use one, but you can still debug into it since it was built locally.

**Comment by charlesnicholson** [comment]
You can see an example of what I'm talking about over [here](https://github.com/charlesnicholson/nanoarq/blob/master/CMakeLists.txt) (definition) and [here](https://github.com/charlesnicholson/nanoarq/blob/master/functional_tests/CMakeLists.txt) (use).

**Comment by jerryryle** [comment]
Yeah, I was about to check that out, but had an older project that pulled it in with add_subdirectory(). When it no longer worked, I figured I'd try to determine why. Thanks for the examples!

**Comment by charlesnicholson** [comment]
Re-reading this, I think your solution of `cpputest_set_test_output_location(CppUTestTests "${CMAKE_CURRENT_BINARY_DIR}")` is correct, since that's exactly the correct location, but CMake doesn't know about Xcode sneaking "Debug", "Release", etc into the path.

**Comment by jerryryle** [comment]
Interesting. I'd thought that `cpputest_set_test_output_location(CppUTestTests "${CMAKE_CURRENT_BINARY_DIR}")` would be redundant because the output location would default to `${CMAKE_CURRENT_BINARY_DIR}`. But I guess it doesn't in the Xcode case.

Here's a quick test project that uses `add_subdirectory()` to pull in cpputest:
https://github.com/jerryryle/NestingTesting

If you clone recursive, it should pull down CppUTest as a submodule in a branch that uses `cpputest_set_test_output_location(CppUTestTests "${CMAKE_CURRENT_BINARY_DIR}")`. Both the standard makefile generator and XCode seem to build this way.
I tried the following successfully (blowing away the 'build' folder between the builds):
* `mkdir build && cd build && cmake .. && make`
* `mkdir build && cd build && cmake -G Xcode ..`

If you think this looks good, I'll submit a PR.

I do think I'll be using `ExternalProject_Add()` henceforth.

**Comment by charlesnicholson** [comment]
Looks like it works, and makes sense. In light of this, I might rename `cpputest_set_test_output_location` to something like `cpputest_normalize_test_output_location` and just take the target name instead of the target name + path.

`cpputest_normalize_test_output_location(CppUTestTests)`
`cpputest_normalize_test_output_location(CppUTestExtTests)`

What do you think? Sorry for this, btw, thanks for cleaning up my mess.

**Comment by jerryryle** [comment]
Makes sense. I'll go ahead and do that in this branch.

No prob. I think you've cleaned up more than one of my messes (recalling a certain makefile that had the potential to perform an `rm -rf /`). And I learned a lot through this exercise. Thanks!

**Comment by charlesnicholson** [comment]
I opened https://github.com/cpputest/cpputest/pull/920 for a fix, pending review + discussion with @jerryryle

**Comment by jerryryle** [comment]
Looks good. Happy to close this out after it's merged.

**Comment by jerryryle** [comment]
Fixed in #920.
