### ISSUE TITLE
MockSupport::expectNoCall does not append scope to function name

### ISSUE THREAD

**Issue by tomnzed** [cpputest/cpputest#922]
When adding an expectation:
`mock("foo").expectOneCall("bar")`
works fine, and will match with
`mock("foo").actualCall("bar")`

However,
`mock("foo").expectNoCall("bar")`
does not match with
`mock("foo").actualCall("bar")`
so if 
`mock("foo").ignoreOtherCalls() `
is also used, no unit testing can be done to check that functions in the test unit are not called.

This bug seems to come from MockSupport.cpp:172 in MockSupport::expectNoCall()
`call->withName(functionName);`
compared to 
`call->withName(appendScopeToName(functionName));`
in MockSupport::expectOneCall().

In the above example, creating the expectation as
`mock("foo").expectNoCall("foo::bar")`
works and does match with 
`mock("foo").actualCall("bar")`

This seems like a small bug

**Comment by offa** [comment]
Since #930 is merged, this should be fixed.
