### ISSUE TITLE
gcc needed in OS X to compile examples

### ISSUE THREAD

**Issue by hmijail** [cpputest/cpputest#928]
I cloned the current cpputest.
In OS X 10.11.4, I can only successfully compile (and run) the examples by using gcc (v5.3, installed via MacPorts).
When using clang, the examples fail to compile like so:

```
...
compiling FEDemoTest.cpp
AllTests/FEDemoTest.cpp:81:21: error: implicit conversion increases floating-point precision: 'float' to 'double'
      [-Werror,-Wdouble-promotion]
    DOUBLES_EQUAL(f / 3.0f, 3.333f, 0.001f);
    ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
```

clang --version reports 

```
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
```

**Comment by itavero** [comment]
Is this related to #864 ?

**Comment by arstrube** [comment]
No, I don't think so.

**Comment by basvodde** [comment]
I think I actually have a local fix for this one...

**Comment by arstrube** [comment]
`(double)(f / 3.0f)` should fix it, right? Didn't have a chance to test that, though.

**Comment by basvodde** [comment]
Fixed this one, I think.

**Comment by davgar** [comment]
The examples are working OK for me using v3.8-75-gb801207 of CppUTest, Apple LLVM version 7.3.0 (clang-703.0.31) on Target: x86_64-apple-darwin15.0.0

I ran: 
`$ make -f ./Makefile_using_MakefileWorker clean examples`

and got as a result 
...
OK (454 tests, 452 ran, 1415 checks, 2 ignored, 0 filtered out, 149 ms)

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C examples  all CPPUTEST_USE_STD_CPP_LIB=Y CPPUTEST_USE_MEM_LEAK_DETECTION=Y
Linking CppUTestExamples_tests
Running CppUTestExamples_tests
...................!!!!.......................`
OK (46 tests, 42 ran, 272 checks, 4 ignored, 0 filtered out, 3 ms)
