### ISSUE TITLE
C API return values are not type-safe

### ISSUE THREAD

**Issue by uecasm** [cpputest/cpputest#933]
For example, if the expectation defines a `float` return value, and the actual call uses `mock_c()->intReturnValue()` to retrieve it, it causes undefined behaviour (typically resulting in the bit-pattern-equivalent int being returned, but that's compiler-specific).

This is because the various `returnValue_c` implementations call `getMockValueCFromNamedValue`, which does check the type defined on the C++ side and populates the appropriate field of a union, but they then return one field of the union without guaranteeing that this was the field just written to.

This also fails to invoke the type conversions implemented by the C++ `MockNamedValue`, eg. between signed and unsigned values.  (Although those aren't entirely consistent either.)

Suggested fix is to replace code such as this:

    int intReturnValue_c()
    {
        return getMockValueCFromNamedValue(actualCall->returnValue()).value.intValue;
    }

With code more like this:

    int intReturnValue_c()
    {
        return actualCall->returnValue().getIntValue();
    }

Or, of course, just:

    int intReturnValue_c()
    {
        return actualCall->returnIntValue();
    }

**Comment by arstrube** [comment]
Is the first version still around? I thought I had cleaned them out?

Whether the second or the third option is correct, depends on the context (same as in C++). The first snipped would suggest that, in this context, the third snippet would be called for.

**Comment by arstrube** [comment]
As far as I can see, this code is only used for testing.

What is the use case for problems showing?

I have run into that sort of problem only for one reason: When a MockNamedValue is **undefined**, it actually defaults to **`int`**, leading to problems like the one you mention. I have been wondering about this before. Could we make MockNamedValues type default to "undefined" in that case, perhaps? How would that have to be handled (presumably fail the test)?

**Comment by uecasm** [comment]
I haven't encountered a problem "in the wild", this was just something I noticed while reading the code.  So yes, it's still there (unless it was changed in the past couple days, maybe).

The code is not just used for testing.  This is the C API.  It will be encountered if anyone makes an expectation with a return value whose type differs from the type used to retrieve the return value in the actual call.

Note that most of the time it will work anyway by coincidence -- eg. mixing up integer types will usually be invisible, because on many platforms int and long are the same size, and signed and unsigned ints can be mixed if you're not using a value in the top bit range.  But relying on different union members to have the same offset in the storage is technically undefined behaviour, even though most implementations will do this.

Both the second and third snippets are equivalent; neither is more "correct" than the other.  The third is merely more concise.

**Comment by arstrube** [comment]
These shouldn't be there; apperently I overlooked them when adding the new functions. Calling the returnValue on actualCall vs. MockSupport is subtly different (see the C++ interface) as far as I remember. When I worked on this a while ago, I thought the returnValue calls on MockSupport were redundant - but not so! I should think the C interface should follow the C++ code.

**Comment by arstrube** [comment]
Actually, to be honest, without looking more closely, I am not sure right now where these functions belong but I *think* it's MockActualCall_c so the actual call version would be appropriate..... :-/

**Comment by arstrube** [comment]
Arggh. *both* interfaces use the same functions.... This isn't good. It must be possible to come up with a test case that exposes a bug here. There should be two sets of functions, the one wrapping MockSupport, the other one wrapping MockActualCall, and they are not (quite) the same.

Will give it some thought later this week. This should definitely be fixed.

**Comment by arstrube** [comment]
Also, yes, your 2. and 3. are of course equivalent and 3. would be preferred. The one I had in mind is like
```c++
void* returnPointerValueOrDefault_c(void * defaultValue)
{
    if (!hasReturnValue_c()) {
        return defaultValue;
    }
    return pointerReturnValue_c();
}
```
and that should wrap MockSupport ( and not MockActualCall).......

**Comment by uecasm** [comment]
Does the distinction matter?  `mock().intReturnValue()` == `mock().returnValue().intReturnValue()` == `(last result of mock().actualCall(...)).intReturnValue()` etc, and it's the same on the C side.

This is required by the split call case, although TBH I think the API would be cleaner if these were removed from MockSupport entirely (perhaps replaced with a `lastActualCall()` method).

**Comment by arstrube** [comment]
About removing it entirely - maybe @basvodde would care to comment? My memory is a bit foggy now, but at some point I was like, hey, let's remove this redundancy (on the C++ side), and then realized that things weren't quite so simple and it's actually needed.

As long as it is there on the C++ side, I think it would be better to implement the C side to match.

Either way, there is no reason any more to access the fields of the MockValue directly, so that code should definitely go. I'll take a closer look at it as soon as I can take the time.

**Comment by basvodde** [comment]
I'm not quite sure what is proposed to be removed?

**Comment by uecasm** [comment]
This is kinda off-topic (probably discussion of removing things should be a separate issue) -- originally this was just about the C API type safety.

But regarding removing things, basically everything in `MockSupport` (both C and C++) dealing with return values seems _almost_ redundant, and it would declutter and simplify the code if they were all removed.

**However**, there are two caveats:

1. Just removing them is unacceptable as it breaks required functionality of splitting `actualCall` usage in two parts (as shown in some of the examples).  However this can be resolved by adding one method to replace all of the existing ones: `mock().lastActualCall()`, which returns a `MockActualCall&` that can then be called through to get at the return value APIs that were removed from the top level.

2. Removing APIs is obviously a breaking change for any test code that currently calls them.  This may be undesirable.

I'm happy to make this into a PR if there's a chance that the second caveat won't torpedo the whole thing (making it a waste of time).

But remember that this is a side-track and is completely unrelated to this current Github issue, which is about the dangers of accessing the wrong union members.

**Comment by basvodde** [comment]
Uhm, I added the code in MockSupport. The reason is, it causes code like:

mock().actualCall( .... )

if (mock().hasReturnValue())
  do something

And, I've written a lot of code like that. Having mock().returnValue have been very valuable shortcuts in practice (for me) and I'm hesitant of removing methods like these. What problem do they cause?

**Comment by uecasm** [comment]
They caused @arstrube to get confused when the C API has the same implementation for both `MockSupport_c` and `MockActualCall_c` when looking at this actual issue.  Other than that, there's no problem, just a little clutter (and more duplication of interfaces, larger coverage surface, etc).

Still, what's wrong with replacing that code with this:

    mock().actualCall(...);
    ...
    if (mock().lastActualCall().hasReturnValue())
        do something

?  That's what I was suggesting, and I think it reads better, even if it is marginally more typing.

**Comment by uecasm** [comment]
ie. yes, it would break existing tests that used those APIs, but the fix is just to find anything that calls

    mock().**something return value-ish**

and replace it with

    mock().lastActualCall().**something return value-ish**

Which is of course an inconvenience, but a pretty trivial one to recover from.

**Comment by arstrube** [comment]
@uecasm confused, huh. Well, maybe. I'm okay with both API's being implemented with the same method, IF it is actually the same. I am opposed to breaking an exiting API (such as removing mock().returnIntValue()) which I found I, too, use a lot. IF it is really okay to implemnt both APIs by calling the same functions in C, then that is fine with me.

As for the code you pointed out above, I will change it. I must have overlooked it last time.

**Comment by arstrube** [comment]
I refactored the code, which now produces exactly the same failure that we started with.

This is where actually the `**orDefaultValue()`-versions need to be called, but the plain version is also called int the test, without an actualcall, which is an error.

**Comment by uecasm** [comment]
I'm not quite sure what you mean.

**Comment by arstrube** [comment]
Have a look at the changed I made to the tests in my latest PR.

**Comment by arstrube** [comment]
@uecasm is original problem still around with the Head revision? If so, could you post a minimal example exposing it? Or has it been solved?

**Comment by uecasm** [comment]
Current HEAD looks fine.  I still think it would be cleaner to remove the duplicated APIs, but I guess that ship has sailed.
