### ISSUE TITLE
Strange stuff happening with long long

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#943]
I built CppUTest thus in Cygwin:
```bash
$ make distclean
$ autoreconf -i ..
$ ../configure
$ make tdd
```
It says long long support is enabled. This is my simple test:
```c++
#include "CppUTest/TestHarness.h"
#include "CppUTest/CommandLineTestRunner.h"

TEST_GROUP(longlong) {
};

TEST(longlong, someValue) {
}

CPPUTEST_DEFAULT_MAIN
```
(yes, I know - it doesn't even do anything) and here is the result:
```bash
g++ -Wextra -Wall -Werror -g3 -O0  -std=c++11  -include"CppUTest/MemoryLeakDetectorNewMacros.h"   -I
/cygdrive/c/data/00_Dev/05_CppUTest/cpputest/include -L/cygdrive/c/data/00_Dev/05_CppUTest/cpputest/
lib OneTimeThrowAwayTests.cpp -lCppUTest -lCppUTestExt -o OneTimeThrowAwayTests.exe
/tmp/cc2WQ8Co.o:OneTimeThrowAwayTests.cpp:(.rdata$_ZTV33TEST_longlong_someValue_TestShell[__ZTV33TES
T_longlong_someValue_TestShell]+0x48): undefined reference to `UtestShell::assertLongLongsEqual(cppu
test_longlong, cpputest_longlong, char const*, char const*, int, TestTerminator const&)'
/tmp/cc2WQ8Co.o:OneTimeThrowAwayTests.cpp:(.rdata$_ZTV33TEST_longlong_someValue_TestShell[__ZTV33TES
T_longlong_someValue_TestShell]+0x4c): undefined reference to `UtestShell::assertUnsignedLongLongsEq
ual(cpputest_ulonglong, cpputest_ulonglong, char const*, char const*, int, TestTerminator const&)'
collect2: error: ld returned 1 exit status
```
I can produce more errors, too, but this one is kind of suprising - why would UtestShell::assertUnsignedLongLongsEqual() be referenced in the absence of any macro that uses it?

**Comment by arstrube** [comment]
This works as expected:
```c++
#include "CppUTest/TestHarness.h"
#include "CppUTest/CommandLineTestRunner.h"
#include <stdio.h>

int main(int, char**) {
    long long value = 0x7FFFFFFFFFFFFFFF;
    printf ("value is %lld\n", value);
    return 0;
}

// CPPUTEST_DEFAULT_MAIN
```
with the output:
```bash
value is 9223372036854775807
```

**Comment by arstrube** [comment]
So, let's do a proper test:
```c++
#include "CppUTest/TestHarness.h"
#include "CppUTest/CommandLineTestRunner.h"

TEST_GROUP(longlong) {
    long long value;
};

TEST(longlong, myTest) {
    value = 0x7FFFFFFFFFFFFFFF;
    LONGLONGS_EQUAL(0x7FFFFFFFFFFFFFFE, value); // expecting failure
}

CPPUTEST_DEFAULT_MAIN
```
Which yields:
```bash
g++ -Wextra -Wall -Werror -g3 -O0  -std=c++11  -include"CppUTest/MemoryLeakDetectorNewMacros.h"   -I
/cygdrive/c/data/00_Dev/05_CppUTest/cpputest/include -L/cygdrive/c/data/00_Dev/05_CppUTest/cpputest/
lib OneTimeThrowAwayTests.cpp -lCppUTest -lCppUTestExt -o OneTimeThrowAwayTests.exe
In file included from /cygdrive/c/data/00_Dev/05_CppUTest/cpputest/include/CppUTest/TestHarness.h:40
:0,
                 from OneTimeThrowAwayTests.cpp:1:
OneTimeThrowAwayTests.cpp: In member function 'virtual void TEST_longlong_myTest_Test::testBody()':
/cygdrive/c/data/00_Dev/05_CppUTest/cpputest/include/CppUTest/UtestMacros.h:224:92: error: overflow
in implicit constant conversion [-Werror=overflow]
         { UtestShell::getCurrent()->assertLongLongsEqual(expected, actual, text, file, line); }
                                                                                            ^
/cygdrive/c/data/00_Dev/05_CppUTest/cpputest/include/CppUTest/UtestMacros.h:212:3: note: in expansio
n of macro 'LONGLONGS_EQUAL_LOCATION'
   LONGLONGS_EQUAL_LOCATION(expected, actual, NULL, __FILE__, __LINE__)
   ^
OneTimeThrowAwayTests.cpp:10:5: note: in expansion of macro 'LONGLONGS_EQUAL'
     LONGLONGS_EQUAL(0x7FFFFFFFFFFFFFFE, value); // expecting failure
     ^
cc1plus: all warnings being treated as errors
```
```

**Comment by arstrube** [comment]
Duh! I fell into the trap of not copying the libs to the lib/ directory. Strangely though, after copying, the linker error doesn't go away :-(.

**Comment by basvodde** [comment]
Its likely because the library is not compiled with LONG_LONG and your test is (or the other way around)

**Comment by arstrube** [comment]
Yes, the library isn't. But when my system supports long long, and ../configure is enabled, then it should be compiled?

**Comment by basvodde** [comment]
Yes, if you used configure, yes. You can check the CppUtestGeneratedConfig.h

**Comment by arstrube** [comment]
```c++
/* Define to 1 if the system has the type `long long int'. */
#ifndef CPPUTEST_HAVE_LONG_LONG_INT
#define CPPUTEST_HAVE_LONG_LONG_INT 1
#endif
```

**Comment by basvodde** [comment]
Ok, that should be ok. Strange.

**Comment by arstrube** [comment]
Do I need to #define anything in my test? That would be very counterintuitive.

**Comment by basvodde** [comment]
You shouldn't. But are you use your test is using the CppUTest you compiled or an installed one?

**Comment by basvodde** [comment]
I'm put an #error in the CppUTestGeneratedConfig and see if your test compiles

**Comment by arstrube** [comment]
The test compiles fine, and then gets the linker error.
Let's see whether cpputest compiles....

**Comment by arstrube** [comment]
Sorry, this is confusing. There's one in generated/, but also in include/CppUTest/. Will need to change that one....

**Comment by basvodde** [comment]
Which include/CppUTest ?

**Comment by arstrube** [comment]
sorry, need to rebuild CppUTest. Can't find generated/ anymore...

**Comment by arstrube** [comment]
<cpputest_root>/include/CppUTest.

**Comment by arstrube** [comment]
Oh, that's why. generated/ is in cpputest_build/.

**Comment by arstrube** [comment]
I'm not sure exactly what is going wrong. But one thing can be said for sure: While the CppUTest build is consistent in itself, something goes awfully wrong for user projects.

**Comment by arstrube** [comment]
If I am not entirely mistaken, pretty much any user build should fail (at least under Cygwin; can't try Osx right now)

**Comment by arstrube** [comment]
CppUTestGeneratedConfig.h is not used. It can't be, because there given my include paths, if it was anywhere, it wouldn't be found. There would have to be a path `<cpputest>/include/generated` for it to be found.

**Comment by arstrube** [comment]
#error will stop cppu in its tracks

**Comment by arstrube** [comment]
Nice monologue :)

**Comment by arstrube** [comment]
> You shouldn't. But are you use your test is using the CppUTest you compiled or an installed one?

1. I did copy the libraries to lib/ this time.

2. `-I/cygdrive/c/data/00_Dev/05_CppUTest/cpputest/include`
`-L/cygdrive/c/data/00_Dev/05_CppUTest/cpputest/lib` - which would make it the one I just compiled.

But, the linker problem persists for some reason.

**Comment by arstrube** [comment]
As an aside, what's the background of the hex values being listed twice in the failure message, once within parenthesis, and once without? e.g.:
```
expected <0 (0x0) 0x0>
```

**Comment by arstrube** [comment]
If I put the same kind of test in the Cppu tests, it works. This would suggest that something is wrong with the headers I am pulling into my simple example.

**Comment by arstrube** [comment]
Since long long support is opt-out, there shouldn't be anything I need to do?!

**Comment by arstrube** [comment]
If I include `-DHAVE_CONFIG_H` on the compiler command line, I get the following error (as expected, actually):
```
error: generated/CppUTestGeneratedConfig.h: No such file or directory
#include "generated/CppUTestGeneratedConfig.h"
```
For this to work in user projects, 
   - generated/CppUTestGeneratedConfig.h needs to be copied to
include/generated/CppUTestGeneratedConfig.h. Not very elegant.
   - it would also need to be installed with the rest of the headers, in case of an install
   - How does the user know whether HAVE_CONFIG_H should be defined? Shouldn't that be dealt with transparently?

**Comment by arstrube** [comment]
Hmm. Now that the file is there, it complains about HAVE_CONFIG_H being redefined :-/. Remove that, and I am back at my original problem......

**Comment by arstrube** [comment]
Oookay. removed the (for some reason, useless) definition from my example test, put it back in the command line, and now it's compiling.

**Comment by arstrube** [comment]
I don't like this. If it is opt-out, it has to work right out of the box, with no funky defines or copying of headers. If that isn't possible, (the example Makefile probably hinted at that), then we should make it opt-in, and with appropriate documentation.

**Comment by basvodde** [comment]
Hmm. The problem is this:

- By default, it would not use LONG_LONG support, at least not for CMake and MakefileWorker... because they can't detect whether there is long long support or not.
- Configure can detect long long support, so when it detect support, it'll enable it. But then it'll need to generate the config.h and install it. Now it does that.
- When you use configure and do NOT install CppUTest (your case), then it will detect long long support and thus compile the library with long long support, but the generated file is not installed. So, the user project would not use long long.

That sucks :)

I'm not sure how to word around that, as I think the installing of the config.h works pretty well actually. That will make sure that homebrew and apt package work fine and long long is default on.

One way we can work around it is by trying to detect long long in the default GeneratedConfig.h file?

Any other suggestions?

**Comment by arstrube** [comment]
I'll give it some thought. I will also test installing it. Installing it should work, right? It would be nice if user projects could detect and use long long support (this should then also work for Makefileworker, correct?

**Comment by arstrube** [comment]
Confirmed - same thing happening on my Mac, and goes away if I install CppUTest & use installed headers. When installed, the proper generated header is inside include/CppUTest. Hmmm.

**Comment by basvodde** [comment]
Yes, I can't do that when it isn't installed :) This only relates to autotools as that is the only one that detects long long support. The easiest way to 'fix' it would be to do a very rough check on long long in the header, that way most cases it would work fine... not elegant, but now know any better solution at the moment.

**Comment by arstrube** [comment]
Interesting. How could such a rough check be done, without blowing up the build?

**Comment by Andne** [comment]
Based on some quick searches, it appears that long long came in as part of C99.  C99 also added `__STDC_VERSION__` with the value `199901L`.  Between that and `__cplusplus` would it be possible to detect the existence of C99 on most compilers?

I'm not sure it would quite work on Visual C++, that might require it's own check since historically they haven't changed the value of `__cplusplus` as they support the newer standards.  Looks like they never define `__STDC_VERSION__` and `__STDC__` is only defined under a version specific set of requirements, so any checks there probably need to use `__MSC_VER`.

**Comment by basvodde** [comment]
I was thinking of just checking LLONG_MIN in limits.h :) It is a very rough and quick check, but it would work, I guess, on Mac/Lin/Win. Usually, when installed, this file should be overridden anyways.

**Comment by arstrube** [comment]
Ahh, clever. So its not being defined would indicate the absense of long long support.

**Comment by Andne** [comment]
Just playing devil's advocate here, but isn't limits.h a standard header?  I have the impression that the intent was to avoid using standard headers as much as possible in order to allow building for things like kernel unit testing and platforms that don't have them.

**Comment by basvodde** [comment]
Indeed, thats whats making me uncomfortable. I thought we already depended on limits.h, but it seems now.

**Comment by Andne** [comment]
Looks like there is one other dependency on it, at least when STD_C isn't disabled completely.  It's in CppUTestConfig.h, [Line 194](https://github.com/cpputest/cpputest/blob/fc9317df1afb0094a44e4bf216bbfbb60a0d57e9/include/CppUTest/CppUTestConfig.h#L194).  Right above the long long check as it turns out.  Given that, checking for `LLONG_MIN` when `CPPUTEST_USE_STD_C_LIB` is defined and just default to either on or off (not sure which is better) when it's not defined would probably work pretty well.

**Comment by arstrube** [comment]
This has been solved, right?

**Comment by basvodde** [comment]
Yes, closed.
