### ISSUE TITLE
Why does autoreconf .. -i call 1.11 version of Autotools when 1.14 should be called?

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#945]
When I compile CppUTest from Head under Cygwin, version 1.11 of Autotools is used, leading to several problems with the latest version of Cygwin.

When I call the same tools from the command line directly, version 1.14 is invoked, e.g.

```
$ aclocal # aclocal-1.14
$ automake # automake-1.14
```

I could not find anything that governs this behavior.

**Comment by basvodde** [comment]
I assume this was an environment issue, so closing it for now. Lemme know if I'm wrong.
