### ISSUE TITLE
GCC 6: Unknown Warnings (-Wno-c++98-compat / -Wno-c++98-compat-pedantic)

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#958]
GCC 6 warns about these two unknown warning switches: `-Wno-c++98-compat` and `-Wno-c++98-compat-pedantic` (Cmake, C++11 enabled).

-----------------------

**Update:** Not emitted if C++11 is disabled.

**Comment by basvodde** [comment]
I think this is now fixed. Could you check this?

**Comment by offa** [comment]
Yes, is solved now - thank you!
