### ISSUE TITLE
Set path / location for XML output

### ISSUE THREAD

**Issue by itavero** [cpputest/cpputest#959]
We are using CppUTest for both our unit tests and our integration tests.
It would be nice if we could change the `cpputest_` prefix of the XML files or set the path where these files are stored.
As far as I can tell both is not possible right now via the command-line interface (or am I wrong?).

I could of course `cd` into another directory and execute the binary from there, but than I have to update the relative paths and such, which is what I'm trying to avoid.

**Comment by itavero** [comment]
I suggest adding a flag like `--file` (or `-of`... _suggestions are welcome_ :wink:) to set the file name.
As [mentioned](//github.com/cpputest/cpputest/issues/967#issuecomment-220410416) in #967, all test output can be in a single file.

**Comment by basvodde** [comment]
I guess this has been implemented with the -k feature. Closing this for now. Let me know if -k doesn't resolve this.
