### ISSUE TITLE
Drop non-free platform_* files from the project

### ISSUE THREAD

**Issue by rhertzog** [cpputest/cpputest#961]
Hello,

I'm the Debian maintainer of cpputest. I recently got a bug report pointing out that some of the files shipped by cpputest are actually non-free for multiple reasons detailed below.

The affected files are:

-    platforms_startup/armcc/AT91SAM7A3/Retarget.c
-    platforms_startup/armcc/AT91SAM7A3/SAM7A3.asm
-    platforms_startup/armcc/LPC1768/Retarget.c
-    platforms_startup/armcc/LPC1768/Serial.h

The problematic license is this one (need a software license):
>  This software may only be used under the terms of a valid, current,
> end user licence from KEIL for a compatible version of KEIL software
> development tools. Nothing else gives you the right to use this software.

- platforms_examples/armcc/AT91SAM7A3/tests/main.cpp
- platforms_examples/armcc/LPC1768/tests/main.cpp

The problematic license is this one (restriction of usage and limited to owners of the book):
>  For use by owners of Test-Driven Development for Embedded C,
>  and attendees of Renaissance Software Consulting, Co. training
>  classes.
>  Authorized users may use this source code in your own projects, however
>  the source code may not be used to create training material, courses,
>  books, articles, and the like. We make no guarantees that this source code
>  is fit for any purpose.

-     platforms_startup/armcc/LPC1833/cmsis_18xx.h
-     platforms_startup/armcc/LPC1833/retarget.c
-     platforms_startup/armcc/LPC1833/startup_LPC18xx.asm
-     platforms_startup/armcc/LPC1768/lpc17xx_clkpwr.c
-     platforms_startup/armcc/LPC1768/lpc17xx_clkpwr.h
-     platforms_startup/armcc/LPC1768/lpc17xx_libcfg_default.c
-     platforms_startup/armcc/LPC1768/lpc17xx_libcfg_default.h
-     platforms_startup/armcc/LPC1768/lpc17xx_pinsel.h
-     platforms_startup/armcc/LPC1768/lpc17xx_timer.c
-     platforms_startup/armcc/LPC1768/lpc17xx_timer.h
-     platforms_startup/armcc/LPC1768/lpc_types.h

The problematic license is this one (the restriction of usage with NXP semiconductors is problematic):
>  Permission to use, copy, modify, and distribute this software and its
>  documentation is hereby granted, under NXP Semiconductors' and its
>  licensor's relevant copyrights in the software, without fee, provided that
>  it is used in conjunction with NXP Semiconductors microcontrollers. This
>  copyright, permission, and disclaimer notice must appear in all copies of
>  this code.

Can you drop those files as they are not needed except tor very special use cases? More likely you want to drop the whole directories...

For the platforms_examples files, you might be able to convince James W. Grenning to relicense them under a really free license...

If you can cram this in the next 3.8 release that would be nice.

FTR the Debian bug report is courtesy of Dmitry Smirnov here: https://bugs.debian.org/823711

**Comment by arstrube** [comment]
@jwgrenning -

>     platforms_examples/armcc/AT91SAM7A3/tests/main.cpp
>     platforms_examples/armcc/LPC1768/tests/main.cpp
> 
> The problematic license is this one (restriction of usage and limited to owners of the book):
> 
>     For use by owners of Test-Driven Development for Embedded C,
>     and attendees of Renaissance Software Consulting, Co. training
>     classes.
>     Authorized users may use this source code in your own projects, however
>     the source code may not be used to create training material, courses,
>     books, articles, and the like. We make no guarantees that this source code
>     is fit for any purpose.

Do you really want to exclude the use of these here? Can you make the problem go away, perhaps?

**Comment by arstrube** [comment]
My question is: Is the armcc stuff still usable after removing these files? Can any of the armcc experts comment on what to do?

**Comment by arstrube** [comment]
Or, put differently, why do these headers need to be here in the first place? I mean, if we compile with GCC for the x86 architecture, we also don't provide headers such as `<bits/avx512bwintrin.h>`; we assume that these come with the compiler installation and the compiler knows where to find them?

**Comment by arstrube** [comment]
@bortsov what do you think?

**Comment by jwgrenning** [comment]
Sorry about that.  That is fine for distribution. It is a copy/pater 
error.

What do I have to do the make the problem go away?

thanks, James

**Comment by jwgrenning** [comment]
Do you want me to edit that out of the file?

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by rhertzog** [comment]
@jwgrenning Please replace those statements with a copy of the BSD license used for the rest of the software, yes.

**Comment by jwgrenning** [comment]
I have changed these two files.  I don't recall ever putting those 
there.

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by arstrube** [comment]
Thanks, @jwgrenning, much appreciated.

Is @bortsov still around? It would be helpful to have some feedback from @basvodde on how to proceed. How usable will these examples be, if we drop the files concerned?

My suggestion for a quick solution is to replace the files by empty stubs, so it is easy to see that they used to be there and where they should be located. People working with those platforms could then replace the stubs by the real thing.

**Comment by arstrube** [comment]
Having looked at the files in more detail, I propose:

1. Leave `platform_examples`, because there were only two problematic files, and they have been fixed.
2. Drop `platform_startup`, because after removing the affected files, what's left seems of little use to me.

I will submit a PR implementing this.

**Comment by basvodde** [comment]
Are all of them now fixed? Can this be closed?

**Comment by arstrube** [comment]
To the best of my knowledge, all of them are now fixed. Perhaps someone else than me should double check, though.

**Comment by basvodde** [comment]
Checked, closing this.
