### ISSUE TITLE
Why do some failures print the hex value twice?

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#975]
An example would be:

```
      expected <97 (0x61) 0x61>
      but was  <98 (0x62) 0x62> 
```

Is there any point in printing it twice? This occurs, for example, in UNSIGNED_LONGS_EQUAL. Other failures just print the hex value once in brackets, which seems to be done elsewhere.

BYTES_EQUAL should actually call UNSIGNED_LONGS_EQUAL_LOCATION, instead of LONGS_EQUAL_LOCATION for clarity, but this is not possible, because of the strange output.

Or am I missing some finer point here?

**Comment by cuitoldfish** [comment]
I don't think there is some finer point here, but some conflict to two class design here.

There is a general string class SimpleString existed in current design, for unsigned decimal number, it will be translate to "%llu (0x%llx)". All other will use SimpleString to construct string and so does the `UnsignedLongsEqualFailure`. But by Contrast to other client, `UnsignedLongsEqualFailure` has a exception -- it will append it's own hex format string which also follow the general design for TestFailure class.

so two class design for SimpleString and TestFailure make this print including hex format value twice, which seems stranger when showed as the failure report.

**Comment by basvodde** [comment]
Eheh :) Needs to be fixed.

**Comment by arstrube** [comment]
Okay. Will take a look at it next week.

**Comment by maxilai** [comment]
Hi, arstrube
    I think the finer point here is "human readable", both dec and hex were
printed.
    example:

TEST(MockExpectedCallComposite, hasUnsignedLongIntParameter)
{
    composite.withParameter("param", (unsigned long int) 5);
    STRCMP_EQUAL("name -> unsigned long int param: <5 (0x5)>",
 call.callToString().asCharString());
}

3 types of value will be printed as dec and hex

1.
SimpleString StringFrom(cpputest_ulonglong value){
    return StringFromFormat("%llu (0x%llx)", value, value);
}
2.
SimpleString StringFrom(unsigned int i){
    return StringFromFormat("%10u (0x%08x)", i, i);
}
3.
SimpleString StringFrom(unsigned long i){
    return StringFromFormat("%lu (0x%lx)", i, i);
}


TEST(UnitTestMacros, TestUNSIGNED_LONGS_EQUAL)
{
    fixture.runTestWithMethod(_UNSIGNED_LONGS_EQUALTestMethod);
    CHECK_TEST_FAILS_PROPER_WITH_TEXT("expected <1 (0x1) 0x1>");
    CHECK_TEST_FAILS_PROPER_WITH_TEXT("but was  <0 (0x0) 0x0>");
}

TEST(UnitTestMacros, TestUNSIGNED_LONGS_EQUAL_TEXT)
{
    fixture.runTestWithMethod(_UNSIGNED_LONGS_EQUAL_TEXTTestMethod);
    CHECK_TEST_FAILS_PROPER_WITH_TEXT("expected <1 (0x1) 0x1>");
    CHECK_TEST_FAILS_PROPER_WITH_TEXT("but was  <0 (0x0) 0x0>");
    CHECK_TEST_FAILS_PROPER_WITH_TEXT("Failed because it failed");
}

TEST(UnitTestMacros, TestUNSIGNED_LONGLONGS_EQUAL)
{
    fixture.runTestWithMethod(_UNSIGNED_LONGLONGS_EQUALTestMethod);
    CHECK_TEST_FAILS_PROPER_WITH_TEXT("expected <1 (0x1) 0x1>");
    CHECK_TEST_FAILS_PROPER_WITH_TEXT("but was  <0 (0x0) 0x0>");
}

TEST(UnitTestMacros, TestUNSIGNED_LONGLONGS_EQUAL_TEXT)
{
    fixture.runTestWithMethod(_UNSIGNED_LONGLONGS_EQUAL_TEXTTestMethod);
    CHECK_TEST_FAILS_PROPER_WITH_TEXT("expected <1 (0x1) 0x1>");
    CHECK_TEST_FAILS_PROPER_WITH_TEXT("but was  <0 (0x0) 0x0>");
    CHECK_TEST_FAILS_PROPER_WITH_TEXT("Failed because it failed");
}

**Comment by maxilai** [comment]
Hi, basvodde and arstrube 
    For now, the StringFrom return different style of string for different type (signed/unsigned).
    for example:
SimpleString StringFrom(cpputest_longlong value){
    return StringFromFormat("%lld", value);
}
SimpleString StringFrom(cpputest_ulonglong value){
    return StringFromFormat("%llu (0x%llx)", value, value);
}
    It was this difference that makes the differ output as arstrube described.
    I think the one for cpputest_ulonglong is better. It makes the output string human readable as below:

name -> unsigned long int param: <5 (0x5)>
    
    What's you opinion?

**Comment by arstrube** [comment]
I think we need to take a close look and make it consistent. StringFrom should only return one thing. In the Failure, we can the assemble it to <dec hex> for example. The hex number should never be printed twice, and either it should have () around it everywhere, or nothing at all. The problem is that SimpleString should provide "Raw values", and the routines that use it should decide whether to display both dec and hex, etc.

**Comment by cuitoldfish** [comment]
agree, it should be consistent
