### ISSUE TITLE
TestHarness.h and CommandLineTestRunner.h breaks standard header under GCC 5.3

### ISSUE THREAD

**Issue by skyscribe** [cpputest/cpputest#982]
The following include sequence would break g++ compiling

```cpp
#include <CppUTest/TestHarness.h>
#include <CppUTest/CommandLineTestRunner.h>

#include <unordered_map>
```

GCC5.3 just prompts such errors regarding hashtable:

```bash
/usr/include/c++/5/bits/hashtable_policy.h: In member function ‘void std::__detail::_Local_iterator_base<_Key, _Value, _ExtractKey, _H1, _H2, _Hash, false>::_M_init(const __hash_code_base&)’:
/usr/include/c++/5/bits/hashtable_policy.h:1484:15: error: expected type-specifier before ‘this’
       { ::new(this->_M_h()) __hash_code_base(__base); }
               ^
/usr/include/c++/5/bits/hashtable_policy.h:1484:15: error: expected ‘)’ before ‘this’
/usr/include/c++/5/bits/hashtable_policy.h: In member function ‘std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type* std::__detail::_Hashtable_alloc<_NodeAlloc>::_M_allocate_node(_Args&& ...)’:
/usr/include/c++/5/bits/hashtable_policy.h:1954:13: error: expected type-specifier before ‘(’ token
      ::new ((void*)__n) __node_type;
             ^
/usr/include/c++/5/bits/hashtable_policy.h:1954:13: error: expected ‘)’ before ‘(’ token
/usr/include/c++/5/bits/hashtable_policy.h:1954:14: error: expected primary-expression before ‘void’
      ::new ((void*)__n) __node_type;
              ^
➜  cpputest g++ --version
g++ (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
Sounds like certain type becomes incomplete. 

Adjust the header inclusion sequence such that  standard headers are before CppUTest headers can resolve this issue. Anything wrong in CppUTest headers?

**Comment by arstrube** [comment]
@basvodde this used to be okay, no?

**Comment by basvodde** [comment]
Yeah, its just the operator new conflict with Standard C++ library.

**Comment by arstrube** [comment]
So why is he getting this error? I remember doing similar includes and not getting an error? I thought there was code in the headers to take care of this.

I guess the question is: Have we always had this problem, or did we break something that used to work?

**Comment by basvodde** [comment]
Always have this.

@skyscribe You'll need to move the StdC++ includes *above* the CppUTest includes, that should solve the problem. If you use a --include file, then you'll need to do some additional things, which you can find at:
http://cpputest.github.io/manual.html#memory_leak_detection

In the section related to STL.

**Comment by skyscribe** [comment]
@basvodde Thanks - I know the solution, I'm just curious why we have such limitation. Thanks for the link and explanation.

**Comment by basvodde** [comment]
It's because the memory leak detector will replace new with a seperate function call. But when you re-define new (as StdC++ does) then it causes a conflict.
