### ISSUE TITLE
Mac check-all fails

### ISSUE THREAD

**Issue by basvodde** [cpputest/cpputest#983]
../tests/CppUTestExt/IEEE754PluginTest.cpp:122: error: Failure in TEST(FE__with_Plugin, should_not_fail_again_when_test_has_already_failed)
    CHECK(IEEE754ExceptionsPlugin::checkIeee754OverflowExceptionFlag()) failed

@arstrube On MacOSX with g++, this still one fails. Any idea about it?

**Comment by arstrube** [comment]
Just with g++?

**Comment by arstrube** [comment]
This went through quite a few changes along the way, so I am not quite clear what is / should be going on.... As far as I recall, Osx doesn't implement the flags interface at all, and I removed my code that emulated the Gcc implementation. That being so, why don't the other tests fail? Why only this one?

So, apparently it **is** working, but doesn't pick up the division by zero. Yet, all the other tests appear to have passed, including the one that checks for division by zero? That's weird.

Could you perhaps provide more detailed output? I only run Clang on Osx.

**Comment by basvodde** [comment]
I tried commenting out the first flag check, but then the second one failed. Not sure what additional output I can give. Any ideas, then I'll provide it :)

**Comment by basvodde** [comment]
Ah, it happens on g++ when the compilation for the standard C++ library is off.

**Comment by arstrube** [comment]
A complete log of `FE__with_Plugin` would be helpful. The behavior you just described is what I would have expected, but how come none of the other tests (not checks) seem to have failed?

What you describe is the "expected" behavior when in fact no flags are checked at all (because it's not implemented in the compiler / Os).

**Comment by arstrube** [comment]
N.B. The point of the test is that, even if all flags are set, and something else fails the test along the way, then only the other failure should be reported, and none of the flags. The check that failed is just to verify that the flag was indeed set.

**Comment by arstrube** [comment]
> Ah, it happens on g++ when the compilation for the standard C++ library is off.

That is an interesting observation.... although I don't quite know what to make of it yet...

**Comment by basvodde** [comment]
Ok, so it is not dependent on clang or gcc, it is just dependent on whether you turn on/off using the Standard C++ library. When standard C++ library is turned off, that one test doesn't pass.

**Comment by arstrube** [comment]
Log, please.

**Comment by arstrube** [comment]
Okay, I can reproduce it now 'cause I'm at my Mac. I also get
```
In file included from <command line>:3:
./../include/CppUTest/MemoryLeakDetectorNewMacros.h:38:11: warning: 'operator new' is missing
      exception specification 'throw(std::bad_alloc)'
    void* operator new(size_t size) UT_THROW(std::bad_alloc);
          ^
                                    throw(std::bad_alloc)
./../include/CppUTest/MemoryLeakDetectorNewMacros.h:39:11: warning: 'operator new[]' is missing
      exception specification 'throw(std::bad_alloc)'
    void* operator new[](size_t size) UT_THROW(std::bad_alloc);
          ^
                                      throw(std::bad_alloc)
2 warnings generated.
```
a lot with ../configure --disable-std-cpp. BTW I have Clang only.

**Comment by arstrube** [comment]
```
IGNORE_TEST(IEEE754ExceptionsPlugin2, should_not_fail_in_ignored_test) - 0 ms
TEST(FE__with_Plugin, should_not_fail_again_when_test_has_already_failed)
../tests/CppUTestExt/IEEE754PluginTest.cpp:122: error: Failure in TEST(FE__with_Plugin, should_not_fail_again_when_test_has_already_failed)
	CHECK(IEEE754ExceptionsPlugin::checkIeee754OverflowExceptionFlag()) failed

 - 0 ms
TEST(FE__with_Plugin, should_fail_only_once_when_all_flags_are_set) - 0 ms
TEST(FE__with_Plugin, should_check_five_times_when_all_flags_are_set) - 0 ms
TEST(FE__with_Plugin, should_succeed_with_5_checks_when_no_flags_are_set) - 0 ms
TEST(FE__with_Plugin, should_succeed_when__FE_INEXACT____is_set_and_disabled) - 0 ms
TEST(FE__with_Plugin, should_fail____when__FE_INEXACT____is_set_and_enabled) - 0 ms
TEST(FE__with_Plugin, should_fail____when__FE_UNDERFLOW__is_set) - 0 ms
TEST(FE__with_Plugin, should_fail____when__FE_OVERFLOW___is_set) - 0 ms
TEST(FE__with_Plugin, should_fail____when__FE_DIVBYZERO__is_set) - 0 ms
```
None of these tests should even be compiled. And even if they are, how com the should_fail tests are passing (in particular the divbyzero one), which would mean the flag was set?

**Comment by basvodde** [comment]
Can't get rid of that warning as std::bad_alloc doesn't exist without C++ library

**Comment by arstrube** [comment]
Ahh... okay. Too bad....

**Comment by basvodde** [comment]
Fixed.
