### ISSUE TITLE
Gcc 5.3.0 warns about sized operator delete

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#991]
```
./../include/CppUTest/MemoryLeakDetectorNewMacros.h:45:10: warning: 'void operator 
delete(void*, size_t)' is a usual (non-placement) deallocation function in C++14 (or with 
-fsized-deallocation) [-Wc++14-compat]
     void operator delete (void* mem, size_t size) UT_NOTHROW;
```
I suppose we might want "-Wno-c++14-compat".

It compiles, links and tests okay, but there are lots of warnings, because for each 'real' warning, it also spits out:
```
cc1plus: warning: unrecognized command line option '-Wno-weak-vtables'
cc1plus: warning: unrecognized command line option '-Wno-exit-time-destructors'
cc1plus: warning: unrecognized command line option '-Wno-global-constructors'
cc1plus: warning: unrecognized command line option '-Wno-keyword-macro'
cc1plus: warning: unrecognized command line option '-Wno-reserved-id-macro'
cc1plus: warning: unrecognized command line option '-Wno-disabled-macro-expansion'
cc1plus: warning: unrecognized command line option '-Wno-c++11-long-long'
```
These tend to go away when the warning causing it is silenced.

**Comment by basvodde** [comment]
What does the warning even mean :)

**Comment by basvodde** [comment]
Before disabling that, I guess we'll need to have a C++14 compilation in the CI :)

**Comment by arstrube** [comment]
My interpretation: It wants to warn you that you shouldn't define this, because if you do, it won't be compatible with C++14 which also defines it. When you do have C++14, you might get no problem -- or worse, I guess.....

If you take this warning serious, it means adding the sized destructor is not compatible with C++14, so silencing the previous warning might have been the better option :P

**Comment by arstrube** [comment]
We don't need a C++14 compilation on the CI, me thinks. But someone needs to do it offline, to see what happens. To play around with all the different possibilities....

**Comment by arstrube** [comment]
1. Why is it that CppUTest is built without `-Werror`?
2. The warnings are alive and well, plus they trigger more warnings about unknown warning options.
3. The warning does not appear with Gcc old enough to not know about C++14. Which version are we using on the TravisCi Gcc build?
This is REALLY UGLY to say the least. If -Werror was enabled, it would also fail the build.

**Comment by arstrube** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/4686469/15652038/b470d23a-2683-11e6-81b6-04b93f4b058a.PNG)
This is what you see for each and every file compiled. Nice, huh?

**Comment by arstrube** [comment]
@basvodde can you please either silence the warning, or remove the destructors (and use -fno-sized-destructors).

**Comment by basvodde** [comment]
I thought I had added the -@no-compat-C++14 to the autoconf build. Not yet to the CMake build though.

**Comment by arstrube** [comment]
What about the absense of -Werror. Is that intended? When is it supposed to be active, and when isn't it?

**Comment by basvodde** [comment]
Yes, the -Werror had to be disabled for the Debian build process. It would too quickly cause build failures for them. So, you can switch the autoconf to "maintainer mode" and then it should work again, I believe.

**Comment by arstrube** [comment]
Ah, I see. That makes sense. Can we get rid of these warnings, though?

**Comment by basvodde** [comment]
Please yes :)

**Comment by arstrube** [comment]
I can't, currently. I no longer have a working installation of Gcc 5.3.x, and the problem doesn't seem to occur with Clang 6.1.0.

What does surprise me is that configure yields a 'yes' for the -Wno-c++14-compat check, but the option is not added to compiler options. Not sure how this mechanism is supposed to work?

**Comment by arstrube** [comment]
Okay, I think it's because it was added to the wrong variable - should be added to CPPUTEST_CXXWARNINGFLAGS instead. I'll submit a PR but unfortunately can't test it. Would assume that, if the flag is present, the warnings will go away.

**Comment by offa** [comment]
I have just compiled CppUTest current master without error using Gcc 5.3.1 (Linux, C++11 enabled). Are there any further settings necessary to reproduce the problem?

**Comment by arstrube** [comment]
@off what if you don't enable C++11? I ran ../configure with no arguments.

**Comment by offa** [comment]
I used cmake for building, should this make a difference?

**Comment by arstrube** [comment]
Yes, definitely. Although @basvodde said he wasn't sure how to handle this on Cmake, I think.

But the problem occurs when building with automake and a version of Gcc that "knows" about C++14.

**Comment by offa** [comment]
I have checked cmake with C++11 on / off, no warning.

Running `autogen.sh` ended like this:

```
$ ./autogen.sh 
configure.ac:10: error: possibly undefined macro: AC_LIBTOOL_DLOPEN
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:11: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by offa** [comment]
Ok now, with Gcc 5 and autotools i get the warning:

```
././include/CppUTest/MemoryLeakDetectorNewMacros.h:45:10: warning: ‘void operator delete(void*, size_t)’ is a usual (non-placement) deallocation function in C++14 (or with -fsized-deallocation) [-Wc++14-compat]
     void operator delete (void* mem, size_t size) UT_NOTHROW;
          ^
././include/CppUTest/MemoryLeakDetectorNewMacros.h:46:10: warning: ‘void operator delete [](void*, size_t)’ is a usual (non-placement) deallocation function in C++14 (or with -fsized-deallocation) [-Wc++14-compat]
     void operator delete[] (void* mem, size_t size) UT_NOTHROW;
          ^

```

**Comment by arstrube** [comment]
@basvodde the warning seems to appear irrespective of whether C++11 is enabled. Which makes sense, because your code _potentially_ conflicts with C++14, regardless.

**Comment by offa** [comment]
For reference: #997 is related to this.

**Comment by dave20874** [comment]
I'm trying to learn CppUTest using Ubuntu 16.04, with GCC 5.3.1 as my platform.  And I'm not able to get the example code from "Test-Driven Development for Embedded C" to run.  The Makefiles for the project have -Werror set, resulting in compile errors from this operator delete problem.  Can you suggest a workaround?

**Comment by arstrube** [comment]
Take out -Werror. :-(

@basvodde I am still convinced that removing the destructors (that nobody uses anyway) and specifying `-fno-sized-destructors` is a much cleaner approach, compatible with everything out there.

**Comment by offa** [comment]
@dave20874 maybe you can workaround this issue by including CppUTest headers as system headers (`-isystem` instead of `-I`).

**Comment by offa** [comment]
Fixed for CMake in #1029.

**Comment by marjonz** [comment]
Sorry to open a year-old thread, but in moving forward and wanting to support C++14, what are the plans for this? The framework is still going to throw the warning if you want to support C++14 moving forward.

**Comment by offa** [comment]
Can you elaborate? I'm using (and compiling) CppUTest successfully with C++11/14/17 without any errors using Gcc (5 - 7) and Clang (3.7 - 4.0).

Is it about *using* CppUTest within a C++14 project or *building* it with?

**Comment by marjonz** [comment]
Building with it. It keeps throwing the warning for the delete (size_t)
operator.

**Comment by offa** [comment]
Are you using the latest version? Also check the compile commands, there should be a flag which disables this warning.

**Comment by marjonz** [comment]
These are the current version (3.8), MingW GCC 5.3.0 and compile flags (based on CMakeLists.txt):
- STD_C  = ON
- STD_CPP = ON
- CPPUTEST_FLAGS = ON
- MEMORY_LEAK_DETECTION = ON
- EXTENSIONS = ON
- LONGLONG = OFF
- MAP_FILE = OFF
- COVERAGE = OFF
- C++11 = OFF
- WERROR = OFF
- TESTS = ON
- TESTS_DETAILED = OFF

I am thinking some of these flags seems to be overridden somewhere in the build chain.
For example: even if "LONGLONG=OFF", CPPUTEST_USE_LONG_LONG will get defined to "1" just by using "__STDC_VERSION__ >= 199901L"
I will keep looking for what might be wrong in my setup.

**Comment by marjonz** [comment]
Sorted the problem, wasn't specifying the correct compile flags. Explicitly defined support for LONGLONG and C++11. Thanks.

**Comment by Renlonol** [comment]
Hi,
I also have these warnings and serial test failed when using Gcc 5.3.0.

**Comment by bryceschober** [comment]
@offa @arstrube @basvodde I'm still getting these warnings when compiling with master and this config:
```
Features configured in CppUTest:
    Memory Leak Detection:              ON
    Compiling Extensions:               ON
    Support Long Long:                  ON
    Use CppUTest flags:                 ON

    Using Standard C library:           ON
    Using Standard C++ library:         ON
    Using C++11 library:                ON
```

> @basvodde I am still convinced that removing the destructors (that nobody uses anyway) and specifying `-fno-sized-destructors` is a much cleaner approach, compatible with everything out there.

Any comments on this idea? How would I try it out myself?

**Comment by offa** [comment]
Are you using cmake or autotools?

**Comment by bryceschober** [comment]
@offa I'm using CMake.

**Comment by offa** [comment]
I can reproduce the error with explicitly setting the C++98 standard.

Does it work with the cmake built-in option?

```sh
cmake -DCMAKE_CXX_STANDARD=11 .. 
```

**Comment by bryceschober** [comment]
@offa I dug into our problem more deeply, and it turns out that it was our fault. We're confusing some deep internals of CMake by doing a many-project recursive build with 4 different toolchain files, so that we can have a "make all" that does everything... but it involves compromises on CMake correctness, and I guess we shot ourselves in the foot on this one. CMake managed to print the correct compiler for its evaluation of compiler flags support, but use the wrong one when actually running the tests. When I build just CppUTest itself, with our intended host toolchain file and C++11 enabled, I get what I deserve.

**Comment by basvodde** [comment]
Does this then require a larger fix?

**Comment by bambre** [comment]
I have the same problem with a simple handwritten makefile and `MakefileWorker.mk` in an Eclipse CDT project, using gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609 :

```
17:26:04 **** Build of configuration TDD for project tuto_cpputest ****
make all 
compiling AllTests.cpp
mkdir -p objs/tests/
g++ -g -Wall -Wextra -Werror -Wshadow -Wswitch-default -Wswitch-enum -Wconversion -Wno-long-long -pedantic-errors -Wsign-conversion -Woverloaded-virtual -include cpputest/include/CppUTest/MemoryLeakDetectorNewMacros.h  -Wall -Wextra -Werror -Wshadow -Wswitch-default -Wswitch-enum -Wconversion -Wno-long-long -pedantic-errors -Wsign-conversion -include cpputest/include/CppUTest/MemoryLeakDetectorMallocMacros.h  -I.  -Icpputest/include    -c -MMD -MP -o objs/tests/AllTests.o tests/AllTests.cpp
In file included from <command-line>:0:0:
./cpputest/include/CppUTest/MemoryLeakDetectorNewMacros.h:63:10: error: ‘void operator delete(void*, size_t)’ is a usual (non-placement) deallocation function in C++14 (or with -fsized-deallocation) [-Werror=c++14-compat]
     void operator delete (void* mem, size_t size) UT_NOTHROW;
          ^
./cpputest/include/CppUTest/MemoryLeakDetectorNewMacros.h:64:10: error: ‘void operator delete [](void*, size_t)’ is a usual (non-placement) deallocation function in C++14 (or with -fsized-deallocation) [-Werror=c++14-compat]
     void operator delete[] (void* mem, size_t size) UT_NOTHROW;
          ^
cc1plus: all warnings being treated as errors
cpputest/build/MakefileWorker.mk:506: recipe for target 'objs/tests/AllTests.o' failed
make: *** [objs/tests/AllTests.o] Error 1
"make all" terminated with exit code 2. Build might be incomplete.
```

The proposed fix looks like it is only for cmake builds, is that correct?  If so, would it be possible to fix this error more generally?

**Comment by offa** [comment]
Yes, my fix is only for cmake.

Probably it's possible to wrap these function in an ifdef block, checking for the used C++ standard?

**Comment by bambre** [comment]
An `ifdef` block sounds like an acceptable solution to me, but I've no idea about the program internals.  I see the ticket is currently closed, but the issue is not resolved.
  
Would be great to get a fix, maybe it's worth reopening the ticket for someone to have another look at this?

**Comment by offa** [comment]
I have opened PR #1255 with such a check.
